### ISSUE TITLE
Fail to attach Mongo Emulator  with error with Cosmos Emulator installed

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1000]
**OS:** Win10
**Node.js:** V10.14.0
**Build Version:** [20190116.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2150&view=results)

**Repro Steps:**
1. Install [Cosmos Emulator](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator) and start it.
2. Right click 'Attached Database Accounts' node --> Select 'Attach Emulator' --> Select 'Mongo'.
3. Check the result.

**Expect:**
Succeed to attach Mongo Emulator.

**Actual:**
Fail to attach Mongo Emulator with error.
![image](https://user-images.githubusercontent.com/34729092/51293082-06cda100-19c2-11e9-8d84-b90be244466d.png)

**More Info:**
Succeed to attach SQL Emulator.
![image](https://user-images.githubusercontent.com/34729092/51293100-1f3dbb80-19c2-11e9-83b7-e4d469306f01.png)

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Can you take a look?  I can't seem to connect, either (mongo or sql).  Thx.

**Comment by StephenWeatherford** [comment]
Ah, this is in master, it's probably webpack and I think I know what.

**Comment by v-dantch** [comment]
Verified on the latest build [20190709.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7532), also repro. So re-open this issue.
