### ISSUE TITLE
can't  open document, but mongoDB Compass open it correctly

### ISSUE THREAD

**Issue by Zimovets** [microsoft/vscode-cosmosdb#1001]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.openDocument
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\7349~1\AppData\Local\Temp\vscode-cosmosdb-editor\Sidra
-cosmos-document.json'

Version: 0.9.1
OS: win32

**Comment by StephenWeatherford** [comment]
@Zimovets Does this happen every time?  Is it only with this one document, or this one collection or DB?  Thx.
cc @PrashanthCorp

**Comment by Zimovets** [comment]
I noticed it just one time

23 січня 2019, 03:57:00, від "Stephen Weatherford (MSFT)" <notifications@github.com>:

@Zimovets Does this happen every time? Is it only with this one document, or this one collection or DB? Thx.
cc @PrashanthCorp

**Comment by PrashanthCorp** [comment]
I'm unable to repro it. I also tried: 
1. Overloading the command with double-clicks
2. placing a directory with `~` in the path, to verify it was appropriately handled. 
3. Induce a race condition by running a scrapbook and opening a document in a span of a quarter second. 

Do you have any pointers on what you might have tried?

**Comment by Zimovets** [comment]
as I remember I did not do something special, I just tried open it with double click and got an error

23 січня 2019, 22:17:52, від "Prashanth" <notifications@github.com>:

I'm unable to repro it. I also tried:
Overloading the command with double-clicks placing a directory with ~ in the path, to verify it was appropriately handled. Induce a race condition by running a scrapbook and opening a document in a span of a quarter second. Do you have any pointers on what you might have tried?

**Comment by StephenWeatherford** [comment]
@Zimovets You only need to single click to open a single in vs code. We have seen occasional cases where double-clicking will cause errors similar to this due to timing issues (as it's registering it as two separate attempts to open). We'll make sure our debounce code that we've placed in similar situations is active here, but in the meantime, I wouldn't worry about it unless it's blocking you.  Thanks for reporting!

**Comment by PrashanthCorp** [comment]
To do: Check if we use the debounce from shared package .

**Comment by nturinski** [comment]
This was resolved with https://github.com/microsoft/vscode-cosmosdb/pull/954/files
