### ISSUE TITLE
Problem connect login string Visual Studio Code 

### ISSUE THREAD

**Issue by mrakovich** [Microsoft/vscode-cosmosdb#1003]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: {"name":"cluster0-shard-00-01-psdsj.mongodb.net:27017","err":{"name":"MongoError","message":"bad auth Authentication failed.","ok":0,"errmsg":"bad auth Authentication failed.","code":8000,"codeName":"AtlasError"}}

Version: 0.9.1
OS: darwin

**Comment by StephenWeatherford** [comment]
@mrakovich Is it possible you've given bad credentials?  That's what the error message seems to indicate.  Thx.
