### ISSUE TITLE
Connection VSCode

### ISSUE THREAD

**Issue by mrakovich** [Microsoft/vscode-cosmosdb#1004]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: connection 212 to cluster0-shard-00-01-psdsj.mongodb.net:27017 closed

Version: 0.9.1
OS: darwin

**Comment by StephenWeatherford** [comment]
Looks like you're using a local instance of a mongodb database.  Is it actually running?  Can you access it from the mongo shell?  Thx.
