### ISSUE TITLE
"There is no provider registered than can provide view data"

### ISSUE THREAD

**Issue by grough** [Microsoft/vscode-cosmosdb#1006]
The extension doesn't appear to be in a working state after I install it and restart the editor. This is what the UI looks like:

<img width="352" alt="screen shot 2019-01-23 at 2 22 23 pm" src="https://user-images.githubusercontent.com/214106/51631310-58be7b80-1f1a-11e9-8001-bb10d72eb92b.png">

And selecting any option yields errors:

```
Error: command 'cosmosDB.attachDatabaseAccount' not found
    at t._tryExecuteCommand (commandService.ts:59)
    at commandService.ts:52
    at <anonymous>
	…
notificationsAlerts.ts:38 Error: command 'cosmosDB.createAccount' not found
    at t._tryExecuteCommand (commandService.ts:59)
    at commandService.ts:52
    at <anonymous>
	…
```

VS Code 1.30.2
Azure Cosmos DB 0.9.1

**Comment by EricJizbaMSFT** [comment]
@grough do you have the azure account extension installed? It's supposed to be installed automatically when you install Cosmos DB, but I'm wondering if it wasn't...

**Comment by grough** [comment]
@EricJizbaMSFT I had it installed, but it was disabled. When I enable the Azure Account extension Cosmos DB works as expected. Thank you!

**Comment by StephenWeatherford** [comment]
@grough Glad @EricJizbaMSFT's suggestion fixed it for you. Do you happen to know how you got into a state where the Azure Account extension was disable but Cosmos wasn't?  vscode isn't supposed to let that happen.  Thanks!

**Comment by StephenWeatherford** [comment]
Thanks!  Indeed a vscode bug, but it's already been fixed in the latest Insiders: https://github.com/Microsoft/vscode/issues/58775
