### ISSUE TITLE
No syntax hightlighting shows on scrapbook

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#1011]
**Version**: 1.31.0-insider (user setup)
**Node.js**: 10.2.0
**OS**: All
**Regression From**: Work well on previous release 0.9.1
**Extension build:** [20190124.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2452)

**Repro Steps:**
1. Create a new mongo scrapbook.
2. Connect to one mongo database then type the following into it.
![image](https://user-images.githubusercontent.com/34729022/51733683-0c5f7100-20bd-11e9-9e96-f4adf397ff3d.png)

**Expect**:
There is a syntax hightlighting for the entered code.

**Actual**:
There is no syntax highlighting.
![image](https://user-images.githubusercontent.com/34729022/51733770-652f0980-20bd-11e9-96b0-8bf88a716eca.png)

**Comment by StephenWeatherford** [comment]
Only seems to repro in the vsce package'd version.
