### ISSUE TITLE
Attach to emulator with custom port

### ISSUE THREAD

**Issue by kirisich** [Microsoft/vscode-cosmosdb#1013]
Because of several reasons I can't use 8081 port for cosmosdb emulator.
when I attach emulator in vs code i see  "unable to reach emulator, please ensure it started and writing to the appropriate port. Then try again" 
when i use the connection string for emulator it shows an error "self signed certificate" 

so there's no option to choose custom port, for example it is 1234.
Is there any updates regarding this feature, are you planning to have it ?
thanks

**Comment by EricJizbaMSFT** [comment]
@kirisich can you try using one of the following [VS Code settings](https://code.visualstudio.com/docs/getstarted/settings):
`cosmosDB.emulator.port`
`cosmosDB.emulator.mongoPort`

**Comment by kirisich** [comment]
yeap, this worked, thanks a lot.
sorry for late reply

**Comment by StephenWeatherford** [comment]
Great, good to know!  I've also changed the error message to point the user to these settings.
