### ISSUE TITLE
Accounts created in portal are not recognized as graph/mongo by the extension

### ISSUE THREAD

**Issue by ghstahl** [Microsoft/vscode-cosmosdb#1018]
VS Code 1.30.2
Installed the Azure Cosmos DB extension
Verified that is is enabled.

restarted VS code several times.
uninstalled VS code and reinstalled.

Expected:
I expected to see the "Azure Cosmos DB" in the explorer panel

Actual:
Nothing

Side Note:
The closest I get to seeing a cosmos db is clicking on my Azure extension, and after login I see a "Cosmos DB" section.  Not your stuff, but that one works.

I am looking for the gremlin support.

**Comment by ghstahl** [comment]
Azure Cosmos DB is installed and enabled, however it doesn't show up.

![image](https://user-images.githubusercontent.com/201257/51850700-2379ab00-22d7-11e9-89d0-4e893fef8105.png)

NOTE: Under azure the Cosmos DB option is there but I don't think that is your stuff.  I just called it out as someone is able to connect to Cosmos DB
![image](https://user-images.githubusercontent.com/201257/51850681-165cbc00-22d7-11e9-93c4-d95c05220272.png)


I expect to see it here, but I don't.
![image](https://user-images.githubusercontent.com/201257/51850713-2a082280-22d7-11e9-90a3-2a606b64a4f0.png)

**Comment by EricJizbaMSFT** [comment]
@ghstahl that is our stuff. We used to have it in the file explorer view (where you expected it) a long time ago, but got feedback that people wanted their file explorer view to stay clean of Azure stuff. If you prefer to have it in the file explorer view, then we might be able to repurpose this issue to create a setting for that.

**Comment by ghstahl** [comment]
Ah, ok then perhaps this is a different problem.
Where is the gremlin interface?
The following, [MarketPlace](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb) illustrates that I should be able to click on "Contacts", "Persons" in my case, and see a right panel that has Json|Graph options.
Nothing comes up when I click or double click on that "Persons" collection.

![image](https://user-images.githubusercontent.com/201257/51851408-b49d5180-22d8-11e9-8d0d-3171696969b7.png)

**Comment by EricJizbaMSFT** [comment]
Interesting - based on your screenshot we're detecting that as a 'SQL' account instead of a 'Gremlin" account. It could be because the type is listed as `(Gremlin (graph))` instead of just `(Gremlin)` like a few of your other accounts.

Can you open that account in the portal and make sure the "defaultExperience" tag is set to "graph"?
![screen shot 2019-01-28 at 8 51 13 am](https://user-images.githubusercontent.com/11282622/51851981-ee228c80-22d9-11e9-9bcf-88b7dd11f36f.png)

Otherwise as a workaround, you can do the following:
1. Right click on account and copy connection string
1. Right click on `Attached Database Accounts` and connect that connection string as Gremlin

**Comment by ghstahl** [comment]
defaultExperience was set to Gremlin (graph)!

Hmm.
It said "Gremlin (graph)", when I clicked the dropdown it cmae with the warning "Only 500 tags..."
I typed in "Graph", hit save, and then I got the "Error"

I have no clue what this 500 Tag warning is, unless someone set something up that adds a bunch of stuff that I don't know about.  I just simply clicked on the "Create Cosmos DB" and let you guys create that Perons collection.

![image](https://user-images.githubusercontent.com/201257/51852579-3aba9780-22db-11e9-9bc6-b1c37029a22b.png)

**Comment by EricJizbaMSFT** [comment]
Yeah not sure about those warnings in the portal. Just curious - how did you create this account? Any idea how the tag was set to "Gremlin (graph)"?

**Comment by ghstahl** [comment]
Looks like the Azure portal is the one putting in the Gremlin (graph).
My contributions are 
1. The account name "forericjizbamsft"
2. Select "Gremlin (graph)"
3. Create
![image](https://user-images.githubusercontent.com/201257/51855150-5d4faf00-22e1-11e9-833f-072ab47e2fae.png)
![image](https://user-images.githubusercontent.com/201257/51855815-01862580-22e3-11e9-9ef5-259aae6fa0c7.png)

**Comment by EricJizbaMSFT** [comment]
Thanks @ghstahl we can repro.

@StephenWeatherford FYI looks like it affects mongo as well:
![screen shot 2019-01-28 at 1 11 28 pm](https://user-images.githubusercontent.com/11282622/51866631-508d8400-22fe-11e9-997a-ce2301043ccf.png)
