### ISSUE TITLE
An error occurs when opening one document which name contains *

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-cosmosdb#1019]
**Version**: 1.31.0-insider (user setup)
**Node.js**: 10.2.0
**OS**: Windows
**Regression From**: Not a regression
**Extension build:** [20190124.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2452)

**Steps to reproduce:**
1. Choose one Mongo DB account -> Create a database, collection and document.
2. Add "name" property for the document which value contains * like 
![image](https://user-images.githubusercontent.com/34729022/51820443-b1be5300-2310-11e9-8943-b621ebbb6338.png)

3. Save it then try to reopen the document after uploading successfully.

**Expect:**
The document can be reopened successfully.

**Actual:**
Fail to open the document with the below error.
![image](https://user-images.githubusercontent.com/34729022/51820384-85a2d200-2310-11e9-934b-570963e7cd42.png)

**More info:**
This issue doesn't reproduce on Mac.

**Comment by PrashanthCorp** [comment]
Replace special characters with an _ perhaps?
We may not need to do any of this, if we use the virtual file system to display files

**Comment by wwlorey** [comment]
Closing since we changed to a new file system
