### ISSUE TITLE
An error occurs when trying to open a graph

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-cosmosdb#1020]
**Version:** 1.31.0-insider (user setup)
**Node.js:** v10.13.0
**OS:** Win10/MacOS/Linux
**Regression From:** Work well on previous release 0.9.1
**Extension build:** [20190124.12](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2452&view=results)

**Repro Steps:**
1. Create a database under one Germlin account.
2. Create a graph under the database and open the graph.

**Expect:**
No error occurs and succeed to open the graph.

**Actual:**
An error occurs when trying to open the graph.
![image](https://user-images.githubusercontent.com/41351993/51820358-6dcb4e00-2310-11e9-9623-7fc053ed7595.png)

**Comment by StephenWeatherford** [comment]
Occurs only with the VSIX
