### ISSUE TITLE
The file name are inconsistent between notification and editor 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1021]
**OS:** Win10/Linux/ Mac
**Node.js:** V10.14.2
**Regression:** Not a Regresion
**Build Version:** [20190127.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2509&view=results)

**Repro Steps:**
1. Create a new SQL account -> Create a new database -> Create a new collection ->Create a new document.
2. Make changes and press 'Ctrl / Cmd + S' to save it -> Check the file name between notification and editor.

**Expect:**
Keep consistent.

**Actual:**
The file name are inconsistent.
![image](https://user-images.githubusercontent.com/34729092/51821821-3072ac00-228f-11e9-81db-6e1966d3066a.png)

**Comment by v-dantch** [comment]
Add more info:
This issue also reproduces for stored procedures like below:
![image](https://user-images.githubusercontent.com/34729092/52037697-9441e280-24e4-11e9-81d7-59c2d5b24aa4.png)

**Comment by PrashanthCorp** [comment]
1. Replace special characters with an _ perhaps? 
2. We may not need to do any of this, if we use the virtual file system to display files
