### ISSUE TITLE
[Suggestion]Update 'Cloud' to 'Azure' for 'Update to Cloud'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#1026]
**OS:** All
**Node.js:** V10.14.0
**Build Version**: [20190129.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2562)

**Repro Steps:**
1. Open one document in editor.
2. Right click anywhere on the editor --> Check the editor context mennu.

**Actual:**
Display 'Update to Cloud'.
![image](https://user-images.githubusercontent.com/34729092/52043629-10dcbd00-24f5-11e9-8956-c8ed9ead861a.png)

**Suggestion:**
Display 'Update to Azure'.

**More Info:**
This issue also reproduces for the notification when updating the changed documents.
![image](https://user-images.githubusercontent.com/34729092/52043785-6e710980-24f5-11e9-8bbc-172279b2ab25.png)

**Comment by StephenWeatherford** [comment]
Eric's point is good - we need to leave them as "Cloud" for those users who are not using Azure.  Thanks.

**Comment by v-dantch** [comment]
Got it. Thanks for your update.
