### ISSUE TITLE
Add telemetry to TaskProvider and DebugProvider

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#1035]
Since these aren't commands, we don't get our telemetry by default. If we want it, we probably need to add it manually.

Talking about the code here:
https://github.com/Microsoft/vscode-azurefunctions/tree/master/src/debug

**Comment by StephenWeatherford** [comment]
Right repo?

**Comment by EricJizbaMSFT** [comment]
Lol nope
