### ISSUE TITLE
API names in VS Code are different than Portal

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#1037]
Note that in the azure portal we see this for the choices for the API

![image](https://user-images.githubusercontent.com/1202528/52670333-449ce700-2ee6-11e9-84b0-6b2e13b8ab96.png)

and we see this in the vs code extension for cosmos

![image](https://user-images.githubusercontent.com/1202528/52670350-51b9d600-2ee6-11e9-93a7-c4b402e3ebb6.png)

I assume that`Core(SQL)` in azure portal === `SQL (DocumentDB)` in the vscode extension.

I think we should make them the same.

Also - the quickstart in the docs points to the portal's version using `Core (SQL)`. 

I ran into this when going through [the quickstart](https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-nodejs-get-started) again and trying it with vs code. This the confusion.

**Comment by StephenWeatherford** [comment]
I already changed out descriptions to match the portal's new ones in #1024. Will ship very soon.

@fiveisprime You want to update the quick start?

**Comment by PrashanthCorp** [comment]
Already fixed
