### ISSUE TITLE
Extension 'ms-azuretools.vscode-cosmosdb' uses the 'vscode.previewHtml' command which is deprecated and will be removed soon.

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#1038]
**OS:** Windows, Mac
**Build Version:** [20190213.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3146)

**Repro Steps:**
1. Reload VS Code.
2. F1 --> Type and select 'Graph(Gremlin):Open Graph Explorer' -->Select a subscription --> Select an account --> Select a database --> Select a graph.
3. Check the result.

**Expect:** 
Succeed to open the Graph Explorer without any warnings.

**Actual:**
Pop up a warning.
![image](https://user-images.githubusercontent.com/34729092/52701291-bd279600-2f2e-11e9-8cc6-784f2236c714.png)

**Comment by StephenWeatherford** [comment]
Prashanth fixed this
