### ISSUE TITLE
[Suggestion]The textbox border is visible 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#1041]
**OS:** Windows, Mac, Linux
**Build Version:** [20190213.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3146)
**Regression**: Not a Regression

**Repro Steps:**
1. Open a Graph Explorer.
2. Check the textbox.

**Actual:**
The textbox border is invisible till clicking it.
![image](https://user-images.githubusercontent.com/34729092/52702526-332cfc80-2f31-11e9-9623-83a8bd6f42ba.png)

**Suggestion:**
The textbox border is visible.

**Comment by StephenWeatherford** [comment]
You're using vscode insiders, right?  This is a bug in Insiders.

**Comment by StephenWeatherford** [comment]
Actually, it was a bug in master, but even with that fix it regressed in Insiders.  Both should be fixed now.

**Comment by v-dantch** [comment]
Hi @StephenWeatherford yes, we are using VS Code Insiders for the most part.
