### ISSUE TITLE
[Mac]The shortcut of select all is 'Ctrl+Shift+A' rather than 'Command+A' on opened graph

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#1047]
**OS:** Mac
**Node.js:** V10.14.2
**Regression:** Not a Regression
**Build Version:** [20190214.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3206)

**Steps to reproduce:**
1. Drill down from one Graph account -> Database -> Graph
2. Type g.V() on the textbox for querying.
3. Try to select all the typed string using shortcut.

**Expect:**
All the string are selected after pressing **'Command+A'**.

**Actual:**
All the string are selected after pressing '**Ctrl+Shift+A**'.

**Comment by PrashanthCorp** [comment]
Verify this with the new webview limitation.

**Comment by PrashanthCorp** [comment]
Stephen verified this. Doesn't repo
