### ISSUE TITLE
Azure Cosmos Db extension error no such file or directory when browsing azure document db

### ISSUE THREAD

**Issue by eric-couch** [Microsoft/vscode-cosmosdb#1050]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
connected to my azure document db, but I can't browse a particular document

Action: cosmosDB.openDocument
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\xxxxxxx\AppData\Local\Temp\vscode-cosmosdb-editor\xxxxxx
-cosmos-document.json'

Version: 0.10.0
OS: win32

**Comment by StephenWeatherford** [comment]
@eric-couch This is always a particular document only?  Is there anything unusual about the _id of that document?

cc @PrashanthCorp
