### ISSUE TITLE
I am getting this error when trying to attach local mongodb instance

### ISSUE THREAD

**Issue by Adeelasd** [Microsoft/vscode-cosmosdb#1051]
Repro steps:

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.10.0
OS: linux

**Comment by PrashanthCorp** [comment]
Hi @Adeelasd , 
We use keytar to handle passwords and wallet access. There's a similar issue on Mailspring about secrets not working: https://github.com/Foundry376/Mailspring/issues/681

What distro and desktop environment are you using? 

You might need to install gnome-keyring. Let us know if that works out for you.

**Comment by Adeelasd** [comment]
it was a problem with the MongoDB driver an update fixed it

**Comment by StephenWeatherford** [comment]
Thanks for letting us know.
