### ISSUE TITLE
Show an empty document name on the opened tab when the value of partition key contains slashes

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#1052]
**OS:** All
**Node.js:** V10.14.2
**Regression:** Not a Regression
**Build Version:** [20190218.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=3315)

**Steps to  reproduce:**
1. Expand one SQL account ->Create a database and collection with Partition Key 'name'.
2. Create a document with 'id=**docutest1**; The value of Partition Key = **name/**' -> Press 'Enter'.
3. Check the shown document name of the opened tab.

**Expect**:
It shows '**name/**-cosmos-cocument.json' on the opened tab.

**Actual**:
It shows '-cosmos-cocument.json' on the opened tab.
![image](https://user-images.githubusercontent.com/34729022/53000003-1e8eaf80-33dc-11e9-90df-0180a8b57992.png)

**Comment by PrashanthCorp** [comment]
We won't fix for now. Mostly cosmetic.
