### ISSUE TITLE
Error upon selecting first document in first collection in locally connected MongoDB

### ISSUE THREAD

**Issue by shadercode** [Microsoft/vscode-cosmosdb#1054]
Repro steps:
1. Open a connection to a locally running mongodb at this url: mongodb:\\localhost:27036.
2. Click on the first document listed in the first collection.
![mongodb_garbled_collection_listing](https://user-images.githubusercontent.com/5846585/53045805-65fc5680-3443-11e9-8baf-79510bab1265.png)

Action: cosmosDB.openDocument
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\jleiba\AppData\Local\Temp\vscode-cosmosdb-editor\r�-�RB��J�
j-cosmos-document.json'

Version: 0.10.0
OS: win32

**Comment by shadercode** [comment]
By the way, this collection only appears garbled in Cosmos DB browser.  It looks perfectly normal in other MongoDB client tools, like Studio3T.

**Comment by StephenWeatherford** [comment]
Do the document contents appear normal in the editor (right-hand side)?  what's the encoding (you can find that in the editor at the bottom right:

![image](https://user-images.githubusercontent.com/6913354/53046400-cb047c00-3444-11e9-83d8-6cb25b782516.png)
![image](https://user-images.githubusercontent.com/6913354/53046433-dbb4f200-3444-11e9-8765-ed9d8c79e244.png)

Thanks!
