### ISSUE TITLE
fail to connect Azure Cosmos DB in VScode to Atlas

### ISSUE THREAD

**Issue by MayaMua** [Microsoft/vscode-cosmosdb#1055]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: {"name":"mycluster-shard-00-00-ue0qi.azure.mongodb.net:27017","err":{"name":"MongoError","message":"bad auth Authentication failed.","ok":0,"errmsg":"bad auth Authentication failed.","code":8000,"codeName":"AtlasError"}}

Version: 0.10.0
OS: darwin

**Comment by PrashanthCorp** [comment]
Might be a dupe of #724

**Comment by PrashanthCorp** [comment]
That's a mongo error that the password is wrong. See : "bad auth Authentication failed".
