### ISSUE TITLE
Getting timed out updating documents under Ubuntu

### ISSUE THREAD

**Issue by fanshaohua-fan** [Microsoft/vscode-cosmosdb#1056]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use configuration-production"

Version: 0.10.0
OS: linux

**Comment by StephenWeatherford** [comment]
Would you mind quickly trying an experimental version that may report better errors? It's easy to uninstall afterwards via the extensions view in vs code.  See instructions here: https://github.com/Microsoft/vscode-cosmosdb/issues/852#issuecomment-479734886.

Thanks!
Stephen

**Comment by fanshaohua-fan** [comment]
@StephenWeatherford , Thanks for the information.
I've installed the preview version of extension, but after so long time, I forgot what I did at that moment...

**Comment by StephenWeatherford** [comment]
Okay, I appreciate your taking the time to try this out.  I'll close for now (we will be incorporating my changes at some point anyway).  Please let us know if you find out anything more.  Thx!
