### ISSUE TITLE
an error

### ISSUE THREAD

**Issue by yangcrazy30** [Microsoft/vscode-cosmosdb#1059]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.createMongoCollection
Error type: 10107
Error Message: not master

Version: 0.10.0
OS: darwin

**Comment by PrashanthCorp** [comment]
This looks like an admin privileges issue AFAICT. There's usually access-control at the collection level.
