### ISSUE TITLE
new Date() does not get accepted

### ISSUE THREAD

**Issue by tosinek** [microsoft/vscode-cosmosdb#1060]
Repro steps:
db.eventsunwound.aggregate([ { $match: { 'udalosti.datum': { $gte: new Date("2019-02-01") } } } ])
Running against local MongoDB 4. When I copy paste the same command to the mongo console, it works ok. Removing "new" returns no data.

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: 'Unrecognized node type encountered. Could not parse newDate as part of newDate("2019-02-01")'. Please check syntax.

Version: 0.10.0
OS: win32

Related to #995

**Comment by PrashanthCorp** [comment]
Hi @tosinek , It looks like you're using the constructor. Using `$gte: Date(...)` should work

**Comment by PrashanthCorp** [comment]
Apologies, `ISODate` should work, `Date` won't.
