### ISSUE TITLE
monogdb connection with node

### ISSUE THREAD

**Issue by ansh07** [Microsoft/vscode-cosmosdb#1062]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [onlineshopkeeperdb.documents.azure.com:10255] on first connect [MongoError: getaddrinfo ENOTFOUND onlineshopkeeperdb.documents.azure.com onlineshopkeeperdb.documents.azure.com:10255]

Version: 0.10.0
OS: win32

**Comment by StephenWeatherford** [comment]
@ansh07 Is this a recurring issue, or has it been resolved?  The ENOTFOUND message simply means it can't find the server.
