### ISSUE TITLE
cosmosdbextentionissue

### ISSUE THREAD

**Issue by yashwanthchannegowda** [Microsoft/vscode-cosmosdb#1064]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.createAccount
Error type: Error
Error Message: Entry not found in cache.

Version: 0.10.0
OS: win32

**Comment by PrashanthCorp** [comment]
When we tried repro'ing, it looks like an authentication issue after VSCode was open for a long while (system sleeps, restarts, etc.). 

It looks like it could be an issue in an auth library used by azure-account.

**Comment by PrashanthCorp** [comment]
Looks like a case of : https://github.com/Microsoft/vscode-azure-account/issues/53

Closing as tracked upstream.
