### ISSUE TITLE
error

### ISSUE THREAD

**Issue by barel13** [Microsoft/vscode-cosmosdb#1065]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: connection 5 to cluster0-shard-00-02-4f5ja.gcp.mongodb.net:27017 closed

Version: 0.10.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @barel13 , 
1. Does this repro consistently? 
2. Does connecting to this database work fine on the mongo shell?
