### ISSUE TITLE
mongodb scrapbook cursor.map() and cursor.foreach() not supported?

### ISSUE THREAD

**Issue by steveland83** [microsoft/vscode-cosmosdb#1068]
The following query runs fine in the command line mongo shell, but fails when run in a mongodb scrapbook in VSCode (excluding the `map` segment of the query works).

`db.collection.find().limit(100).map(function(x){return x.something;});`

The error reported (a VS Code error notification, not a db returned error):
> db.series.find at 4:1: Error near line 3, column 32: 'mismatched input 'function' expecting {')', '{', '[', RegexLiteral, StringLiteral, 'null', BooleanLiteral, NumericLiteral}'. Please check syntax.

The same error occurs is `foreach` is substituted for `map`

**Comment by PrashanthCorp** [comment]
Hi @steveland83 , 
It looks like the parser is incorrectly deciding the end of the statement to be the first `;`. The parser has had problems with parsing full Javascript syntax in the past.

**Comment by mh0** [comment]
Hi,
Is there any way to execute commands from scrapbooks (via shell) without prior verifications or modifications done by the extension to get around this kind of problems ?
