### ISSUE TITLE
Pop up an error 'command 'vscode.previewHtml' not found' when opening a Graph Explorer

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#1070]
**OS:** Windows/Mac
**Build Version:** [20190313.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4006)

**Repro Steps:**
1. F1 -->Type and select 'Graph(Gremlin):Open Graph Explorer'.
2. Select a subscription --> Create a Gremlin account --> Create a new database --> Create a new Graph.
3. Check the result.

**Expect:**
Succeed to open Graph Explorer and no error pops up.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/54345380-2c60da80-4600-11e9-959c-e62de127d157.png)

**Comment by StephenWeatherford** [comment]
Is this vscode Insiders?

**Comment by v-dantch** [comment]
Hi @StephenWeatherford yes, we always test with VS Code-insiders.

**Comment by v-dantch** [comment]
Pop up below warning like [#1038](https://github.com/Microsoft/vscode-cosmosdb/issues/1038) when we verified this issue with the stable VS Code.
![image](https://user-images.githubusercontent.com/34729092/54423013-eb82c780-46cc-11e9-9954-21257a7210e5.png)

**Comment by PrashanthCorp** [comment]
Please verify if this still repros. Should have been fixed in 0.10.1
