### ISSUE TITLE
Timeout when executing an aggregate on mongoDB 

### ISSUE THREAD

**Issue by lannyfrank** [microsoft/vscode-cosmosdb#1071]
Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use database_name"

Version: 0.10.0
OS: win32

This error occurres when using this kind of connectionString
mongodb+srv://<userName>:<password>@host_service?retryWrites=true
(no database has been specified after the service)

while using this kind of connectionString works fine
mongodb+srv://<userName>:<password>@host_service/**database_name**?retryWrites=true

using this last kind of connectionString, you will see only the specified database, while using the first one, you will see every database allowed to the user...

**Comment by PrashanthCorp** [comment]
This error does not seem specific to the aggregate command. 

cc: @StephenWeatherford

**Comment by StephenWeatherford** [comment]
Would you mind quickly trying an experimental version that may report better errors? It's easy to uninstall afterwards via the extensions view in vs code.  See instructions here: https://github.com/Microsoft/vscode-cosmosdb/issues/852#issuecomment-479734886.

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
Fixed by #1162

Hopefully with this fix, you will now see the correct error message and be able to figure out the problem.  Thanks!
