### ISSUE TITLE
Question: how to change Mongodb aggregate limit

### ISSUE THREAD

**Issue by sublimeye** [microsoft/vscode-cosmosdb#1073]
Question:
1. How to make `limit` and `aggregate` with limit return more than 20 elements?
2. I saw `maxDocs` property mentioned in a couple of issues, but I don't understand where do I add it or maybe it's just a built-in internal `package.json` property that is controlled by the extension? I didn't find any mention of it in the documentation. I tried to set `maxDocs` as a global property in `settings.json` - it says that the property is unknown.

Current Behavior:
- `.find()` query returns as many objects as collection contains (at least up to 50)
- `.find().limit(N)` query returns `N` (if `N` <= 20), for `N` larger than 20 returns 20 only
- `.aggregate()` - returns 20 if `$limit` is not set
- `.aggregate([ {$limit: N} ])` – similar behavior to regular `find().limit()`. If `N` less than 20 returns N, otherwise return 20.

**Comment by wwlorey** [comment]
Hi @sublimeye, we just released [v0.14.0](https://github.com/microsoft/vscode-cosmosdb/releases/tag/v0.14.0) which added a setting called "azureDatabases.batchSize" that you can use to configure the aggregate limit.
