### ISSUE TITLE
Remove the 'Attach Emulator' on Command Palette for Linux/Mac

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#1077]
**OS**: Mac/Linux
**Extension Version:** [20190325.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4407&view=results)
Regression: Not a regression

**Steps to reproduce:**
1. Press F1 -> Type 'Attach Emulator'.

**Expect Experience:**
No 'Attach Emulator' lists on the  Command Palette.

**Actual Experience:**
The 'Attach Emulator' list on the Command Palette.
![image](https://user-images.githubusercontent.com/34729022/54982263-aaf63a00-4f67-11e9-97ed-c9d23ab43456.png)

**Comment by PrashanthCorp** [comment]
Closing as wontfix.
