### ISSUE TITLE
Display an blank at the bottom after dragging the Graph

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#1078]
**OS**: All
**Build Version**: [20190325.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4407&view=results)
**Regression**: Not a Regression

**Repro Steps:**
1. F1--> Run "Graph(Gremlin): Open Graph Explorer".
2. Drag the Graph-: pull it up -->pull it down.
3. Check the result.

**Expect:**
The Graph displays well.

**Actual:**
Display an blank at the bottom.
![image](https://user-images.githubusercontent.com/34729092/54985192-99b02c00-4f6d-11e9-9b4d-e5e875cee0cf.png)
![image](https://user-images.githubusercontent.com/34729092/54985233-ad5b9280-4f6d-11e9-93c8-893b2498b862.png)

**Comment by PrashanthCorp** [comment]
Closing as wontfix
