### ISSUE TITLE
[Unstable]All content has not been themed on graph editor with dark theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#1079]
**OS**: All
**Extension Version:** [20190325.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=4407&view=results)

**Steps to reproduce:**
1. Change the current theme to Dark.
2. Expand one Graph account -> Database -> Graph.
3. Open the graph editor -> Check the displayed items.

**Expect Experience:**
All content is clear.

**Actual Experience:**
Fail to see all these items. 
![image](https://user-images.githubusercontent.com/34729022/54986499-fdd3ef80-4f6f-11e9-9ee9-563ef782a7e1.png)

**More info:**
This issue doesn't reproduce after re-opening VS Code.

**Comment by PrashanthCorp** [comment]
Workaround is acceptable.
