### ISSUE TITLE
CosmosDB VS code Driver connection issue

### ISSUE THREAD

**Issue by Leon-Africa** [microsoft/vscode-cosmosdb#1086]
Reproduce:

Install CosmosDB extension - Sign in Azure Account - create a account via IDE (MongoDB API)

After creation error appears: Failed to connect to server (ERR connection refused)

Further when cannot create a database (via IDE using the extenion) - this throws error:

Cannot resolve tree item for element 1//subscriptions/xxx-7e1e-4430-9cf6-xxx/resourceGroups/xxxxx/providers/Microsoft.DocumentDB/databaseAccounts/xxx/xxx

**Comment by PrashanthCorp** [comment]
@Leon-Africa , 
1. Does this consistently reproduce? 
2. Was the account actually created ? After creation, does the account show up in the portal? 
3. Was the `1//` string appear as is, or did you modify it?

**Comment by Leon-Africa** [comment]
@PrashanthCorp 

1. Yes 
2. Account is not showing up in the portal when created from IDE
3. Copied string directly from the portal (What I did was created the DB via portal first (seeing that it was not working to create via IDE)- then refresh in IDE so the newly created DB can show - however I still get the connection error)

**Comment by StephenWeatherford** [comment]
@Leon-Africa I'm having trouble understanding how to reproduce this, and it sounds like there are multiple issues here. Starting with the first, it sounds like you're having trouble creating a MongoDB account, correct?  What error are you getting?
