### ISSUE TITLE
WTF!

### ISSUE THREAD

**Issue by DinHammer** [microsoft/vscode-cosmosdb#1090]
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: AuthorizationFailed
Error Message: The client 'live.com#msntech.azure@gmail.com' with object id '0c92ae9d-4bed-4b1d-9186-cb08b7ff4b63' does not have authorization to perform action 'Microsoft.Resources/subscriptions/resourcegroups/read' over scope '/subscriptions/5a7a3783-be09-4c9d-acb1-1ad5e6cba56a'.

Version: 0.10.1
OS: win32
VS Code Version: 1.33.1

<details>
<summary>Call Stack</summary>

```
module.exports.r.pipeline (dist/extension.bundle.js:666:516275)
o (dist/extension.bundle.js:666:110305)
o (dist/extension.bundle.js:537:56367)
dist/extension.bundle.js:537:57607
s (dist/extension.bundle.js:588:7021)
dist/extension.bundle.js:537:55288
F.module.exports.t.requestLibrarySink.t.headersOnly.t.streamedResponse.t.body.function.t.body.pipe.a [as _callback] (dist/extension.bundle.js:253:140730)
F.module.exports.F.init.t._callback.t.callback.t.callback (dist/extension.bundle.js:648:5443)
F.emit (events.js:182:13)
F.<anonymous> (dist/extension.bundle.js:648:18256)
F.emit (events.js:187:15)
IncomingMessage.<anonymous> (dist/extension.bundle.js:648:17098)
Object.onceWrapper (events.js:273:13)
IncomingMessage.emit (events.js:187:15)
endReadableNT (_stream_readable.js:1090:12)
process._tickCallback (internal/process/next_tick.js:63:19)
```

</details>

**Comment by PrashanthCorp** [comment]
I'm sorry @DinHammer this is not actionable

**Comment by PrashanthCorp** [comment]
@DinHammer , do you have any repro steps that lead you to the error? We
