### ISSUE TITLE
update() timeout BUT find() ok

### ISSUE THREAD

**Issue by futurenz** [microsoft/vscode-cosmosdb#1092]
simple query
db.inventory.updateOne( {rating:{$exists:true}},{$unset:{rating:''}});
causes this error but any find() query works. MongoDB Shell through Command Prompt or Power Shell work without issue
I see several other very similar issues have been logged - I am in New Zealand and the cluster is listed as in N.Virginia - is this more a distance thing?

1.
2.

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use test"

Version: 0.10.1
OS: win32
VS Code Version: 1.33.1

**Comment by PrashanthCorp** [comment]
Hi @futurenz , 
The error implies it was unable to set up the shell to run the command. Can you try a command like `db.inventory.findOneAndUpdate(<fields>)` and let us know if the issue exists? 
Also, please let us know if these commands run properly : findOne, count, insertOne

Again, thanks for using our extension. 

--Prashanth

**Comment by futurenz** [comment]
Hi Prashanth,
findOneAndUpdate fails
findOne is good
count is good
insertOne is good

Thanks for the prompt response.
regards

------ Original Message ------

**Comment by StephenWeatherford** [comment]
@futurenz I've made a fix that kept us from showing the real error in certain cases when the Mongo shell was used for a query (which would be the case for findOneAndUpdate).  Hopefully you will now get the correct error message (after next release) and be able to figure out the problem.  Please let us know if it doesn't.  Thanks!

**Comment by StephenWeatherford** [comment]
Fixed by #1162
