### ISSUE TITLE
Inserting ISODate causes an error with mongodb

### ISSUE THREAD

**Issue by Diggerfdf** [microsoft/vscode-cosmosdb#1096]
I noticed a problem when trying to use ISODate to set a date with a mongodb database.

When I set up the date in the shell, everything is fine. But when I try via VScode Azure, I got an error. The hour always is inserted with an offset of + 3 hours. I don't need to use the UTC time. But I'm at Sao Paulo, Brazil UTC -3.

This is an example with my date and time of birth:

``db.test.insert({
    'datetime': ISODate('1975-07-23T04:10:00')
})``

This is the result

``{
	"result": {
		"ok": 1,
		"n": 1
	},
	"ops": [
		{
			"datetime": "1975-07-23T07:10:00.000Z",
			"_id": "5cc38d66da0aca11a90af39a"
		}
	],
	"insertedCount": 1,
	"insertedIds": [
		"5cc38d66da0aca11a90af39a"
	]
}``

The time is (...)T07:10:00.000Z Why this is happening?

I'm using Kubuntu 18.04 fully upgraded, Azure Cosmos DB Version 0.10.1 and VScode 1.33.1 installed through anaconda.

**Comment by StephenWeatherford** [comment]
Other issues:
1) Date(1) gives the wrong result
1) ISODate(1) should give an error but does not

**Comment by PrashanthCorp** [comment]
TODO: 
1. Check to see if there's a way to get Mongo's ISO function call. 
2. Failing that, send command to the shell.

**Comment by PrashanthCorp** [comment]
@StephenWeatherford: Date(1) and new Date(1) give different results in node since the Function cal does not take any parameters -> Date(1) is equivalent to Date(). If a user chooses to use `Date ` instead of `new Date` we shouldn't give the users an error.

**Comment by nturinski** [comment]
Hi @Diggerfdf

Thanks very much for your patience.  This issue should be resolved now; please let me know if there are still issues with inserting ISODates.

Thank you and have a great weeekend! 😃
