### ISSUE TITLE
how to solve this

### ISSUE THREAD

**Issue by sandeepdas900** [Microsoft/vscode-cosmosdb#1097]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27071] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27071]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @sandeepdas900 , thanks for hte bug report! 
we've seen users encounter this error, and we're working on it.

**Comment by StephenWeatherford** [comment]
@sandeepdas900 Please see the suggestions in https://github.com/Microsoft/vscode-cosmosdb/issues/662, thanks!  If you're still having trouble, feel free to re-open.
