### ISSUE TITLE
Save file for a cosmosDB document seems pointless

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#110]
If a user wants to save to local disk, there is Ctrl+Shift+S (save in another file). 

Approaches: 
1. Open the doc at a file not in their workspace, but in the extension folder? 
2. Open doc in the temp folder

**Comment by EricJizbaMSFT** [comment]
Closing as dup of https://github.com/Microsoft/vscode-cosmosdb/issues/109
