### ISSUE TITLE
Help Connecting MongoDB with Visual Studio Code - IDE

### ISSUE THREAD

**Issue by Satyampc** [microsoft/vscode-cosmosdb#1111]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.33.1
Language: en

<details>
<summary>Call Stack</summary>

```
Pool.eventHandler mongodb-core/server.js:336:35
Pool.emit events.js:182:13
Connection.<anonymous> mongodb-core/pool.js:280:12
Object.onceWrapper events.js:273:13
Connection.emit events.js:182:13
Socket.errorHandler mongodb-core/connection.js:189:49
Object.onceWrapper events.js:273:13
Socket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by AlexYash** [comment]
Hi,
Are you trying to connect to CosmosDB or to a MongoDB server?

**Comment by Satyampc** [comment]
Hi Alex,
Thank you for the response, however the issue was resolved after I found the lost Database folder.
