### ISSUE TITLE
Increase mongo.shell.timeout default value

### ISSUE THREAD

**Issue by AlexYash** [microsoft/vscode-cosmosdb#1115]
At the moment default value is 5 which is very low in case of more or less complex requests to a Mongo Cloud Atlas cluster (like an aggregation query). I would suggest 30 as a default value.

**Comment by PrashanthCorp** [comment]
Thanks for the feedback @AlexYash ! We shall triage this later this week

**Comment by StephenWeatherford** [comment]
When I merge the error-handling PR, it should be fine to increase the timeout default.

**Comment by StephenWeatherford** [comment]
… which will be done this milestone, so it's okay whenever.

**Comment by AlexYash** [comment]
Good to hear it. Thank you gentlemen!
