### ISSUE TITLE
Add JS var support to MongoDB scrapbook 

### ISSUE THREAD

**Issue by AlexYash** [microsoft/vscode-cosmosdb#1116]
Hi,

It looks like MongoDB scrapbooks do not support JavaScript variables definitions so when I put into my scrapbook "var pipeline = [...]" I get an error. Thus I had to put all my aggregation pipeline directly into db.collection.aggregate() call which is not very effective considering debugging. While MongoDB shell handles this kind of scenarios.

Is it possible to add some JS support to the scrapbooks so it would be possible to run a block of JS/MongoDB code?

P.S. And thank you for this great extension.

**Comment by PrashanthCorp** [comment]
Hi @AlexYash, this is an existing feature request for our extension. We are working on getting it fixed.
