### ISSUE TITLE
Can't right-click delete document in a collection which has Shard Key

### ISSUE THREAD

**Issue by JenniferWood** [microsoft/vscode-cosmosdb#1118]
Repro steps:

1. Select a document
2. Right-click to delete it

Action: cosmosDB.deleteMongoDocument
Error type: 61
Error Message: query in command must target a single shard key

Version: 0.10.2
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.35.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
Function.MongoError.create mongodb-core/error.js:31:11
pool.js:497:72mongodb-core/pool.js:497:72
authenticateStragglers mongodb-core/pool.js:443:16
Connection.Pool.socketCount [as messageHandler] mongodb-core/pool.js:477:5
TLSSocket.dataHandler mongodb-core/connection.js:333:22
TLSSocket.emit events.js:182:13
addChunk _stream_readable.js:279:12
readableAddChunk _stream_readable.js:264:11
TLSSocket.Readable.push _stream_readable.js:219:10
TLSWrap.onread net.js:636:20
```

</details>

**Comment by PrashanthCorp** [comment]
@JenniferWood thanks for the report. Did you create the sharded collections in the extension?

**Comment by jbinard** [comment]
We have a similiar issue with the Data Explorer from the Azure Portal.
When clicking on the "delete" button of a document in a collection with a shared key, it does nothing.
In the browser console we have a 400 error with the message "Command delete failed: query in command must target a single shard key."
We can't update a document in this collection. In this case, we get a popup with "Command update failed: query in command must target a single shard key."

We also tried with the shell from the Data Explorer and we have the same issue. Currently, we have no way to update or delete our document.

It looks like there is a serious issue with the Portal Data Explorer :(

**Comment by ddobric** [comment]
Have the same issue in VS code: 
_right click on collection | new document._

![image](https://user-images.githubusercontent.com/1756871/72383728-57cebd00-371c-11ea-8d0b-4fc2dc2b1297.png)
