### ISSUE TITLE
An error occurs when creating a Mongo database with command

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-cosmosdb#1119]
**Version**: 1.34.20-insider (user setup)
**Node.js**: 10.2.0
**OS**: Windows
**Regression From**: Not a regression
**Extension build:** [20190520.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6128)

**Steps to reproduce:**
1. Press F1 -> Select 'MongoDB: Create Databse'
2. Click 'Create New Account' -> Type an account name -> Select an API for the account -> Select a resource group -> Select a location.
3. Enter a name for the new database -> Check the result.

**Expect Experience:**

The database can be created successfully.

**Actual Experience:**

The below error occurs.
![image](https://user-images.githubusercontent.com/34729022/58085208-e53e2980-7bee-11e9-8e71-e464516ea696.png)

**More info:**

This issue doesn't reproduce when creating the database with an existing account(Select an existing account instead of creating a new account in step2)

**Comment by PrashanthCorp** [comment]
Notes: 
Could be down to revealing/searching for the treeItem before its parent is created.
