### ISSUE TITLE
Error while creating azure cosmosdb database

### ISSUE THREAD

**Issue by vensgal** [microsoft/vscode-cosmosdb#1123]
Repro steps:

1.
2.

Action: cosmosDB.createDocDBDatabase
Error type: 407
Error Message: 
<head>
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
  <title>McAfee Web Gateway - Notification</title>
  </head>

<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
  <tr>
    <td class='titleData'>
      Authentication Required.
    </td>
  </tr>
</table>

<table class="contentTable">
  <tr>
    <td class="contentData">
      You must be authenticated to access this URL.
    </td>
  </tr>
</table>

<table class="infoTable">
  <tr>
    <td class="infoData">
      <b>URL: </b>https://demoaccount2-193.documents.azure.com<br />
      <b>U...

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

**Comment by vensgal** [comment]
while creating database in Azure CosmosDb extension of VS Code. I am getting the above error.

**Comment by PrashanthCorp** [comment]
1. Are you able to create the db on the portal? 
2. The 407 error suggests there's a problem with proxies. Do pings from the terminal work fine?
