### ISSUE TITLE
Unable to copy connection string in remote environments

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-cosmosdb#1124]
Repro steps:
1. Connect to a remote environment and install the extension in the remote
2. Right-click an account and choose "Copy connection string"

Action: cosmosDB.copyConnectionString
Error type: Error
Error Message: Couldn't find the required `xsel` binary. On Debian/Ubuntu you can install it with: sudo apt install xsel

Version: 0.10.2
OS: linux
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
handler clipboardy/linux.js:7:9
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by fiveisprime** [comment]
Installing `xsel` on the remote machine results in a different error.

Action: cosmosDB.copyConnectionString
Error type: 1
Error Message: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Inappropriate ioctl for device



Version: 0.10.2
OS: linux
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Promise.all.then.arr execa/index.js:236:11
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment]
It looks like the release uses `clipboardy` : https://github.com/microsoft/vscode-cosmosdb/blob/v0.10.2/src/extension.ts#L161, 
while master has the fix:  https://github.com/microsoft/vscode-cosmosdb/blob/master/src/extension.ts#L159
