### ISSUE TITLE
Auhtentication failed when connect mongodb with username and password on local machine

### ISSUE THREAD

**Issue by zabahey** [microsoft/vscode-cosmosdb#1127]
Repro steps:

1. connect the database with mongodb://<<user>>:<<password>>@localhost:27017
2. all table list in Azure cosmosdb window
3. click on any database in the list get Error: Authentication Failed

Action: cosmosDB.attachDatabaseAccount
Error type: 18
Error Message: Authentication failed.

Version: 0.10.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.MongoError.create mongodb-core/error.js:31:11
mongodb-core/pool.js:497:72
authenticateStragglers mongodb-core/pool.js:443:16
Connection.Pool.socketCount [as messageHandler] mongodb-core/pool.js:477:5
Socket.dataHandler mongodb-core/connection.js:333:22
Socket.emit events.js:182:13
Socket.EventEmitter.emit domain.js:442:20
addChunk _stream_readable.js:279:12
readableAddChunk _stream_readable.js:264:11
Socket.Readable.push _stream_readable.js:219:10
TCP.onread net.js:636:20
```

</details>

**Comment by ldsmike88** [comment]
I get the same thing. If I add "admin" to the connection string (mongodb://<>:<>@localhost:27017/admin) it only shows the admin collection.

**Comment by ldsmike88** [comment]
I figured it out.

`mongodb://username:password@127.0.0.1:27017/?authSource=admin`

if you use `/admin` it only shows that collection, but if you remove it and use the option authSource `/?authSource=admin` it works as expected.

Hope this helps!

**Comment by PrashanthCorp** [comment]
Looks like it's fixed. Thanks for the input @ldsmike88 !
