### ISSUE TITLE
Connect to emulator on local network

### ISSUE THREAD

**Issue by philliphoff** [microsoft/vscode-cosmosdb#1129]
I'm not able to connect VS Code to a Cosmos DB emulator running on the local Windows machine from a Mac on that same network.  If I use a `https` endpoint, I get a "self-signed cert" error.  If I use a `http` endpoint, I get a "protocol not supported" error.

Until such time as the emulator is cross-platform, it'd be nice to be able to point to the Windows version from the Mac.

**Comment by arm-courses** [comment]
I have the same error but on Arch Linux. I also tried to attach and emulator with the Attach Emulator command but it doesn't ask for any connection string. Is it possible to attach the cosmosdb emulator on linux ?
