### ISSUE TITLE
Error Message: The user name or passphrase you entered is not correct.

### ISSUE THREAD

**Issue by incheolha** [microsoft/vscode-cosmosdb#1131]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: The user name or passphrase you entered is not correct.

Version: 0.10.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

**Comment by PrashanthCorp** [comment]
Did you try:

Copying the connection string from the portal as is and pasting it into the extension.
Retrying the attach, just to check if the username or password was entered incorrectly?
Feel free to add more details, but please ensure you do not add any confidential info. :-)
