### ISSUE TITLE
unable to modify db 

### ISSUE THREAD

**Issue by suraj-kawale-au2** [microsoft/vscode-cosmosdb#1132]
Repro steps:

1.
2.

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: Failed to update document with _id '5d09522ac5a2a4afc0124dac'.

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Function.<anonymous> extension.bundle.js:181:35997
s extension.bundle.js:181:34287
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment]
Can you add some details on what you did with the database when you got this error?

**Comment by suraj-kawale-au2** [comment]
No, It was due to some Update VsCode had. Due to which we weren't able to update DB using Azure Cosmos DB. But later After update, it worked fine.
