### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by abhishek-bhati-au2** [microsoft/vscode-cosmosdb#1134]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: Couldn't create item: The secret was transferred or encrypted in an invalid way.

Version: 0.10.2
OS: linux
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

**Comment by PrashanthCorp** [comment]
1. Were you trying to attach a mongo account, or another database account? 
2. Did you check if the access was given to your user credentials? 
3. If mongo, did you try connecting to it from the mongo shell?

**Comment by abhishek-bhati-au2** [comment]
Thanks... But I don't know how problem has solved when I just reload
cosmosdb

**Comment by StephenWeatherford** [comment]
Thanks for letting us know.
