### ISSUE TITLE
Can't connect to emulator with Mongo DB API - SSL error

### ISSUE THREAD

**Issue by ckcampbell248** [microsoft/vscode-cosmosdb#1137]
Repro steps:

1. Right click "Attach Database Accounts"
2. Select "MongoDB"

Action: cosmosDB.attachEmulator
Error type: Error
Error Message: failed to connect to server [localhost:10255] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:10255]

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Pool.eventHandler mongodb-core/server.js:336:35
Pool.emit events.js:182:13
Connection.<anonymous> mongodb-core/pool.js:280:12
Object.onceWrapper events.js:273:13
Connection.emit events.js:182:13
TLSSocket.errorHandler mongodb-core/connection.js:189:49
Object.onceWrapper events.js:273:13
TLSSocket.emit events.js:182:13
TLSSocket._emitTLSError _tls_wrap.js:604:10
Socket.TLSSocket._init.wrap.on _tls_wrap.js:547:36
Socket.emit events.js:182:13
emitErrorNT destroy.js:82:8
emitErrorAndCloseNT destroy.js:50:3
process._tickCallback next_tick.js:63:19
```

</details>

**Comment by PrashanthCorp** [comment]
1. Do you have a local instance of the mongo server running? 
2. Can you provide more specific repro steps?

**Comment by rgherta** [comment]
similar error when connecting to CosmosDB from behind an enterprise firewall / proxy.
It would be nice to have an option to add a ssh tunnel.

**Comment by StephenWeatherford** [comment]
@prashanthcorp I can connect to SQL emulator, but not mongo.

**Comment by StephenWeatherford** [comment]
Please see https://github.com/microsoft/vscode-cosmosdb/wiki/Debugging-Connection-Errors. The emulator changed so that you have to explicitly enable the MongoDB port when starting.  Will update our error message to point to this wiki.
