### ISSUE TITLE
Authentication failed with correct credentials

### ISSUE THREAD

**Issue by rimantoro** [microsoft/vscode-cosmosdb#1138]
Repro steps:

Want to connect to my mongodb4 in local machine.

1. Attach connection mongodb://username:password@127.0.0.1:27018
2. Try to connect, and I get this error.

Action: cosmosDB.createMongoDatabase
Error type: 18
Error Message: Authentication failed.

Version: 0.10.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.35.1
Language: en

<details>
<summary>Call Stack</summary>

```
Function.MongoError.create mongodb-core/error.js:31:11
mongodb-core/pool.js:497:72
authenticateStragglers mongodb-core/pool.js:443:16
Connection.Pool.socketCount [as messageHandler] mongodb-core/pool.js:477:5
Socket.dataHandler mongodb-core/connection.js:333:22
Socket.emit events.js:182:13
addChunk _stream_readable.js:279:12
readableAddChunk _stream_readable.js:264:11
Socket.Readable.push _stream_readable.js:219:10
TCP.onread net.js:636:20
```

</details>

**Comment by PrashanthCorp** [comment]
Looks like you're connecting to a local mongo instance. 
1. Is it running? 
2. Do you have a specific set of repro steps that we can try out? 
3. Did you try connecting through the terminal  `mongo connect(username:password@127.0.0.1:27018) ` , or get into the mongo shell then connect through the URL ? 

Let us know what works and doesn't.
