### ISSUE TITLE
[Suggestion]Add an option to select multiple attached accounts to detach

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1141]
**OS:** All
**Build Version:** [20190702.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7390)
**Regression**: Not a Regression

**Repro Steps:**
1. Attach multiple accounts using connection string.
2. Try to detach them.

**Actual:**
Only one account is allowed to be selected to detach.
![image](https://user-images.githubusercontent.com/34729092/60569897-f4de8f80-9da2-11e9-9610-f9717c8dd8f9.png)

**Suggestion:**
Add an option to select multiple attached accounts to detach.

**Comment by StephenWeatherford** [comment]
Doesn't sound like a common scenario to worry about.
