### ISSUE TITLE
Can not connection local mongod

### ISSUE THREAD

**Issue by simpla-fusion** [microsoft/vscode-cosmosdb#1142]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.10.2
OS: linux
Product: Visual Studio Code - Insiders
Product Version: 1.37.0-insider
Language: zh-cn

**Comment by PrashanthCorp** [comment]
Hi @simpla-fusion , which distro and which desktop env are you running? We've had similar issues with users who use KDE.

**Comment by simpla-fusion** [comment]
OS: KUbuntu 19.04
Problem solved:  sudo apt-get install  gnome-keyring
