### ISSUE TITLE
Failed to show text document

### ISSUE THREAD

**Issue by achin1987** [microsoft/vscode-cosmosdb#1144]
Repro steps:

1.
2.

Action: cosmosDB.openDocument
Error type: Error
Error Message: Failed to show text document file:///c%3A/Users/Achin/AppData/Local/Temp/vscode-cosmosdb-editor/Bob%20Belcher-cosmos-document.json, should show in editor #vs.editor.ICodeEditor:1,$model1

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

<details>
<summary>Call Stack</summary>

```
define.showTextDocument._proxy.$tryShowTextDocument.then.t extensionHostProcess.js:600:345
```

</details>

**Comment by PrashanthCorp** [comment]
Hi @achin1987  can you add some repro steps?
