### ISSUE TITLE
No "(More)" displays after executing one command which including lots of data

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1146]
**OS:** Mac
**Build Version:** [20190716.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7716)
**Regression:** Not a Regression

**Repro Steps:**
1. Connect a blank scrapbook to the mongo shell.
2. Add this to the scrapbook:
  db.lotsofdata.drop();
  db.lotsofdata.insertMany([{"a": "xxxxxxxxxxxxxxxxxxx"},
  {"a": "xxxxxxxxxxxxxxxxxxx"},
  {"b": "xxxxxxxxxxxxxxxxxxx"},
  {"c": "xxxxxxxxxxxxxxxxxxx"},
  {"d": "xxxxxxxxxxxxxxxxxxx"},
  {"e": "xxxxxxxxxxxxxxxxxxx"},
  {"f": "xxxxxxxxxxxxxxxxxxx"},
  {"g": "xxxxxxxxxxxxxxxxxxx"},
  {"h": "xxxxxxxxxxxxxxxxxxx"},
  {"i": "xxxxxxxxxxxxxxxxxxx"},
  {"j": "xxxxxxxxxxxxxxxxxxx"},
  {"k": "xxxxxxxxxxxxxxxxxxx"},
  {"l": "xxxxxxxxxxxxxxxxxxx"},
  {"m": "xxxxxxxxxxxxxxxxxxx"},
  {"n": "xxxxxxxxxxxxxxxxxxx"},
  {"o": "xxxxxxxxxxxxxxxxxxx"},
  {"p": "xxxxxxxxxxxxxxxxxxx"},
  {"q": "xxxxxxxxxxxxxxxxxxx"},
  {"r": "xxxxxxxxxxxxxxxxxxx"},
  {"s": "xxxxxxxxxxxxxxxxxxx"},
  {"t": "xxxxxxxxxxxxxxxxxxx"},
  {"u": "xxxxxxxxxxxxxxxxxxx"},
  {"v": "xxxxxxxxxxxxxxxxxxx"},
  {"w": "xxxxxxxxxxxxxxxxxxx"},
  {"x": "xxxxxxxxxxxxxxxxxxx"},
  {"y": "xxxxxxxxxxxxxxxxxxx"},
  {"z": "xxxxxxxxxxxxxxxxxxx"}]);
  db.lotsofdata.find().pretty();
3. Execute All

**Expect:**
Display "(More)".
![image](https://user-images.githubusercontent.com/41351993/61364151-dce53080-a8b7-11e9-94d4-9d284e2fda58.png)

**Actual:**
No "(More)" displays.
![image](https://user-images.githubusercontent.com/41351993/61364179-e7072f00-a8b7-11e9-8abd-b8f56498058b.png)

**Comment by StephenWeatherford** [comment]
Fixed by #1162
