### ISSUE TITLE
An unmatched error occurs after executing 'db.test.foo().pretty();' in scrapbook

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1149]
**OS:** Windows
**Build Version:** [20190722.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=7901)
**Regression:** Not a Regression

**Repro Steps:**
1. Connect a scrapbook to the mongo shell.
2. Set the mongo.shell.args setting to: **"mongo.shell.args": "-u abc -p abc"**
3. Execute this command in the scrapbook: **db.test.foo().pretty();**

**Expect:**
Pops up this error dialog.
![image](https://user-images.githubusercontent.com/41351993/61695582-56709900-ad66-11e9-8258-7175c2b39aff.png)

**Actual:**
Show the below result.
![image](https://user-images.githubusercontent.com/41351993/61695323-e104c880-ad65-11e9-9cdf-ef193d34a75a.png)

**More info:**
1. Expected output.
![image](https://user-images.githubusercontent.com/41351993/61695269-ca5e7180-ad65-11e9-8423-d51d93adb6da.png)
2. Recognize setting **"mongo.shell.args": "-u abc -p abc"** as unknown configuration setting.
![image](https://user-images.githubusercontent.com/41351993/61696413-dcd9aa80-ad67-11e9-9197-816a7a2317ea.png)

3. This issue also reproduces when setting mongo.shell.args setting to **"mongo.shell.args": "--version"**.

**Comment by v-dantch** [comment]
Update the error screenshot:
![image](https://user-images.githubusercontent.com/34729092/64008784-5cb61a00-cb49-11e9-9a5a-b8722e22d649.png)
