### ISSUE TITLE
No subscription icon displays for one subscription

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1151]
**OS:** Mac/Windows
**Build Version:** [20190731.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8287&view=results)
**Regression:** Previous release

**Repro Steps:**
1. Sign in to Azure.
2. Select subscriptions and check whether the subscription icon displays or not.

**Expect:**
The subscription icon displays well.
![image](https://user-images.githubusercontent.com/41351993/62273203-878c5000-b46f-11e9-83f2-2240405bd07b.png)

**Actual:**
No subscription icon displays for one subscription.
![image](https://user-images.githubusercontent.com/41351993/62273197-83f8c900-b46f-11e9-8604-d0a3286e65ed.png)

**More info:**
This issue also reproduces for Mooncake accounts.
(We didn't verified this issue on Azure Germany account cause we don't know the password of the Azure Germany account)

**Comment by EricJizbaMSFT** [comment]
@v-xianya yeah you'll probably see this in a few extensions. I'm aware of the root cause and will look into fixing it

**Comment by v-xianya** [comment]
@EricJizbaMSFT Got it, thanks for your updates!
