### ISSUE TITLE
MongoDB aggregations all time out with CosmosDB extension

### ISSUE THREAD

**Issue by timfrietas** [microsoft/vscode-cosmosdb#1152]
Issue Type: <b>Bug</b>

Any valid aggregation in MongoDB now times out (timeout set to 60 seconds in my case) when connected to a MongoDB Atlas instance.  I can successfully connect and run non-aggregation pipeline commands but if I have and use a databae with the collection movies, even the most basic aggergation will fail:

db.movies.aggregate([
  {
    $limit : 20
  }
])

Upgrading VSCode to the latest version has no effect.

Running these in the mongo shell works fine.

There does not appear to have been a new release to the Cosmos DB extension.  

Extension version: 0.10.2
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:56:38.504Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.64GB free)|
|Process Argv|-psn_0_1417562|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by PrashanthCorp** [comment]
Sorry to hear that @timfrietas. Do you have any info to share about running an aggregation on a local database too? I'm trying to narrow down on whether it could be a connection to Mongo Atlas, and whether we are reporting Timeouts too often.
Can you share how big the database is?
