### ISSUE TITLE
Cosmos document with id containing a pipe "|" character results in ENOENT error

### ISSUE THREAD

**Issue by daniel-wolf** [microsoft/vscode-cosmosdb#1153]
Repro steps:
1. Use "Create Document" command by right clicking on collection of a cosmodb database
2. Enter a document id of "test|a"
3. Enter a partition key of "test|a"
4. Attempt to open newly created document via tree view
5. Note the document fails to open with the following ENOENT error

Action: cosmosDB.openDocument
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\<redacted>\AppData\Local\Temp\vscode-cosmosdb-editor\test|a-cosmos-document.json'

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.36.1
Language: en

**Comment by PrashanthCorp** [comment]
Hey @daniel-wolf , thanks for catching this! Does the portal allow you to create such a document?

**Comment by daniel-wolf** [comment]
Thanks for the quick response.

Yes, I can create a document with an id of "test|a" via the portal,
presuming you mean the data explorer of Cosmos in the Azure portal.

Here's an screenshot of the document I created and am viewing via the
portal:
[image: image.png]

Best,
Dan

**Comment by nturinski** [comment]
Fixed by PR #1228
