### ISSUE TITLE
Pop up "timed out" error after displaying lots of data

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1157]
**OS**: Win10
**Build Version:** [20190806.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=8566)
**Regression:** Not a Regression

**Repro Steps:**
1. Connect a blank scrapbook to the mongo shell.
2. Add some code to the scrapbook like below:
 ![image](https://user-images.githubusercontent.com/34729092/62600929-c06e6e00-b922-11e9-8044-6cb119eb52c4.png)
3. Execute all--> Check the result.

**Expect:**
There is no error and the data displays well.

**Actual:**
The data displays well like below. But there still pops up "Timed out" error.
![image](https://user-images.githubusercontent.com/34729092/62601034-03c8dc80-b923-11e9-8384-e311f74fe17b.png)
![image](https://user-images.githubusercontent.com/34729092/62601041-088d9080-b923-11e9-8b5e-45c388a00b33.png)

**More Info:**
"Timed out" error still pops up when running "db.test.foo().pretty();"  with ' "mongo.sell.args" : "-u abc -p abc" ' and ' "mongo.shell.args" : "--version" '.

**Comment by StephenWeatherford** [comment]
Fixed by #1162
