### ISSUE TITLE
Cannot connect to the Atlas

### ISSUE THREAD

**Issue by Merazmi** [microsoft/vscode-cosmosdb#1159]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: ETIMEOUT
Error Message: querySrv ETIMEOUT _mongodb._tcp.azureatlas-efcji.azure.mongodb.net

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
QueryReqWrap.onresolve [as oncomplete] dns.js:197:19
```

</details>

**Comment by EricJizbaMSFT** [comment]
Sorry we never got to this - if you're still having issues please add detailed repro steps and we'll look into it
