### ISSUE TITLE
Port 27017 closed, why? it was working yesterday, and now doesn't?

### ISSUE THREAD

**Issue by bublikrowres** [microsoft/vscode-cosmosdb#1160]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: connection 6 to bublikrowrescluster-shard-00-01-sqfpx.mongodb.net:27017 closed

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.37.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.MongoError.create mongodb-core/error.js:29:11
TLSSocket.closeHandler mongodb-core/connection.js:214:22
Object.onceWrapper events.js:273:13
TLSSocket.emit events.js:187:15
TLSSocket.EventEmitter.emit domain.js:442:20
Socket._destroy._handle.close net.js:606:12
Socket.done _tls_wrap.js:386:7
Object.onceWrapper events.js:273:13
Socket.emit events.js:182:13
Socket.EventEmitter.emit domain.js:442:20
TCP.Socket._destroy._handle.close net.js:606:12
```

</details>

**Comment by bublikrowres** [comment]
My ISP changed my IP and it wasn’t on the whitelist on MongoDB Atlas.
Lost 5 hours of coding. Now I know

**Comment by StephenWeatherford** [comment]
Thanks for letting us know, sorry to hear.
