### ISSUE TITLE
For Each dont permitted

### ISSUE THREAD

**Issue by Mateus-Developer** [microsoft/vscode-cosmosdb#1163]
Repro steps:

1.
2.

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 23: 'mismatched input 'function' expecting {')', '{', '[', RegexLiteral, StringLiteral, 'null', BooleanLiteral, NumericLiteral}'. Please check syntax.

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:259407extension.bundle.js:253:259407
module.exports.n extension.bundle.js:253:258473
module.exports.n extension.bundle.js:253:258250
x extension.bundle.js:253:258938
Object.<anonymous> extension.bundle.js:253:262162
module.exports.n extension.bundle.js:253:258473
module.exports.n extension.bundle.js:253:258250
Object.module.exports.t.executeCommandFromText extension.bundle.js:253:262055
Object.<anonymous> extension.bundle.js:666:1094500
s extension.bundle.js:666:1089587
```

</details>

**Comment by StephenWeatherford** [comment]
Thanks for reporting, this is being tracked by #832.
