### ISSUE TITLE
resolve

### ISSUE THREAD

**Issue by sheshadri-h-vst-au4** [microsoft/vscode-cosmosdb#1165]
Repro steps:

1.
2.

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: SyntaxError
Error Message: Unexpected token } in JSON at position 61

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.e.exports.parse extension.bundle.js:666:1024890
MongoDocumentNodeEditor.convertFromString extension.bundle.js:537:166864
CosmosEditorManager.<anonymous> extension.bundle.js:666:1072640
module.exports.n extension.bundle.js:666:1070938
module.exports.n extension.bundle.js:666:1070715
CosmosEditorManager.updateToCloud extension.bundle.js:666:1072597
CosmosEditorManager.<anonymous> extension.bundle.js:666:1074720
s extension.bundle.js:666:1070771
```

</details>

**Comment by StephenWeatherford** [comment]
@sheshadri-h-au3 Thanks for reporting, that's definitely weird.  Do you have any more information on what you were doing when this happened?  Thx.
