### ISSUE TITLE
r

### ISSUE THREAD

**Issue by sheshadri-h-vst-au4** [microsoft/vscode-cosmosdb#1166]
Repro steps:

1.
2.

Action: cosmosDB.createMongoDatabase
Error type: Error
Error Message: Cannot resolve tree item for element 1//cosmosDBAttachedAccounts/127.0.0.1:27017/admini

Version: 0.10.2
OS: win32
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
define.resolveTreeNode.a.asPromise.then.then.e.getChildren.then extensionHostProcess.js:503:900
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by PrashanthCorp** [comment]
Hi @sheshadri-h-au3 , thanks for filing this. Does this reproduce consistently? 
Since this is a local instance, does detaching and then attaching again resolve the issue?
