### ISSUE TITLE
Timeout occurring before connecting string timeout settings

### ISSUE THREAD

**Issue by smv-orrin** [microsoft/vscode-cosmosdb#1174]
PyMongo connection string includes the following timeout settings:
serverSelectionTimeoutMS=49500
connectTimeoutMS=49500
socketTimeoutMS=49500

Repro steps:
1. Connect to a Mongo DB with the above timeout settings in the connection string
2. Execute an aggregate query that project 3 fields and then groups to get counts per group, with allowDiskUse: true

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "db.mongoCollection.aggregate([{"$project":{"_id":0,"first_field":1,"second_field":1,"date_time":1}},{"$group":{"_id":{"first_field":"$first_field","second_field":"$second_field","date_time":"$date_time"},"ct":{"$sum":1}}}],{"allowDiskUse":true})"

Version: 0.10.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

**Comment by StephenWeatherford** [comment]
Does this work if you run it directly in the Mongo shell?

**Comment by StephenWeatherford** [comment]
With this kind of query, we send it directly to the Mongo shell.  I executed the following without problem:

db.test.insert([{
   title: 'MongoDB Overview', 
   description: 'MongoDB is no sql database',
   by_user: 'tutorials point',
   url: 'http://www.tutorialspoint.com',
   tags: ['mongodb', 'database', 'NoSQL'],
   likes: 100
},
{
   title: 'NoSQL Overview', 
   description: 'No sql database is very fast',
   by_user: 'tutorials point',
   url: 'http://www.tutorialspoint.com',
   tags: ['mongodb', 'database', 'NoSQL'],
   likes: 10
},
{
   title: 'Neo4j Overview', 
   description: 'Neo4j is no sql database',
   by_user: 'Neo4j',
   url: 'http://www.neo4j.com',
   tags: ['neo4j', 'database', 'NoSQL'],
   likes: 750
}]);
db.test.aggregate(
[
    { $project: {title:1, by_user: 1, description:1, date_time: 1}},
    {"$group": {
        "_id":{"title":"$title","description":"$description","date_time":"$date_time"},"ct":{"$sum":1}}
    }
],
{"allowDiskUse":true}
)

**Comment by smv-orrin** [comment]
This has started working.  Closing for now, as seems like it may've been network-related.  If it re-occurs, I'll confirm via mongo shell and post both results.

**Comment by StephenWeatherford** [comment]
Thanks for letting us know!
