### ISSUE TITLE
Connecting to local emulator graph

### ISSUE THREAD

**Issue by javaadpatel** [microsoft/vscode-cosmosdb#1175]
Hi,

I've setup the local graph emulator as per: https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#gremlin-api . Is it possible to connect to the local cosmosdb emulator graph endpoint to visualize the graph? 
It seems that the problem is that the local emulator doesn't support SSL so I get this error:
![image](https://user-images.githubusercontent.com/22832462/63920296-cc8cad80-ca40-11e9-93be-6198fa93b7dc.png)

**Comment by PrashanthCorp** [comment]
Related to #1164

**Comment by nturinski** [comment]
Closing as dupe of https://github.com/microsoft/vscode-cosmosdb/issues/1248
