### ISSUE TITLE
Keep executing command more than 3 mins  

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1176]
**OS**: Win10 & Mac
**Build Version**: [20190829.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9268)
**Regression:** Previous Release (0.10.2)

**Repro Steps:**
1. Create a database for a Mongo account.
2. New a scrapbook -> Type below comments:
![image](https://user-images.githubusercontent.com/34729092/64008627-0f39ad00-cb49-11e9-9d6d-245d7833ee43.png)
3. Execute all --> Check the result.

**Expect:**
Succeed to execute all comments.

**Actual:**
Keep executing command more than 3 mins.
![image](https://user-images.githubusercontent.com/34729092/64009155-e665e780-cb49-11e9-8cd2-5e44381cb049.png)

**More Info:**
This issue does not reproduce on the previous release 0.10.2.

**Comment by StephenWeatherford** [comment]
Minor request: When you want us to type something, could you please copy the query text, not the bitmap, so we can copy/paste?  Thanks.

**Comment by v-dantch** [comment]
Got it. Sorry for that :(
