### ISSUE TITLE
updateOpenDocumentIfChanged fails if the current editor is not cosmos-document.json

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#118]
Repro Steps:
1. Open a cosmos db document
1. Edit the document
1. Open any other file
1. Select a different cosmos db document in the tree
1. Select 'Yes' when it says "Your changes to {0} will be lost..."

Expected: It updates my doc to azure
Actual: It tries to upload the most recent file, which is _not_ a cosmos db document

**Comment by PrashanthCorp** [comment]
I looked for an event for Active Text Editor changes. The most relevant I came across was `onDidChangeActiveTextEditor`. However, this fires _after_ the Active Editor changes (i.e., after the user switches/closes the current document). 
I couldn't find any `onPreChangeActiveTextEditor` event. 

This means we might have to listen to and record every editor change. We should discuss offline if this might cause perf issues.
