### ISSUE TITLE
No error pops up after deleting the connected database in Portal

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1180]
**Build Version:** [20190831.14](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=9324)
**OS**: All

**Repro Steps:**
1. New a scrapbook --> Connect a database --> Run any commands.
2. Open the special account in Azure Portal --> Click "Data Explorer" --> Delete the connected database.
3. Back to VS Code--> Refresh the Cosmos DB Explorer --> Make sure the connected database disappears.
4. Click "Execute All" again in the open scrapbook --> Check the result.

**Expect:**
Pop up an error to prompt the users to select a new database to connect
![image](https://user-images.githubusercontent.com/34729092/64106064-04318780-cdaa-11e9-9bbe-4731fc44538a.png)

**Actual:**
Execute well but display empty result.
![image](https://user-images.githubusercontent.com/34729092/64106175-3cd16100-cdaa-11e9-9ce8-6cff45770599.png)

**Comment by v-dantch** [comment]
More Info:
1. Execute well but display empty result on **Mac** after deleting the connected database in Cosmos DB Explorer.
2. Need to connect a new data after deleting the connected database in Cosmos DB Explorer on **Windows**.
![image](https://user-images.githubusercontent.com/34729092/68194505-19b46f00-fff0-11e9-92b5-a45bf3f2cc50.png)

**Comment by EricJizbaMSFT** [comment]
Going to close this as won't-fix. Mongo doesn't seem to throw an error in this case, so we're at least consistent. In a sense, there are no collections names so an empty array is accurate 🤷‍♂️ In addition, it's not worth an extra check against the database just to throw an error from our side
