### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by bkarakashev** [microsoft/vscode-cosmosdb#1183]
Repro steps:

1.
2.

Action: cosmosDB.executeAllMongoCommands
Error type: Error
Error Message: db.runCommand at 1:1: Timed out executing MongoDB command "use sds-fa-db"

Version: 0.10.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.37.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:261758
a extension.bundle.js:253:258357
```

</details>

**Comment by StephenWeatherford** [comment]
We're about to release a fix for some scenarios where we don't report the correct error, and instead show a timeout.  Hopefully it will help you find the actual cause of the problem.  Thx.

**Comment by PrashanthCorp** [comment]
Closing as fixed in next release.
