### ISSUE TITLE
Unable to connect to mLAB database through azure CosmosDB

### ISSUE THREAD

**Issue by rajranjan0608** [microsoft/vscode-cosmosdb#1188]
Action: cosmosDB.attachDatabaseAccount
Error type: ETIMEOUT
Error Message: querySrv ETIMEOUT _mongodb._tcp.portfolio1-90gah.mongodb.net

Version: 0.10.2
OS: linux
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
QueryReqWrap.onresolve [as oncomplete] dns.js:197:19
```

</details>

**Comment by PrashanthCorp** [comment]
1. Are you able to connect to this from the shell? 
2. Did you whitelist your IP address? Mongo Atlas has a firewall that needs IP whitelists:
https://docs.atlas.mongodb.com/security-whitelist/
