### ISSUE TITLE
error

### ISSUE THREAD

**Issue by manish-l-au3** [microsoft/vscode-cosmosdb#1191]
Repro steps:

1.
2.

Action: cosmosDB.attachEmulator
Error type: Error
Error Message: Unable to connect to local Mongo DB instance. Make sure it is started correctly. See https://aka.ms/AA5zah5 for tips.
failed to connect to server [localhost:10255] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:10255]

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:181:30955
a extension.bundle.js:181:30487
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by StephenWeatherford** [comment]
So, did you try out the suggestions in the website?  We can't help if you don't provide any information.
