### ISSUE TITLE
mongodb atlas not connecting

### ISSUE THREAD

**Issue by nikhila-darisa-au3** [microsoft/vscode-cosmosdb#1192]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: ETIMEOUT
Error Message: queryTxt ETIMEOUT bookworm-7t4sr.mongodb.net

Version: 0.10.2
OS: linux
Product: Visual Studio Code
Product Version: 1.27.2
Language: en

<details>
<summary>Call Stack</summary>

```
errnoException dns.js:50:10
QueryReqWrap.onresolve [as oncomplete] dns.js:238:19
```

</details>

**Comment by PrashanthCorp** [comment]
Did you whitelist your IP address? Mongo Atlas has a firewall that needs IP whitelists: 
https://docs.atlas.mongodb.com/security-whitelist/
