### ISSUE TITLE
mongodb

### ISSUE THREAD

**Issue by vandat3010** [microsoft/vscode-cosmosdb#1195]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: Unable to connect to local Mongo DB instance. Make sure it is started correctly. See https://aka.ms/AA5zah5 for tips.
failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.0
Language: en

<details>
<summary>Call Stack</summary>

```
Object.<anonymous> extension.bundle.js:181:30955
a extension.bundle.js:181:30487
process._tickCallback next_tick.js:68:7
```

</details>

**Comment by StephenWeatherford** [comment]
Did you follow the tips?
