### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by kumarmamidi** [microsoft/vscode-cosmosdb#1196]
Repro steps:

1.
2.

Error Message: self signed certificate

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: enAction: cosmosDB.createDocDBDatabase
Error type: DEPTH_ZERO_SELF_SIGNED_CERT

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1049:34
TLSSocket.emit events.js:182:13
TLSSocket._finishInit _tls_wrap.js:631:8
```

</details>

**Comment by nturinski** [comment]
Sorry for the late reply. Could you try setting http.proxyStrictSSL to false?
