### ISSUE TITLE
Unable to rename collection, throws error

### ISSUE THREAD

**Issue by pspkshah** [microsoft/vscode-cosmosdb#1199]
Repro steps:

1. run db.[existing_Collection_Name].renameCollection("[new_collection_name]");

Action: cosmosDB.executeMongoCommand
Error: exception: connect failed
The output window may contain additional information.
Error running process: The process exited with code 1.

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.module.exports.t.wrapError extension.bundle.js:537:160963
m extension.bundle.js:537:160421
module.exports.executeScript.o.push._process.onStdErr.e extension.bundle.js:537:159927
u.fire extensionHostProcess.js:50:207
Socket.module.exports.startCore.n._childProc.stderr.on.e extension.bundle.js:622:1043927
Socket.emit events.js:182:13
addChunk _stream_readable.js:283:12
readableAddChunk _stream_readable.js:264:11
Socket.Readable.push _stream_readable.js:219:10
Pipe.onStreamRead [as onread] stream_base_commons.js:94:17
```

</details>

**Comment by nturinski** [comment]
Hi @pspkshah 

Sorry, but renaming collections is not supported at this time, but it's possible it could come in the future!
