### ISSUE TITLE
Add telemetry for the extension

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#12]
We need to verify what telemetry we get for free from VS Code extensions and discuss what we need to add ourselves

**Comment by fiveisprime** [comment]
Every Node SDK client has a method named `addUserAgentInfo` where you can append data to the UA String that's captured on the server side. The model I've used in the past to measure server-side usage is

```js
const pkg = require('./package.json')

cosmosClient.addUserAgentInfo(`${pkg.name}/${pkg.version}`)
```

**Comment by EricJizbaMSFT** [comment]
https://github.com/Microsoft/vscode-extension-telemetry

**Comment by EricJizbaMSFT** [comment]
All commands now have the following telemetry:
1. Command id
1. Result (Either 'Succeeded' or 'Failed) - we could potentially improve this to include 'Canceled' or other statuses
1. StartTime and EndTime (I thought it might be useful to know how long commands take on average)

Closing this issue and we can open new issues if we want more specific telemetry
