### ISSUE TITLE
Element with id "..." is already registered

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1204]
**OS:** Win10 & Mac
**Build Version:** [20190926.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10491)
**The same issue:** [#1022](https://github.com/microsoft/vscode-cosmosdb/issues/1022) 

**Repro steps:**

1. Right click on a collapse MongoDB database account and create a database.
2. After filling all prompts, quickly expand the new database.

**Expect:**
Expand the database successfully without any error.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/65760072-e0662500-e14e-11e9-885c-4184e4c990e2.png)

**Comment by EricJizbaMSFT** [comment]
Probably a timing problem. We should check if the temporary "creating" node has the same id as the node that eventually gets created after it's done

**Comment by EricJizbaMSFT** [comment]
The "creating" node isn't the problem - that id is based off the label, which includes "Creating" (aka it wouldn't be the same).
