### ISSUE TITLE
[Theme] ‘insertMany’ is a same color with "db" in Light(Visual Studio) theme

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1206]
**OS:** Windows
**Build Version:** [20190928.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10586)

**Repro Steps:**
1. F1- > Color Theme -> Select 'Light(Visual Studio)'.
2. New Mongo Scrapbook -> Type the 'db.c2. insertMany()' to the scrapbook. 
2. Observe the color of 'insertMany' and 'db'.

**Expect:**
'insertMany' is a different color than 'db'.

**Actual:**
‘insertMany’ is a same color with "db".
![image](https://user-images.githubusercontent.com/41351993/65829701-9d38bd00-e2da-11e9-8875-35e852513ed6.png)

**More Info:**
This issue also reproduces in **Solarized Ligh**t/ **Dark (Visual Studio)**/ **Solarized Dark** themes.

**Comment by EricJizbaMSFT** [comment]
JavaScript repros the same behavior:
![Screen Shot 2020-04-23 at 3 31 28 PM](https://user-images.githubusercontent.com/11282622/80155941-9bd12980-8577-11ea-9367-2e8220679ac2.png)
