### ISSUE TITLE
Display '3.2.0' after executing 'db.version();' with 4.2.0 mongodb installed

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1207]
**OS:** Windows
**Build Version:** [20190928.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=10586)

**Repro Steps:**
1. Download and install mongodb with 4.2 mongo shell.
2. In vsCode, go to user settings(F1-> User Settings).
3. Add "mongo.shell.path": "C:\\Program Files\\MongoDB\\Server\\4.2\\bin\\mongo.exe" to settings.json.
4. Run 'db.version();' in scrapbook.
5. Check the result.

**Expect:**
Display '4.2.0'.
![image](https://user-images.githubusercontent.com/41351993/65829551-55fdfc80-e2d9-11e9-8f57-675385f5b63e.png)

**Actual:**
Display '3.2.0'.
![image](https://user-images.githubusercontent.com/41351993/65829543-3ebf0f00-e2d9-11e9-87f1-556a2904ab0f.png)

**Comment by wwlorey** [comment]
@v-xianya Try checking your `mongod --version` and `mongo --version` to see if those numbers match up. You may have updated your shell, not the server

**Comment by v-xinda** [comment]
@wwlorey  This issue also reproduces on the latest build [20200423.10](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18239&view=results).
MongoDB version is consistent with the db version.
![image](https://user-images.githubusercontent.com/57662131/80204102-d5c72c00-865a-11ea-9acb-03a9460bb7d1.png)

**Comment by wwlorey** [comment]
Even if your local mongo version is 4.2.0, mongo will default to the version associated with the given connection string when starting the shell. It makes sense that your result was 3.2.0 since that's the version of your mongo account in Azure (that's the default version we create in the extension)

**Comment by sevoku** [comment]
I think this is clearly the remote server version, not local, as described remote is 3.6 so this is not a bug.
