### ISSUE TITLE
Can't auth with username containing @

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/vscode-cosmosdb#1209]
Repro steps:
1. Try to login to mongo with connections string like `mongodb://username@example.com:password@localhost/` or `mongodb://username%40example.com:password@localhost/`
2. Get error

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: Username containing an unescaped at-sign

Version: 0.11.0
OS: linux
Product: VSCodium
Product Version: 1.38.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:234753
l extension.bundle.js:253:240574
QueryReqWrap.callback extension.bundle.js:253:242137
QueryReqWrap.onresolve [as oncomplete] dns.js:199:10
```

</details>

**Comment by nturinski** [comment]
Hi @SkeLLLA

Thanks for reporting.  I will investigate what we can do to automate this for users, but the current workaround is to escape @ signs with a \ (backslash.  For example:

`mongodb://username\@example.com:password\@localhost`

**Comment by SkeLLLa** [comment]
I didn't remember if I tried escaping, so I can't be sure that it works or not.
However handling this case should be pretty simple: 
1) Find the latest index of `@`.
2) Everything before that index (username and password) should be escaped, and after - that the host part.
