### ISSUE TITLE
Tr to create a cosmos-db

### ISSUE THREAD

**Issue by augcampos** [microsoft/vscode-cosmosdb#1211]
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: Error
Error Message: Entry not found in cache.

Version: 0.11.0
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.39.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
a.module.exports.a.createError extension.js:1:49013
b.<anonymous> extension.js:229:177015
extension.js:229:171630extension.js:229:171630
extension.js:229:43713extension.js:229:43713
extension.js:229:41706extension.js:229:41706
extension.js:229:41328extension.js:229:41328
i.module.exports.i.find extension.js:229:75821
module.exports.find.init.then extension.js:229:23101
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting.  We are tracking the external issue here:
AzureAD/azure-activedirectory-library-for-nodejs#199

Please add some 👍's to give the team feedback that this is an issue worth resolving!
