### ISSUE TITLE
The corresponding document isn't updated after updating one collection successfully

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#1214]
**OS:** All
**Build Version:** [20191009.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11035)

**Repro Steps:**
1. Drill down from Subscription -> Mongo DB Account -> Database -> Collection.
2. Right click one collection and select 'Oepn Collection'.
3. A '**collectionname**-cosmos-collection.json' should open.
4. Add a filed to '**collectionname**-cosmos-collection.json'.
    Like: 
      _{
  "_id": "59c0359f09fcce45653921b9",
  "name": "VSCode",
  "county": "king",
  "city": "Seattle"
  },_
5. Click Save -> The output shows a successful update.
6. Check the corresponding document in the tree view. 

**Expect:**
The corresponding document in the tree view is updated. 

**Actual:**
The corresponding document in the tree view is not updated.

**Comment by nturinski** [comment]
Could you double check this?  I wasn't able to repro this.

**Comment by v-dantch** [comment]
Hi Nathan, we verified this issue on the latest nightly build [20191119.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12561). And this issue also reproduces. Please get the details from below screenshot, and hope this will help you.
![image](https://user-images.githubusercontent.com/34729092/69225219-ead5f580-0bb8-11ea-97eb-a67d00aa8729.png)

**Comment by wwlorey** [comment]
Altering the `_id` object isn't allowed, but updating other properties works fine

**Comment by v-dantch** [comment]
That's it.
