### ISSUE TITLE
Display Gremlin/Table/Cassandra accounts when running "SQL(DocumentDB): Create Stored Procedure"

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1216]
**OS**: Win10
**Build Version**: [20191009.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11035)
**Regression**: Not a Regression

**Repro Steps:**
1. F1 --> Type and select "SQL(DocumentDB): Create Stored Procedure".
2. Check the result.

**Expect:**
Only list the SQL accounts.

**Actual:**
Display Gremlin/Table/Cassandra accounts.
![image](https://user-images.githubusercontent.com/34729092/66742164-a2386780-eea9-11e9-8951-4bc6dcfd0fcd.png)

**More Info:**
There are no commands to create & delete a stored procedure for Graph accounts.
![image](https://user-images.githubusercontent.com/34729092/66742218-c3995380-eea9-11e9-8838-8fa04791ae0b.png)

**Comment by wwlorey** [comment]
Hiding table accounts was fixed in https://github.com/microsoft/vscode-cosmosdb/pull/1530. And it looks like it was intentional to show graph accounts as an ancestor of doc db stored procedures (https://github.com/microsoft/vscode-cosmosdb/pull/762). Please reopen if that's not the case
