### ISSUE TITLE
[Suggestion] Add a "Back" button 

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1217]
**OS**: Win10
**Build Version**: [20191009.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=11035)
**Regression**: Not a Regression

**Repro Steps:**
1. F1 --> Type and select "SQL(DocumentDB): Create Stored Procedure".
2. Prompt to select one subscription if there are 2 applied subscriptions at least --> Select one.

**Actual:**
There is no "Back" button.

**Suggestion:**
Add a "Back" button. In this case, it is more convenient for the users to select another resource.

**Comment by v-xinda** [comment]
There is no "Back" button when executing command "Import Document into a Collection...".

**Comment by wwlorey** [comment]
Closing as duplicate of https://github.com/microsoft/vscode-azurefunctions/issues/1946
