### ISSUE TITLE
MongoDB: Fully qualified namespace is too long error when creating collection with validator

### ISSUE THREAD

**Issue by gtbono** [microsoft/vscode-cosmosdb#1222]
When I try to create a MongoDB collection using the following command on VS Code, I get an error:

```
db.createCollection("teste", {
    validator: {
        jsonSchema: {
            bsonType: "object",
            required: ["teste1", "teste2"],
            properties: {
                teste1: {
                    bsonType: "string",
                    description: "Deve ser uma string"
                },
                teste2: {
                    bsonType: "string",
                    description: "Deve ser uma string"
                },
            }
        }
    }
})
```
But when I ran this exact command on the Mongo shell the command executes without problem, I believe this is somehow being mistaken with the 120 byte limit for the collection name.

**Comment by nturinski** [comment]
Hi @gtbono

Are you creating a local database in the Mongo shell or are you using Azure Cosmos?  I was just curious.

Thanks for reporting! I have a fix for this here: #1236
