### ISSUE TITLE
Newly created document does not show up in the explorer

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#123]
Repro steps:
1. Expand a "DocumentDB" account in the explorer
1. Create a new Document

Expected:
1. New document is added to tree view

Actual:
1. New document is not added. However, it _does_ show after a refresh

**Comment by EricJizbaMSFT** [comment]
I believe this is related to the recent Load More work. I don't think we should do a _full_ refresh of the node (what if they've already clicked 'Load More' a bunch of times?), but we might be able to just add the new node to the cached nodes

**Comment by EricJizbaMSFT** [comment]
Assigning this to @PrashanthCorp since this overlaps with your Load More work and I don't want to mess with conflicts

**Comment by PrashanthCorp** [comment]
Yeah, this is a UI issue. 
Also, the default policy in the API's of returning documents in the order of creation didn't help testing.
