### ISSUE TITLE
PartitionKey extracted from document doesn't match the one specified in the header

### ISSUE THREAD

**Issue by knutole** [microsoft/vscode-cosmosdb#1240]
Repro steps:
1. Open Container Item and make a change to it.
2. Try to save (Upload). 
3. Save fails with error. Partition key is set to /code, and "code" key is included in the Item.

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: BadRequest
Error Message: PartitionKey extracted from document doesn't match the one specified in the header

Version: 0.11.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

**Comment by wwlorey** [comment]
Hi @knutole, is it possible that the partition key value for "code" was changed when you updated the document? That error is thrown when a document's partition key value doesn't match the one specified when the document is created.
