### ISSUE TITLE
An error occurs when attaching MongoDB Emulator

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1241]
**OS:** Windows
**Build Version:** [20191114.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12450&view=results)
**Emulator Version:** 2.7.1.0

**Repro Steps:**
1. Install Cosmos DB Emulator and start it.
2. Right click on 'Attached Database Accounts' -> Attach Emulator -> MongoDB.
3. Check the result.

**Expect:**
Successfully attached.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/68944884-f8226700-07e9-11ea-8184-2feafc0e4ea5.png)

**More info:**
This issue does not reproduce when attaching SQL Emulator.

**Comment by nturinski** [comment]
Did you make sure you enabled the emulator for using MongoDB?  I was able to get it to work:

![image](https://user-images.githubusercontent.com/5290572/68982094-7d8e2300-07ba-11ea-82f3-8fbb7804059f.png)

Follow the instructions here: https://github.com/microsoft/vscode-cosmosdb/wiki/Debugging-Connection-Errors specifically 2.  That will show you how to open it with Mongo DB enabled.

**Comment by v-dantch** [comment]
Thanks for your sharing. Verified with the latest build [20191208.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12927) on Windows. This issue doesn't reproduce after enabling the emulator.

**Comment by v-dantch** [comment]
Reopen this issue due to it reproduces on the latest build [20200415.13](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17851&view=artifacts&type=publishedArtifacts).
![image](https://user-images.githubusercontent.com/34729092/79422898-45507200-7ff0-11ea-84ad-bf531a6c384e.png)
