### ISSUE TITLE
An error occurs when importing document into Mongo DB collection

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1242]
**OS:** Windows
**Build Version:** [20191114.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12450&view=results)

**Repro Steps:**
1. F1->Cosmos DB: Import Document into a Collection->Select a .json file->Select one Mongo DB collection.
2. Check the result.

**Expect:**
Import the document into Mongo DB collection successfully.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/45614674/68945454-69164e80-07eb-11ea-8fca-b9715ec9954b.png)

**More info:**
This issue does not reproduce if import the same document(.json file) into SQL collection.

**Comment by nturinski** [comment]
I wasn't able to repro this either.  Could you give me more information to repro this?

**Comment by v-ruizh** [comment]
@nturinski I can reproduce this issue with the latest nightly build [20191119.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12561&view=results). This issue does not reproduce on the previous released version.

**Comment by wwlorey** [comment]
Fixed in #1309
