### ISSUE TITLE
Settings in vscode about mongodb

### ISSUE THREAD

**Issue by yo-va-ni** [microsoft/vscode-cosmosdb#1243]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: Unable to connect to local Mongo DB instance. Make sure it is started correctly. See https://aka.ms/AA5zah5 for tips.
failed to connect to server [localhost:27017] on first connect [[Error: connect ECONNREFUSED 127.0.0.1:27017
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)] {
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:27017'
}]

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.0
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1054:14
Object.<anonymous> extension.bundle.js:181:30955
a extension.bundle.js:181:30487
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Hi @yo-va-ni 

Are you trying to attach a local Mongo database account?  Please make sure that you have the mongodb service running first.
