### ISSUE TITLE
Minimum container RU/s should be 400

### ISSUE THREAD

**Issue by markjbrown** [microsoft/vscode-cosmosdb#1246]
Hello. I'm a PM on the Cosmos DB Team. We had this reported by a user.

When creating a new container for Cosmos DB the minimum throughput is 400 RU/s. This tool currently only allows for minimum throughput of 1000 RU/s. Can you please update this tool to allow customers to create containers with 400 RU/s?

Any questions please feel to comment here or reach out to me directly.

Thanks.

**Comment by nturinski** [comment]
Hi @markjbrown

Do you know what version of the Cosmos extension that user is using?  I believe that we allow users to set the throughput to 400 (and do so by default)

![image](https://user-images.githubusercontent.com/5290572/69654571-a32cef00-103a-11ea-94e9-47ae70f9b0fd.png)

Just to clarify, when you say creating a new container, are you referring to when creating a container in a Core (SQL) database?

**Comment by markjbrown** [comment]
I don't know what version they are using. However, I just installed this on another one of my machines and still see this as 1000 RU/s minimum.

![image](https://user-images.githubusercontent.com/800166/69655490-76251000-102b-11ea-9191-9be0b0391179.png)

**Comment by nturinski** [comment]
It seems that we set it to 1000 if the collection is fixed.  This seems to be determined by whether or not the collection has a partition key.  Is this logic incorrect?

**Comment by markjbrown** [comment]
The logic is different.

For SQL API accounts there must be a partition key path provided. Minimum RU/s is 400.

For MongoDB API using version 3.6, customers have the option to specify a partition (sharding) key path or not. But for either the minimum RU/s is 400. The difference is whether they get a single partition for storage or not. If customer creates a Mongo 3.2 account, partition key is required but min RU/s is also still 400.

I tested the create Cosmos account and have some other observations as well.

When creating an account, the maximum account name size is now 44 characters. This was increased in our resource provider not too long ago. Also, would be good to include the option to provision a MongoDB 3.2 or MongoDB 3.6 account with the logic above. Also would be great if consistency level could be chosen as well as replica regions. I realize the number of options could quickly explode but those are probably the biggest ones.

Thanks.

**Comment by wwlorey** [comment]
Fixed by https://github.com/microsoft/vscode-cosmosdb/pull/1406
