### ISSUE TITLE
bakwas

### ISSUE THREAD

**Issue by SsumanShahi** [microsoft/vscode-cosmosdb#1247]
Repro steps:

1.
2.

Action: cosmosDB.executeAllMongoCommands
Error type: Error
Error Message: db.tasks.findOne at 3:1: Could not find any documents

Version: 0.11.0
OS: linux
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:268949
a extension.bundle.js:253:265503
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by nturinski** [comment]
Hi @SsumanShahi.

Thanks for reporting. Please provide repro steps
