### ISSUE TITLE
[Suggestion]Update the icon for the stored procedure editor

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1249]
**OS**: All
**Build Version:** [20191128.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12733)
Regression: Not a Regression

**Repro Steps:**
1. Create a SQL account -->Database --> Collection --> Stored Procedures.
2. Check the icon of opened stored procedures editor.

**Actual:**
Display with "JS".

**Suggestion:**
How about displaying an icon for it like in Azure Storage Explorer?
![image](https://user-images.githubusercontent.com/34729092/69847547-63703c80-12b2-11ea-87be-d14d847a51a3.png)

**Comment by EricJizbaMSFT** [comment]
We're fine with the "JS" icon since it's a javascript file
