### ISSUE TITLE
Update the error message after removing the extension file folder from %USERPROFILE%\.vscode\extensions

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1250]
**OS**: Win10
**Build Version:** [20191128.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12733)
**VS Code Version:** 1.10.1 (user setup)
**Regression:** Not a Regression

**Repro Steps:**
1. Install Cosmos DB Extension in VS Code --> Make sure the Cosmos DB Explorer displays well.
2. Delete the extension file folder from the %USERPROFILE%\.vscode\extensions.
3. Check the Cosmos DB Explorer.

**Expect:**
Pop up a clear message to tell the users that the current extension file folder has been removed.

**Actual:**
Pop up a notification "false==true".
![image](https://user-images.githubusercontent.com/34729092/69852432-3a09dd80-12bf-11ea-92fe-a71e82655ba2.png)

**Comment by EricJizbaMSFT** [comment]
The error should go away if you reload VS Code. We can't do anything from our extension since it was literally deleted in step 2. Fun find, though!
