### ISSUE TITLE
Credentials are missing

### ISSUE THREAD

**Issue by slarionoff** [microsoft/vscode-cosmosdb#1253]
Repro steps:

I follow this lesson: https://docs.microsoft.com/en-us/learn/modules/build-cosmos-db-app-with-vscode/2-setup-cosmosdb?source=learn
1. I've created a new Azure Cosmos DB account in Visual Studio Code;
2. After creation it shows an error (given below);
3. I can't follow the next steps as I have the same error. I can't see a place to put in my credentials;

Action: cosmosDB.createDocDBDatabase
Error type: 407
Error Message: 
> Access Denied (authentication_failed)

Your credentials could not be authenticated: "Credentials are missing.". You will not be permitted access until your credentials can be verified.This is typically caused by an incorrect username and/or password, but could also be caused by network problems.
For assistance, contact your network support team.

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

**Comment by nturinski** [comment]
Hi @slarionoff

Are you behind a proxy by chance? If so, you may be able to get around this by using this vscode setting:
`"http.proxyStrictSSL": false`

**Comment by slarionoff** [comment]
Hi @nturinski! This helped. I'm really behind proxy, after setting this parameter I was able to pass further. Thanks a lot!
