### ISSUE TITLE
error connection

### ISSUE THREAD

**Issue by martin-pastorino** [microsoft/vscode-cosmosdb#1254]
Repro steps:

run doker on port 32768 of localhost, bound to doker port 27017. open vscode and try to connect to the next connection string, mongodb://localhost:32768

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: Unable to connect to local Mongo DB instance. Make sure it is started correctly. See https://aka.ms/AA5zah5 for tips.
failed to connect to server [127.0.0.1:32768] on first connect [[Error: connect ECONNREFUSED 127.0.0.1:32768
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1054:14)] {
  name: 'MongoError',
  message: 'connect ECONNREFUSED 127.0.0.1:32768'
}]

Version: 0.11.0
OS: linux
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1054:14
Object.<anonymous> extension.bundle.js:181:30955
a extension.bundle.js:181:30487
processTicksAndRejections task_queues.js:89:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@martin-pastorino this is unlikely to be an issue in the Cosmos DB extension. You can see it's trying to use the `32768` port specified in your connection string and its getting back `ECONNREFUSED`. I would suggest double checking your ports/docker instance running mongo
