### ISSUE TITLE
Cosmosdb doesn't escape characters properly and doesn't allow to do that manually.

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/vscode-cosmosdb#1255]
Repro steps:

1. Create collection with some special characters like `foo#bar.baz`
2. Try to query collection with aggregate

```
db.foo#bar.baz.aggregate(....)
```

It will fail with `SyntaxError: illegal character @(shell):1:8` and that's expected, cause this extension doesn't do anything with such collection name.

If you try to do that in correct way like in mongo shell, e.g.:

```
db["foo#bar.baz"].aggregate(....)
```

Then extension complains `mismatched input '[' expecting '.` which is obviously wrong, cause it's correct syntax.

Action: cosmosDB.executeMongoCommand

Version: 0.11.0
OS: linux
Product: VSCodium
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:266594
extension.bundle.js:253:265619
n extension.bundle.js:253:265396
x extension.bundle.js:253:266081
Object.<anonymous> extension.bundle.js:253:269345
extension.bundle.js:253:265619
n extension.bundle.js:253:265396
Object.t.executeCommandFromText extension.bundle.js:253:269238
Object.<anonymous> extension.bundle.js:622:1078829
s extension.bundle.js:622:1073829
```

</details>

Here's test for you:
```
testParse(
            `db["a"].find({"a":[1,2,3]});`,
            {
                collection: 'a',
                name: 'find',
                args: [{ "a": [1, 2, 3] }],
            }
        );
```

**Comment by nturinski** [comment]
Hi @SkeLLLa, thanks for reporting.  

We should be releasing v0.12.0 sometime next week.  While the release won't fix this issue, it does resolve this issue https://github.com/microsoft/vscode-cosmosdb/issues/981.  You should be able to work around this issue by using `db.getCollection("foo#bar.baz").aggregate(....)`

**Comment by neelip** [comment]
Related to #1193
