### ISSUE TITLE
Error: collection name must be a String on find

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/vscode-cosmosdb#1257]
Repro steps:

1. Add query to scrapbook :
```
db.getCollection('foo').find({
    bar: 1,
})
```
2. Execute query

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: collection name must be a String

Version: 0.11.0
OS: linux
Product: VSCodium
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
t.checkCollectionName extension.bundle.js:5:53946
new C extension.bundle.js:109:8503
N.collection extension.bundle.js:129:33155
MongoFindResultEditor.<anonymous> extension.bundle.js:622:1082492
s extension.bundle.js:622:1081907
processTicksAndRejections task_queues.js:89:5
```

</details>

But if you add `.count()` then it magically works.

**Comment by nturinski** [comment]
Thanks for reporting.  This has been fixed by https://github.com/microsoft/vscode-cosmosdb/pull/1263
