### ISSUE TITLE
appName parameter in mongo db connection string is not passed down by VsCode to cosmos db server

### ISSUE THREAD

**Issue by Liphi** [microsoft/vscode-cosmosdb#1260]
We verified vscode-cosmosdb-0.11.1-alpha.vsix of the unreleased build (https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=12208), and cosmos mongo db account with privateIp set up is not connectable from VsCode.
From the error, we think either appName is dropped by VsCode somewhere before passing to mongo driver, or the mongo driver version used by VsCode doesn't honor this parameter.

We are trying to ensure we have tools to support Private link for Mongo account. And VsCode is the only mongo tool Microsoft has control over, we think. So we have to push and get this bug fixed.

**Comment by neelip** [comment]
@nturinski says this is fixed.
