### ISSUE TITLE
suddenly getting this message

### ISSUE THREAD

**Issue by cortfritz** [microsoft/vscode-cosmosdb#1264]
Repro steps:

1.
2.

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Could not find unique name for new file.

Version: 0.11.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:105:19104
s extension.bundle.js:105:18035
```

</details>

**Comment by nturinski** [comment]
Please provide repro steps.
