### ISSUE TITLE
db.createUser 

### ISSUE THREAD

**Issue by juan-dura** [microsoft/vscode-cosmosdb#1265]
Repro steps:

I try to execute this command:
`db.createUser( {
    user: "username",
    pwd: "password",
    roles: [{role: "readWrite",  db: "dbname"}],
  } )`

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 73: 'mismatched input 'db' expecting '}''. Please check syntax.

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.0
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:253:266594extension.bundle.js:253:266594
extension.bundle.js:253:265619extension.bundle.js:253:265619
n extension.bundle.js:253:265396
x extension.bundle.js:253:266081
Object.<anonymous> extension.bundle.js:253:269345
extension.bundle.js:253:265619extension.bundle.js:253:265619
n extension.bundle.js:253:265396
Object.t.executeCommandFromText extension.bundle.js:253:269238
Object.<anonymous> extension.bundle.js:622:1078829
s extension.bundle.js:622:1073829
```

</details>

**Comment by nturinski** [comment]
This seems to be an issue with our grammar parsing. Thanks for reporting @juan-dura.
