### ISSUE TITLE
Import Document feature ignores files with upper-case .JSON

### ISSUE THREAD

**Issue by marked23** [microsoft/vscode-cosmosdb#1266]
__Steps:__
- right click an existing collection and select "Import Document into a Collection"
- select a json document with a filename that ends with upper-case .JSON
- click Import

__Expected__
Json document is imported

__Observed__
Json document is ignored
__Output message:__
```
Ignoring the following files which are not json:
C:\Data\SomeFile.JSON
Error: Array of documents cannot be empty
```

https://github.com/microsoft/vscode-cosmosdb/blob/0fd2a9df4a36d441b44eb112c8a837f651d8754a/src/commands/importDocuments.ts#L21

**Comment by nturinski** [comment]
Thanks for reporting and even showing which line is causing the issue 👍 @marked23
