### ISSUE TITLE
Improve error message when "mongo.shell.path" doesn't exist

### ISSUE THREAD

**Issue by believetech-orw** [microsoft/vscode-cosmosdb#1267]
Repro steps:

1. Run a "Find" query against a simple table, it should work without a probem
2.Run an "aggregate" query with a simple, single-step `match` step.  It should fail with a warning that the mongo.exe runtime can't be found.

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Could not find c:\Program Files\MongoDB\Server\4.2\bin\mongo.exe
The output window may contain additional information.

Version: 0.11.0
OS: linux (via WSL on Windows)
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.improveError extension.bundle.js:537:160645
ChildProcess.<anonymous> extension.bundle.js:622:1044011
ChildProcess.emit events.js:200:13
Process.ChildProcess._handle.onexit child_process.js:270:12
onErrorNT child_process.js:456:16
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by believetech-orw** [comment]
Worth noting, I'm using a Windows machine with WSL (running Ubuntu 18.04), and VSCode is in remote mode (I started code from a WSL terminal)

**Comment by believetech-orw** [comment]
OK, final note... "it fixed itself" when I changed the following setting:
`"mongo.shell.path": "/mnt/c/Program Files/MongoDB/Server/4.2/bin/mongo.exe"`

**Comment by EricJizbaMSFT** [comment]
@believetech-orw thanks for the details. I thought we would automatically use the mongo path from WSL if you're using VS Code Remote. Was "mongo.shell.path" empty when you hit the bug or was it explicitly set to "c:\Program Files\MongoDB\Server\4.2\bin\mongo.exe"?

**Comment by believetech-orw** [comment]
It was explicitly set to the Windows path when I found it.

**Comment by EricJizbaMSFT** [comment]
Okay seems like we probably just need to mention the "mongo.shell.path" setting in the error message to make this more clear

**Comment by sashasklar** [comment]
@believetech-orw @EricJizbaMSFT  can you provide some more info on your configuration? I've tried a dozen variations and combinations of the "mdb.shell" and "mongo.shell.path" with no success. Here's a couple:

`"mdb.shell": "mongosh", "mongo.shell.path": "/mnt/c/Program Files/MongoDB/mongosh.exe",`
error: "The terminal process failed to launch: Path to shell executable "mongosh" does not exist."

`  "mongo.shell.path": "/usr/bin/mongo"`
Error: The terminal process failed to launch: Path to shell executable "mongo" does not exist.
