### ISSUE TITLE
cosmos scrapbook db connection error when choose attach db account

### ISSUE THREAD

**Issue by inonli** [microsoft/vscode-cosmosdb#1268]
Repro steps:

1. connecting azure cosmos db with visual code.
2. open scrap book
3. when trying to connect the db "attached db account"
i get this error:
"No matching resources found."
"source: azure cosmos db extension"

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: No matching resources found.

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.39.2
Language: en

<details>
<summary>Call Stack</summary>

```
AttachedAccountsTreeItem.<anonymous> extension.bundle.js:253:154866
s extension.bundle.js:253:149407
```

</details>

**Comment by EricJizbaMSFT** [comment]
@inonli please add repro steps
