### ISSUE TITLE
Display "the options [appName] is not supported " in "Mongo Language Server" window when creating a Mongo collection

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#1269]
**OS:** Win10
**Build Version:** [20191223.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=13305&view=results)
**Regression:** Previous Release (0.11.0)

**Repro** **Steps:**
1. F1 --> Type and select "MongoDB: Create Collection".
2. Complete the process according to the notification.
3. Check the "Mongo Language Server" window.

**Expect:**
There is no any error.

**Actual:**
Display "the options [appName] is not supported.
![image](https://user-images.githubusercontent.com/34729092/71401255-42f29280-2664-11ea-92c9-b2463a120acc.png)

**Comment by EricJizbaMSFT** [comment]
Should be included with https://github.com/microsoft/vscode-cosmosdb/issues/1306
