### ISSUE TITLE
Time out issue 

### ISSUE THREAD

**Issue by peeyar** [microsoft/vscode-cosmosdb#1271]
Repro steps:

1.
2.

Action: cosmosDB.detachDatabaseAccount
Error type: ETIMEOUT
Error Message: querySrv ETIMEOUT _mongodb._tcp.dev01-eddiebauer-com-x6i4a.mongodb.net

Version: 0.11.0
OS: darwin
Product: Visual Studio Code
Product Version: 1.40.2
Language: en

<details>
<summary>Call Stack</summary>

```
QueryReqWrap.onresolve [as oncomplete] dns.js:203:19
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting.  Please provide repro steps so we can further investigate this.
