### ISSUE TITLE
Need for toggling cosmos db explorer configuration?

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cosmosdb#1273]
✋ VS Code Dev here..

I see there is a configuration `cosmosDB.showExplorer` to toggle the explorer. I wonder the necessity for this? There are actions for user to hide the view and view container.

**Comment by EricJizbaMSFT** [comment]
The setting has been around since before those actions existed. No strong preference on my part in terms of leaving it there or getting rid of it
