### ISSUE TITLE
Progress is shown at multiple places

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cosmosdb#1274]
✋ VS Code Dev here..

While creating an account, I see progress is shown at two places. Since it is already shown in the tree, I do not think it is necessary to show a notification.

![image](https://user-images.githubusercontent.com/10746682/71909745-e9648a80-3170-11ea-94b7-141f44888265.png)

**Comment by connor4312** [comment]
Deletion as well!

**Comment by nturinski** [comment]
We appreciate your feedback!  However, there are a lot of instances where the tree view wouldn't be visible, such as using the command palette. Or if you start a creating/deleting action and then go back to the File Explorer.
