### ISSUE TITLE
Select Subscription action should be in the title

### ISSUE THREAD

**Issue by sandy081** [microsoft/vscode-cosmosdb#1276]
Hi VS Code dev here 👋

![image](https://user-images.githubusercontent.com/10746682/71910775-d5ba2380-3172-11ea-8d4a-8738667df8a5.png)

Select subscription action should be a global action rather than an action on each entry as it does the same for all entries.

**Comment by nturinski** [comment]
We're currently investigating that in this issue: https://github.com/microsoft/vscode-azuretools/issues/350
