### ISSUE TITLE
Unable to open record

### ISSUE THREAD

**Issue by Wyzix33** [microsoft/vscode-cosmosdb#1279]
Repro steps:

1. I have a collection with this document:
```js
{ "_id" : ObjectId("5e03942812714b1304d508aa"), "name" : "DGASPC GALATI-C.P.M.\"IRENE\"&\"STUART\"", "config" : { "tip" : "client", "client" : "DGASPC GALATI-C.P.M.\"IRENE\"&\"STUART\"", "cif" : "17094425", "reg" : "", "adresa" : "STR.RADU NEGRU ,NR.1", "banca" : "", "iban" : "", "termenplata" : "", "zilegratie" : "", "contact" : "", "tel" : "", "fax" : "", "email" : "", "web" : "", "obs" : "" } }
```

and when i double click this doc i get this error ...

Action: cosmosDB.openDocument
Error type: ENOENT
Error Message: ENOENT: no such file or directory, open 'C:\Users\G\AppData\Local\Temp\vscode-cosmosdb-editor\DGASPC GALATI-C.P.M."IRENE"&"STUART"-cosmos-document.json'

Version: 0.11.0
OS: win32
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

**Comment by nturinski** [comment]
I think that this should be resolved by this PR https://github.com/microsoft/vscode-cosmosdb/pull/1228.  Could you please reopen and let me know if it hasn't?
