### ISSUE TITLE
Importing items into Cosmos DB from VS Code extension takes a long time

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-cosmosdb#1280]
It takes 3 minutes to import 70 items with the following structure...

```json
{
"name": "Single red garden gnome",
"price": 56,
"brand": {
  "name": "Home & Pro tools"
},
  "stockUnits": 98
}
```

That seems like an excessively long time for such a simple document structure.

CC @burkeholland who originally created this issue.

**Comment by burkeholland** [comment]
Here is the full file in case it helps product issue quicker...

https://gist.github.com/burkeholland/d77ff3f57401c626c79e28468595b33d

**Comment by EricJizbaMSFT** [comment]
@burkeholland I tried importing that and it took less than a second. Based on the issue title, seems like this was a db in Azure, right? (as opposed to a local mongo db) How did you create it? Was it importing into an empty collection?

**Comment by wwlorey** [comment]
We weren't able to reproduce this issue. Please reopen if you still run into it
