### ISSUE TITLE
Undo action on document mutations

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-cosmosdb#1287]
When a document updates, we need to refresh its content as the etag and ts will have changed. However, then trying to undo changes and save a document results in an error.

```
Error: Operation cannot be performed because one of the specified precondition is not met., 
```

Perhaps on an etag mismatch, we should prompt the user asking them whether they want to overwrite the document, cancel the operation, or compare them (`vscode.diff` command may help).

**Comment by neelip** [comment]
Verify that documents don't contain 'etag' anymore.

**Comment by neelip** [comment]
Currently, only the "id" is displayed from the document definition; "etag" and "ts" are hidden. This issue is fixed with a recent release.
