### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-cosmosdb#1289]
Repro steps:

1. Create a new Mongo DB database+collection in the emulator
2. Observe the error:

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.11.0
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
LanguageClient.sendRequest vscode-languageclient/client.js:1615:19
MongoDBLanguageClient.<anonymous> extension.bundle.js:622:1080292
extension.bundle.js:622:1079430extension.bundle.js:622:1079430
n extension.bundle.js:622:1079207
MongoDBLanguageClient.connect extension.bundle.js:622:1080241
Object.<anonymous> extension.bundle.js:622:1077327
extension.bundle.js:622:1073996extension.bundle.js:622:1073996
n extension.bundle.js:622:1073773
extension.bundle.js:622:1077138extension.bundle.js:622:1077138
extension.bundle.js:537:172607extension.bundle.js:537:172607
Object.<anonymous> extension.bundle.js:181:43078
extension.bundle.js:181:41170extension.bundle.js:181:41170
n extension.bundle.js:181:40947
Object.t.callWithTelemetryAndErrorHandling extension.bundle.js:181:42997
Object.<anonymous> extension.bundle.js:537:172388
extension.bundle.js:537:172042extension.bundle.js:537:172042
n extension.bundle.js:537:171819
extension.bundle.js:537:172252extension.bundle.js:537:172252
v._executeContributedCommand extensionHostProcess.js:533:925
v._doExecuteCommand extensionHostProcess.js:533:100
```

</details>

**Comment by connor4312** [comment]
Reloading the window, the following error notification pops up:

```
Couldn't start client Mongo Language Server
```

These are all the logs under "Mongo Language Server" output. I enabled trace logging on the vscode level.

````
[Error - 12:48:12 PM] Starting client failed
9
```

**Comment by connor4312** [comment]
I've since installed Mongo and configured `mongo.shell.path`, no luck. Let me know if there's more information I can provide for this issue.

**Comment by connor4312** [comment]
I received the same error "Couldn't start client Mongo Language Server" on my OS X machine. There, I had Mongo installed and in the path previously; providing it explicitly through `mongo.shell.path` didn't appear to make a difference.

**Comment by EricJizbaMSFT** [comment]
Yeah this repros for me too, but only on VS Code insiders

**Comment by AlexSobralFreitas** [comment]
I have the same issue with VS Code Insiders. Seems that is a bug with the last version of extension.

**Comment by nturinski** [comment]
@AlexSobralFreitas @conner4312  Thanks for taking the time to report.

Does this reproduce for you if you're using VS Code Stable? I'm wondering if it's something that changed in the extension or with something that changed in VS Code.

**Comment by EricJizbaMSFT** [comment]
This doesn't repro for me anymore on Insiders. @AlexSobralFreitas @connor4312 can you try again and see if it still repros?

**Comment by connor4312** [comment]
Seems to work on today's insiders

**Comment by AlexSobralFreitas** [comment]
For me it's working now. Seems corrected in the last update. Thanks.
