### ISSUE TITLE
Estimated time remaining on creation notification

### ISSUE THREAD

**Issue by connor4312** [microsoft/vscode-cosmosdb#1297]
Creating Cosmos DB instances can take several minutes. The extension shows an "in progress" notification, but I'm not sure how appropriate this is for 5+ minute processes, since normally the notifications are shown for at most several seconds.

![image](https://user-images.githubusercontent.com/2230985/72650105-4b24b180-3934-11ea-87aa-62ea571d0f10.png)

I noticed the Azure portal now provides you an estimate for how long it'll take for your resource to be created. Perhaps a flow like this would be nicer, particularly for users who haven't deployed much before and don't know how much time is 'normal':

 - A notification pops up saying `Your database is deploying to Azure. It should be ready in N minutes.` (autodismisses)
 - The tree view item displays an estimated time remaining (could be simple a countdown), `Creating copeet-test-creation, 2 minutes left...`
 - Upon completion, like it does today, a success notification is displayed

![image](https://user-images.githubusercontent.com/2230985/72650234-b8d0dd80-3934-11ea-90f7-3d13ec157017.png)

**Comment by EricJizbaMSFT** [comment]
Is this what you're talking about in the portal?
![Screen Shot 2020-03-12 at 3 24 53 PM](https://user-images.githubusercontent.com/11282622/76571849-c6f33400-6475-11ea-8e2e-41acc8791b52.png)

I'm skeptical there's an API in Azure to get the remaining time. I'd be okay adding a generic message like "It should be ready in several minutes." or "It should be ready in 5-15 minutes." or something

**Comment by connor4312** [comment]
Yep, that's what I was looking at
