### ISSUE TITLE
Unable to save opened record

### ISSUE THREAD

**Issue by playerx** [microsoft/vscode-cosmosdb#1298]
Im using the extension to manage data in mongodb, after last release (0.12.0) which was yesterday, I can't save opened record.

Steps to reproduce:
1. Connect to any mongodb instance
2. Open Collection
3. Open Record
4. Save (cmd+S)

There is an error:
```update operation document must contain atomic operators.```

I've rolled back to 1.11.0 version and everything works here.

**Comment by yutsuo** [comment]
I have the same issue, solved rolling back to 1.11.0

**Comment by nturinski** [comment]
Sorry about this regression. We currently have a fix for this in master and show hopefully release it soon.  Another workaround is to edit the document from an opened collection.

You can do this by right-clicking your collection, clicking "Open Collection" and updating the document from that `.json`.

**Comment by nturinski** [comment]
Hi all, v0.12.1 has been released and this issue should be resolved.  Please let me know if it's still causing issues!

Sorry again for the inconvenience. 😦
