### ISSUE TITLE
Prevent creating mongo db with same name as existing db

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-cosmosdb#1312]
Repro steps:

1. Have a database named "db"
2. Create a new database named "db"
3. Name the collection something different than an existing collection

Action: cosmosDB.createMongoDatabase
Error type: Error
Error Message: Cannot resolve tree item for element 1//subscriptions/9b5c7ccb-9857-4307-843b-8875e83f65e9/resourceGroups/naturins-mongo3/providers/Microsoft.DocumentDB/databaseAccounts/naturins-mongo/db/col1

Version: 0.12.1-alpha
OS: win32
Product: Visual Studio Code - Insiders
Product Version: 1.42.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
extensionHostProcess.js:520:900extensionHostProcess.js:520:900
```

</details>

**Comment by nturinski** [comment]
![image](https://user-images.githubusercontent.com/5290572/72947062-b7892180-3d35-11ea-8d43-26efe6c6ad5f.png)

But if you refresh the tree item, turns out they all actually got created
![image](https://user-images.githubusercontent.com/5290572/72947078-ca035b00-3d35-11ea-8986-703836ab64ef.png)

**Comment by EricJizbaMSFT** [comment]
Could be related to https://github.com/microsoft/vscode-cosmosdb/issues/1119
