### ISSUE TITLE
There is no conflict when importing a document into a collection twice

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1319]
**OS:** Windows
**Build Version:** [20200204.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=14373&view=artifacts&type=publishedArtifacts)
**Regression:** Not a Regression

**Repro Steps:**
1. F1->Cosmos DB: Import Document into a Collection->Select a .json file->Select one SQL collection.
2. Import this .json file to the same collection again.

**Expect:**
There is conflict when importing the same file.

**Actual:**
There is no conflict when importing the same file.
![image](https://user-images.githubusercontent.com/45614674/73832130-913da880-4842-11ea-956c-d620c24fbd39.png)

**Comment by neelip** [comment]
Cannot reproduce. Getting this error with second import...
![image](https://user-images.githubusercontent.com/17537419/95517032-169acf00-0975-11eb-9ce4-e5e4f602b83d.png)
