### ISSUE TITLE
Error with noSQL (cassandra)

### ISSUE THREAD

**Issue by israel-viveros** [microsoft/vscode-cosmosdb#1324]
Repro steps:

1.
2.

Action: cosmosDB.createDocDBDocument
Error type: Forbidden
Error Message: Sql api is not supported for this database account
ActivityId: 26d27395-0658-4db3-b7f1-6ca1627eeb26, Microsoft.Azure.Documents.Common/2.9.2

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

**Comment by nturinski** [comment]
Sorry, Cassandra is not supported at this time.  

We are happy to look into implementing it if there is a lot of feedback to do so!

**Comment by EricJizbaMSFT** [comment]
FYI Cassandra support is being tracked here: https://github.com/microsoft/vscode-cosmosdb/issues/207
