### ISSUE TITLE
self-signed certificate

### ISSUE THREAD

**Issue by Selby8707** [microsoft/vscode-cosmosdb#1325]
Repro steps:

1.Attach a Cosmos DB via Connection string on VSCode
2.Press enter

Action: cosmosDB.createDocDBDatabase
Error type: DEPTH_ZERO_SELF_SIGNED_CERT
Error Message: self signed certificate

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.42.0
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:200:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by EricJizbaMSFT** [comment]
@Selby8707 that doesn't reproduce for me with those steps. Can you give us more info - for example are you behind a company proxy or something? Have you configured proxies in VS Code?
