### ISSUE TITLE
ISSUE1

### ISSUE THREAD

**Issue by AnnanyaV** [microsoft/vscode-cosmosdb#1327]
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: da5998f0-9241-4631-a2f4-4a1714d26a08, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2, Microsoft.Azure.Documents.Common/2.9.2".

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.41.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:614:115518
extension.bundle.js:529:61135
extension.bundle.js:245:24944
```

</details>

**Comment by EricJizbaMSFT** [comment]
@AnnanyaV as the error says - please try again and hopefully it'll work. Otherwise, add detailed repro steps
