### ISSUE TITLE
Remove conflicting keybinding

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/vscode-cosmosdb#1328]
Keybinding `ctrl+shift+a` is used in vscode by default to comment block of code. It shouldn't be used by this extension.

**Comment by nturinski** [comment]
Hi @SkeLLLA

Is it possible that you have another extension that is contributing that keybinding?  When I check my keybinding.json, I don't seem to have that command.

![image](https://user-images.githubusercontent.com/5290572/74766232-d1852980-5239-11ea-8d2d-152c574d29af.png)

What version of VS Code are you running?

**Comment by SkeLLLa** [comment]
That's default shortcut in vscode for linux.

**Comment by EricJizbaMSFT** [comment]
@fiveisprime, thoughts? I'm tempted to leave it as-is. We've had this keybinding for a while and this is the first issue filed. More importantly, people should be able to customize if they want on Linux

**Comment by fiveisprime** [comment]
Yeah, I'd say leave it unless we get a big influx of Linux customers running into this. There's a reasonable workaround of remapping it manually so it's not horrible.

**Comment by EricJizbaMSFT** [comment]
So I thought changing the default would affect all users, but didn't think about the fact that we can change just for Linux and leave Mac/Windows as-is. Re-opening with that in mind
