### ISSUE TITLE
Error attach database account

### ISSUE THREAD

**Issue by daniele321b** [microsoft/vscode-cosmosdb#1330]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: MongoNetworkError
Error Message: failed to connect to server [quizazdb.documents.azure.com:10255] on first connect [[Error: getaddrinfo ENOTFOUND quizazdb.documents.azure.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)] {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
Pool.<anonymous> mongodb/server.js:431:11
Pool.emit events.js:200:13
pool.js:580:14mongodb/pool.js:580:14
connect.js:39:11mongodb/connect.js:39:11
callback mongodb/connect.js:261:5
TLSSocket.<anonymous> mongodb/connect.js:286:7
Object.onceWrapper events.js:288:20
TLSSocket.emit events.js:200:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@daniele321b please add detailed repro steps
