### ISSUE TITLE
Mismatched Input - Mongo Scrapbook error - auto formatting

### ISSUE THREAD

**Issue by IamManchanda** [microsoft/vscode-cosmosdb#1332]
**I am trying to remove the "comma" but javascript autoformatting of course**

--------------------------------------------------------------

<img width="606" alt="Screenshot 2020-02-21 at 6 32 32 PM" src="https://user-images.githubusercontent.com/4970624/75036794-a704cc00-54d8-11ea-9e87-234d72ace394.png">

**Comment by nturinski** [comment]
Hi @IamManchanda 

Sorry that you're having issues.  I'm not aware of the Cosmos extension autoformatting Javascript.  Could you check your settings and see if you have any autoformatting settings for Javascript enabled?
