### ISSUE TITLE
Unrecognized node type encountered. Could not parse NumberInt as part of NumberInt(100)

### ISSUE THREAD

**Issue by IamManchanda** [microsoft/vscode-cosmosdb#1333]
<img width="968" alt="Screenshot 2020-02-22 at 12 52 02 AM" src="https://user-images.githubusercontent.com/4970624/75064933-dd107300-550d-11ea-9a7b-2c8c5215fabf.png">

**Comment by nturinski** [comment]
Hi @IamManchanda

Thanks for reporting.  Unfortunately, our scrapbooks don't currently support the `NumberInt` constructor, but if you type `volume: 100` (without any quotes) it should be inserted as an int.

**Comment by IamManchanda** [comment]
Hey @nturinski - Thanks for reply, FWIW I still can't execute my statements due to autoformatting issues => https://github.com/microsoft/vscode-cosmosdb/issues/1332
