### ISSUE TITLE
Update Not working!!!! find , insert are working 

### ISSUE THREAD

**Issue by nitesh-khanduja-au6** [microsoft/vscode-cosmosdb#1335]
Repro steps:

1.
2.

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: The process exited with code 1.
The output window may contain additional information.

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Object.t.wrapError extension.bundle.js:529:161667
p extension.bundle.js:529:160885
Function.<anonymous> extension.bundle.js:529:159508
u extension.bundle.js:529:158650
```

</details>

**Comment by nturinski** [comment]
Hi @nitesh-khanduja-au6 

We defer to the shell when using the `update()` command.  Is your mongo shell installed properly?  Please check your syntax according to this documentation: https://docs.mongodb.com/manual/reference/method/db.collection.update/

**Comment by nitesh-khanduja-au6** [comment]
@nturinski  Yes, In terminal everything is working... But in vs code scrapbook it does't execute the db.collection.update() command ..... So i am using that in terminal ..... It' only error for UPDATE not for 
db.collection.find(), db.collection.insert() ..... Is there any solution?

**Comment by nitesh-khanduja-au6** [comment]
I can attach the whole Error file too! But it is too large. Do tell if Needed :)

**Comment by nitesh-khanduja-au6** [comment]
i don't know what was the issue with that version of vs code was....  but reinstalling it 5th time.... clean installation removing code directory and removing other such directory resolved my issue.....  thanks any ways given so much time for this
