### ISSUE TITLE
Please improve Error message: document does not contain shard key

### ISSUE THREAD

**Issue by softchris** [microsoft/vscode-cosmosdb#1341]
Repro steps:

1. Right-Click a Collection
2. Create Document
3. Get shown an error that says `document does not contain shard key`

Preferred action:
Please ensure there is a link to Docs or a more exhaustive info on how to fix this. 
Maybe even add a prompt that says, would you like to add a shard key? and be taken to a wizard, not sure what's practically possible?

Action: cosmosDB.createMongoDocument
Error type: 61
Error Message: document does not contain shard key

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Connection.<anonymous> mongodb/pool.js:466:61
Connection.emit events.js:200:13
processMessage mongodb/connection.js:364:10
TLSSocket.<anonymous> mongodb/connection.js:533:15
TLSSocket.emit events.js:200:13
addChunk _stream_readable.js:294:12
readableAddChunk _stream_readable.js:275:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by neelip** [comment]
Verify if this error still occurs.

**Comment by neelip** [comment]
Closing as it cannot be reproduced. Please reopen this issue if it recurs.
