### ISSUE TITLE
Can't create MongoDB acount, feature broken or?

### ISSUE THREAD

**Issue by softchris** [microsoft/vscode-cosmosdb#1342]
Repro steps:

1. Right-click subscription
2. Select Create account
3. Enters new name e.g chris-cosmos
4. Selects `Azure CosmosDB for MongoDB`
5. Displays error `Entry not found in cache`

This is not a very helpful message, is something wrong with my subscription, is this feature not supported in the extension ?

Action: cosmosDB.createAccount
Error type: Error
Error Message: Entry not found in cache.

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:48963
b.<anonymous> extension.js:229:179463
extension.js:229:174078
extension.js:229:46161
extension.js:229:44154
extension.js:229:43776
i.find extension.js:229:78269
extension.js:229:25219
```

</details>

**Comment by EricJizbaMSFT** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
