### ISSUE TITLE
Error message is unclear : Retryable writes are not supported

### ISSUE THREAD

**Issue by softchris** [microsoft/vscode-cosmosdb#1343]
Repro steps:

1. Create a MongoDB Database by right clicking on CosmosDB acount
2. Shows `Retryable writes are not supported`

Comment: I don't understand why I have to do this. Will the extension not work properly if I don't? 
Why can't this be done for me?
From a UX perspective, it looks weird that I get an error the first thing that happens after creating a Database, makes me think something is broken in general

Action: cosmosDB.createMongoDatabase
Error type: 2
Error Message: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.

Version: 0.12.1
OS: darwin
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
Connection.<anonymous> mongodb/pool.js:466:61
Connection.emit events.js:200:13
processMessage mongodb/connection.js:364:10
TLSSocket.<anonymous> mongodb/connection.js:533:15
TLSSocket.emit events.js:200:13
addChunk _stream_readable.js:294:12
readableAddChunk _stream_readable.js:275:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by DarkLite1** [comment]
I received the same error message today from the extension for our Azure Cosmos MongoDB. For us it happened after right clicking the database and selecting `Create new collection`. The thing is the error popped up and it seemed like the collection was not created. After restart it appears the collection was created none the less. Really strange bug....

**Comment by DarkLite1** [comment]
The same error is thrown when trying to create a new document:

> Connection to the database is successful
> (node:14120) UnhandledPromiseRejectionWarning: MongoError: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.
>     at MessageStream.messageHandler (T:\Test\Brecht\Node\acadamind\mean-course\node_modules\mongodb\lib\cmap\connection.js:261:20)
>     at MessageStream.emit (events.js:321:20)
>     at processIncomingData (T:\Test\Brecht\Node\acadamind\mean-course\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
>     at MessageStream._write (T:\Test\Brecht\Node\acadamind\mean-course\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
>     at doWrite (_stream_writable.js:454:12)
>     at writeOrBuffer (_stream_writable.js:436:5)
>     at MessageStream.Writable.write (_stream_writable.js:327:11)
>     at TLSSocket.ondata (_stream_readable.js:708:22)
>     at TLSSocket.emit (events.js:321:20)
>     at addChunk (_stream_readable.js:297:12)
>     at readableAddChunk (_stream_readable.js:273:9)
>     at TLSSocket.Readable.push (_stream_readable.js:214:10)
>     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23)
> (node:14120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:14120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will
> terminate the Node.js process with a non-zero exit code.
>

**Comment by DarkLite1** [comment]
Related to #1296

**Comment by sinal01** [comment]
I don't see the solution/fix for the issue and 1296 is also closed. Can some one give a clear solution as setting retryWrites: false  looks like did not work..

**Comment by EricJizbaMSFT** [comment]
@sinal01 this issue is still open and we don't have a fix yet. We hope to fix in the current milestone

My understanding of the bug was that it was a pretty gross error message, but it didn't occur consistently. Are you blocked from doing something or does it work if you try again? If you're blocked, can you give more detailed steps on how you created the database, what action you're performing, and anything else that might be useful for us to get a consistent repro

**Comment by sinal01** [comment]
I tried in one of our lower environment adding to connections String - &retrywrites=false
I did not see the issue anymore.  We did upgrade to spring-boot 2.2.4 and started seeing this issue. But again looks like it is fixed by adding retryWrites=false. I will keep you posted if I find any thing related to this bug. Thank you for quick turnaround.

**Comment by sinedied** [comment]
@EricJizbaMSFT I got this issue when trying to insert data on a CosmosDB account created from the portal, here's some things I saw:
- There's no error if you choose MongoDB `3.2` during Cosmos DB account creation, it only occurs with `3.6`.
- adding `&retrywrites=false` to the connection strings makes the error disappear, as said by @sinal01 
- Azure CLI use 3.2 by default for account creation, but the portal have 3.6 selected by default, is there any reason for that difference?
