### ISSUE TITLE
erro creating account cosmos db

### ISSUE THREAD

**Issue by ebilieri** [microsoft/vscode-cosmosdb#1344]
Repro steps:

1.
2.

Action: cosmosDB.createAccount
Error type: 403
Error Message: Failed with code "403".

Version: 0.12.1
OS: win32
Product: Visual Studio Code
Product Version: 1.42.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:614:499041extension.bundle.js:614:499041
s extension.bundle.js:614:109108
s extension.bundle.js:529:56222
extension.bundle.js:529:57466extension.bundle.js:529:57466
a extension.bundle.js:536:7046
extension.bundle.js:529:55135extension.bundle.js:529:55135
U._callback extension.bundle.js:245:158443
U.t._callback.t.callback.t.callback extension.bundle.js:596:5450
U.emit events.js:200:13
U.<anonymous> extension.bundle.js:596:18310
U.emit events.js:205:15
IncomingMessage.<anonymous> extension.bundle.js:596:17142
Object.onceWrapper events.js:288:20
IncomingMessage.emit events.js:205:15
endReadableNT _stream_readable.js:1154:12
processTicksAndRejections task_queues.js:84:9
```

</details>

**Comment by EricJizbaMSFT** [comment]
@ebilieri you likely don't have permissions to create a resource group. Try selecting an existing one instead.

This has been improved in https://github.com/microsoft/vscode-azuretools/pull/651 (but not shipped yet)
