### ISSUE TITLE
Support for query execution metrics being displayed

### ISSUE THREAD

**Issue by tknandu** [microsoft/vscode-cosmosdb#1345]
[Tweet](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Ftwitter.com%2FSavranWeb%2Fstatus%2F1234462555818668032%3Fs%3D20&data=02%7C01%7Cramkris%40microsoft.com%7C2aa42127b3ed49df09d308d7c066c73f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637189419965789360&sdata=Zz96XTTXNbZ4tWzzVXIVn606gvf6PS4zQ2gy9MtoAsM%3D&reserved=0)

**Comment by EricJizbaMSFT** [comment]
Related to https://github.com/microsoft/vscode-cosmosdb/issues/814

**Comment by jinglouMSFT** [comment]
This ask is to expose the SQL API query execution metrics.
