### ISSUE TITLE
I'm also having this issue, if I can be helpful by sharing my config or other, please reach out.

### ISSUE THREAD

**Issue by FaresKis** [microsoft/vscode-cosmosdb#1360]
I'm also having this issue, if I can be helpful by sharing my config or other, please reach out.
EDIT : I'm having this issue on VS Code Stable, not insiders.

_Originally posted by @aymericbouzy in https://github.com/microsoft/vscode-cosmosdb/issues/1334#issuecomment-597497257_

Same here. Seems like the new Stable version of VS Code doesn't handle MongoDB correctly.

**Comment by nturinski** [comment]
We should have a patch out for this soon.  Thanks for reporting!

Dupe of #1334
