### ISSUE TITLE
There is no response after clicking "View Extension" button

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1371]
**OS:** Windows
**Build:** [20200318.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=16396&view=artifacts&type=publishedArtifacts)

**Steps:**
1. Don't install the Cosmos DB Graph extension.
2. Expand the Gremlin account and click a graph.
3. Click the "View Extension" button in the prompt dialog.
![image](https://user-images.githubusercontent.com/45614674/76963154-899e1300-695b-11ea-8b9e-cc1f6345aded.png)

**Expect:**
It should bring up the marketplace page for Cosmos DB Graph extension.

**Actual:**
There is no response after clicking "View Extension" button.

**Comment by EricJizbaMSFT** [comment]
@v-ruizh this is expected. It won't work until we publish the first version of the Cosmos DB Graph extension, which won't happen for a little while
