### ISSUE TITLE
"Create New Collection" doesn't validate input?

### ISSUE THREAD

**Issue by whiskeyjay** [Microsoft/vscode-cosmosdb#139]
1. Right click on a (Mongo) database and then select "Create Collection".
2. In the InputBox type in an invalid name, like "!@)*#&!@#", then hit enter.

Expected:
InputBox validation will catch invalid names.

Actual:
Nothing happens (no error message, no new collection)

**Comment by nturinski** [comment]
This applies to creating a new Document as well.  If you put invalid characters, the output pane appends a new blank line, but no error and no new document is created.

**Comment by nturinski** [comment]
Nit: Apparently, Partition keys cannot start with numbers or any other symbol other than a alphabet character.  Not a big deal, but it'd be nice to see that before trying to create the collection

**Comment by PrashanthCorp** [comment]
![image](https://user-images.githubusercontent.com/30420973/32353937-b44489d6-bfe4-11e7-8e18-ab2e3c0a785d.png)
Seems to fail a little gracefully in my use case.
