### ISSUE TITLE
Add ability to run multiple Mongo commands at a time

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#14]
We should provide some way to run multiple selected commands. We could also consider adding a 'Execute All Commands' option that runs all commands in a scrapbook

In order to fix this, we would have to deal with #13 otherwise a lot of output would be lost

**Comment by StephenWeatherford** [comment]
Closing as dup of #386

**Comment by StephenWeatherford** [comment]
Fixed via #515
