### ISSUE TITLE
Notification shows "Import into SQL successful. Inserted 1 document(s)..." after importing the second file 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1400]
**OS:** Windows
**Build:** [20200331.21](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=17072&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Right click the account --> Import Document into a Collection...
2. Select a file to import into a SQL collection.
3. Import a different file to this collection again.

**Expect:**
Notification shows "Import into SQL successful. Inserted 2 document(s)...".

**Actual:**
Notification still shows "Import into SQL successful. Inserted 1 document(s)..."
![image](https://user-images.githubusercontent.com/57662131/78124446-43a87b00-7442-11ea-88aa-35bc0a43fa72.png)

**More info:**
1. This issue also reproduces for Mongo account.
2. The notification will show "Inserted 3 document(s)..." after importing the third file.
![image](https://user-images.githubusercontent.com/57662131/78124363-25db1600-7442-11ea-8d03-72de89e0b212.png)

**Comment by EricJizbaMSFT** [comment]
@v-xinda please add more info here. It's hard to tell what the numbers should be when we don't know how many documents you're importing at a time

**Comment by v-xinda** [comment]
Import different documents one by one, the result shows as below: 


Document | Notification
-- | --
First | Import into SQL   successful. Inserted 1 document(s)…
Second | Import into SQL   successful. Inserted 1 document(s)…
Third | Import into SQL   successful. Inserted 3 document(s)…
Fourth | Import into SQL   successful. Inserted 1 document(s)…
Fifth | Import into SQL   successful. Inserted 1 document(s)…
