### ISSUE TITLE
microsofts azure Extensions issue

### ISSUE THREAD

**Issue by prathap-web** [microsoft/vscode-cosmosdb#1403]
Repro steps:

1.
2.

Action: cosmosDB.executeAllMongoCommands
Error type: Error
Error Message: db.friends.find at 13:1: Error near line 17, column 0: 'mismatched input 'mongo' expecting <EOF>'. Please check syntax.

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:245:242732extension.bundle.js:245:242732
u extension.bundle.js:245:239243
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by EricJizbaMSFT** [comment]
@prathap-web can you give us the exact command that was giving you this error
