### ISSUE TITLE
org.freedesktop.secrets exception

### ISSUE THREAD

**Issue by kcwms** [microsoft/vscode-cosmosdb#1405]
Repro steps:

1. from CosmosDB tab sign into Azure
2. select "Attach Database Account" and select "Azure Cosmos DB for MongoDB Api"
3. enter primary connection string copied from Azure CosmosDB Connection String tab
4. Enter and receive the following error

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: The name org.freedesktop.secrets was not provided by any .service files

Version: 0.12.2
OS: linux
Product: Visual Studio Code
Product Version: 1.43.2
Language: en

**Comment by kcwms** [comment]
@nturinski 

No and no ... at least not that I'm aware of. 

Note that, although I get the error, my CosmosDB account is found and I'm able to see my documents.

Also, when in the WIN10 partition on this same machine, I get no errors and I'm able to see my documents as expected.

**Comment by nturinski** [comment]
Interesting, so this only reproduces on Linux? Also, it is not blocking you from using the extension either?

**Comment by kcwms** [comment]
>>so this only reproduces on Linux?
You sound surprised :)
But seriously, yes both statements are correct.

By the way, what does the error actually mean?

**Comment by nturinski** [comment]
Haha, it's less like disbelief and more like dismay 😬 

I think it has to do with using keytar to store the Cosmos Account credentials.  There's an article here that discusses the error [here](https://rtfm.co.ua/en/linux-the-nextcloud-client-qtkeychain-and-the-the-name-org-freedesktop-secrets-was-not-provided-by-any-service-files-error/) but the TLDR is, I think that this can be resolved if you install `gnome-keyring`.  

If you do install it, please let me know if that resolves the issue! 😃
