### ISSUE TITLE
Support Postgres Functions

### ISSUE THREAD

**Issue by wwlorey** [microsoft/vscode-cosmosdb#1407]
Stored procedures and functions were both created using the `CREATE FUNCTION` syntax until Postgres 11. The newest versions added support for `CREATE PROCEDURE` which also allows you to run transactions.

I think it would be best to add support for functions and stored procedures separately and only show procedures for v11. This would be consistent with how GUIs like pgAdmin handle this:

<img width="257" alt="Screen Shot 2020-04-06 at 1 11 20 PM" src="https://user-images.githubusercontent.com/22795803/78601526-c5fdba00-7809-11ea-9a83-42a05d7f0269.png"><img width="264" alt="Screen Shot 2020-04-06 at 1 13 55 PM" src="https://user-images.githubusercontent.com/22795803/78601533-c8601400-7809-11ea-9995-a73172671e6e.png">

@fiveisprime, @EricJizbaMSFT, @nturinski what do you think of this approach?

**Comment by fiveisprime** [comment]
Agreed. So this would mean that v10 databases won't show "Procedures," right?

**Comment by wwlorey** [comment]
Right, only v11 and up would show procedures

**Comment by wwlorey** [comment]
Splitting stored procs into a separate issue: https://github.com/microsoft/vscode-cosmosdb/issues/1471
