### ISSUE TITLE
Not able to delete documents

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#141]
I am unable to delete documents from the extension.  I created a document from the extension and from the portal and both are giving me the same error (attached).
![image](https://user-images.githubusercontent.com/5290572/32351487-c56b6f86-bfda-11e7-9f9e-3c8147fe7fe7.png)
![image](https://user-images.githubusercontent.com/5290572/32351512-e1030b82-bfda-11e7-9264-1f7792cf57e2.png)

**Comment by PrashanthCorp** [comment]
Just to clarify, are you trying to delete a collection (as the title says) or a document (as the description says) ?
