### ISSUE TITLE
local mongo db server is not working

### ISSUE THREAD

**Issue by mrrwaa** [microsoft/vscode-cosmosdb#1416]
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: MongoNetworkError
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [[Error: connect ECONNREFUSED 127.0.0.1:27017
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14)] {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.44.0
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1056:14
Pool.<anonymous> mongodb/server.js:431:11
Pool.emit events.js:203:13
pool.js:580:14mongodb/pool.js:580:14
connect.js:39:11mongodb/connect.js:39:11
callback mongodb/connect.js:261:5
Socket.<anonymous> mongodb/connect.js:286:7
Object.onceWrapper events.js:291:20
Socket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Thanks for reporting @mrrwaa 

Could you provide repro steps?  That error is generally seen when the local Mongo instance isn't running.  How are you running mongod?
