### ISSUE TITLE
Canceling "Create Document" creates a new document anyway

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#142]
If you click "Create Document" from the context menu, it will create a new document with a random id anyway.  Same behavior as just hitting enter when you have not entered input yet.

**Comment by PrashanthCorp** [comment]
I disallowed the empty id after feedback on https://github.com/Microsoft/vscode-cosmosdb/pull/148. 
Removing the check.

**Comment by EricJizbaMSFT** [comment]
@whiskeyjay were you aware an empty id would auto-generate an id for the user when you gave that feedback? It might not be obvious to the user at first, but it seems like a useful feature to me (Plus it's easy to delete the document if that's not what you wanted)
