### ISSUE TITLE
Fail to delete a SQL document

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1434]
**OS:** Mac
**Build Version:** [20200422.7](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18192&view=artifacts&type=publishedArtifacts)

**Repro Steps:**
1. Create a SQL account.
2. Create a Collection with a partition key.
3. Create a document and leave blank for partition key.
4. Delete the document.

**Expect:**
Delete the document successfully without any error.

**Actual:**
Fail to delete the document and pop up an error.
![image](https://user-images.githubusercontent.com/57662131/80090718-83bad380-8592-11ea-87b0-0e8a27b4117b.png)
 Details in output:
	
2:57:23 PM: Error: Entity with the specified id does not exist in the system., 
	RequestStartTime: 2020-04-23T06:57:23.1250635Z, RequestEndTime: 2020-04-23T06:57:23.1250635Z,  Number of regions attempted:1
	ResponseTime: 2020-04-23T06:57:23.1250635Z, StoreResult: StorePhysicalAddress: rntbd://bluprdapp02-docdb-1.documents.azure.com:14471/apps/b3102e89-1a41-41aa-b073-4499e437059e/services/f29eff1a-a796-4f9f-aa41-7f1b28cdd08d/partitions/7fa2dfbb-71bc-4cd5-a2ed-1cae9d50deef/replicas/132315858713877073p/, LSN: 9, GlobalCommittedLsn: 9, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 9, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Delete
	, Microsoft.Azure.Documents.Common/2.10.0
```

**Comment by neelip** [comment]
We are able to repro this issue, we will get to fixing it in the next update
