### ISSUE TITLE
A suggestion to use {useUnifiedTopology:true}

### ISSUE THREAD

**Issue by arindamlahiri** [microsoft/vscode-cosmosdb#1438]
Every time I open up the azure tab, this deprecation warning pops up.
`DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`
I know it's just a warning and doesn't produce a fatal error but it pops open the output console unnecessarily and interrupts the workflow. Hope this addition can be made.

PS- This is my first time raising an issue. I'm not sure if this even deserves an issue. Hope I didn't waste anybody's time.

**Comment by EricJizbaMSFT** [comment]
Tracking this in https://github.com/microsoft/vscode-cosmosdb/issues/1306
