### ISSUE TITLE
Error when quickly clicking Updateto Azure

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#144]
If you spam click the 'Update to Azure' button, it outputs this error:

ActivityId: 4261b04b-918f-4dab-9a5c-49c5f8e3284d, Request URI: /apps/40790e35-e390-4e4f-91a1-18885677940a/services/46dca2d1-0d38-486b-9bb1-92a83eb74db9/partitions/c9a2a5d2-be1d-4576-aec7-8f1a0ba4ed4d/replicas/131540403065647044p
Message: {"Errors":["One of the specified pre-condition is not met"]}

**Comment by PrashanthCorp** [comment]
Unable to repro.
