### ISSUE TITLE
Error trying to attach Azure Cosmos Emulator in VS Code

### ISSUE THREAD

**Issue by esQmo** [microsoft/vscode-cosmosdb#1440]
Repro steps:

1. Right click the “Attached Database Accounts” then click “Attach Emulator”.
2. Choose API = Azure Azure Comos for MongoDb API
3. Error arises

Action: cosmosDB.attachEmulator
Error type: MongoNetworkError
Error Message: failed to connect to server [localhost:10255] on first connect [Error: connect ECONNREFUSED 127.0.0.1:10255
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1056:14) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.44.2
Language: en

<details>
<summary>Call Stack</summary>

```
TCPConnectWrap.afterConnect [as oncomplete] net.js:1056:14
Pool.<anonymous> mongodb/server.js:431:11
Pool.emit events.js:203:13
Pool.EventEmitter.emit domain.js:476:20
pool.js:580:14mongodb/pool.js:580:14
connect.js:39:11mongodb/connect.js:39:11
callback mongodb/connect.js:261:5
TLSSocket.<anonymous> mongodb/connect.js:286:7
Object.onceWrapper events.js:291:20
TLSSocket.emit events.js:203:13
TLSSocket.EventEmitter.emit domain.js:476:20
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
It looks like the Mongo emulator isn't actually running.  In order to run the emulator with Mongo specifically, you have to run it with "/EnableMongoDbEndpoint".  You can learn more about that [here](https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#azure-cosmos-dbs-api-for-mongodb)
