### ISSUE TITLE
Display the option "+Create new Account…" after selecting "Cosmos DB: Delete Account…" from Command palette

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1441]
**OS:** Win10
**Build Version:** [20200427.6](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=18396&view=results)

**Repro Steps:**
1. F1 --> Type and select "Cosmos DB: Delete Account...".
2. Prompt to select subscription.
3. Prompt to select Account to delete.

**Expect:**
Only display the existing accounts.

**Actual:**
Display the option "+Create new Account…".
![image](https://user-images.githubusercontent.com/57662131/80476173-99f2d600-897c-11ea-985b-56bddb7e81ff.png)

**More Info:**
This issue also reproduces on all delete command from Command Palette.

**Comment by neelip** [comment]
Do we want to remove this option for all "delete" commands? If so, what do we want to display when the list is empty?

**Comment by wwlorey** [comment]
I'd vote for removing it from all delete commands as long as that's not too much work. And if the list is empty, doesn't it already throw a "no matching resources found" error?
