### ISSUE TITLE
Document ID does not refresh on Explorer

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#145]
If you rename an id, it does not refresh on the explorer unless you manually refresh it.  It should probably refresh itself to update the label on the explorer if the id is changed.

**Comment by EricJizbaMSFT** [comment]
@nturinski please add more detailed repro steps. I don't believe we support editing the '_id' property at the moment

**Comment by PrashanthCorp** [comment]
I think it is tied to [this issue](https://github.com/Microsoft/vscode/issues/27823#issuecomment-351144189) I talked about. This hasn't gotten much traction though. 
In [this PR](https://github.com/Microsoft/vscode-cosmosdb/pull/277/files#diff-45327f86d4438556066de133327f4ca2R108), I still resort to refreshing the node to show the `(Connected)` sign next to a connected DB. 

I would mark this bug as external.

**Comment by EricJizbaMSFT** [comment]
To clarify, you can't change the '_id' filed for a mongo document, so this doesn't apply in that case. However, we should consider fixing for docdb

**Comment by StephenWeatherford** [comment]
This is possible to do, but the work-around is simply to refresh.
