### ISSUE TITLE
Add support for Self-signed Certificates

### ISSUE THREAD

**Issue by levz0r** [microsoft/vscode-cosmosdb#1458]
Hello everyone,

I have an unmanaged MongoDB instance running on a VM. In addition to basic authentication, the server requires the client to use a .pem certificate (the certificate is protected with a passphrase).

Here are the connection settings from a popular commercial mongo client:

![image](https://user-images.githubusercontent.com/4564386/81741940-fccd8c80-94a7-11ea-8ef7-84699f50232a.png)

It will be awesome if Cosmos would support this somehow!

Thank you!

**Comment by wwlorey** [comment]
VS Code handles certificates for this extension. Try this out and let us know if that solves your problem: https://code.visualstudio.com/docs/setup/network

**Comment by levz0r** [comment]
Hi,

After checking the link, I am still not sure how to use these features in order to load the self-signed certificate.

Any help will be appreciated.
