### ISSUE TITLE
There is no deleting status next to PostgreSQL server when deleting a PostgreSQL server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1460]
**OS:** Win10
**Build Version:** [20200512.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=19144&view=artifacts&type=publishedArtifacts)

**Repro Steps:**

1. Delete a PostgreSQL server from the context menu
2. Check its status

**Expect:**
There is a deleting status, such as:
![image](https://user-images.githubusercontent.com/62053665/81801564-373a3680-9547-11ea-96fc-89bbff8a0b30.png)

**Actual:**
There is no status of deleting.
![image](https://user-images.githubusercontent.com/62053665/81801611-44efbc00-9547-11ea-965f-5333882e548b.png)

**Comment by wwlorey** [comment]
The deleting status shows up after you select delete in the confirmation dialog 

<img width="278" alt="Screen Shot 2020-05-13 at 9 43 27 AM" src="https://user-images.githubusercontent.com/22795803/81841870-e94e1000-94ff-11ea-9720-cc3abc0cd250.png">
