### ISSUE TITLE
Connection string includes "retrywrites=false" but still getting error when trying to retryable writes 

### ISSUE THREAD

**Issue by helloanh** [microsoft/vscode-cosmosdb#1466]
Repro steps:

1. Go into the collection and edit the item.  
2. Click on save.

This is my updated xxxx-cosmos-document.json
`{
  "_id": {
    "$oid": "5ebeba4f63abcb27ec075111"
  },
  "title": "Someone stole the mobile pizza oven ",
  "city": "Hyattsville",
  "description": "This person stole their mobile pizza oven.",
  "publishedDate": {
    "$date": "2020-04-01T07:00:00.000Z"
  },
  "imgUrl": "https://d3926qxcw0e1bh.cloudfront.net/post_photos/a0/30/a030e99440f75e38527db20844c4ab06.jpeg.smartcrop279x304.jpeg"
}`

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: 2
Error Message: Retryable writes are not supported. Please disable retryable writes by specifying "retrywrites=false" in the connection string or an equivalent driver specific config.

Version: 0.12.2
OS: darwin
Product: Visual Studio Code
Product Version: 1.45.0
Language: en

<details>
<summary>Call Stack</summary>

```
Connection.<anonymous> mongodb/pool.js:466:61
Connection.emit events.js:203:13
processMessage mongodb/connection.js:364:10
TLSSocket.<anonymous> mongodb/connection.js:533:15
TLSSocket.emit events.js:203:13
addChunk _stream_readable.js:295:12
readableAddChunk _stream_readable.js:276:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by nturinski** [comment]
Hi @helloanh

Sorry that you're running into issues!  Can you verify with me that you are adding the retrywrites=false parameter in the follow way:

`mongodb://mongodb0.example.com:27017/?retrywrites=false`

**Comment by nturinski** [comment]
Should be fixed by https://github.com/microsoft/vscode-cosmosdb/pull/1493
