### ISSUE TITLE
How to connect to Atlas?

### ISSUE THREAD

**Issue by pife00** [microsoft/vscode-cosmosdb#1470]
when I write in the panel say that:
![Captura](https://user-images.githubusercontent.com/65521330/82169811-48a57a80-9888-11ea-8645-e684239c2786.PNG)

but the String has it, I don't know if I did bad. Local mongo works well, thanks for the extension

**Comment by nturinski** [comment]
Hi @pife00 
It loos like you have quotes prefixing your connection string.  Try removing the quote at the beginning (and the end if it is present there, I cannot tell by the screenshot) and try again!

Let me know the result 😃

**Comment by pife00** [comment]
I did:
![Captura2](https://user-images.githubusercontent.com/65521330/82262533-b4d6bb80-9926-11ea-8dd7-8c40971b3d3e.PNG)
Buy only get this:
![Captura3](https://user-images.githubusercontent.com/65521330/82262549-be602380-9926-11ea-9379-51c01d19efa5.PNG)

**Comment by neelip** [comment]
Sorry for the delay. It seems like you are using the CLI connection string rather than the URI.
