### ISSUE TITLE
following ms learn turturial should not be error

### ISSUE THREAD

**Issue by xilef88** [microsoft/vscode-cosmosdb#1473]
Repro steps:

1.
2.

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: PreconditionFailed
Error Message: Operation cannot be performed because one of the specified precondition is not met., 
RequestStartTime: 2020-05-19T20:15:44.5372791Z, RequestEndTime: 2020-05-19T20:15:44.5472810Z,  Number of regions attempted:1
ResponseTime: 2020-05-19T20:15:44.5472810Z, StoreResult: StorePhysicalAddress: rntbd://cdb-ms-prod-northeurope1-fd28.documents.azure.com:14356/apps/aed88975-8c4b-4d55-baf4-19034ff50107/services/7da6b923-0451-40c0-9bf2-1322c471bd40/partitions/3d361a6c-633f-46ae-aa46-5089da201796/replicas/132343854015097043p/, LSN: 20, GlobalCommittedLsn: 20, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 412, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: 20, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Replace
, Microsoft.Azure.Documents.Common/2.11.0

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

**Comment by nlksg** [comment]
Ya.. I also face same error while doing same tutorial during Cloud Skills Challenge
