### ISSUE TITLE
can't update my file

### ISSUE THREAD

**Issue by iqranaz240** [microsoft/vscode-cosmosdb#1481]
Repro steps:

1.
2.

Action: cosmosDB.update
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND iqraaaa.documents.azure.com

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.40.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by wwlorey** [comment]
Please add steps to reproduce
