### ISSUE TITLE
An error "syntax error..." occurs when deleting one Function

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1494]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
1. Drill down PostgreSQL->One database->Right click Functions node and select "Create Function Query".
2. Execute this function query.
3. Delete this new created Function.

**Expect:**
Delete the Function successfully.

**Actual:**
An error "syntax error..." occurs when deleting this Function.
![image](https://user-images.githubusercontent.com/45614674/82656275-1021ea00-9c56-11ea-9038-6c7516728812.png)

**Comment by wwlorey** [comment]
@v-ruizh what function name and return type did you use? Also did you edit the function query at all before executing?

**Comment by v-ruizh** [comment]
@wwlorey we tried several return type and name function with random characters. **Not edit** the function query before executing. Such as create function "test" and return type void, then execute query and delete the created function. 

**More info:**
1. This issue reproduces for the PostgreSQL which created from VS Code. 
2. The function can be deleted successfully if the PostgreSQL is created from portal.
