### ISSUE TITLE
There are 4 errors for the created "Function Query"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1495]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
1. Drill down PostgreSQL->One database->Right click Functions node and select "Create Function Query"->Provide a function name->Select return type.
2. Install the SQL Server extension when prompt to install it.
3. Check the "PROBLEMS"

**Expect:**
There is no error in the "PROBLEMS".

**Actual:**
There are 4 errors in the "PROBLEMS".
![image](https://user-images.githubusercontent.com/45614674/82656663-b79f1c80-9c56-11ea-85e6-c855cc79a978.png)

**More info:**
Execute query successfully with these errors.
![image](https://user-images.githubusercontent.com/45614674/82656908-15cbff80-9c57-11ea-884a-650bac394518.png)

**Comment by wwlorey** [comment]
For now, let's use the `psql` file extension and let people download a separate extension for coloring support
