### ISSUE TITLE
Change the command "Cosmos DB: Attach Database Account" to "Azure Databases: Attach Database Account"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1498]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
F1->Check the command "Attach Database Account..."

**Expect:**
This command shows "Azure Databases: Attach Database Account...".

**Actual:**
This command shows "Cosmos DB: Attach Database Account..."
![image](https://user-images.githubusercontent.com/45614674/82659464-5594e600-9c5b-11ea-8540-926a651907fe.png)

**Comment by wwlorey** [comment]
We shouldn't let people select a Postgres account from that command. And since this doesn't apply to Postgres accounts, I think we want to keep the label as "Cosmos DB". Good find!
