### ISSUE TITLE
There is no auto-refresh for Functions node when creating functions

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1499]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
1. Drill down PostgreSQL->One database->Right click Functions node and select "Create Function Query"->Provide a function name->Select return type.
2. Execute this function query.
3. Check the Functions node. 

**Expect:**
There is auto-refresh for Functions node, the new created function lists in it.

**Actual:**
There is no auto-refresh for Functions node.

**More info:**
Change the function name in the query, execute the function query again, the Functions node will auto-refresh and list the first function.

**Comment by wwlorey** [comment]
This is by design for now (we're limited by engineering on this one)
