### ISSUE TITLE
[Suggestion] Add the log "Created a function..." in output when executing the function query

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1500]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
1. Drill down PostgreSQL->One database->Right click Functions node and select "Create Function Query"->Provide a function name->Select return type.
2. Execute this function query.
3. Check the output log.

**Actual:**
The output log is always "Successfully executed 'CREATE' query".
![image](https://user-images.githubusercontent.com/45614674/82663000-7102ef80-9c61-11ea-8337-d225706a0d5f.png)

**Suggestion:**
Add the log "Created a function..." in output, it's very clear to check which function is created.

**Comment by wwlorey** [comment]
The only info returned from the `QueryResult` object when a function is created via a query is the command used (in this case "CREATE"). You could also create a table or stored procedure using a create query and the same object would be returned.

Is it worth parsing the query ourselves to determine the type of resource created?

**Comment by EricJizbaMSFT** [comment]
> Is it worth parsing the query ourselves to determine the type of resource created?

I vote no
