### ISSUE TITLE
[Suggestion] Add a checkbox for every function in the list when deleting function using command

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1501]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
1. F1->PostgreSQL: Delete Functions...->Select the subscription and account->Select database
2. Check the Function list.

**Actual:**
There is no checkbox in Function list, we can only delete one Function at a time. 
![image](https://user-images.githubusercontent.com/45614674/82663452-46fdfd00-9c62-11ea-95f8-24bb71f01ac5.png)

**Suggestion:**
Add a checkbox for every function, it is convenient to delete multiple function at one time.

**Comment by wwlorey** [comment]
While this is nice to have, we'll see if a user reports this before implementing
