### ISSUE TITLE
Combine the delete commands for Cosmos DB account and PostgreSQL server

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1503]
**OS:** All
**Build Version:** 20200522.22

**Repro Steps:**
Check the delete server commands from Command Palette.

**Expect:**
Combine the delete commands for Cosmos DB account and PostgreSQL server with one command "Azure Databases: Delete Server...", like the create server command.
![image](https://user-images.githubusercontent.com/45614674/82665566-a5c57580-9c66-11ea-9261-b5be5b732b29.png)

**Actual:**
There are 2 separate commands for Cosmos DB account and PostgreSQL server.
![image](https://user-images.githubusercontent.com/45614674/82665624-c68dcb00-9c66-11ea-82d8-ef34024ca9c3.png)

**Comment by wwlorey** [comment]
Closing as by design
