### ISSUE TITLE
The validation error is unclear when inputting a duplicate account name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1505]
**OS:** All
**Build Version:** 20200522.22

**Repro step:**

1. Create a server with name "test1"
2. Create a server --> type a duplicate name "test1"
3. Check the validation error

**Expect:**
The validation error is clear-"The account name is already exists", like the static web app.
![image](https://user-images.githubusercontent.com/62053665/82655529-e4523480-9c54-11ea-8570-476b269bce60.png)

**Actual:**
The validation error is unclear.
![image](https://user-images.githubusercontent.com/62053665/82655436-c1c01b80-9c54-11ea-965c-366f292d9cd0.png)

**Comment by v-ruizh** [comment]
This issue is fixed for PostgreSQL but it also reproduces for other accounts(Mongo DB/SQL/Gremlin/Table), reopen it.
