### ISSUE TITLE
[Unstable] Failed to configure firewall rule for IP to the PostgreSQL server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1508]
**OS:** Mac
**Build Version:** 20200522.22

**Repro step:**

1. Create a server for PostgreSQL with select "Skip for now" when ask to "add firewall rule for IP"
2. Drill down from Account-->Database-->Function
3. Click "Configure firewall to connected to..."
4. Pop up a prompt ask to continue?-->Yes

**Expect:**
Configure firewall to this PostgreSQL server successfully.

**Actual:**
Failed to Configure firewall to the PostgreSQL server.

**More info:**
This is an unstable issue, even after the configuration is successful, sometimes it require to launch and reconfigure.

**Comment by wwlorey** [comment]
@v-mengwe I'm not able to repro this. When this happens does an error appear? Or does the long running notification resolve but you still can't drill down into the functions node?
