### ISSUE TITLE
Azure Cosmos DB Activity Bar view not visible

### ISSUE THREAD

**Issue by mwoodpatrick** [microsoft/vscode-cosmosdb#1511]
I have new Azure Activity Bar view installed in VSCODE running under WSL-2 and VSCODE shows the extension is installed:

Extension is enabled on 'WSL: Ubuntu-18.04'

But the view disappeared from my activity bar yesterday and is no longer listed as an available view. Any suggestions as to how to debug this and get the view back. Is there a log file I can look at somewhere to see what the issue might be

**Comment by neelip** [comment]
Are you still facing this issue?
