### ISSUE TITLE
There is no command "Import Document into a Collection..." for launch.json/tasks.json file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1519]
**OS:** Mac
**Build Version:** 20200522.22

**Repro Steps:**

1. Open myExpressApp project on VS Code.
2. Right click .vscode/launch.json.

**Expect:**
There is a command "Import Document into a Collection..." appears in the context menu, such as:
![Screen Shot 2020-05-25 at 8 21 46 PM](https://user-images.githubusercontent.com/62053665/82812461-a1e35e80-9ec5-11ea-8563-2695836be07d.png)

**Actual:**
There is no command "Import Document into a Collection..." disappears in the context menu.
![Screen Shot 2020-05-25 at 7 59 43 PM](https://user-images.githubusercontent.com/62053665/82812485-ab6cc680-9ec5-11ea-8291-b6385cfe858a.png)

**More info:**
This issue reproduces for .vscode/tasks.json.

**Comment by wwlorey** [comment]
Supporting that command for JSON files in .vscode isn't needed. Thanks for filing!
