### ISSUE TITLE
Add "Attach Emulator..." tree item

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1520]
**OS:** Windows 10
**Build Version:** 20200522.22

**Repro Steps:**
Check the "Attach Database Accounts" and its context menu.
![image](https://user-images.githubusercontent.com/45614674/82815861-9e070a80-9ecc-11ea-82fa-5a59ef801f2e.png)

**Actual:**
It only shows "Attach Database Account".

**Suggestion:**
Change "Attach Database Account" to "Attach Database Account or Emulator".

**Comment by wwlorey** [comment]
We think these are good as separate menu items. We'll add "Attach Emulator" in the tree though
