### ISSUE TITLE
Can't Create Database Problem!

### ISSUE THREAD

**Issue by tristanmagpayo** [microsoft/vscode-cosmosdb#1521]
Repro steps:

1.
2.

Action: cosmosDB.createDocDBDatabase
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND tristanjohnmagpayo.documents.azure.com

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by neelip** [comment]
Please add repro steps
