### ISSUE TITLE
please help us

### ISSUE THREAD

**Issue by nithyashree199** [microsoft/vscode-cosmosdb#1527]
Repro steps:

1.
2.

Action: cosmosDB.createDocDBDatabase
Error type: Error
Error Message: Element with id /subscriptions/34cd0048-a4c1-4ccb-a729-4df7f3cb6e2a/resourceGroups/learn-fb0192d6-71e5-4c79-a9a3-b8ef7f2f63b7/providers/Microsoft.DocumentDB/databaseAccounts/godhelpme/SchoolDB/StudentCourseGrades is already registered

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
e.createAndRegisterTreeNode extensionHostProcess.js:607:521
extensionHostProcess.js:606:225extensionHostProcess.js:606:225
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by neelip** [comment]
Please add repro steps
