### ISSUE TITLE
How to query (for Date)

### ISSUE THREAD

**Issue by TinusScheppers** [Microsoft/vscode-cosmosdb#153]
Hi,

How do you use the scratch book to query your DB for Date?
This does not seem to work:
`db.member.find({ resp_week: { $lt: new Date(), $ne: null } })`
resulting in:
`Unexpected end of input`

More in general, is there any documentation on querying (except for the mongo shell docs, which does not suffice for Date query's)?

Kind regards
Tinus

**Comment by PrashanthCorp** [comment]
Did you try `db.member.find({ ts: { '$lt': 'new Date()', '$ne': null } })` ? Quotes around the expressions that need to be parsed as JS. 

We try to support the mongo shell to the best we can. We feel the [mongo shell documentation](https://docs.mongodb.com/manual/reference/mongo-shell/#basic-shell-javascript-operations) should be a good reference.

**Comment by TinusScheppers** [comment]
Indeed that did the trick!
Thanks!
