### ISSUE TITLE
Cannot create document

### ISSUE THREAD

**Issue by andrejs86** [microsoft/vscode-cosmosdb#1537]
Repro steps:
1. While doing exercise from MS Learning https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance, Activated Sandbox
2. Install CosmosDB (preview) Extension 
3. Create an account
4. Create a database
5. Create a collection 
6. Tried to create a new document.

Action: cosmosDB.createDocDBDocument
Error type: EAI_AGAIN
Error Message: getaddrinfo EAI_AGAIN basaschool.documents.azure.com

Version: 0.12.2
OS: win32
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>
![Screenshot_1](https://user-images.githubusercontent.com/35151217/83053655-77a9b200-a027-11ea-9b9b-c3b6a3c5af9b.png)

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by neelip** [comment]
EAI_AGAIN is a network or proxy related error.

**Comment by neelip** [comment]
Try following this document https://code.visualstudio.com/docs/setup/network and reopen the issue if it doesn't help.
