### ISSUE TITLE
[Suggestion] Keep consistent for connect command between Mongo DB and PostgreSQL

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1542]
**OS:** All
**Build Version:** 20200527.16

**Repro Steps:**
F1-> Input connect-> Check the connect command for Mongo DB and PostgreSQL.

**Actual:**
The connect command is inconsistent between Mongo DB and PostgreSQL.
![image](https://user-images.githubusercontent.com/45614674/83126217-1a872c80-a10b-11ea-80dd-aa86e3d4874f.png)

**Suggestion:**
Keep consistent for connect command between Mongo DB and PostgreSQL.

**Comment by EricJizbaMSFT** [comment]
Let's do "Connect to Database" for both
