### ISSUE TITLE
Database Creation Error

### ISSUE THREAD

**Issue by PandaPerio** [microsoft/vscode-cosmosdb#1549]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.createDocDBDatabase
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND tiger-db4.documents.azure.com

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
@PandaPerio please add repro steps

Could be related to https://github.com/microsoft/vscode-cosmosdb/issues/1550
