### ISSUE TITLE
Update To Cloud Error  cosmos db 

### ISSUE THREAD

**Issue by codehepta** [microsoft/vscode-cosmosdb#1550]
I was doing https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance and cosmos db is created in learn subscription

Always happening.
I was doing https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance and cosmos db is created in learn subscription
![image](https://user-images.githubusercontent.com/20475679/83361585-ca220000-a392-11ea-85ae-84308798f87c.png)
![image](https://user-images.githubusercontent.com/20475679/83361592-d312d180-a392-11ea-8597-1251d5794a30.png)

Action: azureDatabases.update
Error type: ENOTFOUND
Error Message: getaddrinfo ENOTFOUND scshool.documents.azure.com

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
```

</details>

**Comment by EricJizbaMSFT** [comment]
We should try the learn module and make sure it works
