### ISSUE TITLE
Error occured at the time of opening cosmos db account

### ISSUE THREAD

**Issue by prasenjit9619** [microsoft/vscode-cosmosdb#1551]
The issue text was copied to the clipboard.  Please paste it into this window.

Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: ServiceUnavailable
Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 0a2c653e-592e-4307-906a-9dc4f9931c02, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.45.1
Language: en

<details>
<summary>Call Stack</summary>

```
PollingState.getCloudError extension.bundle.js:626:118908
extension.bundle.js:535:35930extension.bundle.js:535:35930
extension.bundle.js:245:159183extension.bundle.js:245:159183
next extension.bundle.js:245:177181
extension.bundle.js:535:35564extension.bundle.js:535:35564
extension.bundle.js:535:36408extension.bundle.js:535:36408
extension.bundle.js:535:38632extension.bundle.js:535:38632
retryCallback extension.bundle.js:626:112523
retryCallback extension.bundle.js:535:30448
extension.bundle.js:535:32061extension.bundle.js:535:32061
handleRedirect extension.bundle.js:542:7714
extension.bundle.js:535:29233extension.bundle.js:535:29233
Request._callback extension.bundle.js:245:125102
Request.r._callback.r.callback.r.callback extension.bundle.js:602:4469
Request.emit events.js:203:13
Request.<anonymous> extension.bundle.js:602:17578
Request.emit events.js:208:15
IncomingMessage.<anonymous> extension.bundle.js:602:16368
Object.onceWrapper events.js:291:20
IncomingMessage.emit events.js:208:15
endReadableNT _stream_readable.js:1168:12
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Hi @prasenjit9619 

Thanks for reporting.  It seems like there was high demand at the time you tried to create a server.  Could you try again and let me know if this issue is recurring?  If so, could you provide repro steps?

**Comment by prasenjit9619** [comment]
Thanks @nturinski 

The problem has been solved by selecting the server from a different location.
