### ISSUE TITLE
It always keeps importing status when importing an invalid .json file to collection

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1558]
**OS:** Win10/Mac
**Build:** 20200601.4

**Repro Steps:**

1. Create a new .json file and type a string.
2. Right click --> Import Document into a collection --> Select a SQL collection.
3. Check the result.

**Expect:**
Pop up an error message if this is an invalid .json file.

**Actual:**
There is no error, notification is always "Importing documents...: Parsed documents. Importing" unchanged.
![image](https://user-images.githubusercontent.com/62053665/83728107-a56ea680-a678-11ea-8062-c4d455d5e4a5.png)

**Comment by neelip** [comment]
I am getting a different error, however this is not as clear of an error either.
![image](https://user-images.githubusercontent.com/17537419/100937188-7ad69c80-34a7-11eb-9edd-b3c451b758e9.png)
