### ISSUE TITLE
An error "cannot open azureDatabases:/test-cosmos-collection.json…" occurs when executing command "db.test.find()"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1576]
**OS:** Windows
**Build Version:** 20200616.8

**Repro step:**

1. Create a Scrapbook and connect a database.
2. Type the following in Scrapbook.
	`db.test.drop()`
	`db.test.insertOne({"value":1})`
	`db.test.insertOne({"value":2, "age": 34})`
	`db.test.find()`
3. Execute All.

**Expect:**
There is no error.

**Actual:**
An error "cannot open azureDatabases:/test-cosmos-collection.json…" occurs.
![image](https://user-images.githubusercontent.com/57662131/84875994-4a49a480-b0b9-11ea-9721-56dbaafc6b46.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20200626.4, this issue does not reproduce, so close it.
