### ISSUE TITLE
Unable to Connect VSCode to Azure Emulator

### ISSUE THREAD

**Issue by VSPradip** [microsoft/vscode-cosmosdb#1577]
Does this occur consistently?  No
Repro steps:

1. Error: Self Signed Certificate

Action: cosmosDB.createDocDBDatabase
Error type: DEPTH_ZERO_SELF_SIGNED_CERT
Error Message: self signed certificate

Version: 0.13.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
TLSSocket.onConnectSecure _tls_wrap.js:1317:34
TLSSocket.emit events.js:203:13
TLSSocket._finishInit _tls_wrap.js:792:8
TLSWrap.ssl.onhandshakedone _tls_wrap.js:606:12
```

</details>

**Comment by nturinski** [comment]
@VSPradip that doesn't reproduce for me with those steps. Can you give us more info - for example are you behind a company proxy or something? Have you configured proxies in VS Code?
