### ISSUE TITLE
mongoose error

### ISSUE THREAD

**Issue by Santoshkhadka98480** [microsoft/vscode-cosmosdb#1578]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.createMongoDocument
Error type: 11000
Error Message: E11000 duplicate key error collection: TaskManager.users index: username_1 dup key: { username: null }

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.0
Language: en

<details>
<summary>Call Stack</summary>

```
Function.create mongodb/error.js:43:12
toError mongodb/utils.js:149:22
common_functions.js:265:39mongodb/common_functions.js:265:39
pool.js:404:18mongodb/pool.js:404:18
processTicksAndRejections task_queues.js:75:11
```

</details>

**Comment by wwlorey** [comment]
@Santoshkhadka98480 can you provide repro steps?
