### ISSUE TITLE
[Unstable]An error occurs when creating a document 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1580]
**OS:** Mac
**Build Version:** 20200623.1

**Repro step:**

1. Right click a Database of SQL account --> Create Collection...
2. Enter an id and the partition key for the Collection.
3. Right click "Documents" node--> Create Document…

**Expect:**
Create a document successfully.

**Actual:**
Fail to create a document and pop up an error.
![image](https://user-images.githubusercontent.com/57662131/85383693-db65c300-b572-11ea-9dff-a457e2604e55.png)

**More Info:**
The probability of reproduction is one fifth.

**Details in Output:**
`3:00:17 PM: Error: cannot open azureDatabases:/doc111-cosmos-document.json?id%3D%2Fsubscriptions%2F92be7e56-8a60-427c-a3e3-0ebd54a827a1%2FresourceGroups%2Fcti-nicole%2Fproviders%2FMicrosoft.DocumentDB%2FdatabaseAccounts%2Fnicole-sql%2Fcore11%2Ftestabcd%2F%24Documents%2FH0tyAI8tu%2BoEAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/doc111-cosmos-document.json?id=/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/cti-nicole/providers/Microsoft.DocumentDB/databaseAccounts/nicole-sql/core11/testabcd/$Documents/H0tyAI8tu+oEAAAAAAAAAA==' (EntryNotFound (FileSystemError): azureDatabases:/doc111-cosmos-document.json?id=/subscriptions/92be7e56-8a60-427c-a3e3-0ebd54a827a1/resourceGroups/cti-nicole/providers/Microsoft.DocumentDB/databaseAccounts/nicole-sql/core11/testabcd/$Documents/H0tyAI8tu+oEAAAAAAAAAA==)`

**Comment by wwlorey** [comment]
Likely fixed by https://github.com/microsoft/vscode-azuretools/pull/753
