### ISSUE TITLE
The final result is inconsistent with the expected result

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1592]
**OS:** Win10
**Build Version:** 20200626.4
Does this occur consistently? Yes 

**Repro steps:**

1. Create a Scrapbook and connect a database.
2. Type the following in Scrapbook.
```
db.heroes.drop();
db.heroes.insert({
    "name": "Batman",
    "saying": "I'm Batman"
});
db.heroes.insert({
    "_id": {"$oid" : "5a7e04558ceb7f33005d6134"},
    "name": "Joker",
    "saying": "Ha ha"
});
db.heroes.find({"name": "Joker", 
"_id": {"$oid" : "5a7e04558ceb7f33005d6134"},
}, {"name": 0})
```
3. Execute all.

**Expect:**
Final result is:
![image](https://user-images.githubusercontent.com/62053665/86075445-98e43f00-baba-11ea-86d0-e91fcfa57121.png)

**Actual:**
Final result is:
![image](https://user-images.githubusercontent.com/62053665/86075432-91249a80-baba-11ea-9eff-c511649455a7.png)

**Comment by wwlorey** [comment]
This is something to investigate. The issue may be in this line: `}, {"name": 0})`

**Comment by v-mengwe** [comment]
Verified on the latest build 20201102.9, this issue also reproduces for GitHub codespaces.

**Comment by neelip** [comment]
The current supported api versions of MongoDB on Azure CosmosDB are 3.2 and 3.6.

![image](https://user-images.githubusercontent.com/17537419/105422983-87e75080-5bf9-11eb-9b44-fabc07ca2d09.png)
https://docs.mongodb.com/manual/reference/method/db.collection.insert/

**Comment by neelip** [comment]
The current supported api versions of MongoDB on Azure CosmosDB are 3.2 and 3.6.

![image](https://user-images.githubusercontent.com/17537419/105422983-87e75080-5bf9-11eb-9b44-fabc07ca2d09.png)
https://docs.mongodb.com/manual/reference/method/db.collection.insert/

**Comment by neelip** [comment]
Can you retest this with the latest build of VSCode?

**Comment by v-mengwe** [comment]
Verified on the latest build 20210121.1, this issue still reproduces for now.

**Comment by michelalbers** [comment]
I have the same problem with any version > 0.13.0.

When I do ```db.users.find({})``` I get something like:

```
[
  {
    "_id": {
      "$oid": "5d3c9d0bf9872c048594328c"
    },
    name: "foo"
  }
]
```

When I want to retrieve that single document I would use:

```
db.users.find({
  _id: ObjectId("5d3c9d0bf9872c048594328c")
})
```

or

```
db.users.find({
  _id: { $oid: "5d3c9d0bf9872c048594328c" }
})
```

With versions above 0.13.0 this produces 

```
[]
```

With versions below or equal to 0.13.0 it produces the expected result:

```
[
  {
    "_id": {
      "$oid": "5d3c9d0bf9872c048594328c"
    },
    name: "foo"
  }
]
```
