### ISSUE TITLE
[Suggestion] Keep tag consistent for PostgreSQL server account with other Azure Database Server accounts

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1594]
**OS:** Win10
**Build Version:** 20200626.4

**Repro steps:**
Check the tag of Azure Database Server accounts.

**Actual:**
The tag of PostgreSQL server account is inconsistent with other Azure Database Server accounts.
![image](https://user-images.githubusercontent.com/62053665/86077065-df876880-babd-11ea-8d9d-a898ad92cba3.png)

**Suggestion:**
Keep tag consistent for PostgreSQL server account with other Azure Database Server accounts.

**Comment by EricJizbaMSFT** [comment]
PostgreSQL is correct. The other database types are not using `AzExtTreeItem.description` properly
