### ISSUE TITLE
Error while communicating with Azure : EPROTO 2811507512:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 70

### ISSUE THREAD

**Issue by sharmakartik25** [microsoft/vscode-cosmosdb#1599]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.createGraphDatabase
Error type: EPROTO
Error Message: write EPROTO 2811507512:error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION:../../third_party/boringssl/src/ssl/tls_record.cc:587:SSL alert number 70

Version: 0.13.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
WriteWrap.onWriteComplete [as oncomplete] stream_base_commons.js:83:16
```

</details>

**Comment by wwlorey** [comment]
Could you provide repro steps?
