### ISSUE TITLE
Not able to create sql db

### ISSUE THREAD

**Issue by 9128343207** [microsoft/vscode-cosmosdb#1605]
Does this occur consistently? Yes 
Repro steps:

1. Create new server from database section of azure web service extention.
2. Choose Account name

Action: azureDatabases.createServer
Error type: Error
Error Message: Entry not found in cache.

Version: 0.13.0
OS: linux
OS Release: 4.15.0-106-generic
Product: Visual Studio Code
Product Version: 1.46.1
Language: en

<details>
<summary>Call Stack</summary>

```
a.createError extension.js:1:49459
b.<anonymous> extension.js:229:174287
extension.js:229:168902
extension.js:229:54224
extension.js:229:52217
extension.js:229:51839
i.find extension.js:229:86332
extension.js:229:33268
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by neelip** [comment]
Thanks for filing - as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
