### ISSUE TITLE
An error "no primary found in replicaset or invalid replica set name" occurs for MongoDB account

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1606]
**OS:** Ubuntu 18.04
**Build Version:** 20200707.1
**VS Code Version:** 1.46.1
![image](https://user-images.githubusercontent.com/45614674/87014008-16682780-c1fe-11ea-9377-dce570eb9d40.png)

**Repro steps:**
Create a MongoDB account and expand it.

**Expect:**
There is no error.

**Actual:**
An error "no primary found in replicaset or invalid replica set name" occurs.
![image](https://user-images.githubusercontent.com/45614674/86900832-6e3f5980-c13e-11ea-88d4-4e8b034c96a2.png)

**Comment by neelip** [comment]
We weren't able to reproduce it, how did you go about creating it?

**Comment by v-ruizh** [comment]
@neelip This issue doesn't reproduce on the newer build 20200711.5 with VS Code 1.47.0, close it.
