### ISSUE TITLE
The name of the function does not match the input 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1609]
**OS:** Mac
**Build Version:** 20200708.13

**Repro steps:**

1. Right click a PostgreSQL account.
2. Create a new database.
3. Right click  "Functions" node --> Click "Create Function Query…".
4. Provide function name and select return type.
5. Execute the query.
6. Check the result.

**Expect:**
The name of the function is the same as the input.

**Actual:**
The name of the function does not match the input.
Input:
![image](https://user-images.githubusercontent.com/57662131/87112381-36e7be80-c29e-11ea-85cf-ba827a747f87.png)
Created:
![image](https://user-images.githubusercontent.com/57662131/87112396-3ea76300-c29e-11ea-884f-bbdb1f9a2487.png)

**Comment by wwlorey** [comment]
Verify we aren't messing with casing before running the create function query
