### ISSUE TITLE
error in creating an Azure Cosmos DB database and collection in Visual Studio Code

### ISSUE THREAD

**Issue by yuem99** [microsoft/vscode-cosmosdb#1614]
Does this occur consistently? Yes 
Repro steps:

1.I followed the steps at https://docs.microsoft.com/en-us/learn/modules/build-cosmos-db-app-with-vscode/2-setup-cosmosdb
![Capture](https://user-images.githubusercontent.com/40189841/87198005-36601f80-c2c0-11ea-8a5f-37fd6343b8b8.PNG)

2. when I tried the following steps: 
1) In the Azure: Cosmos DB pane, right-click your new account, and then click Create Database.

2) In the input palette at the top of the screen, type Users for the database name and press Enter.

I got the error message as shown in the screenshot in step 1. 
"Error Message: read ECONNRESET
Source: Azure Databases (Extension)"

Action: cosmosDB.createDocDBDatabase
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.13.0
OS: win32
OS Release: 10.0.17134
Product: Visual Studio Code
Product Version: 1.47.0
Language: en

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:183:27
```

</details>

**Comment by nturinski** [comment]
Hi @yuem99 Thanks for reporting.  Are you behind any proxies or corporate net?  This can sometimes cause issues that can be fixed via network connection settings.  You can try following this [guide](https://code.visualstudio.com/docs/setup/network#_proxy-server-support).

That being said, we've seen other users having issues with the Learn modules, so we are planning on investigating this issue.
