### ISSUE TITLE
There is no error message when inputting a Cosmos DB account with name "elsa-"

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1616]
**OS:** All
**Build Version:** 20200711.5

**Repro Steps:**

1. F1 --> Azure Databases: Create Server... --> Select Core(SQL) --> Input a Cosmos BD account name with "elsa-".
2. Check the result.

**Expect:**
There is an error message, such as:
![image](https://user-images.githubusercontent.com/62053665/87276038-1889f900-c512-11ea-982a-392a3310eccf.png)

**Actual:**
There is no error message.
![image](https://user-images.githubusercontent.com/62053665/87276148-4ec77880-c512-11ea-933b-7eb0b901ceac.png)

**More info:**

1. This issue also reproduces when selecting Azure Cosmos DB for MongoDB API/Azure Table/Gremlin.
2. This issue **doesn't reproduce** when selecting PostgreSQL.

**Output Logs:**
```
1:49:58 PM: Creating Cosmos DB account "elsa-" with the "Gremlin" API... It should be ready in several minutes.
1:50:02 PM: Error: The character '-' at index 4 is not allowed in the DatabaseAccount name
ActivityId: 683cb76b-c2f2-4b31-960e-c6b9b50fedfd, Microsoft.Azure.Documents.Common/2.11.0
```

**Comment by neelip** [comment]
PostgreSQL has different validation rules for username and password compared to Core(SQL)/Gremlin/Mongo/Table. However, "test-" is an invalid input on Azure portal for the all four accounts. We will get to fixing this.
