### ISSUE TITLE
The document is still updated with the changes after clicking "X" or "Don't upload" button in the notification

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1619]
**OS:** All
**Build Version:** 20200711.5

**Repro Steps:**
1. Open one document and make some changes for it.
2. Press "Ctrl+S", pop up a notification.
![image](https://user-images.githubusercontent.com/45614674/87283871-55f98100-c528-11ea-813c-cdefa38bcfdd.png)
3. Click "X" or "Don't upload" button in the above notification.
4. Close and reopen the document, then check the result.

**Expect:**
The document is not updated.

**Actual:**
The document is updated with the changes.

**Comment by wwlorey** [comment]
The document isn't updated on the server unless "Upload" or "Always upload" is selected. If you refresh without uploading, the unsaved change will be gone.
