### ISSUE TITLE
[Unstable]Pop up an error "EntryNotFound…" when creating a SQL document

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1621]
**OS:** Mac/Linux
**Build:** 20200711.5

**Repro Step:**
	1. Select/create a Database account.
	2. Create a Collection with entering a partitionKey and expand it.
	3. Right click "Documents" node.
	4. Create Document.

**Expect:**
Create successfully without any error.

**Actual:**
Create successfully and pop up an error.
![image](https://user-images.githubusercontent.com/57662131/87278192-70c2fa00-c516-11ea-9399-06b489ec57a3.png)

**More Info:**
This issue also reproduces when opening a SQL document.

**Comment by wwlorey** [comment]
Can you provide the collection's partition key and the partition key value for the document you created? 

And just to verify - the id for the document you created is "h+UHAP01k-EBAAAAAAAAAA=="?

**Comment by v-xinda** [comment]
This issue doesn't reproduce on the build 20200711.5, so I close it.
