### ISSUE TITLE
23:00:09: Error: failed to connect to server [127.0.0.1:27017] on first connect [[Error: connect ENOBUFS 127.0.0.1:27017 - Local (undefined:undefined)

### ISSUE THREAD

**Issue by AviadC31** [microsoft/vscode-cosmosdb#1630]
Does this occur consistently?  Repro steps:   1. 2.  Action: stat Error type: MongoNetworkError Error Message: failed to connect to server [127.0.0.1:27017] on first connect [[Error: connect ENOBUFS 127.0.0.1:27017 - Local (undefined:undefined) 	at internalConnect (net.js:835:16) 	at defaultTriggerAsyncIdScope (internal/async_hooks.js:301:12) 	at net.js:926:9 	at processTicksAndRejections (internal/process/task_queues.js:75:11)] {   name: 'MongoNetworkError',   [Symbol(mongoErrorContextSymbol)]: {} }]  Version: 0.14.0 OS: win32 OS Release: 10.0.18362 Product: Visual Studio Code Product Version: 1.47.2 Language: en  <details> <summary>Call Stack</summary>  ``` internalConnect net.js:835:16 defaultTriggerAsyncIdScope async_hooks.js:301:12 net.js:926:9net.js:926:9 processTicksAndRejections task_queues.js:75:11 Pool.<anonymous> mongodb/server.js:438:11 Pool.emit events.js:203:13 pool.js:561:14mongodb/pool.js:561:14 pool.js:994:11mongodb/pool.js:994:11 connect.js:31:7mongodb/connect.js:31:7 callback mongodb/connect.js:264:5 Socket.<anonymous> mongodb/connect.js:294:7 Object.onceWrapper events.js:291:20 Socket.emit events.js:203:13 emitErrorNT destroy.js:91:8 emitErrorAndCloseNT destroy.js:59:3 processTicksAndRejections task_queues.js:77:11 ```  </details>

**Comment by nturinski** [comment]
Thanks for reporting @AviadC31.  Do you have a local mongo server running?
