### ISSUE TITLE
The CosmosDB account with the same name can't be created again after the first failed creation

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1631]
**OS:** Win10/Mac
**Build Version:** 20200714.9

**Repro steps:**

1. Create a CosmosDB account in location "South India".
2. Check the result --> An error pops up and the account creation is failed.

> Action: azureDatabases.createServer
> Error type: ServiceUnavailable
> Error Message: Long running operation failed with error: "Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
> ActivityId: fdcca7a9-a902-444c-a244-b0c876c055be, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

3. Create a CosmosDB account with the same name.
4. Check the result.

**Expect:**
There is no error when inputting the same CosmosDB account name.

**Actual:**
There is an error when inputting the same CosmosDB account name, such as:
![Screen Shot 2020-07-20 at 3 09 06 PM](https://user-images.githubusercontent.com/62053665/87911967-14745300-ca9f-11ea-8583-d74f2a9bf131.png)

**More info:**
This CosmosDB account does not exist in the subscription after step 1.
This CosmosDB account already exists in the portal after step 1.

Version: 0.14.1-alpha
OS: darwin
OS Release: 19.5.0
Product: Visual Studio Code - Insiders
Product Version: 1.48.0-insider
Language: en

**Comment by nturinski** [comment]
@v-mengwe  Can you consistently repro this?  I think the error is saying that because of the high demand, the create timed out, but it might still being processed.  Are you able to create the account "elsa-graph" today?  It might also be an error that goes away with time.

**Comment by v-mengwe** [comment]
@nturinski  Thanks for your update.

1. Create a CosmosDB account in location "South India".
2. Check the result --> An error pops up and the account creation is failed.
3. Create a CosmosDB account with the same name again one day later.

This issue still reproduces, but if you delete this CosmosDB account from portal will fix this issue.

**Comment by nturinski** [comment]
@v-mengwe Thanks for your update, we will look into this!
