### ISSUE TITLE
The default status of the function file is confused

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1632]
**OS:** Win10/Mac
**Build Version:** 20200714.9

**Repro steps:**

1. Drill down a PostgreSQL server --> Database --> Functions.
2. Create a function --> Click the function.
3. Check the status of the opened file.

**Expect:**
The status of the opened file is saved.

**Actual:**
The status of the opened file is unsaved.
![image](https://user-images.githubusercontent.com/62053665/87922395-86a06400-caae-11ea-8129-cf855cc18fcc.png)

**Comment by nturinski** [comment]
This is actually by-design.  Because the file is being pulled from Azure remotely, there is no local version of this file saved.  If the user wants to keep it locally, then they would have to save it (which is why we marked it as dirty).
