### ISSUE TITLE
Unable to install Azure Databases into VS code

### ISSUE THREAD

**Issue by glennstratton** [microsoft/vscode-cosmosdb#1633]
I have VS code 2019 installed on my machine, however when I click install from the VS marketplace it does not seem to do anything. I also have searched the extension within VS code and was unable to find it. Any help would be greatly appreciated!

**Comment by wwlorey** [comment]
@glennstratton you can download the extension via this link: https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb

**Comment by glennstratton** [comment]
@wwlorey I appreciate the quick response, however when I try and click install nothing happens. What should I do?

**Comment by wwlorey** [comment]
@glennstratton I would try reinstalling VS Code. Unfortunately there's not much we can do here since we don't control the install experience. 

If you're still having problems after reinstalling, I would contact general VS Code support: https://visualstudio.microsoft.com/support/
