### ISSUE TITLE
[Suggestion] Remove action "Delete Database…" from context menu of "postgres" node 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1638]
**OS:** Windows
**Build Version:** 20200729.3

**Repro steps:**

1. Create a new PostgreSQL account.
2. Right click the "postgres" node.
3. Select "Delete Database...".
4. Check the result.

**Actual:**
Pop up an error "Cannot drop system database 'postgres'".
![image](https://user-images.githubusercontent.com/57662131/88906709-587b0b00-d28a-11ea-8bcd-6dd71e532c8d.png)

**Suggestion:**
Remove action "Delete Database…" from context menu of "postgres" node.

**Comment by EricJizbaMSFT** [comment]
Let's make sure it doesn't take a long time to show this error. Probably not worth hiding it from the context menu, though
