### ISSUE TITLE
The notification will be disappeared after successfully creating an Azure Database server Core/MongoDB/Table/Gremlin

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1644]
**OS:** All
**Build Version:** 20200731.1

**Repro Steps:**
1. Create an Azure Database server, such as Core/MongoDB/Table/Gremlin server.
2. Check if there is a notification about "Successfully created... server".

**Expect:**
There is a notification about "Successfully created... server".

**Actual:**
The notification will be disappeared after creation.

**More Info:**
This issue does not reproduce for PostgreSQL server.
![image](https://user-images.githubusercontent.com/45614674/89265272-cea2b780-d666-11ea-8332-cfc5c31b0c62.png)

**Comment by nturinski** [comment]
It disappears or it never appears?  VS Code will eventually hide notifications that can be displayed by clicking the bell at the bottom right corner.

**Comment by v-ruizh** [comment]
There is "Creating Cosmos DB account..." log during creating, but it will disappear after creation.
![image](https://user-images.githubusercontent.com/45614674/89600066-b19efc00-d893-11ea-8160-4924138b9bf4.png)

**Comment by wwlorey** [comment]
We should add a success notification

**Comment by v-mengwe** [comment]
Verified on the latest build 20210323.1, this issue also reproduces for now, we will continue to track this issue.
