### ISSUE TITLE
[Suggestion] Add a "View Output" button in the notification after successfully creating an Azure Database server

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1645]
**OS:** All
**Build Version:** 20200731.1

**Repro Steps:**
1. Create an Azure Database server PostgreSQL.
2. Check the notification.

**Actual:**
There is no "View Output" button.
![image](https://user-images.githubusercontent.com/45614674/89265995-e9c1f700-d667-11ea-9914-1f09f2c5631a.png)

**Suggestion:**
Add a "View Output" button in the notification after successfully creating an Azure Database server.

**Comment by wwlorey** [comment]
The output is the same as this notification
