### ISSUE TITLE
The Connected tag does not switch to the new database which created from command "Import Document..."

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1650]
**OS:** Win10/Mac
**Build Version:** 20200731.1

**Repro Steps:**

1. Create a MongoDB account  --> Create a database with name "test".
2. Check the Connected tag next to the database "test".
3. F1 --> Type and select "Cosmos DB: Import Document into a Collection..." --> Select a .json file without any error --> Select subscription --> Select the MongoDB account --> Select "+ Create new Database..." --> Enter the Database name "test1" -->Select "+ Create new Collection..." --> Enter the Collection name.
4. Check the Connected tag.

**Expect:**
The Connected tag should switch correctly to the database "test1".

**Actual:**
The Connected tab does not switch to the database "test1".
![image](https://user-images.githubusercontent.com/62053665/89519310-bbcae700-d80e-11ea-851b-96cd0bcc10fa.png)

**Comment by EricJizbaMSFT** [comment]
We automatically connect if the user executed the "Create Database" command, but it might be confusing if we auto-connected if they create as part of another command
