### ISSUE TITLE
Erro de acesso ao mongodb atlas

### ISSUE THREAD

**Issue by SilvioGarciaSM** [microsoft/vscode-cosmosdb#1651]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: MongoNetworkError
Error Message: failed to connect to server [cluster0.fopdb.mongodb.net:27017] on first connect [[Error: getaddrinfo ENOTFOUND cluster0.fopdb.mongodb.net
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)] {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]

Version: 0.14.0
OS: win32
OS Release: 6.1.7601
Product: Visual Studio Code
Product Version: 1.47.3
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
Pool.<anonymous> mongodb/server.js:438:11
Pool.emit events.js:203:13
pool.js:561:14mongodb/pool.js:561:14
pool.js:994:11mongodb/pool.js:994:11
connect.js:31:7mongodb/connect.js:31:7
callback mongodb/connect.js:264:5
Socket.<anonymous> mongodb/connect.js:294:7
Object.onceWrapper events.js:291:20
Socket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.

But also, do you have a local mongo server instance running?
