### ISSUE TITLE
[Suggestion] Add two commands "Graph(Gremlin): Create Stored Procedure..." and "Graph(Gremlin): Delete Stored Procedure..." for Graph(Gremlin) command list

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1653]
**OS:** Win10/Mac
**Build Version:** 20200731.1

**Repro Steps:**
F1 --> Type "Gremlin" --> Check the Command list.

**Actual:**
There is no commands "Graph(Gremlin): Create Stored Procedure..." and "Graph(Gremlin): Delete Stored Procedure...".
![image](https://user-images.githubusercontent.com/62053665/89603172-1ad63d80-d89b-11ea-9a13-021f9f12c3b7.png)

**Suggestion:**
Add two commands "Graph(Gremlin): Create Stored Procedure..." and "Graph(Gremlin): Delete Stored Procedure..." for Graph(Gremlin) command list.

**Comment by EricJizbaMSFT** [comment]
Similar reasoning to https://github.com/microsoft/vscode-cosmosdb/issues/1655. Not worth it at the moment
