### ISSUE TITLE
Remove Graph(Gremlin) accounts from the list when executing "Core(SQL): Create Stored Procedure..." command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1655]
**OS:** Win10/Mac
**Build Version:** 20200731.1

**Repro Steps:**
F1 --> Type and select "Core(SQL): Create Stored Procedure..." --> Select a subscription --> Check the account list.

**Expect:**
It only shows the Core(SQL) accounts.

**Actual:**
It shows the Core(SQL) accounts and Graph(Gremlin) accounts.
![image](https://user-images.githubusercontent.com/62053665/89602227-d8136600-d898-11ea-894f-68b6adabebb0.png)

**More Info:**
This issue also reproduces when executing "Core(SQL): Delete Stored Procedure..." command.
![image](https://user-images.githubusercontent.com/62053665/89601991-5de2e180-d898-11ea-95c8-b0cbd0cce250.png)

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. Graph might actually support stored procedures, so the real fix would be to change the label of the command. However, doesn't quite meet the bar to look further into that
