### ISSUE TITLE
No primary found in replicaset or invalid replica set name.

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-cosmosdb#1658]
My existing MongoDB database shows this error 

![image](https://user-images.githubusercontent.com/1186948/90046584-83e7f780-dc85-11ea-87a6-1a780a8b3c50.png)

Creating a new database shows that error as well

![image](https://user-images.githubusercontent.com/1186948/90046613-8fd3b980-dc85-11ea-9291-0aca4350f598.png)

1. Create a Cosmos DB account with the MongoDB API
2. Once created the database is unusable with the above error

The below info is what happens when you attempt to create a database within the account.

---

Action: cosmosDB.createMongoDatabase
Error type: MongoError
Error Message: no primary found in replicaset or invalid replica set name

Version: 0.14.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code - Insiders
Product Version: 1.48.0-insider
Language: en

<details>
<summary>Call Stack</summary>

```
replset.js:624:11mongodb/replset.js:624:11
connectNewServers mongodb/replset.js:279:12
topologyMonitor mongodb/replset.js:611:12
Server.<anonymous> mongodb/replset.js:841:7
Object.onceWrapper events.js:291:20
Server.emit events.js:203:13
Pool.<anonymous> mongodb/server.js:384:12
Pool.emit events.js:203:13
pool.js:580:12mongodb/pool.js:580:12
pool.js:1035:7mongodb/pool.js:1035:7
callback mongodb/connect.js:97:5
connect.js:397:5mongodb/connect.js:397:5
auth_provider.js:61:11mongodb/auth_provider.js:61:11
_callback mongodb/connect.js:349:5
Connection.messageHandler mongodb/connect.js:378:5
Connection.emit events.js:203:13
processMessage mongodb/connection.js:384:10
TLSSocket.<anonymous> mongodb/connection.js:553:15
TLSSocket.emit events.js:203:13
addChunk _stream_readable.js:295:12
readableAddChunk _stream_readable.js:276:11
TLSSocket.Readable.push _stream_readable.js:210:10
TLSWrap.onStreamRead stream_base_commons.js:166:17
```

</details>

**Comment by nturinski** [comment]
After investigating this, it seems that this only reproduces on Windows VS Code Insiders.  This repros on v1.48.0-insider and v1.49.0-insider (that is far back as I checked).  Stable v1.48.0 and Insiders of Mac seem to work.

Furthermore, this bug also occurs on old versions of Databases, all the way back to v0.12.0.  I assume it repros on older versions, but I didn't check any further than that.

**Comment by fiveisprime** [comment]
I'm seeing something similar when attaching to a local mongo instance (no query parameters)

![image](https://user-images.githubusercontent.com/1186948/90831078-c77ed900-e2f7-11ea-8c1e-416a0049ea33.png)

This works correctly on stable
![image](https://user-images.githubusercontent.com/1186948/90831094-d4033180-e2f7-11ea-9ede-ea71e5269454.png)
