### ISSUE TITLE
Database does not exist due to encoding error

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#1662]
Repro steps:
1. In an Azure Postgres server, create a database named `ab%3ac`
1. Copy connection string
1. Attach with that connection string
1. Expand nodes

Expected:
It displays a database with the correct name and attaches

Actual:
It does some extra decoding and thinks the database name is `ab:c`
<img width="290" alt="Screen Shot 2020-08-19 at 11 14 10 AM" src="https://user-images.githubusercontent.com/11282622/90673832-20257780-e20d-11ea-906e-53150b541935.png">

**Comment by neelip** [comment]
Any special characters in the uri components need to encoded as `parse()` from `pg-connection-string` library, expects encoding of special characters.
