### ISSUE TITLE
Support adding new documents by saving the collection file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1666]
**OS:** Win10/Mac
**Build Version:** 20200820.12

**Repro Steps:**

1. Drill down a MongoDB account -> Database -> Collection.
2. Right click the collection -> Select "Open Collection" -> Open a "cosmos-collection.json" file.
3. Insider this file, add a field to insert a new document, such as:
 ```
 {
   "_id": {
     "$oid": "5f3f3da1630707cf301586ab"
   }
 }
 ```
4. Save and upload this change.
5. Check the result.

**Expect:**
Update a document successfully and add a new document to the collection.

**Actual:**
Update a document failed and the collection is unchanged.

**Comment by wwlorey** [comment]
@v-mengwe can you try this with a property other than '_id'?

**Comment by v-mengwe** [comment]
@wwlorey Verified on the latest build 20200826.18.

1. This issue also reproduces with a property other than '_id' if the opened "cosmos-collection.json" file is empty.
 ![image](https://user-images.githubusercontent.com/62053665/91526538-734aa900-e936-11ea-831c-60486505dc83.png)
3. There is an error with a property other than '_id' if the opened "cosmos-collection.json" file is not empty.
 ![image](https://user-images.githubusercontent.com/62053665/91526627-a856fb80-e936-11ea-8b1d-ba2bdc1b30a2.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20210523.1:
The collection unchanged after deleting and saving a document in the opened "cosmos-collection.json" file.
![test](https://user-images.githubusercontent.com/62053665/119331390-e1e84780-bcb9-11eb-90f2-508fc78943ff.gif)
The collection changes after setting a new name to the document and saving the document in the opened "cosmos-collection.json" file.
![test1](https://user-images.githubusercontent.com/62053665/119331399-e44aa180-bcb9-11eb-9c0c-3c4eb8006480.gif)
