### ISSUE TITLE
Azure COSMOSDB_ ENOBUFS ERROR

### ISSUE THREAD

**Issue by angelmariadas** [microsoft/vscode-cosmosdb#1667]
I am using node version 10.6.0 and connects to Azure COSMOS DB using 'MongoCllient'. Code as below:

**index.js**

     var MongodbConnectionString = process.env.COSMOS;

     server.post('/api/test/',(req,res,next) =>{

     var MongoClient = require('mongodb').MongoClient;

            MongoClient.connect(MongodbConnectionString, {
             useNewUrlParser: true
            }, function (err, client) {

     var db = client.db("DBname");
     //rest of the code
     }
    });

Node application is hosted on **azure app service** and works fine. But after many http request i am getting error
_**MongoNetworkError: failed to connect to server [URI:PORT] on first connect [MongoNetworkError: connect ENOBUFS  - Local (undefined:undefined)]**_

If I restart the azure app service, application is up and running , maybe like after 2 days same issue popups and need to restart app service again.

How it could be resolved? Please help me out

**Comment by nturinski** [comment]
Did this resolve your issue?
> Try setting the database URL inside the code to use this parameter 'authSource', Something like this - mongodb://myUserName:example/databaseName?authSource=admin
