### ISSUE TITLE
[Suggestion] Add a "View Output" button in the notification after importing document to a collection

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1671]
**OS:** All
**Build Version:** 20200826.18

**Repro Steps:**
1. Import one document to a collection.
2. Check the notification.

**Actual:**
There is no "View Output" button.
![image](https://user-images.githubusercontent.com/45614674/91423143-bbac8d00-e88a-11ea-946e-4482320f2b9e.png)

**Suggestion:**
Add a "View Output" button in the notification after importing document.

**Comment by wwlorey** [comment]
Maybe we should turn the word "output" into a link
