### ISSUE TITLE
An error occurs when creating a Collection with the any content as partition key for the SQL Emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1673]
**OS:**  Win10
**Build Version:** 20200826.18

**Repro Steps:**
1. Create a Database for SQL Emulator.
2. Right click the Database --> Click "Create Collection..." --> Enter an id --> Enter the partition key with any content --> Enter the initial throughtput capacity with 400.

**Expect:**
Create the Collection successfully without any error.

**Actual:**
An error occurs when creating a Collection with the any content as partition key for the SQL Emulator, such as "/loaction/city".
![image](https://user-images.githubusercontent.com/57662131/91515502-eabf0f00-e91b-11ea-9883-441ee93f5bc6.png)
Details in Output:
```
10:41:47 AM: Error: Partition key path /loaction/city is invalid for MongoDB API.
ActivityId: 92e36f05-84c9-4141-9ca4-07e0dd84a109, Microsoft.Azure.Documents.Common/2.11.0

```
**More Info:**
This issue doesn't reproduce for a Collection with the empty partition key.

**Comment by wwlorey** [comment]
@v-xinda are you able to successfully use that key in the portal?

**Comment by v-xinda** [comment]
@wwlorey Hi, I can create a collection successfully in portal/VS Code with that partition key. Fail to create with that key only for SQL Emulator.
