### ISSUE TITLE
The database which created from "MongoDB Emulator" node will automatically display under the "SQL Emulator" node 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1674]
**OS:** Win10
**Build Version:** 20200826.18

**Repro Steps:**
1. Expand the "MongoDB Emulator" node and "SQL Emulator" node.
2. Create a Database for "MongoDB Emulator" node.
3. Check their "Database" nodes.

**Expect:**
The new created Database only displays under the "MongoDB Emulator" node.

**Actual:**
The new created Database also displays under the "SQL Emulator" node.
![image](https://user-images.githubusercontent.com/57662131/91516385-e72c8780-e91d-11ea-8f20-677ae735482d.png)

**More Info:**
1. This issue also reproduces when executing commands "import document/create Collection/delete Collection" from SQL Emulator/MongoDB Emulator.

**Comment by wwlorey** [comment]
Its running the same CosmosDB emulator for both mongo and SQL. And its expected that they have the same databases
