### ISSUE TITLE
There is an invalid collection when creating a collection for MongoDB

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1675]
**OS:** Mac
**Build Version:** 20200831.4

**Repro steps:**

1. Create a MongoDB account -> Expand the MongoDB account -> Right click the MongoDB account 
 -> Select "Create Database..." -> Input a database name -> Input a collection name.
2. Expand the database and check the result.

**Expect:**
There is no invalid collection.

**Actual:**
There is an invalid collection.
![image](https://user-images.githubusercontent.com/62053665/91964866-46d1cb00-ed42-11ea-8758-7cc012a3fa30.png)

**More Info:**
The invalid collection will disappear after refreshing.

**Comment by wwlorey** [comment]
This is a timing issue that doesn't happen often. Related https://github.com/microsoft/vscode-cosmosdb/issues/1204
