### ISSUE TITLE
Support for serverless

### ISSUE THREAD

**Issue by markjbrown** [microsoft/vscode-cosmosdb#1682]
Cosmos now has support for serverless. Can you change the create workflow to allow a customer to select serverless for throughput? Also would need to be able to detect this during database or collection creation to not show throughput options.

**Comment by ThomasWeiss** [comment]
We would need to:

- Add a "capacity model" choice when creating Core, Mongo, Table or Gremlin account types; options are "provisioned throughput" or "serverless"
  ![image](https://user-images.githubusercontent.com/4797533/108789899-33086400-7530-11eb-9637-ea59b59a8745.png)
- Modify the container creation flow to make throughput optional - and prompt that no throughput should be passed in a serverless account.
  ![image](https://user-images.githubusercontent.com/4797533/108789951-58956d80-7530-11eb-9143-cdaaeb17efa7.png)
