### ISSUE TITLE
MongoNetworkError VS Code Failed to connect to server 

### ISSUE THREAD

**Issue by CarlosLunaGit** [microsoft/vscode-cosmosdb#1685]
Does this occur consistently? YES
Repro steps:

1.  Opening VS Code and login
2.   Installed "Azure Databases" Extension
3. Click on Attach Database account (optional because it can be also auto attached when your account syncs)
4. Either way i get the same error and dont show up my data

Action: cosmosDB.attachDatabaseAccount
Error type: MongoNetworkError
Error Message: failed to connect to server [globalesvpoc-db.mongo.cosmos.azure.com:10255] on first connect [[Error: getaddrinfo ENOTFOUND globalesvpoc-db.mongo.cosmos.azure.com
	at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)] {
  name: 'MongoNetworkError',
  [Symbol(mongoErrorContextSymbol)]: {}
}]

Version: 0.14.0
OS: win32
OS Release: 10.0.17763
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
GetAddrInfoReqWrap.onlookup [as oncomplete] dns.js:60:26
Pool.<anonymous> mongodb/server.js:438:11
Pool.emit events.js:203:13
pool.js:561:14mongodb/pool.js:561:14
pool.js:1008:9mongodb/pool.js:1008:9
connect.js:31:7mongodb/connect.js:31:7
callback mongodb/connect.js:264:5
TLSSocket.<anonymous> mongodb/connect.js:294:7
Object.onceWrapper events.js:291:20
TLSSocket.emit events.js:203:13
emitErrorNT destroy.js:91:8
emitErrorAndCloseNT destroy.js:59:3
processTicksAndRejections task_queues.js:77:11
```

</details>

**Comment by neelip** [comment]
Cannot reproduce this. Do you see this problem with all mongo attached accounts?
