### ISSUE TITLE
No database shows in the attached PostgreSQL server if there is another attached PostgreSQL server with a database

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1691]
**OS:** All
**Build Version:** 20200908.6

**Repro steps:**
1. Create several Databases for PostgreSQL server.
2. Attach PostgreSQL server with a database (add the database name next to the connection string).
3. Attach the above PostgreSQL server without database (remove the database name from the connection string).
4. Expand and check the attached PostgreSQL server without database.

**Expect:**
It shows all databases in the attached PostgreSQL server.
![image](https://user-images.githubusercontent.com/45614674/92566436-cf0a2000-f2ae-11ea-8586-b37e2d84297f.png)

**Actual:**
No database shows in the attached PostgreSQL server.
![image](https://user-images.githubusercontent.com/45614674/92566324-a1bd7200-f2ae-11ea-9b7a-91aaa9ebfb6a.png)

**More Info:**
This issue does not reproduce if detach the PostgreSQL server with a database.

**Comment by neelip** [comment]
Related #1692
