### ISSUE TITLE
An error "Element with id... is already registered" occurs when expanding the attached PostgreSQL server

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1692]
**OS:** All
**Build Version:** 20200908.6

**Repro steps:**
1. Attach PostgreSQL server with a database (add the database name next to the connection string).
2. Attach the above PostgreSQL server without database (remove the database name from the connection string).
3. Expand the attached PostgreSQL server without database.

**Expect:**
It shows all databases in the attached PostgreSQL server without error.

**Actual:**
An error "Element with id... is already registered" occurs.
![image](https://user-images.githubusercontent.com/45614674/92568686-1e058480-f2b2-11ea-8641-dbf92d786426.png)

**More Info:**
1. This issue does not reproduce if only attach the PostgreSQL server without database.
2. This error also reproduces if refresh the attached PostgreSQL server or create a new database for it.

**Comment by neelip** [comment]
https://github.com/microsoft/vscode-cosmosdb/pull/1640#discussion_r470867053
Options for fix: append `/database` to `id` of `PostgresDatabaseTreeItem`, or handle the "Element with id... is already registered" error to throw a more clear error?
With the current implementation, same server cannot be attached twice even if one is with and other is without database.

**Comment by EricJizbaMSFT** [comment]
Two questions:
1. Does Mongo have the same behavior?
1. If I attach both with and without a db, is it easy to detach either one and get into a "good" state?

If so, I think this is low priority and we can fix in a later release
