### ISSUE TITLE
The functions of database display incorrectly for attached PostgreSQL server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1696]
**OS:** All
**Build Version:** 20200908.6

**Repro steps:**

1. Attach PostgreSQL server without database (remove the database name from the connection string).
2. Check the Functions of database and postgres.

**Expect:**
The functions of database display correctly.

**Actual:**
The functions of database display incorrectly.
![image](https://user-images.githubusercontent.com/62053665/92577963-d4bb3200-f2bd-11ea-9686-7222f41b2b39.png)

**Comment by neelip** [comment]
Have you tried refreshing either of the Attached or non-Attached "Functions" node?
