### ISSUE TITLE
Cannot attach Cosmos DB and hit:"Error: If you see this message please contact SupportHub"

### ISSUE THREAD

**Issue by Shawngbk** [microsoft/vscode-cosmosdb#1716]
After installing the Azure Databases extension in VS Code, tried to attach the Cosmos DB account but with hitting below error message.
"cannot attach Cosmos DB and hit:"Error: If you see this message please contact SupportHub"
![image](https://user-images.githubusercontent.com/18609174/93846781-a3882c00-fcd7-11ea-901f-b11060e8d828.png)

Attach other Azure resources worked fine. May I know is there any idea for this issue? May I know how to mitigate it.

**Comment by neelip** [comment]
This message is not generated through the extension. This might be generated due to a corporate proxy.

**Comment by neelip** [comment]
@Shawngbk are we good to close this issue?
