### ISSUE TITLE
VSCode Can't create a mongodb resource

### ISSUE THREAD

**Issue by diberry** [microsoft/vscode-cosmosdb#1721]
Does this occur consistently? Yes
Repro steps:

1. On Windows 10, in VSCode, using Azure Databases extension, right click on subscription, select **Create Server**
2. Select MongoDB from choices
3. Enter name such as `cosmos-mongodb-diberry`. 
4. Error is `Entry not found in cache.`
5. I would like to use this functionality in a Microsoft Docs Tutorial - can I have an estimate on timeline? 

All I want to do is create the MongoDB in Cosmos - I don't want any other Mongo shell/tools. If I just want to create the resource, do I need anything else on my local computer other than VSCode and the extension? 

![image](https://user-images.githubusercontent.com/41597107/95021740-b7148a80-0627-11eb-87a0-c08f23b3769c.png)

Action: azureDatabases.createServer
Error type: Error
Error Message: Entry not found in cache.

Version: 0.15.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.49.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599extension.js:393:36599
extension.js:243:74686extension.js:243:74686
extension.js:243:72667extension.js:243:72667
extension.js:243:72287extension.js:243:72287
i.find extension.js:243:106819
extension.js:243:53526extension.js:243:53526
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
You should be able to create a resource without anything else.  This is actually a common problem with the Azure Account extension especially if the VS Code window is left opened for an extended period of time-- as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53
