### ISSUE TITLE
Modify document fails for Azure Database Tool on CosmosDB SQL

### ISSUE THREAD

**Issue by nhouck** [microsoft/vscode-cosmosdb#1722]
Does this occur consistently? Yes, tried it on a few docs in different collections with different partition keys.
Repro steps:
1. Open a document in a database via the left nav of the Azure Tools / Databases / Cosmosdb (SQL)
2. Modify anything in the document and save.
3. Document should be updated, but instead it throws the error.

Action: writeFile
Error type: BadRequest
Error Message: PartitionKey extracted from document doesn't match the one specified in the header

Version: 0.15.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.49.1
Language: en

**Comment by nturinski** [comment]
Hi @nhouck, is it possible that the partition key value was changed when you updated the document? That error is thrown when a document's partition key value doesn't match the one specified when the document is created.

**Comment by neelip** [comment]
Reopen if the issue persists.
