### ISSUE TITLE
Unable to create collection on Emulator

### ISSUE THREAD

**Issue by BalwantPatel** [microsoft/vscode-cosmosdb#1726]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.createDocDBCollection
Error type: InternalServerError
Error Message: Unknown server error occurred when processing this request.
ActivityId: 5b36dd2c-841a-4da1-8c60-f609b0b1aa7f, Microsoft.Azure.Documents.Common/2.11.0

Version: 0.15.0
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

**Comment by nturinski** [comment]
Please provide detauked repro steps.
