### ISSUE TITLE
A new editor opens when clicking the function query again

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1727]
**OS:** Windows
**Build Version:** 20201022.1

**Repro Steps:**
1. Create a function query for PostgreSQL server and open it.
2. Click the function query again.
3. Check the result.

**Expect:**
No new editor opens.

**Actual:**
A new editor opens.
![image](https://user-images.githubusercontent.com/57662131/96963629-83989200-153b-11eb-80ab-92d11c943613.png)

**More Info:**
A new editor opens when clicking function query again after saving it.
![image](https://user-images.githubusercontent.com/57662131/96973929-1ee53380-154b-11eb-9ef0-038bffc439f2.png)

**Comment by neelip** [comment]
This is by design. With the current release, saving a query file will not update it in the server but will only save it in a local folder. To update the query in the server, the query needs to executed with "Execute Query".
