### ISSUE TITLE
MongoDB method syntax is not supported  

### ISSUE THREAD

**Issue by AdamMomen** [microsoft/vscode-cosmosdb#1731]
Does this occur consistently? 
Repro steps:

1. tried to query mongo 
``` js 
db.pricebook.find({"market_inplay": true}).limit(25).map(function(el){return el["selection_id"]})
```

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Unable to parse syntax. Error near line 1, column 58: "mismatched input 'function' expecting {')', '{', '[', RegexLiteral, StringLiteral, 'null', BooleanLiteral, NumericLiteral}"

Version: 0.15.0
OS: win32
OS Release: 10.0.20215
Product: Visual Studio Code
Product Version: 1.50.1
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:245:242710extension.bundle.js:245:242710
extension.bundle.js:245:241639extension.bundle.js:245:241639
i extension.bundle.js:245:241325
executeCommand extension.bundle.js:245:242227
Object.<anonymous> extension.bundle.js:245:246290
extension.bundle.js:245:241639extension.bundle.js:245:241639
i extension.bundle.js:245:241325
Object.executeCommandFromActiveEditor extension.bundle.js:245:246100
Object.<anonymous> extension.bundle.js:626:1364235
fulfilled extension.bundle.js:626:1358899
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by neelip** [comment]
Related #832
