### ISSUE TITLE
[Codespaces] A notification "Saving '***' will update the entity..." pops up when not saving for 'cosmos-collection.json' file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1733]
**OS:** Win10
**Build Version:** 0.15.0 (latest release build)

**Repro Steps:**

1. Drill down from MongoDB Account -> Database -> Collection.
2. Right-click a collection -> Click 'Open Collection' -> Make changes in the opend 'cosmos-collection.json' file.
3. Don't save and check the result.

**Expect:**
No notification pops up.

**Actual:**
A notification "Saving '***' will update the entity..." pops up.
![coll](https://user-images.githubusercontent.com/62053665/97844639-5c557800-1d26-11eb-88a2-a68fd143e3d0.gif)

**More Info:**
This issue also reproduces when making changes for the opened "cosmos-stored procedure/document.json" file.
![coll1](https://user-images.githubusercontent.com/62053665/97848074-85c4d280-1d2b-11eb-8f03-f6646a2a618a.gif)

**Comment by neelip** [comment]
This error does reproduce and is specific to Codespaces. This error persists even with the latest version of Databases (0.15.1).

**Comment by fiveisprime** [comment]
Is there a way to determine that a save action was executed via an autosave?
