### ISSUE TITLE
A list of completions does not expand after typing "db." in a scrapbook

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1734]
**OS:** Win10
**Build Version:** 20201102.9

**Repro Steps:**

1. Create a new scrapbook for a database that has at least one collection.
2. Type "db.“.
3. Check the result.

**Expect:**
A list of completions comes up and expands.
![image](https://user-images.githubusercontent.com/62053665/97956018-9421f580-1de2-11eb-81f3-77ce8c38f484.png)

**Actual:**
A list of completions comes up, but not expands.
![db2](https://user-images.githubusercontent.com/62053665/97955798-0219ed00-1de2-11eb-94d3-58300f38bb22.gif)

**More Info:**

1. This issue doesn't reproduce after pressing CTRL+SPACE.
2. This issue also reproduces for GitHub codespaces.
  ![db1](https://user-images.githubusercontent.com/62053665/97955866-3d1c2080-1de2-11eb-84b5-42a377732921.gif)

**Comment by neelip** [comment]
Cannot reproduce on VSCode. This does exist on Codespaces but not too frequently. 

There is no problem in Codespaces is window is large enough.
