### ISSUE TITLE
mongo db

### ISSUE THREAD

**Issue by Daniloalencarxp** [microsoft/vscode-cosmosdb#1741]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: Error
Error Message: Failed to update document with _id '0002'.

Version: 0.15.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.51.0
Language: pt-br

<details>
<summary>Call Stack</summary>

```
Function.<anonymous> extension.bundle.js:173:164729
fulfilled extension.bundle.js:173:163617
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Please provide detailed repro steps.
