### ISSUE TITLE
Fail to create a new graph account with an error "Internal error: Expected value to be neither null nor undefined: body"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1747]
**OS:** Win10
**Build Version:** 20201115.1

**Repro Steps:**
1. Create a new graph account in VS Code.
2. Check the result.

**Expect:**
Succeed to create a new graph account without any error.

**Actual:**
Fail to create a new graph account with an error "Internal error: Expected value to be neither null nor undefined: body".
![image](https://user-images.githubusercontent.com/57662131/99223952-685e3100-2820-11eb-92fb-d70cc55bd9f4.png)
![image](https://user-images.githubusercontent.com/57662131/99220564-dd7a3800-2819-11eb-9f6e-9a8aff16b72f.png)
Details in Output:
```
6:26:11 AM: Creating resource group "nicole-graph01" in location "eastus2"...
6:26:12 AM: Successfully created resource group "nicole-graph01".
6:26:12 AM: Creating Cosmos DB account "nicole-graph01" with the "Gremlin" API... It should be ready in several minutes.
6:32:21 AM: Successfully created Cosmos DB account "nicole-graph01".
6:32:22 AM: Error: Internal error: Expected value to be neither null nor undefined: body
```

**Comment by EricJizbaMSFT** [comment]
@neelip is this related to the recent sdk changes

**Comment by neelip** [comment]
This is not related to the recent updates. This issue was noted before sdk changes were merged.
