### ISSUE TITLE
test

### ISSUE THREAD

**Issue by chimerashashi** [microsoft/vscode-cosmosdb#1750]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: Error
Error Message: Entry not found in cache.

Version: 0.15.0
OS: linux
OS Release: 5.4.0-47-generic
Product: Visual Studio Code
Product Version: 1.48.2
Language: en

<details>
<summary>Call Stack</summary>

```
s.createError extension.js:16:58035
b.<anonymous> extension.js:393:42004
extension.js:393:36599
extension.js:243:75486
extension.js:243:73467
extension.js:243:73087
i.find extension.js:243:107619
extension.js:243:53535
processTicksAndRejections task_queues.js:85:5
```

</details>

**Comment by nturinski** [comment]
You should be able to create a resource without anything else. This is actually a common problem with the Azure Account extension especially if the VS Code window is left opened for an extended period of time-- as a workaround you could try signing out and signing back in to your Azure Account using the command palette.

Unfortunately there's not much we can do in this extension, but this is being tracked upstream here: microsoft/vscode-azure-account#53

Please reopen if that doesn't resolve your issue.
