### ISSUE TITLE
Fail to save the document which created in portal after changing contents in VS Code

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1751]
**OS:** Win10
**Build Version:** 20201125.4

**Repro Steps:**
1. Right click a SQL account --> Click "Open in Portal" --> Click on the "Data Explorer" tab -->Click "New Container" --> Select a existing database 'SQLTest' --> Enter the Container id 'partitionKeyTest' --> Enter the Partition key '/a/b' --> Click "OK".
2. Drill down from SQLTest --> partitionKeyTest --> Items --> Click "New Item".
3. Add "a": {"b" : "efg"} --> Save the item.
4. Back to the VS Code, change the document contents except partition key and save it.
5. Check whether the document is saved successfully or not.

**Expect:**
The document is saved successfully.

**Actual:**
There is an error when saving the document.
![image](https://user-images.githubusercontent.com/57662131/100328136-25157680-3007-11eb-9823-0f554582a2e1.png)
Details in Output:
```
4:22:46 PM: Error: Entity with the specified id does not exist in the system. More info: https://aka.ms/cosmosdb-tsg-not-found, 
RequestStartTime: 2020-11-26T08:22:46.5716282Z, RequestEndTime: 2020-11-26T08:22:46.5816507Z,  Number of regions attempted:1
ResponseTime: 2020-11-26T08:22:46.5816507Z, StoreResult: StorePhysicalAddress: rntbd://dz5prdddc02-docdb-2.documents.azure.com:14217/apps/dd7ae3cf-26e1-4547-bd3b-6fa08581b5e8/services/4488146f-777e-4ccd-9437-402619f5b523/partitions/f5e653bc-f814-4168-924a-08c7715f8a28/replicas/132504754276417087p/, LSN: 2, GlobalCommittedLsn: 2, PartitionKeyRangeId: 0, IsValid: True, StatusCode: 404, SubStatusCode: 0, RequestCharge: 1.24, ItemLSN: -1, SessionToken: -1#2, UsingLocalLSN: False, TransportException: null, ResourceType: Document, OperationType: Replace
, Microsoft.Azure.Documents.Common/2.11.0
```
**More Info:**
1. This issue doesn't reproduce when creating database and collection in portal -> Create a document in VS Code.
2. This issue doesn't reproduce when creating database and collection in VS Code -> Create a document in portal.

**Comment by ejizba** [comment]
I tried this and could not repro it. What id did you use in step 3? And how did you edit the document in step 4? Screenshots of the document in each case might be helpful

**Comment by v-xinda** [comment]
@ejizba  Verified this issue also reproduces on the latest build 20201206.1. Id used in step 3 is automatically generated after creating a item.
Detailed steps and screenshots as the below:
1. Create a new collection using a existing database in portal.
![image](https://user-images.githubusercontent.com/57662131/101315896-6c68f600-3896-11eb-9452-2a979d4158c4.png)
2. Create a new item and type the partition key in portal, then save it.
![image](https://user-images.githubusercontent.com/57662131/101316092-cb2e6f80-3896-11eb-9da3-46ca625084b0.png)
3. Back to the VS Code, add a property or change the id in the document and save it.
![image](https://user-images.githubusercontent.com/57662131/101316346-4f80f280-3897-11eb-9cd3-239367e9a96c.png)
