### ISSUE TITLE
The "Quick Start" page of one MongoDB account is opened in portal when executing "Open in Portal" action for the first time 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1755]
**OS:** Mac/Linux
**Build Version:** 20201126.3

**Repro Steps:**
1. Create a MongoDB account.
2. Right click above account and execute "Open in Portal" action.
3. Check whether the "Overview" page is opened in portal or not.

**Expect:**
The "Overview" page is opened in portal .

**Actual:**
The "Quick Start" page is opened in portal.
![openinportal](https://user-images.githubusercontent.com/45614674/100417297-90b91b80-30bb-11eb-8144-ec4cfaa9490c.gif)

**More Info:**
1. This issue also reproduces for SQL/Graph/Table accounts.
2. This issue does not reproduce for an account which executing "Open in Portal" more than one time.

**Comment by neelip** [comment]
I can only reproduce this with Table accounts. 
Is it something that happens only the first time "Open in Portal" executed for a given account? Does this happen often?

**Comment by v-ruizh** [comment]
This issue only reproduces for the first time. It does not reproduce after executing "Open in Portal" more than one time. 
We can't reproduce this issue using the latest extension build 20201204.14. Will keep tracking this issue.

**Comment by v-mengwe** [comment]
Verified on the latest build 20210610.3, this issue also reproduces for now.

**Comment by nturinski** [comment]
Most likely this only happens with new accounts.  I'm pretty sure when you create an account on the Portal, the very first time, it'll take you from overview to quick start.  I'm not sure if this is behavior that we can (or want to) override.

**Comment by ejizba** [comment]
> I'm not sure if this is behavior that we can (or want to) override.

No, I don't think we can or want to override this
