### ISSUE TITLE
Database Node should expand after creating a collection

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-cosmosdb#176]
According to @jinglouMSFT this repros for DocumentDB accounts

I'd have to investigate further if it repros for other types

**Comment by v-flyuan** [comment]
Hi Eric,

After creating Blob Container/File Share/Queue/Table successfully, the nodes Blob Containers/File Shares/Queues/Tables cannot expand automatically. You have to expand it manually, then you can focus on the newly created items.
