### ISSUE TITLE
Fail to update the "id" property in the final result for a MongoDB account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1774]
**OS:** All
**Build Version:** 20201203.7

**Repro Steps:**

1. Create a Scrapbook and connect a database of MongoDB account.
2. Type the following in Scrapbook.
   ```
   db.test2.drop()
   db.test2.insert({"_id":"a","abc":"def"})
   db.test2.insert({"_id":123,"abc":"def"})
   db.test2.find()
   ```
3. Execute All -> Change the value `"_id":"a"` to `"_id":"abc"` in the final result -> Save it -> Click "Upload".
4. There is no error and display "Successfully update" logs in "Output".
5. Refresh the collection in the tree view -> Check whether the document is updated successfully.

**Expect:**
The document is updated successfully after refreshing.

**Actual:**
The document isn't updated successfully after refreshing.
![coll](https://user-images.githubusercontent.com/62053665/100989134-75528280-358b-11eb-8153-8ba17236ab6e.gif)

**More Info:**
There is an error when uploading the changes of document.

> Click the document in the tree view -> Change the value `"_id":"a"` to `"_id":"abc"` in opened .json file.
![coll1](https://user-images.githubusercontent.com/62053665/100989154-7b486380-358b-11eb-98f2-645bf049b694.gif)

**Comment by neelip** [comment]
Related to #166 as It will be creating new document with a change in `id`.
