### ISSUE TITLE
Fail to create a PostgreSQL server using Azure China/Germany account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1775]
**OS:** Win10
**Build Version:** 20201203.7

**Repro Steps:**
1. Sign in with the Azure China/Germany account.
2. Create a PostgreSQL account. 
3. Check whether the PostgreSQL account created successfully or not. 

**Expect:**
Succeed to create the PostgreSQL account.

**Actual:**
Fail to create the PostgreSQL account with an error. 
![image](https://user-images.githubusercontent.com/57662131/101001011-902bf380-3599-11eb-8671-61dc52fa9957.png)

**More Info:**
This issue doesn't reproduce for MongoDB/SQL/Graph/Table account.

**Comment by neelip** [comment]
Are you getting a problem when creating directly in the portal with a Azure China/Germany account?

**Comment by v-xinda** [comment]
@neelip Yeah, an error as below occurs when selecting the location in the portal with a Azure China/Germany account.
![image](https://user-images.githubusercontent.com/57662131/101109853-c2c60280-3612-11eb-97e5-fac33a7b4b4d.png)
