### ISSUE TITLE
pressing "Loard more..."  

### ISSUE THREAD

**Issue by ash0411-maker** [microsoft/vscode-cosmosdb#1783]
Does this occur consistently? 
Repro steps:

1. press "Loard more..." in db files
2. showing the message "cursor id 3969594440258372306 not found"

Action: azureDatabases.loadMore
Error type: 43
Error Message: cursor id 3969594440258372306 not found

Version: 0.15.1
OS: darwin
OS Release: 19.6.0
Product: Visual Studio Code
Product Version: 1.51.1
Language: ja

<details>
<summary>Call Stack</summary>

```
MessageStream.messageHandler mongodb/connection.js:268:20
MessageStream.emit events.js:223:5
processIncomingData mongodb/message_stream.js:144:12
MessageStream._write mongodb/message_stream.js:42:5
doWrite _stream_writable.js:435:12
writeOrBuffer _stream_writable.js:419:5
MessageStream.Writable.write _stream_writable.js:309:11
Socket.ondata _stream_readable.js:728:22
Socket.emit events.js:223:5
addChunk _stream_readable.js:309:12
readableAddChunk _stream_readable.js:290:11
Socket.Readable.push _stream_readable.js:224:10
TCP.onStreamRead stream_base_commons.js:181:23
```

</details>

**Comment by nturinski** [comment]
Hi @ash0411-maker 
I just want to confirm, but this is with an Azure account and not the emulator, correct?
