### ISSUE TITLE
The Notification icon disappears after hiding the notification during creating the server

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1784]
**OS:** Win10
**Build Version:** 20201215.1

**Repro Steps:**
1. Create a new server.
2. Hide the notification during creating the server. 
3. Check the state bar. 

**Expect:**
The Notification icon shows normally.

**Actual:**
The Notification icon disappears.
![test01](https://user-images.githubusercontent.com/57662131/102315251-ceb8a980-3fae-11eb-9254-ca64362f5a6b.gif)

**More Info:**
This issue doesn't reproduce when deleting the server.
![image](https://user-images.githubusercontent.com/57662131/102315339-f0b22c00-3fae-11eb-8ef3-69fb532d8588.png)

**Comment by neelip** [comment]
I am not able to repro this on my end. 
Can you please elaborate on the issue? What is the notification icon you are referring to in both the images?

**Comment by v-xinda** [comment]
@neelip I'm very sorry, it's a typo. Opened this issue for VS Code, you can get the more details from [112640](https://github.com/microsoft/vscode/issues/112640).

**Comment by neelip** [comment]
@v-xinda, no problem :) sounds good!
