### ISSUE TITLE
[Suggestion] Remove "Report an issue" button from "Delete Database..." error dialog 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1787]
**OS:** All
**Build Version:** 202001227.1

**Repro steps:**

Drill down a PostgreSQL server --> Right click the "postgres" node --> Click "Delete Database...".

**Actual:**
There is an button "Report an issue" on the error dialog.
![image](https://user-images.githubusercontent.com/57662131/103200352-184ab200-4928-11eb-921c-4bf9958b83a2.png)

**Suggestion:**
Remove "Report an issue" button from "Delete Environment…" error dialog.

**Comment by ejizba** [comment]
fixed in https://github.com/microsoft/vscode-cosmosdb/pull/1821
