### ISSUE TITLE
Error connecting to Postgres from VS Code

### ISSUE THREAD

**Issue by oaviles** [microsoft/vscode-cosmosdb#1788]
Does this occur consistently? 
Repro steps:

1. Open Visual Studio Code
2. Select Azure Extension
3. Open Azure Subscription on Databases Area
4. Select Postgres DB
5. Right click on selected postgres db and click on "Copy Connection String"

Action: postgreSQL.copyConnectionString
Error type: ECONNRESET
Error Message: read ECONNRESET

Version: 0.15.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
TLSWrap.onStreamRead stream_base_commons.js:200:27
```

</details>

**Comment by neelip** [comment]
Cannot reproduce this error. Could you please verify if this is recurring?
