### ISSUE TITLE
There is no validation when inputting the duplicate stored procedure name

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1789]
**OS:** Win10
**Build Version:** 20210105.1

**Repro Steps:**
1. Drill down the SQL account.
2. Create a stored procedure with name "test".
3. Right click the "Stored Procedures" node --> Click "Create Stored Procedure..." --> Input name "test" again.
4. Check if there is a validation for the duplicate name.

**Expect:**
There is a validation when inputting the duplicate stored procedure name.

**Actual:**
There is no validation when inputting the duplicate stored procedure name.
![image](https://user-images.githubusercontent.com/45614674/103737522-54b79580-502d-11eb-96fb-925572ba1598.png)

**More Info:**
There is an error when creating a stored procedure with the duplicate name.
![image](https://user-images.githubusercontent.com/45614674/103737549-5da86700-502d-11eb-9db4-fa0b75177fdb.png)

**Comment by neelip** [comment]
Related #1773
