### ISSUE TITLE
[Suggestion] Remove the PostgreSQL/Table/Gremlin account types from the list when creating a new account during importing document

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1790]
**OS:** Win10
**Build Version:** 20210105.1

**Repro Steps:**
1. F1 -> Cosmos DB: Import Document into a Collection -> Select a .json file -> Select the subscription -> Select "**+ Create new Account...**".
2. Check the account list.

**Actual:**
All account types show in the list.
![image](https://user-images.githubusercontent.com/45614674/103738590-36529980-502f-11eb-86d9-3c0ca2557ba5.png)

**Suggestion:**
Remove the PostgreSQL/Table/Gremlin account types except Mongo/SQL from the list.

**Comment by neelip** [comment]
Also, the statement "Create new Account..." doesn't match "Create new Azure Database Server" title of the prompt.
