### ISSUE TITLE
There is an error under the collection node of MongoDB Emulator after creating a document for SQL Emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1791]
**OS:** Win10
**Build Version:** 20210105.1

**Repro Steps:**
1. Make sure Azure Cosmos DB Emulator is installed.
2. Attach both MongoDB Emulator and SQL Emulator.
3. Create a database named 'data001' under **MongoDB Emulator**.
4. Expand **SQL Emulator** -> Create a document named 'test01' under the new created database in step3.
5. Check whether the document displays under the collection node.

**Expect:**
The document "test01" displays under the collection node.

**Actual:**
There is an error under the collection node.
![image](https://user-images.githubusercontent.com/57662131/103739676-e379e180-5030-11eb-8bdf-6cc03bba68b4.png)

**More Info:**
This issue doesn't reproduce under the SQL Emulator after creating a document for MongoDB Emulator.

**Comment by neelip** [comment]
Mongo and SQL use different database Api and it is not expected for them to show each others data.

**Comment by neelip** [comment]
Please let us know if you see this error occur again.

**Comment by v-xinda** [comment]
@neelip Hi, verified this issue with above steps on the latest build 20210128.1, it still reproduces.
Show an error under the collection node of the **MongoDB Emulator** and pop up an error "cannot open azureDatabases:/doc01-cosmos-document.json?" after creating a document for SQL Emulator.
![image](https://user-images.githubusercontent.com/57662131/106236384-b38cbb00-6237-11eb-8394-f8e2d4695ea3.png)
**Details in Output:**
`11:06:31 AM: Error: cannot open azureDatabases:/doc01-cosmos-document.json?id%3D%2FcosmosDBAttachedAccounts%2Flocalhost%3A8081%2Fdata01%2Fcoll002%2F%24Documents%2F%2B3IbALMpVg0CAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/doc01-cosmos-document.json?id=/cosmosDBAttachedAccounts/localhost:8081/data01/coll002/$Documents/+3IbALMpVg0CAAAAAAAAAA==' (Error: Unable to resolve non-existing file 'azureDatabases:/doc01-cosmos-document.json?id=/cosmosDBAttachedAccounts/localhost:8081/data01/coll002/$Documents/+3IbALMpVg0CAAAAAAAAAA==')`
