### ISSUE TITLE
Add `verifyRegisterProvider` step to Wizard's executeSteps

### ISSUE THREAD

**Issue by CaptainAndy01** [microsoft/vscode-cosmosdb#1795]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.15.1
OS: darwin
OS Release: 19.3.0
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:56:970
extension.bundle.js:260:2896
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by nturinski** [comment]
Looks like it's possible that subscription doesn't have the proper namespace registered.  Based on the user's other issues, I'd assume that the namespace eventually does get created automatically, so we should add the `verifyRegisterProviderStep` like so like that https://github.com/microsoft/vscode-azurefunctions/blob/main/src/tree/SubscriptionTreeItem.ts#L133

**Comment by CaptainAndy01** [comment]
Hello SO how do I fix this issue??
Cell 415 710 3361
Time zone Pacific San Francisco

**Comment by nturinski** [comment]
@CaptainAndy01 If you follow the steps here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/resource-providers-and-types, you should be able to register `Microsoft.DocumentDB` and resolve your issue.
