### ISSUE TITLE
Regarding an unexpected token in JSON file

### ISSUE THREAD

**Issue by Jassi10000** [microsoft/vscode-cosmosdb#1807]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: SyntaxError
Error Message: Unexpected token } in JSON at position 44

Version: 0.15.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
DocDBDocumentTreeItem.<anonymous> extension.bundle.js:188:182934
extension.bundle.js:188:181351extension.bundle.js:188:181351
n extension.bundle.js:188:181037
DocDBDocumentTreeItem.writeFileContent extension.bundle.js:188:182887
DatabasesFileSystem.<anonymous> extension.bundle.js:797:103386
fulfilled extension.bundle.js:797:101953
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by neelip** [comment]
It is possible that there is one or more extra brace surrounding the JSON object or extra comma right before the closing brace. You should see the red squiggles right under the syntax error. 
![image](https://user-images.githubusercontent.com/17537419/105913290-729b6900-5fe1-11eb-967b-e3e46f54da82.png)

**Comment by Jassi10000** [comment]
@neelip Mam , Am actually creating some json files to store some data  in it , and storing them in a database , after I make some changes to json ,( like add some stuff ) , my VS Code  prompts a message  , showing this error 

### Unexpected token } in JSON at position 83 
Similarly for  81 and many other line numbers , 
it simply redirects me to create an issue , 
this is the max info I can provide you of what I actually saw

**Comment by neelip** [comment]
This error seems to be specific to the syntax in your document, we won't be able to support you without looking at the syntax.

**Comment by Jassi10000** [comment]
@neelip Should I send the code here ?

**Comment by neelip** [comment]
Yes, you can upload here if you don't mind sharing it publicly. Make sure to redact any sensitive information before sharing.
