### ISSUE TITLE
Again one more unexpected token in JSON 

### ISSUE THREAD

**Issue by Jassi10000** [microsoft/vscode-cosmosdb#1808]
Does this occur consistently? 
Repro steps:

1.
2.

Action: writeFile
Error type: SyntaxError
Error Message: Unexpected token } in JSON at position 177

Version: 0.15.1
OS: win32
OS Release: 10.0.18363
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
DocDBDocumentTreeItem.<anonymous> extension.bundle.js:188:182934
extension.bundle.js:188:181351extension.bundle.js:188:181351
n extension.bundle.js:188:181037
DocDBDocumentTreeItem.writeFileContent extension.bundle.js:188:182887
DatabasesFileSystem.<anonymous> extension.bundle.js:797:103386
extension.bundle.js:797:102199extension.bundle.js:797:102199
n extension.bundle.js:797:101885
DatabasesFileSystem.writeFileImpl extension.bundle.js:797:102818
DatabasesFileSystem.<anonymous> extension.bundle.js:724:19199
fulfilled extension.bundle.js:724:17628
processTicksAndRejections task_queues.js:94:5
```

</details>

**Comment by neelip** [comment]
Related #1807

**Comment by Jassi10000** [comment]
> Related #1807

Respected Mam @neelip  #1807 also has an error that too on line 44 

#1808 also has the same error but on line 177 
Please have a look
