### ISSUE TITLE
Fail to create a collection on the SQL Emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1809]
**OS:** Win10
**Build Version:** 20210128.1

**Repro Steps:**
1. Make sure Azure Cosmos DB Emulator is installed.
2. Attach both MongoDB Emulator and SQL Emulator.
3. Create a database named 'data001' under **SQL Emulator** --> Create a collection.
4. Check whether the collection is created successfully or not.

**Expect:**
The collection is created successfully.

**Actual:**
Fail to create the collection with an error.
![image](https://user-images.githubusercontent.com/57662131/106226286-cc8a7180-6221-11eb-81f8-64e0524813e9.png)
**Details in Output:**
```
10:56:39 AM: Error: Partition key path /_partitionKey is invalid for MongoDB API.
ActivityId: 5d887daa-1f88-468e-a36e-c33100e62740, Microsoft.Azure.Documents.Common/2.11.0
```

**Comment by neelip** [comment]
Related # 1791

**Comment by CharlieDigital** [comment]
I am encountering the same issue.

This also occurs when trying to provision the sample database from the emulator web interface:

![image](https://user-images.githubusercontent.com/779970/117037364-6441a500-acd4-11eb-8079-747fc7a44563.png)

The same error listed by @v-xinda occurs in VS Code as well.

I believe that this is an issue with the emulator itself.

**Comment by JasonYeMSFT** [comment]
Unfortunately I won't have enough time to investigate this issue in 0.21.0. Let's move it to the back log so we can publish 0.21.0 soon.

**Comment by sevoku** [comment]
This is really old. Please reopen if this still occurs with the latest version of the extension and emulator.
