### ISSUE TITLE
Cluster Mongo DB

### ISSUE THREAD

**Issue by cassiachan96** [microsoft/vscode-cosmosdb#1811]
Does this occur consistently? 
Repro steps:

1.
2.

Action: cosmosDB.attachDatabaseAccount
Error type: MongoServerSelectionError
Error Message: getaddrinfo ENOTFOUND chan.0pjus.mongodb.net

Version: 0.15.1
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.52.1
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout._onTimeout mongodb/topology.js:438:30
listOnTimeout timers.js:531:17
processTimers timers.js:475:7
```

</details>

**Comment by nturinski** [comment]
Please add repro steps.
