### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by kumaranimesh** [microsoft/vscode-cosmosdb#1814]
cannot open azureDatabases:/b56231fe-58cd-4a6b-8bbf-8d7b105180ed-cosmos-document.json?id%3D%2Fsubscriptions%2F18974119-7a45-4077-9932-f95c83cee0e3%2FresourceGroups%2Flearn-491722b1-4d2d-4400-a080-fbf46b74de12%2Fproviders%2FMicrosoft.DocumentDB%2FdatabaseAccounts%2Fnjs1%2FSchoolDB%2FStudentCourseGrades%2F%24Documents%2F44AmAL%2Bi7mgDAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/b56231fe-58cd-4a6b-8bbf-8d7b105180ed-cosmos-document.json?id=/subscriptions/18974119-7a45-4077-9932-f95c83cee0e3/resourceGroups/learn-491722b1-4d2d-4400-a080-fbf46b74de12/providers/Microsoft.DocumentDB/databaseAccounts/njs1/SchoolDB/StudentCourseGrades/$Documents/44AmAL+i7mgDAAAAAAAAAA==' (Error: Unable to resolve non-existing file 'azureDatabases:/b56231fe-58cd-4a6b-8bbf-8d7b105180ed-cosmos-document.json?id=/subscriptions/18974119-7a45-4077-9932-f95c83cee0e3/resourceGroups/learn-491722b1-4d2d-4400-a080-fbf46b74de12/providers/Microsoft.DocumentDB/databaseAccounts/njs1/SchoolDB/StudentCourseGrades...

**Comment by neelip** [comment]
Could you please provide the repro steps?

**Comment by kumaranimesh** [comment]
This error occurred when trying to add an item to a collection within Cosmos.

**Comment by neelip** [comment]
I am unable reproduce this error. There might be a problem with the format of the document. 
Are you seeing this error often? Is this error from Mongo or SQL server?

**Comment by brassman2000** [comment]
I see the same error.  Seems each Cosmos DB SQL record is expecting a .JSON extension?  Each of my Cosmos SQL records is not saved with a .JSON externsion.

**Comment by brassman2000** [comment]
In the DATABASES Explorer, for a Cosmos SQL database, each document uses the unique ID of the document as the "displayname" for each record.  For example, document records use email address as the unique ID so the Explorer displays each Cosmos DB SQL document using the email address as the display name.  Each document is valid JSON format (it opens in the Azure Storage Explorer validated JSON format), but this VS code extension cannot render the JSON for each document when you select it in the Explorer.  You see similar errors as reported above.
