### ISSUE TITLE
Error while going through the "Create Azure Cosmos DB resources in Visual Studio Code" exercise

### ISSUE THREAD

**Issue by Meister1867** [microsoft/vscode-cosmosdb#1817]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: MissingSubscriptionRegistration
Error Message: The subscription is not registered to use namespace 'Microsoft.DocumentDB'. See https://aka.ms/rps-not-found for how to register subscriptions.

Version: 0.15.1
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.53.0
Language: en

<details>
<summary>Call Stack</summary>

```
new RestError extension.bundle.js:56:970
extension.bundle.js:260:2896extension.bundle.js:260:2896
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by neelip** [comment]
Please follow the link here: https://github.com/microsoft/vscode-cosmosdb/issues/1795#issuecomment-758859241
