### ISSUE TITLE
eroor please help

### ISSUE THREAD

**Issue by vivolscute** [microsoft/vscode-cosmosdb#1820]
The issue text was copied to the clipboard.  Please paste it into this window.
4:21:12 pm: Creating Cosmos DB account "cheems" with the "SQL" API... It should be ready in several minutes.
4:22:01 pm: Error: Long running operation failed with error: "Database account creation failed. Operation Id: e7f263f7-758f-43fa-9b1d-3e2be31c4b47, Error : Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: acb3453b-1eb6-4466-9f66-d75c393188cc, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".
4:22:31 pm: Creating Cosmos DB account "cheems" with the "SQL" API... It should be ready in several minutes.
4:22:36 pm: Error: DatabaseAccount cheems is in a failed provisioning state because the previous attempt to create it was not successful. Please delete the previous instance before attempting to recreate this account.
ActivityId: 037409e3-bbde-4c8c-8cb2-2e2a56edb6a7, Microsoft.Azure.Documents.Common/2.11.0
4:23:13 pm: Creating Cosmos DB account "vivekschool" with the "SQL" API... It should be ready in several minutes.
4:23:58 pm: Error: Long running operation failed with error: "Database account creation failed. Operation Id: e7e5563e-4237-4398-87f7-fbb0cde026b6, Error : Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. We work continuously to bring more and more capacity online, and encourage you to try again shortly. Please do not hesitate to contact us via Azure support at any time or for any reason using this link http://aka.ms/azuresupport.
ActivityId: 01e48b9f-53c5-47db-829c-2e59e1382e90, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0, Microsoft.Azure.Documents.Common/2.11.0".

**Comment by nturinski** [comment]
Sorry for the issues.  This is frustrating, but it seems like the region you're selecting is having high traffic.  Could you try creating again or in a different region?
