### ISSUE TITLE
The error message is unclear after executing a Stored Procedures query on a PostgreSQL server created in VS Code

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1830]
**OS:** Win10
**Build Version:** 20210219.1

**Repro Steps:**

1. Create a PostgreSQL server in VS Code, e.g. "testvscode".
2. Create a PostgreSQL server with version 11 in Portal, e.g. "testportal".
3. Expand the PostgreSQL server "testportal" -> Expand the "postgres" node -> Right click the "Stored Procedures" -> Select "Create Stored Procedures Query..." -> Enter a name.
4. Open a .psql file -> Click **`Connected to "postgres"`** -> Select a subscription -> Select the PostgreSQL server "testvscode" -> Select a database -> Click "Execute Query".
5. Check whether the error message is clear.

**Expect:**
The error message is clear.

**Actual:**
The error message is unclear.
![image](https://user-images.githubusercontent.com/62053665/108591133-1a6a4380-73a2-11eb-8fbd-2c0202de4061.png)

**Comment by neelip** [comment]
Could you please share the .psql file that was used? 
The create stored procedure prompt should automatically load the .psql file after enter the name. And the loaded .psql file should already be connected to the appropriate database.

**Comment by v-mengwe** [comment]
There are two PostgreSQL servers, the PostgreSQL server created in VS Code does not have "Stored Procedures", so an error will be reported. 
![image](https://user-images.githubusercontent.com/62053665/108807550-b92fb380-75df-11eb-8772-7480003dc7c6.png)

Details of steps:
![post](https://user-images.githubusercontent.com/62053665/108808279-3dcf0180-75e1-11eb-9d94-d4dc2497667f.gif)

**Comment by neelip** [comment]
The Postgres servers created in the extension are defaulted to version 10. And stored procedures are allowed only for servers starting from version 11.

**Comment by v-mengwe** [comment]
You are right! But it would be better if the error message is clear to user when the connected database from version 11 is changed to the database from version 10.
![image](https://user-images.githubusercontent.com/62053665/109245408-617d8c00-781b-11eb-97a8-d84415e68a7d.png)
