### ISSUE TITLE
The result is inconsistent between the mongo account and the MongoDB Emulator after importing documents

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1837]
**OS:** Windows
**Build Version:** 20210316.1

**Repro Steps:**
1. Open the Smith.json file and add the partition key to it, as below:
 ```
{
      "First Name" : "J R",
      "Last Name": "Smith",
      "_partitionKey": ""
  }
```
2. Import the Smith.json file to the collection of the mongo account.
3. Import the Smith.json file to the collection of the MongoDB Emulator.
4. Check whether the result is consistent between the step2 and step3.

**Expect:**
The result is consistent between the step2 and step3.

**Actual:**
1. An error occurs when importing the Smith.json file to the collection of the mongo account.
![image](https://user-images.githubusercontent.com/57662131/111426277-60ab8c00-872f-11eb-8d6f-1664c57b7cc1.png)
2. Succeed to import the Smith.json file to the collection of the MongoDB Emulator.
![image](https://user-images.githubusercontent.com/57662131/111426406-981a3880-872f-11eb-9dc2-bcf314a9c51b.png)

**Comment by neelip** [comment]
I am able to successfully import the above json file but not able to see the "_partitionKey" in the imported document. Can you please try it with a different name for partition key, may be by removing the underscore?

**Comment by v-xinda** [comment]
@neelip Succeed to import the above json file when renaming the partition key(e.g. testkey) or removing the underscore of the partition key.
I also can't see the "_partitionKey" in the imported document after importing the above the json file to the MongoDB Emulator. 
But the result is inconsistent between the mongo account and the MongoDB Emulator after importing the above json file, is it by design?

**Comment by neelip** [comment]
Could you elaborate on the last part? Do you mean to say you can import successfully but the "_partitionKey" doesn't appear after importing?

**Comment by v-xinda** [comment]
@neelip I **can not import** the json file which contained "_partitionKey" property to the **normal mongo account**. Get more details from below:
![testmongo](https://user-images.githubusercontent.com/57662131/112570490-17d78f80-8e21-11eb-860c-3bb39f4915d1.gif)
For the **MongoDB Emulator**, I can import successfully but the "_partitionKey" doesn't appear after importing. More details as below:
![testemulator](https://user-images.githubusercontent.com/57662131/112570502-1c9c4380-8e21-11eb-8fe0-6ec19c36733a.gif)
