### ISSUE TITLE
Succeed to execute a query when executing the query with the function name "test," in the opened .psql file

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1839]
**OS:** Win10
**Build Version:** 20210323.1

**Repro Steps:**

1. Expand a PostgreSQL server -> Postgres -> Right click "functions" node -> Click "Create Function Query..." -> Type function name with "test," -> There is a verification prompt.
  ![image](https://user-images.githubusercontent.com/62053665/112437453-ee1b5b80-8d81-11eb-8680-9b4b8d628125.png)
2. Type a valid function name, e.g. "test" -> Select a return type -> Change the function name to "test," in the opened file -> Click "Execute Query".
   ![image](https://user-images.githubusercontent.com/62053665/112438927-72221300-8d83-11eb-9a1f-494b2a116a78.png)
3. Check whether the query is executed successfully.

**Expect:**
Fail to execute query.

**Actual:**
Succeed to execute query.
![image](https://user-images.githubusercontent.com/62053665/112439073-a39ade80-8d83-11eb-9902-3c24fbe478bf.png)

**Comment by neelip** [comment]
I can still run queries against a function with a comma in the name as long as it is wrapped in quotes. 

We can possibly remove the "," restriction on the extension creating functions.

**Comment by v-mengwe** [comment]
Verified on the latest build 20210610.3, this issue also reproduces for other function names.
![image](https://user-images.githubusercontent.com/62053665/121641571-ed14e300-cac1-11eb-93d9-d1668b76c253.png)

**Comment by neelip** [comment]
- [ ] Update Postgres Function name validation for next release.

**Comment by v-xinda** [comment]
This issue also reproduce for **stored procedures**.
Create the **stored procedure** with the name "test*01" successfully after changing the name in the opened `.psql` file.

**Comment by JasonYeMSFT** [comment]
I don't know where the validation rule come from but I think it's a recommendation rather than requirement. According to this, people can name things using those characters but it would require more careful handling of them. https://www.postgresql.org/docs/7.0/syntax525.htm#:~:text=Names%20in%20SQL%20must%20begin,but%20they%20will%20be%20truncated.

 I'll defer relaxing the validation rules until someone complains.
