### ISSUE TITLE
There is an error under the "SQL Emulator" node after attaching the SQL Emulator account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1842]
**OS:** Win10
**Build Version:** 20210329.1
**VS Code Version:** 1.56.0-insider (user setup)

**Repro Steps:**

1. Right Click "Attached Database Accounts" --> Click "Attached Emulator..." --> Select "Core(SQL)".
2. Expand the "Attached Database Accounts" node --> Expand "SQL Emulator" node.

**Expect:**
There is no error.

**Actual:**
There is an error under the "SQL Emulator" node.
![image](https://user-images.githubusercontent.com/62053665/113268744-49ad9200-930a-11eb-82b8-a23eba005750.png)

**More Info:**
There is a same issue which was fixed in December last year.https://github.com/microsoft/vscode-cosmosdb/issues/1763

**Comment by pseudoramble** [comment]
I bumped into this myself a moment ago. My workaround for it was to do two things, which frankly aren't great:

1. Disabled Proxy Strict SSL.
2. Shut off Proxy Support.

My settings look like this:
![image](https://user-images.githubusercontent.com/12829967/113767230-6f60df80-96ec-11eb-89d3-8fb6ad1fe3d8.png)

I'm unsure why this fixed the issue, but it did seem to. I also don't happen to need proxy settings in my context. I don't know what you do if you need them. I'm also unsure why the plugin won't accept the self-signed cert. It's in my Windows Trust Store, and I've added the win-ca plugin for VSC to try and get it to read different trust stores.

**Comment by nturinski** [comment]
@v-ruizh @v-xinda Could you confirm that this is still reproducing? Between updates to the emulator and VS Code, this may have resolved itself.

**Comment by nturinski** [comment]
I tried myself using v2.14.6.0 of the emulator with the proxy settings on. Things are working as expected so I will close it for now.

**Comment by v-xinda** [comment]
@nturinski  Verified on the latest build 20220818.1, this issue doesn't reproduce for now.
