### ISSUE TITLE
Not able to View Gremlin Cosmo DB in visual studio code

### ISSUE THREAD

**Issue by SanthoshSubbanna** [microsoft/vscode-cosmosdb#1849]
Does this occur consistently? 
Repro steps:

1. Attached the Database using the Connection String
2. Trying to see the database, getting this issue.

Action: AzureTreeDataProvider.getChildren
Error type: FetchError
Error Message: invalid json response body at  "Gremlin Cosmo DB URL" reason: Unexpected end of JSON input

Version: 0.16.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

<details>
<summary>Call Stack</summary>

```
extension.bundle.js:188:158103extension.bundle.js:188:158103
processTicksAndRejections task_queues.js:97:5
```

</details>

**Comment by nturinski** [comment]
Hi @SanthoshSubbanna 

What type of connection string are you using to attach?  Are you using Azure Databases or a different platform?

How did you create this graph account and how are you generating your connection string?  Through the extension, I was able to create a graph account and copy the connection string and attach it.  Did you happen to create it somewhere else?
