### ISSUE TITLE
Fail to delete the attached database of PostgreSQL server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1850]
**OS:** Win10/Mac
**Build Version:** 20210419.1

**Repro Steps:**

1. Create a PostgreSQL server -> Create a database -> Copy the database connection string.
2. Click "Attach Database Account..." -> Select PostgreSQL -> Enter the database connection string.
3. Right click the attached database -> Delete the attached database.
4. Check whether the attached database is deleted successfully without any error.

**Expect:**
The attached database is deleted successfully without any error.

**Actual:**
Fail to delete the attached database with an error.
![image](https://user-images.githubusercontent.com/62053665/115379154-d65db880-a203-11eb-9385-635acc1298f3.png)

**More Info:**
This issue doesn't reproduce for the non-attach PostgreSQL account.

**Comment by nturinski** [comment]
The error thrown by the extension indicates that you must close/disconnect from the current database before deleting.  

We could get around this by forcing the detach and then deleting the database, but the error is actionable and the user scenario seems fairly uncommon.
