### ISSUE TITLE
need the Query tab

### ISSUE THREAD

**Issue by katlimruiz** [microsoft/vscode-cosmosdb#1855]
Does this occur consistently? yes, there is no option at all!
Repro steps:

1. Where is the query tab?

Version: 0.16.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.55.2
Language: en

**Comment by neelip** [comment]
Currently we support Mongo Scrapbooks and "Execute Query" command for Postgres, but don't have a dedicated Querying tool. 
Could you please provide more info on this? Which database type and possible use cases?
