### ISSUE TITLE
CosmosDB: enableEndpointDiscovery must be configurable

### ISSUE THREAD

**Issue by cmendible** [microsoft/vscode-cosmosdb#1857]
Hi team!

With the current implementation of the getCosmosClient function: 

https://github.com/microsoft/vscode-cosmosdb/blob/252441e1663f3a638bd0eeb75e46b3dc7ddfe710/src/docdb/getCosmosClient.ts#L12

It´s not possible to connect with a CosmosDB database that is protected via private endpoint and also behind an Azure Application Gateway because the default connection policy enables endpoint discovery: https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.connectionpolicy.enableendpointdiscovery?view=azure-dotnet

The extension should provide a way to disable endpoint discovery, using code similar to the one shown in the following snippet:

``` node
var enableEndpointDiscovery = vscode.workspace.getConfiguration().get<boolean>(ext.settingsKeys.enableEndpointDiscovery);
const connectionPolicy = { enableEndpointDiscovery: (enableEndpointDiscovery === undefined) ? true : enableEndpointDiscovery };
return new CosmosClient({ endpoint, key, userAgentSuffix: appendExtensionUserAgent(), agent: new https.Agent({ rejectUnauthorized: isEmulator ? !isEmulator : vscodeStrictSSL }), connectionPolicy: connectionPolicy });
```

**Comment by cmendible** [comment]
@nturinski can we close the issue since #1858 was already merged?

**Comment by nturinski** [comment]
Yeah, thanks for reminding me and for your contribution!
