### ISSUE TITLE
Creating a graph fails silently if graph name is invalid

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#186]
Graph name: @##$#$#
Partition Key: asdfasdf

If the partition key is valid, but the graph name is not, the "Create Graph" command will silently fail.

**Comment by jinglouMSFT** [comment]
This is more of a validation issue for graph, which we already have a bug on. Once that issue is fixed, this should get an error when creating the graph.

**Comment by StephenWeatherford** [comment]
Sounds like more of an error handling issue.

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford please fix for 0.3.0
