### ISSUE TITLE
[Suggestion] It would be better if add the database's name in the popped up notification when deleting an attached PostgreSQL database

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1864]
**OS:** All
**Build Version:** 20210525.1

**Repro Steps:**

1. Create a PostgreSQL server -> Create a new database "testdata" for it.
2. Attach the "postgres" and new created database "testdata" by connection string.
3. Navigate to the "Attached Database Accounts" node.
4. Delete the "postgres" and new created database "testdata".
5. Check the notification.

**Actual:**
1. Popped up notification doesn't contain the database's name for the new created database "testdata".
![image](https://user-images.githubusercontent.com/57662131/119779221-03844180-befb-11eb-9a32-46ff90cf88d0.png)
2. Popped up notification contains the database's name for the "postgres" database.
![image](https://user-images.githubusercontent.com/57662131/119779336-257dc400-befb-11eb-8960-c097f5678ca7.png)

**Suggestion:**
It would be better if add the database's name in the popped up notification when deleting a PostgreSQL database, like below:
![image](https://user-images.githubusercontent.com/57662131/119779264-10089a00-befb-11eb-8cea-895d88b8a766.png)

**Comment by neelip** [comment]
The error notification is coming directly from the postgres api, currently not planning to change this.
