### ISSUE TITLE
Cannot Attach to Emulator

### ISSUE THREAD

**Issue by m365ken** [microsoft/vscode-cosmosdb#1866]
Does this occur consistently? 
Repro steps:

1. Launch Azure Cosmos Emulator
2. Attempt to "Attach Emulator" via Azure Databases extension by selecting Core (SQL)
3. SQL Emulator appears under Attached Database Accounts
4. Expanding SQL Emulator results in Error

Action: AzureTreeDataProvider.getChildren
Error type: Error:
Error Message: Unable to reach emulator. Please ensure it is started and connected to the port specified by the 'cosmosDB.emulator.port' setting, then try again.

cosmosDB.emulator.port is set to 8081 which is the port on Azure Cosmos Emulator.
Interestingly, I am able to right-click on SQL Emulator and  choose "Create Database" and follow the prompts in Command palette to create a new database successfully. I just cannot view any local databases from within the Databases view in vscode.

Version: 0.16.0
OS: win32
OS Release: 10.0.19041
Product: Visual Studio Code
Product Version: 1.56.2
Language: en

<details>
<summary>Call Stack</summary>

```
Timeout._onTimeout extension.bundle.js:574:54833
listOnTimeout timers.js:554:17
processTimers timers.js:497:7
```

</details>

**Comment by nturinski** [comment]
Verified that this doesn't reproduce with v2.14.6.0 of the Azure Cosmos Emulator on Windows.
