### ISSUE TITLE
Fail to execute query when the stored procedure name duplicates with an existing function name

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1874]
**OS:** All
**Build Version:** 20210617.3

**Repro Steps:**

1. Expand a PostgreSQL server -> Right click "Functions" node -> Create a function with name "**test**" successfully.
2. Right click "Stored Procedures" node -> Create a stored procedure with the same name "**test**" -> Execute query.
3. Check whether succeed to execute query.

**Expect:**
Succeed to execute query without any error.

**Actual:**
Fail to execute query with an error "cannot change routine kind".
![image](https://user-images.githubusercontent.com/62053665/122896243-760e0300-d37b-11eb-8810-530c74bb6b4a.png)

**More Info:**
Vice versa, fail to execute query when the function name duplicates with an existing stored procedure  name.

**Comment by neelip** [comment]
`The name of the new procedure must not match any existing procedure or function with the same input argument types in the same schema.` -- https://www.postgresql.org/docs/11/sql-createprocedure.html

This is bydesign that stored procedures and functions cannot have same name with same argument type. However we should a more clear error.
