### ISSUE TITLE
[Suggestion] It would be better to add a validation to distinguish the connection string of the Table/Graph/SQL accounts when attaching database account

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1875]
**OS:** All
**Build Version:** 20210617.3

**Repro Steps:**

1. Right click a **Table/Graph** account -> Click "Copy Connection String".
2. Click the "Attach Database Account..." button -> Select **SQL**(SQL) -> Paste the copied connection string.
3. Check whether pop up an error message.

**Actual:**
There is no error message when attaching a SQL account with the connection string of **Table/Graph** account.
![image](https://user-images.githubusercontent.com/62053665/122899642-94293280-d37e-11eb-86c5-7554c9bd22bb.png)

**Suggestion:**
It would be better to add a validation to distinguish the connection string of the **Table**/**Graph**/**SQL** accounts.

**More Info:**
**Vice versa**, the connection string format of **Table**/**Graph**/**SQL** accounts are the same and can be attached with each type.

**Comment by neelip** [comment]
I am able to repro this. The attachment is successful with no error, however the attached graph account is labeled as SQL. 
![image](https://user-images.githubusercontent.com/17537419/123002285-9b444680-d366-11eb-8df2-fe9d549a00d1.png)
