### ISSUE TITLE
Fail to save the collection file which has no change

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1879]
**OS:** All
**Build Version:** 20210622.7

**Repro Steps:**
1. Create a collection for a MongoDB account.
2. Right click this collection and select "Open Collection".
3. "Ctrl+S" to save the opened collection file without any change.
4. Check whether succeed to save the collection file or not.

**Expect:**
Succeed to save the collection file which has no change.

**Actual:**
Fail to save the collection file which has no change.
![image](https://user-images.githubusercontent.com/45614674/123068012-17608c00-d444-11eb-808d-b59d60b9b546.png)

**Comment by v-mengwe** [comment]
Verified on the latest build 20210818.3, this issue still reproduces for now.

**Comment by nturinski** [comment]
Unable to reproduce this now.
