### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by YuzhouLin** [microsoft/vscode-cosmosdb#1883]
- Issue Type: `Performance`
- Extension Name: `vscode-cosmosdb`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.57.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\57600\AppData\Local\Temp\ms-azuretools.vscode-cosmosdb-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by neelip** [comment]
Could you please provide repro steps for this issue?
