### ISSUE TITLE
Support PostgreSQL Flexible Server with version 13 in VS Code

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1891]
**OS:** All
**Build Version:** 20210715.8

**Suggestion:**
Support creating PostgreSQL **Flexible** Server (Preview) with version **13** in VS Code.

**More Info:**
We can create a PostgreSQL Flexible Server with version13 in portal.

**Comment by neelip** [comment]
Planning to add this option once Advanced Create and Basic Create are ready. For the next release, specify which version when choosing API.
