### ISSUE TITLE
Fail to configure firewall to the PostgreSQL Single server on Mac

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1893]
**OS:** Mac
**Build Version:** 20210715.8

**Repro Steps:**

1. Create a PostgreSQL Single Server.
2. Drill down the server -> Postgres -> Click "Configure firewall to connected to...".
3. Pop up a prompt asking to continue? -> Yes.
4. Check whether succeed to configure firewall to the PostgreSQL Single server.

**Expect:**
Succeed to configure firewall to the PostgreSQL Single server.

**Actual:**
Fail to configure firewall to the PostgreSQL Single server.

**More Info:**
This issue only reproduces on Mac.

**Comment by neelip** [comment]
I am not able to repro this for Single Server. Does this happen often and what is the error that it is failing with?

**Comment by v-mengwe** [comment]
Yes, we test on both machines are stable and reproducible without any error.

**Comment by neelip** [comment]
Looks like this is resolved. Thanks for retesting @v-mengwe!
