### ISSUE TITLE
Fail to create a graph with partition key "location/city" for a Graph server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1896]
**OS:** All
**Build Version:** 20210715.8

**Repro Steps:**

1. Create a graph with partition key "`location/city`" for a Graph server.
2. Check whether succeed to create a graph.

**Expect:**
Succeed to create a graph with partition key "`location/city`".

**Actual:**
Fail to create a graph with partition key "`location/city`".
![image](https://user-images.githubusercontent.com/62053665/126146087-67e0cef2-76bf-471e-8cea-cba316b9537c.png)

**More Info:**

1. This issue doesn't reproduce on SQL server.
2. The prompt information is inconsistent between the VS Code and Portal for the Graph server.
    ![image](https://user-images.githubusercontent.com/62053665/126145324-ecfd4852-10ff-451b-8fa2-d5bdea88b6ec.png)
3. Fail to create a graph with partition key "`location/city`" with the below error in the portal, so my guess is that the prompt information is wrong and misleads me, so the prompt information should be changed.
     ![image](https://user-images.githubusercontent.com/62053665/126152547-10e3bfbb-6b9e-49f4-bbc6-47d7f10e189d.png)

**Comment by neelip** [comment]
- [ ] Update placeholder
