### ISSUE TITLE
[Suggestion] It would be better if the prompt message is consistent with PostgreSQL Single Server when creating a duplicate server name for PostgreSQL Flexible Server 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1900]
**OS:** All
**Build Version:** 20210720.10

**Repro Steps:**

1. Create a PostgreSQL Flexible Server -> Create a PostgreSQL Flexible Server with the same server name again.
2. Check the prompt message.

**Actual:**
The prompt message is "Specified server name is already used".
![image](https://user-images.githubusercontent.com/62053665/126444291-1485d9fe-f6cd-4b4b-bd59-9e1d531ea493.png)

**Suggestion:**
It would be better if the prompt message is consistent with PostgreSQL Single Server.
![image](https://user-images.githubusercontent.com/62053665/126444270-1fccbbe0-89e3-48c5-ae32-dffbf2c914a1.png)

**Comment by neelip** [comment]
Both messages are coming directly from the api, currently don't have any plans to modify this.
