### ISSUE TITLE
[Suggestion] It would be better to add the double quotes for function name in the notification after deleting an existing function for PostgreSQL Flexible server

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1901]
**OS:** All
**Build Version:** 20210720.10

**Repro steps:**

1. Create a PostgreSQL Flexible server.
2. Expand the server -> Postgres -> Functions.
3. Right click an existing function -> Click "Delete Function..." -> Click "Delete" when popping up a dialog.
4. Check the contents of the notification.

**Actual:**
The function name without double quotes in the notification.
![image](https://user-images.githubusercontent.com/57662131/126450480-408f39d7-175f-470b-baba-b92f88c662d8.png)

**Suggestion:**
It would be better to add the double quotes for function name in the notification, like below.
![image](https://user-images.githubusercontent.com/57662131/126450552-c64c1cfd-479d-4a37-aa5d-f07ccb5d33dc.png)

**More Info:**
1. This issue also reproduces when deleting a table.
2. This issue also reproduces for the output log.
![image](https://user-images.githubusercontent.com/57662131/126454193-747d2e35-a911-465b-a763-94dd4682c72a.png)
3. This issue doesn't reproduce when deleting a function that created by us.

**Comment by neelip** [comment]
The error is coming directly from the api, currently not planning to modify this.
