### ISSUE TITLE
[Suggestion] It would be better to keep the notification consistent between the PostgreSQL Flexible server and PostgreSQL Single server

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1902]
**OS:** All
**Build Version:** 20210720.10

**Repro Steps:**

1. Delete the postgres of the PostgreSQL Flexible server.
2. Delete the postgres of the PostgreSQL Single server.
3. Check whether the notification is consistent between the PostgreSQL Flexible server and PostgreSQL Single server.

**Actual:**
The notification is inconsistent between the PostgreSQL Flexible server and PostgreSQL Single server.
![image](https://user-images.githubusercontent.com/57662131/126467140-2c98bb61-9d29-4ed5-82ec-007962c7c71c.png)

**Suggestion:**
It would be better to keep the notification consistent between the PostgreSQL Flexible server and PostgreSQL Single server.

**Comment by neelip** [comment]
These messages are directly coming from the api, currently don't have any plans to modify it.
