### ISSUE TITLE
The opened .psql file shows that is connected to the database "postgres" when clicking an existing function for a new PostgreSQL Flexible server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1903]
**OS:** All
**Build Version:** 20210720.10

**Repro steps:**

1. Create a new PostgreSQL Flexible server.
2. Expand the server -> Postgres -> Functions -> Click an existing function.
3. Check the opened .psql file.

**Expect:**
The opened .psql file shows that isn't connected to any database, like below:
![image](https://user-images.githubusercontent.com/62053665/126466255-8c0db15b-83be-4587-a746-06ee54554cee.png)

**Actual:**
The opened .psql file shows that is connected to the database "postgres", like below:
![image](https://user-images.githubusercontent.com/62053665/126466603-4ba80ce7-8019-48bf-9890-bbf179b0f71e.png)

**More Info:**
There is no "Connected" state next to the database "postgres" for the new PostgreSQL Flexible server.
![image](https://user-images.githubusercontent.com/62053665/126467114-43d72b97-323e-4ce9-9141-b824927222c7.png)

**Comment by neelip** [comment]
Unable to reproduce this error, I am guessing it might be a behavior that happens with the initial VSCode window loading. 
@v-mengwe Is this something that happens frequently?

As for the "Connected" not being shown, it does appear when you first create a function in the flexible server but not when you open the preloaded functions. Also this is something that is happening with the latest release as well, where you need to  to run the "Connect to Database..." command for each database to change the database name on the functions. 

The Database name on a function file automatically changes only with:
- Create new function 
- when "Connect to Database" is run

**Comment by v-mengwe** [comment]
@neelip Thanks for your confirmation. This issue only happened one when retesting today,  I will close it for now and pay attention to it in the regular test.
