### ISSUE TITLE
Add more info to "Database" name in a function file to better identify

### ISSUE THREAD

**Issue by neelip** [microsoft/vscode-cosmosdb#1905]
Currently, this is how the description looks like...
![image](https://user-images.githubusercontent.com/17537419/126536917-85cc57ff-8e8c-4024-b863-acf517c2e411.png)

As all Postgres Servers have a "postgres" database, I think this might get confusing to identify which server the database is from. 
My suggestion: "servername.databasename"

@fiveisprime is this a good way to display the name?

**Comment by JasonYeMSFT** [comment]
I am going to close this issue until there is an explicit user request.
