### ISSUE TITLE
command 'cosmosDB.updateMongoDocuments' not found

### ISSUE THREAD

**Issue by ticruz38** [Microsoft/vscode-cosmosdb#191]
I used to manually update my collections in test mode and used this command a lot, it seems like it's not available in the new version anymore.
Is there any workaround for me to be able to update my mongo collection again?

Thanks

**Comment by PrashanthCorp** [comment]
As for a workaround: Currently you can update each document in the document view mode.

Thanks for the feedback! We didn't estimate the amount of user feedback this feature receive. We shall work on trying to re-incorporate it in the current user experience (currently, clicking on a collection opens up a treeview of it's documents, hence there's a conflict from a user experience).

**Comment by ticruz38** [comment]
Yeah, I attached a keymap to it so this feature made the extension very very helpful, I will be downgrading as long as this feature is missing in the upgrade.
Thank you, looking forward further improvement

**Comment by PrashanthCorp** [comment]
Fixed with [this PR](https://github.com/Microsoft/vscode-cosmosdb/pull/219).

**Comment by PrashanthCorp** [comment]
Our new release now has this functionality added back. 
Have a look [here](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb)
