### ISSUE TITLE
There is an error when signing the PostgreSQL Flexible server on another virtual machine

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1913]
**OS:** Win10
**Build Version:** 20210725.1

**Repro steps:**
1. Create a PostgreSQL Flexible server -> Successfully added firewall rule for IP to it.
2. Expand the same PostgreSQL Flexible server on another virtual machine -> Enter the username and password.
3. Check whether the "Configure firewall to connect..." action shows under the PostgreSQL Flexible server.

**Expect:**
The "Configure firewall to connect..." action shows under the PostgreSQL Flexible server.

**Actual:**
There is an error under the PostgreSQL Flexible server.
![image](https://user-images.githubusercontent.com/62053665/126971991-f84030d7-53d8-460f-a9f9-5f30b1ab6076.png)

**More Info:**
This issue doesn't reproduce for the PostgreSQL Single server.

**Comment by neelip** [comment]
Hi @v-mengwe, did you create the server on the portal or the extension?

**Comment by v-mengwe** [comment]
This issue does not only happen on Windows, you can:

1. Create the server on the portal/extension on **Mac** -> Successfully added firewall rule for IP to it on **Mac**.
2. Then expand the same PostgreSQL Flexible server on **Windows** -> Enter the username and password.

Vice versa, this issue only reproduces when signing in the same PostgreSQL Flexible server from one machine to another machine.(Mac -> Windows, Windows -> Mac, Windows 1 -> Windows 2)

**Comment by neelip** [comment]
Thank you. Is the one created on the portal version 12 or 13?

**Comment by v-mengwe** [comment]
Yes, create the PostgreSQL Flexible server with version 12 on the portal.
**details of steps:**
The steps on the first machine:
![post1](https://user-images.githubusercontent.com/62053665/127275360-77fc1409-6cb7-42ae-8f50-cdaf6ffe88ce.gif)
The steps on the second machine:
![post2](https://user-images.githubusercontent.com/62053665/127275433-d6afc2d9-c76d-43ec-88f9-1e64df6bb321.gif)

**Comment by neelip** [comment]
I tested out the same steps on a windows machine and I can reproduce this error on Windows. Thank you, working on a fix.

**Comment by v-mengwe** [comment]
Verified on the latest build 20210729.6, this issue still reproduces when signing the same PostgreSQL Flexible server from **windows** machine to **mac** machine, so reopen it.

**Repro steps:**

1. Create a PostgreSQL Flexible server in VS Code or portal(V12) on **Windows** -> Successfully added firewall rule for IP to it on **Windows**.
2. Then expand the same PostgreSQL Flexible server on **Mac** machine -> Enter the username and password -> Successfully added firewall rule for IP to it on **Mac**.
3. Check the result on **Mac**.

**Comment by neelip** [comment]
I have followed the steps but I am not seeing an ETIMEDOUT Error. When I configure the firewall on Mac, the database is correctly expanding. But what I do see is that when I go back to Windows, I get "Configure firewall..." option again even though I configured it earlier. 
I am guessing error might occur if both where running the add firewall rule at the same time.

**Comment by v-mengwe** [comment]
Sorry for the late reply. Verified on the latest build 20210805.1, this issue still reproduces and unstable.

**Comment by neelip** [comment]
Update: weren't able to reproduce after a round of testing with @v-mengwe.
