### ISSUE TITLE
An extra notification "Getting publish IP..." pops up when expanding a new PostgreSQL Flexible server

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1914]
**OS:** Win10
**Build Version:** 20210727.1

**Repro steps:**

1. Create a PostgreSQL Flexible server -> Expand it under the DATABASES node -> Click "postgres" node.
2. Check whether an extra notification pops up.

**Expect:**
No extra notification pops up.

**Actual:**
An extra notification "Getting publish IP..." pops up.
![post](https://user-images.githubusercontent.com/62053665/127273899-ebe7ce23-ebe1-40bb-a1f3-c9d858d6aae6.gif)

**Comment by neelip** [comment]
Removing notification and maybe extending the "Create..." notification.

**Comment by JasonYeMSFT** [comment]
I have removed the get IP notification.
