### ISSUE TITLE
why is update result removed?

### ISSUE THREAD

**Issue by TinusScheppers** [Microsoft/vscode-cosmosdb#192]
From the changelog:
`Removed`

`View Mongo documents in 'result.json' by clicking on a collection in the explorer`
`Edit and persist the result of a Mongo scrapbook command`

Why have these key features been removed?
I used the update documents from the result set of a query very often, why is it removed all of a sudden?

Kind regards
Tinus

**Comment by PrashanthCorp** [comment]
Thanks for the feedback! We didn't estimate the amount of user feedback this feature receive. We shall work on trying to re-incorporate it in the current user experience. 
Currently, clicking on a collection opens up a treeview of it's documents, hence there's a conflict from a user experience. That was the rationale behind replacing the previous UX.

**Comment by TinusScheppers** [comment]
Hi, that sounds great!
Maybe its a possibility to add a right click action to the collection?

**Comment by PrashanthCorp** [comment]
Fixed with [this PR](https://github.com/Microsoft/vscode-cosmosdb/pull/219).

**Comment by PrashanthCorp** [comment]
That's what we did. :-) 

Our new release now has this functionality added back. 
Have a look [here](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb)
