### ISSUE TITLE
Azure SQL support

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-cosmosdb#1925]
Similar experience to PG

**Comment by nturinski** [comment]
Possibly we could ask the owners of this [repo](https://github.com/Microsoft/vscode-mssql) to contribute Azure SQL resources to our Resources Extension?

**Comment by amthomas46** [comment]
@nturinski Hi Nathan, we'd love to contribute, please share any guidance that you might have

**Comment by nturinski** [comment]
Hi @amthomas46

That's awesome to hear! Could you email me at nathan.turinski@microsoft.com? Our team would love to help onboard your team to contribute to the extension/
