### ISSUE TITLE
The scrapbook's language ID changes to other language ID when inserting too many values

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1929]
**OS:** All
**Build Version:** 20210905.1
**Visual Studio Code:** 1.60.0
**Regression:** Not a regression

**Repro steps:**

1. Create a Mongo DB account -> Create a database.
2. Create a new Mongo Scrapbook and connect the database.
3. Type the following contents in the scrapbook.
```
	db.lotsofdata.drop();
		db.lotsofdata.insertMany([{"a": "xxxxxxxxxxxxxxxxxxx"},
		{"a": "xxxxxxxxxxxxxxxxxxx"},
		{"b": "xxxxxxxxxxxxxxxxxxx"},
		{"c": "xxxxxxxxxxxxxxxxxxx"},
		{"d": "xxxxxxxxxxxxxxxxxxx"},
		{"e": "xxxxxxxxxxxxxxxxxxx"},
		{"f": "xxxxxxxxxxxxxxxxxxx"},
		{"g": "xxxxxxxxxxxxxxxxxxx"},
		{"h": "xxxxxxxxxxxxxxxxxxx"},
		{"i": "xxxxxxxxxxxxxxxxxxx"},
		{"j": "xxxxxxxxxxxxxxxxxxx"},
		{"k": "xxxxxxxxxxxxxxxxxxx"},
		{"l": "xxxxxxxxxxxxxxxxxxx"},
		{"m": "xxxxxxxxxxxxxxxxxxx"},
		{"n": "xxxxxxxxxxxxxxxxxxx"},
		{"o": "xxxxxxxxxxxxxxxxxxx"},
		{"p": "xxxxxxxxxxxxxxxxxxx"},
		{"q": "xxxxxxxxxxxxxxxxxxx"},
		{"r": "xxxxxxxxxxxxxxxxxxx"},
		{"s": "xxxxxxxxxxxxxxxxxxx"},
		{"t": "xxxxxxxxxxxxxxxxxxx"},
		{"u": "xxxxxxxxxxxxxxxxxxx"},
		{"v": "xxxxxxxxxxxxxxxxxxx"},
		{"w": "xxxxxxxxxxxxxxxxxxx"},
		{"x": "xxxxxxxxxxxxxxxxxxx"},
		{"y": "xxxxxxxxxxxxxxxxxxx"},
		{"z": "xxxxxxxxxxxxxxxxxxx"}]);
		db.lotsofdata.find().pretty();
```
4. Check whether the scrapbook's language ID doesn't change.

**Expect:**
The scrapbook's language ID doesn't change.
![image](https://user-images.githubusercontent.com/57662131/132291521-1c6ec925-de41-4b73-88d2-f53615b905b6.png)

**Actual:**
The scrapbook's language ID changes to other language ID.
![actual1](https://user-images.githubusercontent.com/57662131/132291478-49e2fca4-2562-419b-a517-fedd01280462.gif)

**More Info:**
This issue doesn't reproduce on Visual Studio Code 1.59.1.

**Comment by wwlorey** [comment]
Can you try to reproduce this using the latest version of VS Code? We think it may have been fixed there.

**Comment by v-xinda** [comment]
Hi Will, verified on the latest build 20220209.1, this issue also reproduces.

**Comment by nturinski** [comment]
This no longer reproduces.

Tested with:
```
Version: 1.71.0-insider (user setup)
Commit: dd0ed9381aa5d0d43159463ccad1f7e060021580
Date: 2022-08-17T05:16:54.224Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22000
Sandboxed: Yes
```
