### ISSUE TITLE
It takes more than 20 seconds to pop up the error message if attaching emulator without emulator started

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1934]
**OS:** Win 10
**Build Version:** 20211002.1
**Regression:** Not a regression

**Repro steps:**
1. Don't start the Azure Cosmos DB emulator.
2. F1 -> Cosmos DB: Attach Emulator.... -> Azure Cosmos DB for MongoDB API.
3. Check whether the error message pops up in 5 seconds or not.
![image](https://user-images.githubusercontent.com/45614674/137469133-0de92bb2-a6d4-4f82-b42b-21bb793fdf7e.png)

**Expect:**
The error message pops up in 5 seconds.

**Actual:**
It takes more than 20 seconds to pop up the error message.

**More Info:**
This issue also reproduces on the previous released Databases extension 0.18.1.

**Comment by wwlorey** [comment]
Can you verify if this still takes 20 seconds to popup the error message?

**Comment by v-ruizh** [comment]
@wwlorey Verified this issue on Azure Databases extension 20220205.1, it still reproduces. It takes more than 20 seconds to pop up the error message.

For "5 seconds", I think it is an acceptable range if it takes less than 5 seconds to pop up the error message. Of course it would be better if it takes only 1 or 2 seconds to pop up the error message.

**Comment by nturinski** [comment]
While I agree that having 20 seconds to time out is bad UX, this is a pretty edge case scenario (usage for Mongo Emulator is also not that high) so we will close this as wontfix unless there is customer feedback indicating they would like this.
