### ISSUE TITLE
The command bar disappears in the scrapbook after copying longer commands to it

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1935]
**OS:** Win 10
**Build Version:** 20211002.1
**Regression:** Not a regression

**Repro steps:**
1. Create a Mongo DB account -> Create a database.
2. Create a new Mongo Scrapbook and connect the database.
3. Copy the following **longer commands** in the scrapbook.
```
db.lotsofdata.drop();
db.lotsofdata.insertMany([{"a": "xxxxxxxxxxxxxxxxxxx"},
{"a": "xxxxxxxxxxxxxxxxxxx"},
{"b": "xxxxxxxxxxxxxxxxxxx"},
{"c": "xxxxxxxxxxxxxxxxxxx"},
{"d": "xxxxxxxxxxxxxxxxxxx"},
{"e": "xxxxxxxxxxxxxxxxxxx"},
{"f": "xxxxxxxxxxxxxxxxxxx"},
{"g": "xxxxxxxxxxxxxxxxxxx"},
{"h": "xxxxxxxxxxxxxxxxxxx"},
{"i": "xxxxxxxxxxxxxxxxxxx"},
{"j": "xxxxxxxxxxxxxxxxxxx"},
{"k": "xxxxxxxxxxxxxxxxxxx"},
{"l": "xxxxxxxxxxxxxxxxxxx"},
{"m": "xxxxxxxxxxxxxxxxxxx"},
{"n": "xxxxxxxxxxxxxxxxxxx"},
{"o": "xxxxxxxxxxxxxxxxxxx"},
{"p": "xxxxxxxxxxxxxxxxxxx"},
{"q": "xxxxxxxxxxxxxxxxxxx"},
{"r": "xxxxxxxxxxxxxxxxxxx"},
{"s": "xxxxxxxxxxxxxxxxxxx"},
{"t": "xxxxxxxxxxxxxxxxxxx"},
{"u": "xxxxxxxxxxxxxxxxxxx"},
{"v": "xxxxxxxxxxxxxxxxxxx"},
{"w": "xxxxxxxxxxxxxxxxxxx"},
{"x": "xxxxxxxxxxxxxxxxxxx"},
{"y": "xxxxxxxxxxxxxxxxxxx"},
{"z": "xxxxxxxxxxxxxxxxxxx"}]);
db.lotsofdata.find().pretty();
```
4. Check whether the command bar is available or not.

**Expect:**
The command bar is available.
![image](https://user-images.githubusercontent.com/45614674/137471116-707df7e0-5e72-40b8-8bee-f4a8f34f9db0.png)

**Actual:**
The command bar disappears.
![test123](https://user-images.githubusercontent.com/45614674/137469883-bcbcf18c-32f4-44e3-95aa-0f5297dc7494.gif)

**More Info:**
1. The command bar is back after saving this scrapbook.
2. This issue also reproduces on the previous released Databases extension 0.18.1.

**Comment by wwlorey** [comment]
It looks like that "Execute" hint appears after the file is saved.
