### ISSUE TITLE
The document's name is not crossed automatically by the strikethrough after deleting it

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1936]
**OS:** All
**Build Version:** 20211017.1
**Regression:** Not a regression

**Repro Steps:**
1. Drill down one SQL account and create a collection and document for it.
2. Click the document to open it in editor.
3. Right click the document -> Click "Delete Document...".
4. Check whether the document's name is crossed automatically by the strikethrough.

**Expect:**
The document's name is crossed automatically by the strikethrough.
![image](https://user-images.githubusercontent.com/57662131/137706696-76726ca3-89af-49f4-b32c-678f2ca163ea.png)

**Actual:**
The document's name is not crossed automatically by the strikethrough.

**More Info:**
1. This issue also reproduces on the MongoDB account.
2. Click the other window and go back to this document, the document's name is crossed by the strikethrough.
![actual01](https://user-images.githubusercontent.com/57662131/137706617-4c076c18-e47e-4c6e-8673-af610ad0f0d2.gif)

**Comment by wwlorey** [comment]
As of right now we are ok with this behavior. Thanks for the suggestion!
