### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ahmadsyamsu** [microsoft/vscode-cosmosdb#1937]
- Issue Type: `Performance`
- Extension Name: `vscode-cosmosdb`
- Extension Version: `0.18.1`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.61.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\uddin\AppData\Local\Temp\ms-azuretools.vscode-cosmosdb-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by nturinski** [comment]
Please attach the file from this directory `c:\Users\uddin\AppData\Local\Temp\ms-azuretools.vscode-cosmosdb-unresponsive.cpuprofile.txt`
