### ISSUE TITLE
Azure Cosmos DB Graph extension deprecated

### ISSUE THREAD

**Issue by HaoHoo** [microsoft/vscode-cosmosdb#1941]
When I use create Gremlin database and graph from Azure Databases extension, and click on the graph, VS Code prompt to install Azure Cosmos DB Graph extension but it shows be deprecated.

**Comment by jinglouMSFT** [comment]
We recommend using the portal Cosmos DB graph for its most up to date features. The graph extension is still there on the extension gallery for install but it's not been actively developed anymore.

**Comment by wwlorey** [comment]
Closing based on @jinglouMSFT's explanation
