### ISSUE TITLE
Can't see the extension tab in Explorer

### ISSUE THREAD

**Issue by corradocavalli** [microsoft/vscode-cosmosdb#1942]
I can't see the extension in Explorer, also tried enabling/disabling it in the settings but nothing changes.
Extension is listed as installed.

**Comment by alexweininger** [comment]
Hello! My first thought would be to check if it somehow has been hidden from the Activity Bar. I've attached a video of hiding/unhiding the Azure extension view from the Activity Bar.

Right click the Explorer icon (or anywhere on the Activity Bar) and hopefully you'll see an Azure option. It should be checked like this:
![image](https://user-images.githubusercontent.com/12476526/140524733-a76e9845-5476-4c55-a7d8-3de21b1abcdf.png)

Video:

https://user-images.githubusercontent.com/12476526/140524308-032f3e05-c4e2-4d1b-8bde-252aff5317d2.mov

…

**Comment by corradocavalli** [comment]
@alexweininger Hello, I have rebooted my machine and now seems to work.
Thanks!
