### ISSUE TITLE
BUG `!` at end of password for psql throws error

### ISSUE THREAD

**Issue by hrittikhere** [microsoft/vscode-cosmosdb#1952]
Hey,
Currently, I am using Azure Database for PostgreSQL server and found an error while trying to connect to DB using psql. The error shows that having
`!` at the end of the password for a connection string (copied using the extension) would make psql think
that `!` is included in the host. This is problematic and the following picture would give you more information. Changing the password to not
include the `!` at the end would resolve the error or adding quotes for password in the connection string.

![](https://i.imgur.com/vw9W5VK_d.webp?maxwidth=640&shape=thumb&fidelity=medium)

I can try to add a PR for this. Let me know!

**Comment by hrittikhere** [comment]
Solution is simple: Password in the string should be in quotes

**Comment by alexweininger** [comment]
Thanks for filing this issue! Nice looking screenshot btw :)

> I can try to add a PR for this. Let me know!

If you do want to submit a PR, that'd be awesome. We encourage open source contributions! The relevant file for this would probably be https://github.com/microsoft/vscode-cosmosdb/blob/649873572001d4717d293facff28b14698831f9d/src/postgres/postgresConnectionStrings.ts

**Comment by hrittikhere** [comment]
Yes, I found the file and I have started to work on it too. Will update you once the PR is ready.
