### ISSUE TITLE
Deployment of Azure Cosmos DB failes

### ISSUE THREAD

**Issue by andreih89** [microsoft/vscode-cosmosdb#1958]
Hi,

We tried multiple times to create an Azure cosmos DB instance in our subscription but it fails every time with the error:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"ServiceUnavailable","message":"Database account creation failed. Operation Id: c3ba349d-dfa5-41a1-86cf-333833428c55, Error : Sorry, we are currently experiencing high demand in this region, and cannot fulfill your request at this time. The access to the region is currently restricted, to request region access for your subscription, please follow this link https://aka.ms/cosmosdbquota for more details on how to create a region access request.\r\nActivityId: a468f1b1-edab-4c46-ab62-71ecfa80d2a9, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0, Microsoft.Azure.Documents.Common/2.14.0"}]}

Please help me with this.

Regards,
Andrei

**Comment by hrittikhere** [comment]
Were you able to create the DB at the same region using the Azure Portal? Some regions are out of bound and to access them you need to contact Azure support.

**Comment by andreih89** [comment]
I tried to create it in the same region as the ones we already have West Europe
