### ISSUE TITLE
Unable to open Graph Explorer for cosmos graph db 

### ISSUE THREAD

**Issue by shaik-suhail** [microsoft/vscode-cosmosdb#1965]
Does this occur consistently? Yes
Repro steps:
1. Add database connection for azure cosmos graph db with gremlin api 
2. Double click the graph to open graph explorer  

Version: 0.18.1
OS: win32
OS Release: 10.0.19043
Product: Visual Studio Code
Product Version: 1.64.2
Language: en

Even after installing the extension trying to open  Graph Explorer throws a popup saying install the extension

![1](https://user-images.githubusercontent.com/48115551/155176430-4f4a59f0-18f4-4a8e-92bc-e762dab29bc4.PNG)

**Comment by nturinski** [comment]
Hi @shaik-suhail 

We actually deprecated the Graph Explorer extension back in [2020-09-18](https://github.com/microsoft/vscode-cosmosdbgraph/commit/ec06c24db904ab7d8f33adda74c6cad403d05517).  We recommend using the portal to visualize your graph data.

If you would really like to use VS Code for data visualization, you can manually install the vsix from here: https://github.com/microsoft/vscode-cosmosdbgraph/releases

Thanks for filing the issue and using the extension!
