### ISSUE TITLE
An error occurs after attaching "postgres" database for a PostgreSQL account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1966]
**OS:** Win10
**Build Version:** 20220215.11
**Regression:** Previous Release

**Repro Steps:**
1. Create a PostgreSQL account.
2. Expand PostgreSQL account -> Right click "postgres" -> Copy Connection String.
3. Attach "postgres" database with `connection string?ssl=true`.
4. Check whether no error occurs after attaching "postgres" database.

**Expect:**
No error occurs after attaching "postgres" database.
![image](https://user-images.githubusercontent.com/57662131/155699857-a957aa80-90a6-4dae-8b2f-041807ba9231.png)

**Actual:**
An error occurs after attaching "postgres" database.
![image](https://user-images.githubusercontent.com/57662131/155699811-3a3b2969-0149-44f0-8a8a-de460b449ab2.png)

**Comment by nturinski** [comment]
Most likely commit https://github.com/microsoft/vscode-cosmosdb/commit/0f7f31702758dd9bb0986f6a1f3b92d9c7c82582 impacted the postgres attaching.  Could you confirm if the `Copy Connection String` command is outputting the same value between the two releases?

**Comment by v-xinda** [comment]
@nturinski There is an **extra single quote** in the Connect String when using the latest build 20220324.1. But the Connect String doesn't contain the extra single quote when using the release build.
**Connect String:**
**latest build:** postgres://use%40nicole-single-b:**'Daxinge0104.'**@nicole-single-b.postgres.database.azure.com:5432/postgres
**release build:** postgres://use%40nicole-single-b:**Daxinge0104.**@nicole-single-b.postgres.database.azure.com:5432/postgres
