### ISSUE TITLE
Remove marketplace link to Graph Explorer

### ISSUE THREAD

**Issue by nturinski** [microsoft/vscode-cosmosdb#1967]
Clicking on Graph here prompts users to install Graph Explorer, but that extension has been archived and is no longer in the marketplace.

![image](https://user-images.githubusercontent.com/5290572/156672005-95008aa9-a91f-4c98-9578-acae225eb50c.png)

We should remove this marketplace link and probably the Graph tree item.

**Comment by yuanhao-li** [comment]
How can we view / explore the graph now? I can't find a solution now.

**Comment by bwateratmsft** [comment]
A customer has hit this issue today causing confusion.

**Comment by mnbf9rca** [comment]
I'm not clear - are you proposing to drop the ability to visualise graphs? or to fix it? If the former - why? there are macos no tools (that i can find) to explore the graph visually other than the very restricted version in azure portal.

**Comment by alexweininger** [comment]
> I'm not clear - are you proposing to drop the ability to visualise graphs? or to fix it? If the former - why? there are macos no tools (that i can find) to explore the graph visually other than the very restricted version in azure portal.

What features of the graph visualization in the extension are missing in the portal version?

**Comment by JasonYeMSFT** [comment]
Attempting to open the graph explorer will result in an error notification with a link to this page: https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/visualization-partners
