### ISSUE TITLE
The error is not clear when creating a Table account with location "South Central US"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#1968]
**OS:** Win10
**Build Version:** 20220308.1

**Repro steps:**
1. Try to create a Table account with location "South Central US", fail to create the Table account with location "South Central US".
2. Check whether the error is clear or not.

**Expect:**
The error is clear.

**Actual:**
The error is not clear.
![image](https://user-images.githubusercontent.com/45614674/157410378-b89741fc-fc2d-4248-8d90-27c196f1633b.png)

**More Info:**
Succeed to create a Table account with location "East US".

**Comment by nturinski** [comment]
This seemed to work for me just now.  Could you try again?  It could have just been a temporary Azure outage.

**Comment by v-ruizh** [comment]
Verified on the latest extension build 20220324.1, this issue does not reproduce. Close it.
