### ISSUE TITLE
When trying to create a new document in collection get "is not a legal HTTP header value"

### ISSUE THREAD

**Issue by jaydestro** [microsoft/vscode-cosmosdb#1969]
I am going through [this tutorial on Learn](https://docs.microsoft.com/en-us/learn/modules/build-node-cosmos-app-vscode/3-exercise-create-cosmosdb-instance) and found that no matter what I do I cannot create individual documents using the extension in a container.

These instructions give the following output in terminal:

```
10:22:02 AM: Creating Cosmos DB account "jagord-school" with the "SQL" API... It should be ready in several minutes.
10:24:11 AM: Successfully created Cosmos DB account "jagord-school".
10:28:36 AM: Error: [
    ""
] is not a legal HTTP header value
```

<b>In the Enter a document ID box, enter S101, and then press Enter. This will be the ID of a student document.

Leave the Partition key box blank, and press Enter.

The document will be created and appear in Visual Studio Code, in JSON format. The id and StudentNumber fields will be populated with the values you specified. The document will also contain other fields that are added automatically by Azure Databases extension for its internal use</b>

Visual Studio Code 1.65.1
Azure Databases v0.18.1
Windows 2011

**Comment by jaydestro** [comment]
@neelip - any idea if there's something wrong here?

**Comment by jaydestro** [comment]
Reinstalled extension

Additionally, when I created a document in the portal and tried to access it in VS Code:

```
cannot open azureDatabases:/S101-cosmos-document.json?id%3D%2Fsubscriptions%2F4b6f991f-8cd8-4563-a4a8-eae962ec0b5f%2FresourceGroups%2Flearn-c45f52b7-d728-4d02-ba28-2b2788c0ee5c%2Fproviders%2FMicrosoft.DocumentDB%2FdatabaseAccounts%2Fjagord-school%2FSchoolDB%2FStudentCourseGrades%2F%24Documents%2Fbo8%2BAKAYMKABAAAAAAAAAA%3D%3D. Detail: Unable to read file 'azureDatabases:/S101-cosmos-document.json?id=/subscriptions/4b6f991f-8cd8-4563-a4a8-eae962ec0b5f/resourceGroups/learn-c45f52b7-d728-4d02-ba28-2b2788c0ee5c/providers/Microsoft.DocumentDB/databaseAccounts/jagord-school/SchoolDB/StudentCourseGrades/$Documents/bo8+AKAYMKABAAAAAAAAAA==' (Error: Unable to resolve nonexistent file 'azureDatabases:/S101-cosmos-document.json?id=/subscriptions/4b6f991f-8cd8-4563-a4a8-eae962ec0b5f/resourceGroups/learn-c45f52b7-d728-4d02-ba28-2b2788c0ee5c/providers/Microsoft.DocumentDB/databaseAccounts/jagord-school/SchoolDB/StudentCourseGrades/$Documents/bo8+AKAYMKABAAAAAAAAAA==')
```

**Comment by nturinski** [comment]
Hi @jaydestro.  Sorry it took so long to get back to you on this.  

> using the extension in a container

When you say in a container, could you specify how you're running the extension and what OS the container is running?  We have tried this tutorial on both a Mac and a Windows11 machine, and it seems that we were able to create the document following the same steps.
