### ISSUE TITLE
Clicking on collection no longer opens the results in a json file

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#198]
This used to work prior to v 0.2.0. It is quite convenient so we can see the json contents. Otherwise, we have to create a scrapbook and type the mongo commands.

This is a regression from the previous version.

**Comment by PrashanthCorp** [comment]
Fixed with [this PR](https://github.com/Microsoft/vscode-cosmosdb/pull/219).

**Comment by PrashanthCorp** [comment]
Our new release now has this functionality added back. 
Have a look [here](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-cosmosdb)
