### ISSUE TITLE
There is no "Create Server..." action in the "Azure CosmosDB" node context menu

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1982]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Right click the "Azure CosmosDB" node.
2. Check whether there is a "Create Server..." action in the context menu or not.

**Expect:**
There is a "Create Server..." action in the context menu.

**Actual:**
There is no "Create Server..." action in the context menu.
<img width="358" alt="Screen Shot 2022-04-24 at 18 06 01" src="https://user-images.githubusercontent.com/62053665/164971315-924f99bf-37c5-48cc-9c61-c098235ff325.png">

**Comment by alexweininger** [comment]
Closed by #2000
