### ISSUE TITLE
There is a "Create Server..." action in the Subscription context menu after installing Database extension unified build

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1983]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the Database extension installed from VSIX.
2. Right click the Subscription.
3. Check whether there is no "Create Server..." action in the context menu or not.

**Expect:**
There is no "Create Server..." action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/165009473-f64e3157-8690-4421-b77f-598e6147ff14.png)

**Actual:**
There is a "Create Server..." action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/165009158-ca7ffd63-ba9e-49ff-9d5d-046539125781.png)

**Comment by alexweininger** [comment]
Closed by #2000
