### ISSUE TITLE
There are duplicate actions in the Subscription context menu after installing Database extension unified build

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1984]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Make sure the Database extension installed from VSIX.
2. Right click the Subscription.
3. Check whether there is no duplicate action in the context menu or not.

**Expect:**
There is no duplicate action in the context menu.
![image](https://user-images.githubusercontent.com/57662131/165009473-f64e3157-8690-4421-b77f-598e6147ff14.png)

**Actual:**
There are duplicate actions in the context menu.
![image](https://user-images.githubusercontent.com/57662131/165009997-073ccad1-d39e-42b4-b787-0d7bc79e8b97.png)

**More Info:**
This issue also reproduces in the database account context menu.
![image](https://user-images.githubusercontent.com/57662131/165014003-88b3d881-daef-4f76-a07e-ec659de25740.png)

**Comment by alexweininger** [comment]
Closed by #2000
