### ISSUE TITLE
An error occurs after creating a document for a Mongo/SQL account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1985]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Expand a mongo account.
2. Right click the collection -> Click "Create Document".
3. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/165012240-d4cdf19c-74ce-4493-95ae-784836c85045.png)

**More Info:**
1. Fail to open the new created document.
2. This issue also reproduces for a SQL account.
3. This issue also reproduces when creating a stored procedure for a SQL/Graph account.

**Comment by v-xinda** [comment]
Same error occurs after executing "Open Collection" for a Mongo/SQL account.
![image](https://user-images.githubusercontent.com/57662131/165040441-34169600-0b61-4351-a7e0-011a15a6dd5d.png)

**Comment by alexweininger** [comment]
Needs verification @nturinski

**Comment by nturinski** [comment]
@v-xinda Could you verify that this is still reproducing?  I believe that it should be fixed.

**Comment by v-xinda** [comment]
@nturinski Fail to create a SQL/Mongo account with an error [2005](https://github.com/microsoft/vscode-cosmosdb/issues/2005). I will verified the above issue after fixing the issue [2005](https://github.com/microsoft/vscode-cosmosdb/issues/2005).

**Comment by v-xinda** [comment]
Verified on the latest build 20220517.5, this issue is fixed.
