### ISSUE TITLE
Fail to configure firewall for the PostgreSQL Single server with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#1986]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Expand a PostgreSQL server.
2. Expand the postgres node -> Click "Configure firewall to connect to...".
3. Pop up a prompt asking to continue -> Yes.
4. Check whether succeeds to configure firewall for the PostgreSQL Single server.

**Expect:**
Succeed to configure firewall for the PostgreSQL Single server.

**Actual:**
Fail to configure firewall for the PostgreSQL Single server with an error.
![image](https://user-images.githubusercontent.com/57662131/165031747-7ea1655a-a28c-47d3-a827-c47ddc03ba2e.png)

**More Info:**
There is a same error under the postgres node of the PostgreSQL Flexible server
![image](https://user-images.githubusercontent.com/57662131/165032729-84623683-d4c6-4ae7-a350-db5d22407fde.png)

**Comment by alexweininger** [comment]
Closed by #2000
