### ISSUE TITLE
[Unstable] Pop up an error when refreshing the subscription node

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1987]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. During creating/deleting a server ->  Right click the subscription node -> Refresh.
2. Check whether no error pops up or not.

**Expect:**
No error pops up.

**Actual:**
Pop up an error.
<img width="452" alt="Screen Shot 2022-04-25 at 17 05 12" src="https://user-images.githubusercontent.com/62053665/165057269-b8fb041e-6f5d-40be-88ff-134d8467267b.png">

**More Info：**
Restart VS Code -> Another error occurs.
<img width="597" alt="Screen Shot 2022-04-25 at 17 19 04" src="https://user-images.githubusercontent.com/62053665/165067947-d78e46c3-fe7f-4c38-9977-51d7c80d3f05.png">

**Comment by nturinski** [comment]
I tried a lot of refreshes to get this to reproduce without any success. 

It seems pretty unlikely to happen and honestly, refreshing during a delete is kind of an edge case scenario.
