### ISSUE TITLE
The "(Table)" label disappears next to the Table server after executing “Refresh” command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1988]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. During deleting a Table server ->  Right click the subscription node -> Refresh.
2. Check whether the "(Table)" label always displays next to the Table server or not.

**Expect:**
The "(Table)" label always displays next to the Table server.

**Actual:**
The "(Table)" label disappears next to the Table server.
<img width="230" alt="Screen Shot 2022-04-25 at 18 14 02" src="https://user-images.githubusercontent.com/62053665/165069541-02c2947c-8212-4b93-9ecb-96dbd6f2332d.png">

**More Info:**
This issue also reproduces for other servers.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/227
