### ISSUE TITLE
The "Deleting" status disappears next to the deleted server after executing “Refresh” command

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1989]
**OS:** All
**Azure Resource Extension Build Version:** 20220421.32 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. During deleting a server ->  Right click the subscription node -> Refresh.
2. Check whether the "Deleting" status displays next to the deleted server or not.

**Expect:**
The "Deleting" status displays next to the deleted server.
<img width="363" alt="Screen Shot 2022-04-25 at 18 34 17" src="https://user-images.githubusercontent.com/62053665/165072660-2960c739-eace-458c-8552-c7bac8778de3.png">

**Actual:**
The "Deleting" status disappears next to the deleted server.

**Comment by nturinski** [comment]
We aren't tracking the temporary descriptions and don't have any plans to, so will close this as won't fix for now.  If we get user feedback that this is a wanted feature request, we will re-open.
