### ISSUE TITLE
[Suggestion] It would be better if the prompt information is "Select Database" in the input box when selecting a database 

### ISSUE THREAD

**Issue by v-mengwe** [microsoft/vscode-cosmosdb#1991]
**OS:** All
**Azure Resource Extension Build Version:** 20220426.4 (unified)
**Azure App Database Extension Build Version:** 20220422.3 (unified)
**Regression:** Not a regression

**Repro Steps:**

1. Click "Connect to a database" in an opened Mongo Scrapbook -> Select a subscription -> Select "Azure CosmosDB" -> Select a resource.
2. Check whether the prompt information is clear in the input box or not.

**Actual:**
The prompt information is unclear in the input box.
<img width="242" alt="Screen Shot 2022-04-27 at 14 47 51" src="https://user-images.githubusercontent.com/62053665/165468942-63f1221d-e760-486a-8daa-bf1cd219d335.png">

**Suggestion:**
It would be better if the prompt information is "Select Database".
<img width="268" alt="Screen Shot 2022-04-27 at 14 47 37" src="https://user-images.githubusercontent.com/62053665/165469148-b562af57-4ef6-4729-a697-32e758b43d7a.png">

**Comment by alexweininger** [comment]
Fixed by #1998
