### ISSUE TITLE
How do I fix this?

### ISSUE THREAD

**Issue by mtdnfts** [microsoft/vscode-cosmosdb#1994]
I keep running into "CATCH ERROR: ERROR STATUS: 403" when I try to "npm run deploy_contract" any ideas why this is happening? I already uploaded my meta data, I have also already made a collection using the same code.

**Comment by nturinski** [comment]
Hi @mtdnfts

This doesn't seem to be related to our extension. We're going to close this for now, but please re-open with more details on how we would reproduce this issue and assist you.
