### ISSUE TITLE
Fail to detach a PostgreSQL Flexible/Single server with an error

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2006]
**OS:** Win10
**Build Version:** 20220514.1
**Regression:** Not a regression

**Repro Steps:**
1. Attached a PostgreSQL server -> Right click this server -> Click "Detach".
2. Check whether succeeds to detach this server.

**Expect:**
Succeed to detach this server.

**Actual:**
Fail to detach this server with an error.
![image](https://user-images.githubusercontent.com/57662131/168539451-c040e1da-cc54-46a6-aefd-9675f63a7c8a.png)

**More Info:**
There is an error under the "Attached Database Accounts" node after refreshing the workspace view.
![image](https://user-images.githubusercontent.com/57662131/168539554-58037862-e37d-4d65-a16d-a24ce1127791.png)

**Comment by v-ruizh** [comment]
Verified on the build 20220523.2, this issue also reproduces when detach other attached Cosmos DB accounts.

**Comment by alexweininger** [comment]
IIRC this is a keytar issue

**Comment by nturinski** [comment]
Same as https://github.com/microsoft/vscode-azurestorage/issues/1045

**Comment by JasonYeMSFT** [comment]
I believe this has been fixed. The extension has replaced keytar with vscode secret storage module.
