### ISSUE TITLE
The created database server is not focused after clicking "Click to view resource" in "ACTIVITYLOG"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2013]
**OS:** Win10
**Azure Database Build Version:** 20220516.20
**Resource Goup Build Version:** 20220516.8

**Repro Steps:**
1. Create a database server.
2. Click "Click to view resource" in "ACTIVITYLOG".
3. Check whether the created database server is focused.

**Expect:**
The created database server is focused.

**Actual:**
The created database server is not focused.

**More Info:**
The created database server will be focused after changing the way resource groups are grouped.

**Comment by alexweininger** [comment]
I believe this is fixed in the latest RGs build: 20220517.3

**Comment by alexweininger** [comment]
This isn't fixed in 20220517.6

**Comment by alexweininger** [comment]
Verified that this bug doesn't reproduce for creating storage accounts.

**Comment by v-xinda** [comment]
Verified on the latest Database build 20220517.18 and Resource Group build 20220518.13, this issue doesn't reproduce.
