### ISSUE TITLE
An error occurs if there is a wrong database server in the resource group after refreshing the "Resources" view

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2015]
**OS:** Win10
**Azure Database Build Version:** 20220517.5
**Resource Goup Build Version:** 20220517.3

**Repro Steps:**
1. Create a database server with an unsupported location (Central US) -> Refresh the "Resources" view.
2. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/57662131/168766559-85b596b1-a00b-4416-98eb-4c978f7ad11c.png)

**Comment by v-mengwe** [comment]
Based on this issue, there are some successful and failed (_create a server with invalid location_) servers under the Azure Cosmos DB node.
F1 -> Azure: Delete... -> Select a subscription -> Select a resource group, e.g. "Azure Cosmos DB" -> The resource list is inconsistent before and after installing the Database extension.

> All successful and failed server resources show in the list when the Database extension is not installed.
> ![image](https://user-images.githubusercontent.com/62053665/168774898-4248e770-b896-4a70-a209-cf13cf1899d0.png)
> Only failed server resources show in the list when the Database extension is not installed.
> ![image](https://user-images.githubusercontent.com/62053665/168774948-dce94adb-5e58-4260-8459-734563b6e691.png)

**Comment by alexweininger** [comment]
I think this is low priority. The create operation fails as expected so the users will know something went wrong.

![Image](https://user-images.githubusercontent.com/12476526/168941031-89085c68-4e9e-4983-acb0-f736099e0604.png)

**Comment by nturinski** [comment]
Any idea why the discrepancies between it being installed and not?

**Comment by nturinski** [comment]
As mentioned, this is a bit of a low priority and hard to debug issue. Since there are errors on creation, I think it's safe to assume users will know that these resources are invalid. Also since installing the extension seems to resolve this issue, it has an easy workaround.
