### ISSUE TITLE
Green "run" arrow in the scrapbook file

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#203]
- Can we add a green arrow to the scrapbook to execute it in the editor? perhaps to the top of the file or to the right of the current line?

**Comment by EricJizbaMSFT** [comment]
Let's investigate adding a green arrow next to the current line.

We don't want to add a green arrow to the file since we only support running one command at a time (If you want to run the whole file - I would file a separate issue for that)

**Comment by johnpapa** [comment]
good point. on the line or in the gutter would be cool

**Comment by StephenWeatherford** [comment]
The current command is extremely non-obvious. It would be good to indicate what that shortcut is someone in the UI as well (and preferably add something easier, such as CTRL+ENTER).

**Comment by StephenWeatherford** [comment]
Fixed via #515
