### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by nigbose** [microsoft/vscode-cosmosdb#2031]
Does this occur consistently? 
Repro steps:

1.
2.

Action: azureDatabases.createServer
Error type: Error
Error Message: The long running operation has failed. The provisioning state: failed.

Version: 0.19.0
OS: win32
OS Release: 10.0.19042
Product: Visual Studio Code
Product Version: 1.67.2
Language: en

<details>
<summary>Call Stack</summary>

```
isAzureAsyncPollingDone extension.bundle.js:2:654502
extension.bundle.js:2:654605extension.bundle.js:2:654605
GenericPollOperation.poll extension.bundle.js:2:655706
GenericPollOperation.update extension.bundle.js:2:657882
LroEngine.pollOnce extension.bundle.js:2:659320
```

</details>

**Comment by alexweininger** [comment]
If you are still facing this issue, please add repro steps.
