### ISSUE TITLE
CosmosDB documents won't load

### ISSUE THREAD

**Issue by brnwdrng** [microsoft/vscode-cosmosdb#2035]
Connect to any CosmosDB database in Azure, then try to open/view any document: error message.

![171737256-82c493e7-a8be-4448-9377-da69414a485a](https://user-images.githubusercontent.com/3201523/171910360-b5892010-419b-4aea-8d70-7e8195559184.png)

**Comment by JasonYeMSFT** [comment]
Given that the id of your document contains '+', I believe your issue is a duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/1732. I'll have a fix in 0.20.0. If it doesn't resolve your issue, feel free to come back and re-open this one.
