### ISSUE TITLE
There is no response after clicking "Load More..." for the emulator MongoDB account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2039]
**OS:** Win10
**Build Version:** 20220613.1
**Regression:** Not a regression

**Repro Steps:**
1. Attach the emulator MongoDB account.
2. Create a database -> Create a collection -> Import more than 60 documents into the collection.
3. Expand the collection -> Click "Load More...".
4. Check whether displays all documents after clicking "Load More...".

**Expect:**
Display all documents after clicking "Load More...".

**Actual:**
There is no response after clicking "Load More...".
![actual1](https://user-images.githubusercontent.com/57662131/173550146-cf30e970-cf74-4281-b119-e3f513009f56.gif)

**Comment by alexweininger** [comment]
Should be fixed by https://github.com/microsoft/vscode-azureresourcegroups/pull/357
