### ISSUE TITLE
[Suggestion] It would be better to add the "Deleting database account 'xxx'..." log message next to the "Delete Database Account 'xxx'"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2043]
**OS:** Win10
**Build Version:** 20220628.2

**Repro Steps:**
1. Right click a database server -> Delete it.
2. Check the log message in the Activity Log.

**Actual:**
There is no "Deleting database account 'xxx'..." log message next to the "Delete Database Account 'xxx'".
![image](https://user-images.githubusercontent.com/57662131/176385261-f1f7da67-601f-4eee-a61d-f993e7d76c3d.png)

**Suggestion:**
It would be better to add the "Deleting database account 'xxx'..." log message next to the "Delete Database Account 'xxx'", like below:
![image](https://user-images.githubusercontent.com/57662131/176383139-9221e34b-4f41-4c6f-99f2-0bcfb4f2a99e.png)

**Comment by JasonYeMSFT** [comment]
The additional message doesn't seem to carry any additional information. Let's keep the behavior as is for now.
