### ISSUE TITLE
Authentication using Azure AD

### ISSUE THREAD

**Issue by sdebruyn** [microsoft/vscode-cosmosdb#2051]
My Cosmos DB account is secured with Azure AD RBAC roles and has local authentication disabled. Thus, you cannot use the master account keys and can only authenticate using Azure AD. This tool does not seem to support that scenario. When I try to open my Cosmos DB account, I get `Error: Local Authorization is disabled. Use an AAD token to authorize all request` It is unclear how to proceed, how would I let this extension use an AAD token?

**Comment by sdebruyn** [comment]
When I try to manually attach an account, I get an error saying that the connection string requires an AccountKey

**Comment by Dakota-Whitson** [comment]
@sdebruyn Hello, I came across this while researching the same issue.

https://learn.microsoft.com/en-us/azure/search/search-howto-managed-identities-cosmos-db#prerequisites

> At this time, Cognitive Search obtains keys with the identity and uses those keys to connect to the Azure Cosmos DB account. This means that [enforcing RBAC as the only authentication method in Azure Cosmos DB](https://learn.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac#disable-local-auth) isn't supported when using Search with managed identities to connect to Azure Cosmos DB.

It seems this is currently not supported.

**Comment by sevoku** [comment]
This is fixed. RBAC is fully supported and if role assignment is missing the extension will provide guidance.
