### ISSUE TITLE
The PostgreSQL version displays 14.3 after creating a flexible server with PostgreSQL version 14 in the portal

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2059]
**OS:** Win10
**Build Version:** 20220801.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a PostgreSQL flexible server with **PostgreSQL version 14** in the portal.
![image](https://user-images.githubusercontent.com/57662131/182313843-2c6d256c-1422-4ffa-bce7-bb9cb1b7e172.png)
2. Check the PostgreSQL version after creating it.

**Expect:** 
The PostgreSQL version displays **14**.

**Actual:**
The PostgreSQL version displays **14.3**.
![image](https://user-images.githubusercontent.com/57662131/182313708-e96925e1-19f9-41ed-ac11-6ca5cd155d4f.png)

**More Info:**
This issue doesn't reproduce for PostgreSQL single server.

**Comment by alexweininger** [comment]
Is this an issue that reproduces using VS Code?

**Comment by v-xinda** [comment]
@alexweininger  Reproduce this issue using portal rather than using VS Code.

**Comment by nturinski** [comment]
This is out of our control. While it's a good find, there's nothing that we can do so I'll close this one.
