### ISSUE TITLE
Fail to create a stored procedure which name contains "+"

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2060]
**OS:** Win10
**Build Version:** 20220801.1
**Regression:** Not a regression

**Repro Steps:**

1. Create a SQL account -> Create a database -> Create a collection -> Create a stored procedure which name contains "**+**", like "test+".
2. Check whether succeeds to create a stored procedure which name contains "**+**".

**Expect:** 
Succeed to create a stored procedure which name contains "**+**".

**Actual:**
Fail to create a stored procedure which name contains "**+**".
![image](https://user-images.githubusercontent.com/57662131/182545652-8abd4eaf-a7f7-48d7-a016-e03bb69a0500.png)
**More details in Output:**
```
12:06:07 AM: Error: cannot open azureDatabases:/test%2B-cosmos-stored-procedure.js?id%3D%2Fsubscriptions%2F3b55f2b8-b6d0-4e03-a3f9-2b22471450c6%2Fmicrosoft.documentdb%2Fdatabaseaccounts%2Fsubscriptions%2F3b55f2b8-b6d0-4e03-a3f9-2b22471450c6%2FresourceGroups%2Fnicole-sql-pro%2Fproviders%2FMicrosoft.DocumentDB%2FdatabaseAccounts%2Fnicole-sql-pro%2Fdata01%2Fimport%2F%24StoredProcedures%2Ftest%2B. Detail: Unable to read file 'azureDatabases:/test+-cosmos-stored-procedure.js?id=/subscriptions/3b55f2b8-b6d0-4e03-a3f9-2b22471450c6/microsoft.documentdb/databaseaccounts/subscriptions/3b55f2b8-b6d0-4e03-a3f9-2b22471450c6/resourceGroups/nicole-sql-pro/providers/Microsoft.DocumentDB/databaseAccounts/nicole-sql-pro/data01/import/$StoredProcedures/test+' (Error: Unable to resolve nonexistent file 'azureDatabases:/test+-cosmos-stored-procedure.js?id=/subscriptions/3b55f2b8-b6d0-4e03-a3f9-2b22471450c6/microsoft.documentdb/databaseaccounts/subscriptions/3b55f2b8-b6d0-4e03-a3f9-2b22471450c6/resourceGroups/nicole-sql-pro/providers/Microsoft.DocumentDB/databaseAccounts/nicole-sql-pro/data01/import/$StoredProcedures/test+')
```
**More Info:**
This issue also reproduces for the Graph account.

**Comment by JasonYeMSFT** [comment]
As pointed out in https://github.com/microsoft/vscode-cosmosdb/issues/1732, the user shouldn't try to create resources whose name contain '+' or '%2B'.
