### ISSUE TITLE
Change the minimum VS Code version that the Azure Databases extension supports

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2062]
**OS:** Win10
**Build Version:** 20220830.1

**Repro Steps:**

1. Figure out the oldest vs code version that the extension supports, the version is 1.57.0 as below.
![image](https://user-images.githubusercontent.com/107091828/187630614-79d893e5-c205-4f0e-aa45-1205069908c4.png)
2. Install VS Code 1.57.1 from https://code.visualstudio.com/updates.
3. Install the Azure Databases extension from VSIX.
4. Expand the subscription node.
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://user-images.githubusercontent.com/107091828/187630800-af9bfeee-0021-4b0b-9a4c-18682cdf11f5.png)

**Comment by JasonYeMSFT** [comment]
I have bumped the VSCode engine version to 1.82.0.
