### ISSUE TITLE
Fail to delete a stored procedure named "." or ".."

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2065]
**OS:** Win10
**Build Version:** 20220928.1
**Regression:** Not a Regression

**Repro Steps:**

1. Create a SQL account -> Create a database -> Create a collection -> Create a stored procedure named "." or ".." -> Delete the stored procedure 
2. Check whether succeeds to delete the stored procedure named "." or "..".

**Expect**
Succeed to delete the stored procedure named "." or "..".

**Actual:**
Fail to delete the stored procedure named "." or "..".
![image](https://user-images.githubusercontent.com/107091828/193216091-bfe1c865-2637-4668-be73-f8c7fc676289.png)

**More Info:** 
1. This issue also reproduces on the previous released Databases extension 0.19.2.
2. This issue doesn't reproduce when delete a stored procedure named "..." or "....".

**Comment by MicroFish91** [comment]
Closing this as won't fix.  This is not a case we anticipate a customer will run into
