### ISSUE TITLE
unable to execute cosmos stored procedures inside of VS code

### ISSUE THREAD

**Issue by Orddu** [microsoft/vscode-cosmosdb#2066]
Does this occur consistently? Yes
Repro steps:

1. connect to azure account 
2. open a stored procedure inside of cosmos
3. attempt to run stored procedure, as available in the web app 

Version: 0.19.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.71.2
Language: en

**Comment by nturinski** [comment]
Hi @Orddu
What is the error that you're seeing when you try to run the stored procedure?
