### ISSUE TITLE
There is an extra step "Initial throughout capacity" when creating a collection for an attached "Serverless" SQL account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2075]
**OS:** Win10
**Build Version:** 20221101.1
**Regression:** Not a regression

**Repro steps:**
1. Create a SQL account with **Serverless** capacity model.
2. Attach it. 
3. Right click the attached SQL account -> Create Database... -> Enter a name -> Enter an id for the collection -> Enter a partition key.
4. Check whether there is no extra step.

**Expect:**
There is no extra step.

**Actual:**
1. There is an extra step "Initial throughout capacity".
![image](https://user-images.githubusercontent.com/57662131/199656056-570d8ef8-342d-4740-9d83-8ea4681ac7cc.png)
2. Fail to create a collection.
![image](https://user-images.githubusercontent.com/57662131/199655866-f703347d-5592-4628-abb6-9ef664b98174.png)
Details in Output:
```
8:46:22 AM: Error: Setting offer throughput or autopilot on container is not supported for serverless accounts.
ActivityId: 1e7e6a91-9ca0-4fc1-bc09-e45f673c7a93, Microsoft.Azure.Documents.Common/2.14.0
```

**More Info:**
Before attaching, there is no extra step "Initial throughout capacity" when creating a collection.

**Comment by nturinski** [comment]
This seems related to how we handle "attached" accounts specifically.
