### ISSUE TITLE
The document contents show garbled code for the attached emulator SQL 

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2082]
**OS:** Win10
**Build Version:** 20221127.1

**Repro Steps:**
1. Create a document in the attached MongoDB Emulator.
2. Refresh the attached SQL Emulator.
3. Check whether the document contents show well or not.

**Expect:**
The document contents show well.

**Actual:**
The document contents show garbled code.
![image](https://user-images.githubusercontent.com/57662131/204248132-d8896d1e-6da5-4c5a-bef6-2757692be80f.png)

**Comment by nturinski** [comment]
It seems like only the id property is impacted by this. The id property should be automatically generated so I don't think this will impact users as long as they are still able to open the documents.

Could you see if there are any other instances where the contents are garbled like this?

**Comment by v-xinda** [comment]
@nturinski  The documents don't contain the garbled contents after creating documents by right clicking "Documents" node or importing documents.

**Comment by alexweininger** [comment]
> 1. Create a document in the attached MongoDB Emulator.
> 2. Refresh the attached SQL Emulator.
> 3. Check whether the document contents show well or not.

Are you creating the document in VS Code using the extension, or are you creating the document via the MongoDB Emulator?

**Comment by v-xinda** [comment]
@alexweininger  Create the documents via the MongoDB Emulator.
