### ISSUE TITLE
Prompted to install Graph extension

### ISSUE THREAD

**Issue by davidmw** [microsoft/vscode-cosmosdb#2086]
I've attached to our trial Cosmos DB Gremlin account from the Azure Databases VS Code (macOS) extension.

I can drill down to the database but when I click on the Graph I'm presented with this message:
![Screenshot 2022-12-21 at 11 20 32 am](https://user-images.githubusercontent.com/3413901/208791800-63aa86db-ed17-4707-a737-71a055e76a33.png)

Clicking the View Extension button doesn't result in product page appearing in VS Code or browser.  Searching for 'Cosmos DB Graph' in the extensions marketplace isn't returning a match.

**Comment by mnbf9rca** [comment]
Is there any way to request you to unarchive the graph extension? Or incorporate it in to this extension?

**Comment by alexweininger** [comment]
> Is there any way to request you to unarchive the graph extension? Or incorporate it in to this extension?

We don't currently have plans to unarchive the graph extension, or to incorporate it into this extension.

There is a documentation page about visualization tools: https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/visualization-partners, and there is a graph explorer on the Azure Portal.

**Comment by ThomasVandenbon** [comment]
@alexweininger I came accross this github repository just now and when I saw the gremlin demo on the front page, I was instantly sold. 

I was then confused to see it not work and am now very disappointed to read this issue.

Please remove the demo from your front page in order not to waste people's time.

**Comment by JasonYeMSFT** [comment]
Attempting to open the graph explorer will result in an error notification with a link to this page: https://learn.microsoft.com/en-us/azure/cosmos-db/gremlin/visualization-partners
