### ISSUE TITLE
No matching resources found. when trying to connect to cosmos/mongo db

### ISSUE THREAD

**Issue by ddobric** [microsoft/vscode-cosmosdb#2090]
Using Azure Extension and scrapbook for mongo db. 
When trying to connect, I can successfully sign-in to Azure and select a subscription. However, when trying to connect to DB, ..
![image](https://user-images.githubusercontent.com/1756871/210748696-1e4da8a1-1e96-4859-9090-9dc16c978c89.png)

..the extension fails with the following error:

No matching resources found:
![image](https://user-images.githubusercontent.com/1756871/210748855-d792e51f-62b2-4f28-a11d-24e7cfef030b.png)

PS.Have many subscriptions under the signed account.

**Comment by JasonYeMSFT** [comment]
I've recently got deployed to work on this project. I know it's a bit late but the best explanation I can come up with is that there is no MongoDB database account found under your selected subscription. You can check if that's the case by expanding your subscription node, expanding Azure Cosmos DB node, and see if there are any database account nodes. The 2nd best explanation is that for some reason your database account has these properties modified and ended up in an unexpected state.

```
"type": "Microsoft.DocumentDb/databaseAccounts",
"tags": {
        "defaultExperience": "Azure Cosmos DB for MongoDB API"
},
"kind": "MongoDB"
```

You can right click the database you meant to connect to, select "View Properties" and see if all these properties values match.

**Comment by JasonYeMSFT** [comment]
I am going to close this issue. I don't have enough information to investigate this issue.
