### ISSUE TITLE
Azure Cosmos noSql isn't showing

### ISSUE THREAD

**Issue by kealanocallaghan2000** [microsoft/vscode-cosmosdb#2096]
Does this occur consistently? 
Repro steps:

https://learn.microsoft.com/en-us/azure/azure-functions/functions-add-output-binding-cosmos-db-vs-code?pivots=programming-language-csharp&tabs=in-process

1. In Visual Studio Code, select View > Command Pallete... then in the command pallete search for Azure Databases: Create Server...
2. Provide the following information at the prompts:
3. Choose Azure Cosmos DB for NoSQL (Not showing)

Version: 0.19.2
OS: win32
OS Release: 10.0.19044
Product: Visual Studio Code
Product Version: 1.74.3
Language: en

**Comment by alexweininger** [comment]
The extension doesn't currently support Azure Cosmos DB for NoSQL, I think this may be a typo in the documentation.

According to this image in the docs, they are actually choosing the "Core (SQL)" option.
![image](https://user-images.githubusercontent.com/12476526/214976631-5effd467-76ff-4ffb-92b7-b9a98fe0d000.png)

<img width="610" alt="image" src="https://user-images.githubusercontent.com/12476526/214976698-82b91863-0dae-4910-9f34-d120b768e191.png">

**Comment by alexweininger** [comment]
We will need to follow up with the docs team on this.

**Comment by JasonYeMSFT** [comment]
This has been fixed in the doc. https://github.com/MicrosoftDocs/azure-docs/commit/ae35f8daaa9f754a503e06273817f69121bb3a7e
