### ISSUE TITLE
The "Connected" label appears next to both the "test" and "postgres" databases

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2100]
**OS:** Win10
**Azure Resource Group Build Version:** 20230219.1
**Azure Databases Build Version:** v0.19.3

**Repro Steps:**

1. Create a PostgreSQL account -> Create a database "test".
2. Right click "postgres" database -> Select "Connect to Database...".
3. Check whether the "Connected" label disappears automatically next to "test" database.

**Expect:**
The "Connected" label disappears automatically next to "test" database.

**Actual:**
The "Connected" label appears next to both the "test" and "postgres" databases.
![image](https://user-images.githubusercontent.com/107091828/220055040-728114fc-527d-498c-81e1-1edfbe801bad.png)

**More Info:**
1. This issue also reproduces when executing command "PostgreSQL: Connect to database..." from command palette.
2. This issue also reproduces for the MongoDB account.
3. This issue will be fixed after refreshing.

**Comment by JasonYeMSFT** [comment]
Given that this is a minor issue that can be fixed via refreshing, I am going to close this as won't fix.
