### ISSUE TITLE
Show all database accounts (SQL, MongoDB, Graph, Table) in the list when executing "MongoDB: Connect to Database..." command from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2101]
**OS:** Win10
**Azure Resource Group Build Version:** 20230219.1
**Azure Databases Build Version:** v0.19.3

**Repro Steps:**

1. F1 -> MongoDB: Connect to Database... -> Select subscription. 
2. Check the resouce list.

**Expect:**
Only show the Mongo DB accounts.

**Actual:**
Show all database accounts (SQL, MongoDB, Graph, Table) in the list.
![image](https://user-images.githubusercontent.com/107091828/220058687-7432e953-a5a6-43e6-953f-5626ee7b6e36.png)

**More Info:**
1. This issue also reproduces when executing the about "SQL\Graph\table" command from command palette.
2. This issue also reproduces when clicking "Connect to a database" in an opened Mongo Scrapbook.

**Comment by alexweininger** [comment]
The compatibility shim for pick app resource does not support filtering by tags like v1 pick app resource did.

**Comment by JasonYeMSFT** [comment]
Given that this is a minor issue that can be easily worked around by selecting the correct resource, I am going to close this issue as won't fix.
