### ISSUE TITLE
There is no "+ Create new Database..." command in the list when executing "Connect to a database" command  from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2102]
**OS:** Win10
**Azure Resource Group Build Version:** 20230219.1
**Azure Databases Build Version:** v0.19.3

**Repro Steps:**

1. F1 -> Mongo: Connect to Database -> Select subscription -> Select a resource.
2. Check whether there is a "+ Create new Database" command in the list.

**Expect:**
There is a "+ Create new Database..." command in the list.
![image](https://user-images.githubusercontent.com/107091828/220063603-b2b9ddb0-d96c-434e-8f20-e4a3a9d1ea32.png)

**Actual:**
There is no "+ Create new Database..." command in the list.

**More Info:**
1. This issue also reproduces when executing "MongoDB: Create Collection.../Create Document/Open collection" command from command palette.
2. This issue also reproduces when executing "Core(SQL): Create Collection.../Create Document.../Create Stored Procedure..." command from command palette.
3. This issue also reproduces when executing "PostgreSQL: Connect to Database..." command from command palette.
4. This issue also reproduces when executing "Graph(Gremlin): Create Graph..." command from command palette.
5. This issue also reproduces when clicking "Connect to a database" in an opened Mongo Scrapbook.
6. This issue also reproduces when clicking "Connect to a database" in an opened Function Query and Stored Procedure Query.

**Comment by alexweininger** [comment]
Fixed by https://github.com/microsoft/vscode-azuretools/pull/1386
