### ISSUE TITLE
The detached database account shows in the Attached Database Accounts view after executing "Cosmos DB: Detach" from command palette

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2103]
**OS:** Win10
**Azure Resource Group Build Version:** 20230219.1
**Azure Databases Build Version:** v0.19.3

**Repro Steps:**

1. Attached a database account -> F1 -> Cosmos DB: Detach -> Select the above database account. 
2. Check whether the detached database account shows in the Attached Database Accounts view.

**Expect:**
The detached database account doesn't show in the Attached Database Accounts view.

**Actual:**
The detached database account shows in the Attached Database Accounts view.

**More Info:**
1. This issue doesn't reproduce after executing "Detach" action from context menu.
2. Refresh can fix this issue.

**Comment by JasonYeMSFT** [comment]
Given that this is a minor issue which can be easily worked around by refreshing the tree view, I am going to close this issue as won't fix.
