### ISSUE TITLE
The created database doesn't auto display in the tree view

### ISSUE THREAD

**Issue by v-chenzha** [microsoft/vscode-cosmosdb#2106]
**OS:** Win10
**Azure Resource Group Build Version:** 20230219.1
**Azure Databases Build Version:** v0.19.3

**Repro Steps:**

1. Expand a MongoDB account -> F1 -> MongoDB: Create Database...
2. Check whether the created database auto displays in the tree view.

**Expect:**
The created database auto displays in the tree view.

**Actual:**
The created database doesn't auto display in the tree view.

**More Info:**
1. This issue also reproduces when executing "MongoDB/PostgreSQL/Core (SQL)/Graph: Create Database..." command from command palette.
2. This issue also reproduces when executing "MongoDB: Open Collection" and then Selecting "+ Create new Collection "command from command palette.
3. This issue also reproduces after creating the Function Query and Stored Procedure Query.
4. Refresh can fix this issue.

**Comment by JasonYeMSFT** [comment]
The database extension is calling the correct APIs of resource group to create the child. The resource group extension is not updating the tree view correctly in its implementation of createChild.

**Comment by sevoku** [comment]
I can't reproduce this, seems to be fixed upstream.
