### ISSUE TITLE
[Suggestion] It would be better to remove the "Load More..." button after importing 50 documents into the collection

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2119]
**OS:** Windows 10
**Azure Database Build Version:** 20230314.4
**Azure Resources Build Version:** 0.6.2
**Regression:** Not a regression

**Repro Steps:**

1. Create a MongoDB account -> Create a database -> Create a collection.
2. Import 50 documents into the above collection.
3. Expand the above collection -> Click "Load More...".
4. Check whether more document load in the list.

**Actual:**
No more documents load in the list.

**Suggestion:**
It would be better to remove the "Load More..." button after importing 50 documents into the collection.

**More Info:**
This issue also reproduces for the SQL account.

**Comment by JasonYeMSFT** [comment]
Since this issue also involves "load more", let's track it in #2113
