### ISSUE TITLE
There is no "Attach Database Account..." action in the context menu of "Attached Database Accounts" node

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2124]
**OS:** Win10
**Build Version:** 20230403.1

**Repro Steps:**
1. Navigate to "WORKSPACE" view -> Right click "Attached Database Accounts" node.
2. Check whether there is an "Attach Database Account..." action in the context menu.

**Expect:**
There is an "Attach Database Account..." action in the context menu of "Attached Database Accounts" node.

**Actual:**
There is no "Attach Database Account..." action in the context menu of "Attached Database Accounts" node.
![image](https://user-images.githubusercontent.com/45614674/229737804-8346edc9-2bf9-4b2d-b8ab-1d5d0f24dfef.png)

**Comment by tatkaN** [comment]
I have the same problem.

**Comment by sevoku** [comment]
This is fixed via #2397, no context menu is needed.
