### ISSUE TITLE
The "Deleting..." label shows next to the database of the SQL emulator when deleting the database of the MongoDB emulator

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2129]
**OS:** Win10
**Build Version:** 20230510.1
**Regression:** Not a regression

**Repro Steps:**
1. Attach the MongoDB emulator and SQL emulator.
2. Create a database.
3. Expand the MongoDB emulator and SQL emulator nodes.
4. Right click the database under the MongoDB emulator node -> Click "Delete Database...".
5. Check whether the "Deleting..." label shows next to the database of the MongoDB emulator.

**Expect:**
The "Deleting..." label shows next to the database of the MongoDB emulator.

**Actual:**
The "Deleting..." label shows next to the database of the SQL emulator.
![actual1](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/008c7bb2-730b-405e-8764-8d9cb7f5c136)

**More Info:**
1. This issue also reproduces when deleting the collection of the MongoDB emulator.
2. This issue doesn't reproduce when deleting the database or collection of the SQL emulator.
3. This issue doesn't reproduce if the SQL emulator node is collapsed and refresh the Workspace view.
4. If you create a database for the SQL emulator then expand the MongoDB emulator and SQL emulator nodes, the "Deleting..." label shows next to the database of the MongoDB emulator when deleting the database of the SQL emulator.

**Comment by MicroFish91** [comment]
Can you please confirm if the right resource being deleted after refreshing?

**Comment by v-xinda** [comment]
Verified this issue on the latest main branch build 20230802.1, it doesn't reproduce for now.
