### ISSUE TITLE
There is no "Create Server..." action in the context menu for focused "Azure Cosmos DB/PostgreSQL server (Flexible)/PostgreSQL server (Srandard)" node

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2132]
**OS:** Win 10
**Build Version:** 20230528.1
**Regression:** Not a Regression

**Repro Steps:**

1. Click "Focus Group" icon to focus the "Azure Cosmos DB" node.
2. Right click the "Azure Cosmos DB" node.
3. Check the context menu.

**Expect:**
There is "Create Server..." action in the context menu.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/dd746c24-26e8-463a-bfaa-7f8adb4b963c)

**Actual:**
There is no "Create Server..." action in the context menu.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/c761c93c-2b74-491a-8e91-faf6a84ee536)

**More Info:**
This issue also reproduces for "PostgreSQL server (Flexible)" and "PostgreSQL server (Srandard)" nodes.

**Comment by JasonYeMSFT** [comment]
This is by design. The Focused group node will enumerate database servers under different subscriptions. It is ambiguous to create server there because we don't know in which subscription should the server be created.
