### ISSUE TITLE
[Suggestion] It would be better to keep the TLS version consistently between the account created in VSCode and in portal

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2141]
**OS:** Win10
**Build Version:** 20220621.1

**Repro steps:**

1. Create a SQL account in VSCode -> Open in portal -> Settings -> Networking -> Connectivity -> Check the TLS version.
2. Create a SQL account in portal -> Click "Go resource" -> Settings -> Networking -> Connectivity -> Check the TLS version.
3. Check whether the TLS version is consistent between the VSCode and portal.

**Actual:**
The TLS version is inconsistent between the VSCode and portal.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/467773f8-675a-46cc-889c-d78841569f21)

**Suggestion:**
It would be better to keep the TLS version consistently between the account created in VSCode and in portal.

**More Info:**
This issue also reproduces for Graph and Table accounts.

**Comment by JasonYeMSFT** [comment]
We don't manually control the TLS version for the created database account. It's determined by the SDK. Let's re-verify this right before we release 0.20.0-alpha.0 to see what version the SDK has updated to.

**Comment by JasonYeMSFT** [comment]
I have tested this. The TLS versions of new created database accounts are updated to use the new TLS version.
