### ISSUE TITLE
Azure Cosmos DB for MongoDB (vCore) is not showing in the list of Databases

### ISSUE THREAD

**Issue by vamsi981** [microsoft/vscode-cosmosdb#2146]
Azure Cosmos DB for MongoDB (vCore) is not showing up in the VS code widget. Is there any way where i can explore the data ?

**Comment by MicroFish91** [comment]
Sorry, unfortunately we don't support Mongo clusters yet.  We may look into implementing this as a feature in the future.

**Comment by tnaum-ms** [comment]
We're excited to announce that development on Azure Cosmos DB for MongoDB (vCore) support is now underway. We're actively working on the first release and can't wait to make it available to everyone soon.

**Comment by sevoku** [comment]
This is done and merged with #2318, release will be available soon!
