### ISSUE TITLE
Mongo Scrapbook cannot connect to Attached database accounts in Workspace

### ISSUE THREAD

**Issue by RobyOne77** [microsoft/vscode-cosmosdb#2148]
When I open Mongo Scrapbook and click "connect to a database" can't access to Attached database accounts in Workspace.

![image](https://github.com/microsoft/vscode-cosmosdb/assets/70849241/ad37672e-21bd-488d-8878-9ec7065faca5)

Are mandatory have an azure account for use this extension?
In the past version i haven't this issue.

**Comment by MicroFish91** [comment]
Could you try attaching a database account through the local workspace view:

![image](https://github.com/microsoft/vscode-cosmosdb/assets/40250218/97990d86-2314-4e3e-9212-2ce40f5c6c5c)

![image](https://github.com/microsoft/vscode-cosmosdb/assets/40250218/f4ef5416-b4cc-4626-8c47-713a2dd601bc)

Let me know if that works for you, thanks!
