### ISSUE TITLE
[Suggestion] It would be better to add a "Create Server..." action for the "Azure Databases" icon in workspace view

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2155]
**OS:** Win 10
**Build Version:** 20230820.1
**Regression:** Not a Regression

**Repro Steps:**
1. Navigate to workspace view and click the "Azure Databases " icon.
2. Check whether there is a "Create Server..." action for the "Azure Databases" icon.

**Actual:**
There is no "Create Server..." action for the "Azure Databases" icon.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/f73994d3-10d9-45f1-b02b-655edbf42a13)

**Suggestion:**
It would be better to add a "Create Server..." action for the "Azure Databases" icon in workspace view.

**Comment by JasonYeMSFT** [comment]
The attached database account already has a Create Server action. I don't think adding a Create Server action at the workspace level is necessary.
