### ISSUE TITLE
Fail to create a function with name "test" for a PostgreSQL Flexible server 

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2159]
**OS:** Win10
**Build Version:** 20230822.5
**Regression:** Not a Regression

**Repro Steps:**
1. Drill down a PostgreSQL Flexible server -> Database "postgres" -> Right click the "Functions" node -> Click "Create Function Query..." -> Create a function query with name "test" -> Execute the query.
2. Check whether succeeds to create a function or not.

**Expect:**
Succeed to create a function with name "test".

**Actual:**
Fail to create a function with name "test".
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/ebd5ca5c-2ca8-4789-bfd7-bbd28959233c)

**More Info:**
1. This issue also reproduces on the current released extension v0.19.4.
2. This issue does not reproduce on PostgreSQL single server or new created database.

**Comment by JasonYeMSFT** [comment]
@v-ruizh Could you re-test this with the latest build using either
- Username and password
- MS EntraID

and see if it can reproduce? I successfully created the 'test' function with both type of credentials.

**Comment by v-ruizh** [comment]
@JasonYeMSFT Verified this issue on the latest Azure Databases extension 20240207.4, it is no longer reproduce. Thanks for your update.
