### ISSUE TITLE
Fail to connect to PostgreSQL server

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2166]
**OS:** Win10
**Build Version:** 20230910.1
**Regression:** Previous Build

**Repro Steps:**
1. Create one PostgreSQL single server in VS Code.
2. Expand the above single server in VS Code -> Expand "postgre" database. 
3. Check whether the "Configure firewall to connect to..." shows under the "postgre" database or not.

**Expect:**
The "Configure firewall to connect..." shows under the "postgre" database.

**Actual:**
1. The "Enter server credentials to connect to..." shows under the "postgre" database.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/36caae79-0da5-4788-aa40-762df59fc8fb)
2. Click "Enter server credentials to connect to..." and input the correct username and password, it is still disconnected.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/f20fe566-15f9-4b4b-b9fa-8b5f820bc0fe)

**More Info:**
1. This issue also reproduces for PostgreSQL Flexible server.
2. This issue does not reproduce on the previous extension build 20230907.2.

**Comment by JasonYeMSFT** [comment]
I merged a fix for this bug.
