### ISSUE TITLE
An extra notification pops up when executing action for "postgre" database

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2168]
**OS:** Win10
**Build Version:** 20230910.1

**Repro Steps:**
1. Create one PostgreSQL server in VS Code.
2. Expand the above single server -> Expand "postgre" database -> Connect to this server.
3. Right click "postgre" database and execute any action of below.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/48a45e17-c8ce-4a7f-968f-8fca425c7f80)
4. Check whether no extra notification pops up or not.

**Expect:**
No extra notification pops up.

**Actual:**
An extra notification pops up.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/08dd8c7c-20a9-4ac1-9649-ae6ba4535867)

**More Info:**
1. This issue reproduces for both single and flexible PostgreSQL server.
2. This issue reproduces when executing any action for "postgre" database.
3. This issue also reproduces when executing commands for "postgre" database from "Command Palette".

**Comment by JasonYeMSFT** [comment]
Getting the IP is expected since we need to check for firewall settings. However, I do notice that the default get IP method is taking unexpectedly long time. I will look into that and consider removing the notification.

**Comment by JasonYeMSFT** [comment]
The first method we use to get IP no longer works and takes an annoyingly long time to time out. I get rid of it and suppressed the "Getting public IP" info notification. Not it shouldn't take too long to expand the nodes if the firewall rules are configured or prompt the firewall error if it's not.

**Comment by v-ruizh** [comment]
This issue does not reproduce on extension build 20230919.6, close it.
