### ISSUE TITLE
The wrong web page is opened when executing command "Learn more about authenticating with Azure Active Directory"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2191]
**OS:** Win10
**Build Version:** 20230927.1
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Select "PostgreSQL: Learn more about authenticating with Azure Active Directory".
2. Check whether the corresponding web page is opened or not.

**Expect:**
The corresponding web page is opened.

**Actual:**
The wrong web page is opened.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/8a24b2af-6acb-474a-ac51-6f2c12786848)

**More Info:**
This issue also reproduces when clicking the button "Learn more about authenticating with Azure Active Directory".
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/cfd8a42e-59a6-4627-808b-35ee64f5733f)

**Comment by JasonYeMSFT** [comment]
This is expected for now. I will activate the forward link before publishing 0.20.0.

**Comment by JasonYeMSFT** [comment]
The wiki page has been activated.

**Comment by v-ruizh** [comment]
Verified this bug on the latest build 20231017.2, it has been fixed.
