### ISSUE TITLE
[Suggestion] It would be better to change the "Database" to "database" in the input box

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2198]
**OS:** All
**Build Version:** 20231007.1
**Regression:** Not a regression

**Repro steps:**
1. F1 -> Click "Cosmos DB: Delete Document...".
2. Check the tip in the input box.

**Actual:**
Show "Select resource" tip in the input box.
<img width="605" alt="Screenshot 2023-10-09 at 15 24 01" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/3b89896f-58f4-47c7-bc01-972c59ce4a25">

**Suggestion:**
It would be better to change the "resource" to "Resource" in the input box. Like below:
<img width="605" alt="Screenshot 2023-10-09 at 15 24 13" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/ccb300fd-4b39-4ab1-b227-b10ce99b9dc9">

**More Info:**
This issue also reproduces when more than one subscription is selected.
<img width="613" alt="Screenshot 2023-10-09 at 15 27 29" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/ff044569-a6f6-4135-8181-963aed4e3173">

**Comment by MicroFish91** [comment]
I personally prefer the non-branded resource names to be lower-case.  I do agree that we should be consistent about this though

**Comment by JasonYeMSFT** [comment]
The string is pulled from the `childTypeLabel` of the database node's AzExtTreeItem object by the utils package. Since this is a minor issue and changing the value of childTypeLabel may carry unknown impact, let's not worry about this string for now.
