### ISSUE TITLE
There is no timestamp for the log message in the Output window after importing a document into a collection

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2199]
**OS:** All
**Build Version:** 20231007.1
**Regression:** Not a regression

**Repro steps:**
1. Make sure the setting "Azure Databases: Enable Output Timestamps" is checked.
2. Create a Mongo DB account -> Create a database -> Create a collection.
3. Right click the collection -> Click "Import Document into a Collection..." -> Select a .Json file -> Import.
4. Check whether there is a timestamp for the log message in the Output window.

**Expect:**
There is a timestamp for the log message in the Output window.
<img width="1033" alt="Screenshot 2023-10-09 at 16 09 40" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/9bac76d9-ce3c-4131-b240-ec6ac4f5f275">

**Actual:**
There is no timestamp for the log message in the Output window.
<img width="1090" alt="Screenshot 2023-10-09 at 15 51 49" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/aa694ea2-aae5-44b6-b9b1-565c51619f5b">

**More Info:**
This issue also reproduces after creating a new function query or Stored Procedure Query for the PostgreSQL account.
<img width="986" alt="Screenshot 2023-10-09 at 16 07 35" src="https://github.com/microsoft/vscode-cosmosdb/assets/57662131/ed03493f-a4a9-4906-a674-cbf3033685ae">

**Comment by JasonYeMSFT** [comment]
This is because these messages are written using an API that doesn't respect the timestamp setting.
