### ISSUE TITLE
Query NoSQL DB

### ISSUE THREAD

**Issue by zack-docusign** [microsoft/vscode-cosmosdb#2206]
Is it possible to run a query on a NoSQL DB? I do not have access to Azure Portal Data Explorer (because of security reasons) and want to run a query search for a specific document in my container.

**Comment by JasonYeMSFT** [comment]
@zack-docusign We currently don't offer querying CosmosDB NoSQL databases. This can be a new feature for us to look into. Could you elaborate on what security reasons prevent you from using Azure Portal? At the end of the day, Azure Portal and us make similar network calls and I cannot think of reasons making the extension more secure than Azure Portal.
