### ISSUE TITLE
Show "Select Documents" tip in the input box when deleting a document of the SQL account

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2208]
**OS:** Win10
**Build Version:** 20231116.4
**Regression:** Not a Regression

**Repro Steps:**
1. F1 -> Core (SQL): Delete Document... -> Select SQL account -> Select Database -> Select Collection.
2. Check the tip in the input box.

**Expect:**
Show "Select Document" tip in the input box.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/adab9e08-fa62-4d8a-ab2b-2ee28514cca2)

**Actual:**
Show "Select Documents" tip in the input box.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/d1759baf-9036-41f5-a892-120c553f6cbf)

**More Info:**
This issue doesn't reproduce for the Mongo DB account.

**Comment by JasonYeMSFT** [comment]
The string comes from the ResourceGroup extension. It is not configurable in database extension.
