### ISSUE TITLE
The created database doesn't display under the Mongo DB account after creating a database using "+ Create new Database..." from scrapbook file

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2210]
**OS:** Win10
**Build Version:** 20231119.1
**Regression:** Not a regression

**Repro Steps:**
1. Create a scrapbook -> Click "Connect to a database" -> Select a subscription -> Select a Mongo DB account -> + Create new Database... -> Enter a name -> Enter.
2. Expand the above Mongo DB account.
3. Check whether the created database displays under the Mongo DB account.

**Expect:**
The created database displays under the Mongo DB account.

**Actual:**
1. The created database doesn't display under the Mongo DB account.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/35729452-3258-46a1-860f-034504866fea)
2. No database is connected after reloading the VS Code.

**More Info:**
The created database will display under the Mongo DB account after executing "Execute All" command, and the database doesn't disconnect after reloading the VS Code.

**Comment by JasonYeMSFT** [comment]
There is no way for us to predict that the execution of the command will result in the creation of such databases. The user will need to manually refresh the tree to see the changes.
