### ISSUE TITLE
Change the minimum VS Code version that the Azure Database extension supports

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2212]
**OS:** Win10
**Build Version:** 20231119.1

**Repro Steps:**
1. Figure out the oldest vs code version that the extension supports, the version is 1.66.0.
2. Install VS Code 1.66.2 from https://code.visualstudio.com/updates.
3. Install the Azure Database extension.
4. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/4d2659ca-6194-47e7-8e8c-ab065f00e6e8)

**Comment by JasonYeMSFT** [comment]
Technically 1.66.0 should be the oldest version that database extension supports. However, I noticed that the dev package and the utils package have added APIs using features from newer VSCode versions that wouldn't work in 1.66.0. I am going to upgrade the minimum supported VSCode version to 1.82.0.
