### ISSUE TITLE
The SQL account is pinned on the top of the Azure view when pulling down scroll bar

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2220]
**OS:** Win 10
**Build Version:** 20231213.2
**Regression:** Previous release

**Repro Steps:**

1. Create a new SQL account -> Create a database -> Create a collection -> Create several documents -> Pull down scroll bar.
2. Check whether the SQL account is not pinned on the top of the Azure view.

**Expect:**
The SQL account is not pinned on the top of the Azure view.

**Actual:**
The SQL account is pinned on the top of the Azure view.
![actual](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/caec3853-7f29-41f7-8850-63b12fd82d56)

**More info:**
1. This issue also reproduces for the Mongo DB account.
2. This issue also reproduces for the Stored Procedures.

**Comment by JasonYeMSFT** [comment]
I am not able to reproduce this issue. Could you give me the version of resource group extension and vs code?

**Comment by v-xinda** [comment]
@JasonYeMSFT The details as below:
**Resource Group Version:** 0.8.3
**VS Code Version:** 1.86.0-insider (user setup)

**Comment by JasonYeMSFT** [comment]
I am able to reproduce the same behavior in the VS Code Insider 1.86.0 now.
