### ISSUE TITLE
An error occurs after executing "Execute All" for the scrapbook

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2228]
**OS:** Win10
**Build Version:** 20240110.1
**Regression:** Previous regression

**Repro Steps:**
1. Create a Mongo DB account -> Create a database.
2. Create a new scrapbook and type the following.
```
db.test.drop()
db.test.insertOne({"value":1})
db.test.insertOne({"value":2, "age": 34})
db.test.find()
```
4. Click "Execute All".
5. Check whether no error occurs.

**Expect:**
No error occurs.

**Actual:**
An error occurs.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/6c3d4402-f010-40bf-9538-2947d0583c91)

**More Info:**

1. If you executed the above commands with the current released Azure Databases firstly, this issue doesn't reproduce when executing them again with the latest build.
2. An error as below occurs when executing the first command `db.test.drop()`, but no error occurs after executing other commands. 
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/3bcf1011-12b9-4269-98e8-180deb6f5779)

**Comment by JasonYeMSFT** [comment]
The error message indicates that the collection to drop doesn't exist. However, instead of getting the error in VS Code, I get this output file opened in the editor

<img width="1178" alt="image" src="https://github.com/microsoft/vscode-cosmosdb/assets/39359541/52052da4-d3f1-426c-973d-34063c4d62c7">

**Comment by v-xinda** [comment]
@JasonYeMSFT  This issue doesn't reproduce after creating the "test" collection.
