### ISSUE TITLE
There is no operation "Enter server credentials to connect 'xxx'" after expanding "postgres" node on another machine

### ISSUE THREAD

**Issue by v-xinda** [microsoft/vscode-cosmosdb#2231]
**OS:** Win10
**Build Version:** 20240112.17
**Regression:** Previous release

**Repro Steps:**
1. Create a PostgreSQL Flexible server.
2. Expand the PostgreSQL Flexible server on another machine -> Expand "postgres" node.
3. Check whether there is an operation "Enter server credentials to connect 'xxx'".

**Expect:**
There is an operation "Enter server credentials to connect 'xxx'".
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/81a63614-e976-4d05-a31b-efde924a0e07)

**Actual:**
1. There is no operation "Enter server credentials to connect 'xxx'".
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/0afcf70d-bacb-4cd3-805d-ea40b5d89dea)
2. Prompt to enter server credentials to connect 'xxx'.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/57662131/515958c4-d00e-42a9-ba7a-d143b36bf258)

**More Info:**
This issue doesn't reproduce for the PostgreSQL Single server.

**Comment by JasonYeMSFT** [comment]
I wasn't able to reproduce and I have zero idea how this could happen. The code for showing the warning and the code for showing the "enter credential node" are literally next to each other. If you can get a reproducing server, could you share it with me and let me try it?

**Comment by JasonYeMSFT** [comment]
We did some more investigation offline. The root cause is that our auto firewall configuration detects that the current IP is already included in the IP whitelist but still get an IP address blocked error. This can happen if the client is under an uncooperative NAT that uses different IP addresses to connect to database server.
