### ISSUE TITLE
No resource shows in "Azure View" after updating the Azure Databases extension build

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2287]
**OS:** Win10
**Build Version:** 20240706.1

**Repro Steps:**
1. Install the current released Azure Databases extension v0.22.0.
2. Navigate to "Azure View", the Azure resources show well.
3. F1 -> Select "Extensions: Install from VSIX..." to install the latest main branch Azure Databases extension v0.22.1-alpha.
4. Click "Restart Extensions" button in the below notification.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/5a6465d0-e5e2-4542-af4b-5a7aff6c1808)
5. Check whether the Azure resources show well or not.

**Expect:**
The Azure resources show well.
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/284bf8a6-c73a-4c0b-be7f-d725dcad8065)

**Actual:**
No resource shows in "Azure View".
![image](https://github.com/microsoft/vscode-cosmosdb/assets/45614674/79a5e9ee-5dae-4c54-aefa-d80d08aa1332)

**More Info:**
Refresh the "Azure View" can fix this issue.

**Comment by Amar-QA** [comment]
The issue also occurs after updating the Azure Container Apps Extension Build.
**Build Version:** 20240705.1

![image](https://github.com/microsoft/vscode-cosmosdb/assets/156269329/35cf0151-5913-4d9b-9c43-9ace5ff926ee)

**Comment by sevoku** [comment]
This is more likely a [vscode-azureresourcegroups](https://github.com/microsoft/vscode-azureresourcegroups) issue.
