### ISSUE TITLE
Can't resolve private link IP address of CosmosDB Mongo

### ISSUE THREAD

**Issue by leilifremont** [microsoft/vscode-cosmosdb#2291]
Error message:
024-07-25 06:09:41.657 [info] Error: Error=13, Details='Request originated from IP 20.150.154.75 through public internet. This is blocked by your Cosmos DB account firewall settings. More info: https://aka.ms/cosmosdb-tsg-forbidden
ActivityId: c6c1d94c-c4fb-4cfc-95e2-959509361f4e, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.20348.0

I attach VS code to debug pod running in AKS.  From the debug pod, if I run nslookup, I will get:

```
nslookup msf-models-maindb-dev.mongo.cosmos.azure.com
;; Got recursion not available from 10.0.0.10
;; Got recursion not available from 10.0.0.10
;; Got recursion not available from 10.0.0.10
Server:         10.0.0.10
Address:        10.0.0.10#53

Non-authoritative answer:
msf-models-maindb-dev.mongo.cosmos.azure.com    canonical name = msf-models-maindb-dev.privatelink.mongo.cosmos.azure.com.
Name:   msf-models-maindb-dev.privatelink.mongo.cosmos.azure.com
Address: 10.120.32.75
```

**Comment by sevoku** [comment]
I don't quite get the issue here, the local IP is not allowed to access the account, it doesn't matter whether the address resolves through DNS.

**Comment by leilifremont** [comment]
@sevoku ,
This issue was opened according to suggestion of Microsoft Support engineer.

**Comment by leilifremont** [comment]
He said that you should understand, but seems you need more context.

**Comment by leilifremont** [comment]
Let me open another internal support ticket
