### ISSUE TITLE
Show a count of graph vertices and edges

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#235]

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford is this fixed already?

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT No, this would be a new feature.  I thought I removed this from 0.3.

**Comment by StephenWeatherford** [comment]
Although I guess I'm considering it, since it's not hard...

**Comment by StephenWeatherford** [comment]
We expect to switch to using the data explorer.
