### ISSUE TITLE
NoSQL queries with comments fail to run

### ISSUE THREAD

**Issue by sevoku** [microsoft/vscode-cosmosdb#2414]
Enter any query with a commented out section as simple as:
```
/* SELECT TOP 10 * FROM c */

SELECT * FROM c
```
and run it.

Expected: the uncommented query gets executed.

Actual: query fails with:
```
Query failed Message: {"errors":[{"severity":"Error","location":{"start":0,"end":1},"code":"SC1001","message":"Syntax error, incorrect syntax near '/'."}]}
```

This works in Azure Data Explorer.

**Comment by bk201-** [comment]
@sevoku Are you sure that it works in Azure Data Explorer?

I've just run query there
![Image](https://github.com/user-attachments/assets/9a010c35-97e1-41cd-b92e-b26e45a0ba40)

**Comment by sevoku** [comment]
Thanks for double checking @bk201-. And I can confirm that `--` comments work as expected in both Scrapbooks and the new Query Editor.
