### ISSUE TITLE
The document file of "Cosmos DB for NoSQL" account is not saved by clicking "Ctrl+S"

### ISSUE THREAD

**Issue by v-ruizh** [microsoft/vscode-cosmosdb#2429]
**OS:** Windows 10
**Build Version:** 20241116.1

**Repro Steps:**
1. Create a "Cosmos DB for NoSQL" account.
2. Expand the above account -> Right click the "Documents" node -> Select "Create Document..." -> Edit the document file.
3. Click "Ctrl+S".
4. Check whether the document file is saved by clicking "Ctrl+S".

**Expect:**
The document file is saved by clicking "Ctrl+S".

**Actual:**
The document file is not saved by clicking "Ctrl+S".

**More Info:**
1. Clicking the "Save" button can save the document file.
![Image](https://github.com/user-attachments/assets/84dc9c0a-b373-4f97-8840-ecbc0d00e738)
2. This issue also reproduces on the current released Azure Databases extension V0.24.0.

**Comment by sevoku** [comment]
#2425 should fix this :)

**Comment by v-ruizh** [comment]
This issue has been fixed on Azure Databases extension 20241121.1, close it.
