### ISSUE TITLE
Updating a collection with an empty set of documents gives an error

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#255]
Issue arises at the Mongo API call site - the API call does not accept an empty array as a list of operations

**Comment by PrashanthCorp** [comment]
![empty collection update](https://user-images.githubusercontent.com/30420973/33637179-57b67b16-d9d4-11e7-990c-cb06df46fafc.PNG)

**Comment by EricJizbaMSFT** [comment]
Won't fix this. The error message is good enough
