### ISSUE TITLE
Scrapbook result update doesn't percolate to appropriate document(s)

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#259]
The reason being we create [new `MongoDocumentNodes` and `MongoCollectionNodes` in the `executeCommandFromActiveEditor` method](https://github.com/Microsoft/vscode-cosmosdb/blob/b843d9a7f9e5ebe9cbea049f1011b2d165cec947/src/mongo/commands.ts#L35).

Fix : Find the appropriate collection and documents, and use those nodes. 
Glitch : The document(s) returned may not exist on the viewtree yet. In which case we'll have to create an adhoc node anyway.

**Comment by EricJizbaMSFT** [comment]
@PrashanthCorp this is an issue for 0.2.2, but it's not worth blocking the release. It's also already been fixed on the master branch (as a part of my shared tree provider work [here](https://github.com/Microsoft/vscode-cosmosdb/commit/9d3c2c3320b38e8c5018e219945e24108cd22c09)) so I'll close this issue

**Comment by PrashanthCorp** [comment]
I didn't know it was fixed. I just put it down for documentation. Good to know. :)

**Comment by EricJizbaMSFT** [comment]
Yep sounds good - better safe than sorry
