### ISSUE TITLE
Mongo DB document nodes are listed by _id

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#261]
The label on a Mongo DB document node uses the procedurally generated _id rather than the id that the user specifies.  I'm not sure if this classifies as a bug, but I thought it was worth mentioning.

**Comment by PrashanthCorp** [comment]
id's aren't unique, _id is unique. 

_id is less readable. 

We might have to discuss this in the next stand-up.

**Comment by EricJizbaMSFT** [comment]
Closing as won't-fix. We're consistent with the portal
