### ISSUE TITLE
Updating a mongo collection does not add/remove IDs from explorer

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#262]
If you open a Mongo DB collection and add or delete a document and then update the collection, the data does not persist.

**Comment by PrashanthCorp** [comment]
Can you define what you mean by the data not persisting? 

If you refresh the collection node, it shows up to me.

**Comment by PrashanthCorp** [comment]
Looks like a dupe of #312

**Comment by EricJizbaMSFT** [comment]
This was by-design when originally implemented. However, it's a feature we could consider adding
