### ISSUE TITLE
Performing some operations during no Internet connection results in no error message

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#273]
E.g. try deleting a graph with WiFi turned off.

ErrorData.message = "", so vscode ignores us trying to show the blank error message.

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford I had to fix [this unrelated bug](https://github.com/Microsoft/vscode-cosmosdb/pull/333) first, but I see this message:

![screen shot 2018-01-22 at 2 54 15 pm](https://user-images.githubusercontent.com/11282622/35248971-fce7a116-ff84-11e7-9616-ffd3fd0c00df.png)

Was this fixed as a part of your error parsing changes?

**Comment by StephenWeatherford** [comment]
This is for graph?  Should be pointing to graphs.azure.com.

**Comment by EricJizbaMSFT** [comment]
I was deleting a graph - which should _**not**_ be a graph-specific operation, correct? I think the endpoint is correct
