### ISSUE TITLE
Theme does not change until rerender

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#298]
Not sure if this is a bug or just a limitation of the HtmlPreview window, but when you change themes, the colors do not update until you change tabs.

**Comment by nturinski** [comment]
![image](https://user-images.githubusercontent.com/5290572/34060526-bd80caf0-e1a9-11e7-9c7c-b90ca39fe92e.png)

Also is this supposed to be white now??  It starts as black (when querying) and then swaps to white.

**Comment by StephenWeatherford** [comment]
Would be a minor pain to fix.
