### ISSUE TITLE
Mongo Language Server output channel keeps popping up

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-cosmosdb#30]
The Mongo Language Server output channel is opened quite frequently when using the extension. I simply connected to a cosmos mongodb and then this pops open

![image](https://user-images.githubusercontent.com/1487073/29797497-3ac48b6c-8c0c-11e7-9474-bb7045cac860.png)

I don't know if it is coming from the extension or the languageserver module, it seems like the latter. For end users, none of this is very actionable, so not forcing it open would be the best experience.

**Comment by EricJizbaMSFT** [comment]
That's related to #28 and fixed in #29

**Comment by EricJizbaMSFT** [comment]
Thanks for filing the issue though :) Better safe than sorry

**Comment by chrisdias** [comment]
my point is that the output channel keeps coming up.  is that part fixed, or the error itself (which is goodness) ?

**Comment by EricJizbaMSFT** [comment]
I'm not quite sure I understand what you're asking. The error itself is fixed, so the output channel shouldn't pop up (unless some other error is occurring). I just merged the fix, so you can try it from master close this issue as you see fit

**Comment by chrisdias** [comment]
ok, i see the fix in for the error. my point was the fact that the output pane keeps popping to the foreground when i dont think it should.  i'll reopen with a better repro.
