### ISSUE TITLE
When specifying storage account for AzureWebJobsStorage, extension doesn't allow you to create a new one

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#301]
1) create new function
2) select e.g. Blob Trigger
3) Asks for AzureWebJobsStorage
4) Choose Select Storage Account
!) Only shows existing accounts, doesn't allow creating new one

**Comment by EricJizbaMSFT** [comment]
Closingt his since it's a functions bug. Copied it over here: https://github.com/Microsoft/vscode-azurefunctions/issues/139
