### ISSUE TITLE
Graph command input box does not support Ctrl+A, and has limited memory

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#303]
Repro steps : 
1. Create graph, `names` with partitionKey 'name'
2. Execute : 
`	g.addV('label','employee','id','s','name','Stephen').addV('label','employee','id','e','name','Eric').addV('label','manager','id','j','name','Jing').addE("manages").to(g.V("s")).outV().addE("manages").to(g.V("e")).inV().addE("knows").to(g.V("s")).inV().addE("knows").to(g.V("e"))
`
in the command box. 
3. Place a cursor on the box, and try 
a) Ctrl+A
b) Delete everything with Ctrl+Backspace. Then Ctrl+Z -> undo only works so much.

**Comment by StephenWeatherford** [comment]
We expect to switch to using the data explorer.
