### ISSUE TITLE
Two items are focused with highlight using keyboard

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#306]
Repeo Steps:
1. Make sure one item is focused.
2. Use keyboard to focus on another item.

Expect:
Only one item is focused with highlight.

Actual:
Two items are focused with highlight. --Please see the below attachment:
![two_items](https://user-images.githubusercontent.com/34729022/34244345-d3066668-e65f-11e7-96fb-61f8a4f791bb.png)

**Comment by PrashanthCorp** [comment]
This seems to be VSCode's behavior. Marking this as external. 

Note: You can get as many as 3 focused items
![triplefocus](https://user-images.githubusercontent.com/30420973/34496977-7888ee86-efb0-11e7-935c-ca3bf209742b.png)
