### ISSUE TITLE
No way to get the all prompt information

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#307]
Repro Steps:
1. Create a new gragh for Graph database.
2. Verify the prompt notification when inputting throughput capacity.

Expext:
We can get all information when putting the cursor to the prompt notification.

Actual:
No way to get all the prompt information. --Please see the below attachment:
![prompt](https://user-images.githubusercontent.com/34729022/34243213-aec614b0-e65a-11e7-88b8-656af1ef9f86.png)

**Comment by PrashanthCorp** [comment]
The text in brackets is boilerplate text from VSCode - 
Press Enter to confirm or Escape to Cancel. 

I don't think this would affect a lot of users.

**Comment by whiskeyjay** [comment]
https://github.com/Microsoft/vscode/issues/33181

**Comment by v-xuanzh** [comment]
Cose this issue. And we will continue to track the issue[#33181](https://github.com/Microsoft/vscode/issues/33181)
