### ISSUE TITLE
The graph/collection tab isn't auto closed after deleting it in the left tree view

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#308]
Repro Steps:
1. Choose a Cosmos DB account and expand it.
2. Create a graph/collection under database node.
3. Make sure the new graph/collection tab is opened.
4. Delete the graph/collection in the left tree view.

Expect:
The opened graph/collection tab is auto closed.

Actual:
The opened graph/collection tab isn't auto closed.

**Comment by EricJizbaMSFT** [comment]
Unfortunately VS Code doesn't provide an api where extensions can close tabs. We could potentially bother them to provide an api, but I don't think this bug is worth it. Closing as won't-fix
