### ISSUE TITLE
Double clicking a parent node can't expand it

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#309]
Repro Steps:
1. Double click one parent node.
2. Check whether it is can be expanded or not.

Expect:
The parenet node can be expanded.

Actual:
The parenet node can't be expanded.

More info:
Press 'Enter' also can't expand the parent node.

**Comment by StephenWeatherford** [comment]
@v-xuanzh I don't see the issue.  Single-clicking on a node will expand it, and pressing RIGHT-ARROW (not ENTER) will also expand it.  If you still see an issue, please provide more details, thanks.

**Comment by v-xuanzh** [comment]
For VS, three ways to expand one node:
1. Single click on the node.
2. Press Right-Arrow.
3. Double-click the node.
So we think it should be expanding after double-clicking on a node.

**Comment by StephenWeatherford** [comment]
@v-xuanzh This is actually VSCode behavior and we can't change it.
