### ISSUE TITLE
Show creation process as a dummy node in explorer

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-cosmosdb#31]
testing off of the ej/create branch, so may already be fixed.

I created a new cosmosdb and after it was created (5min?) i did a "refresh" in the explorer, but the new database would not show up.

i confirmed i did not have any subscription or resource group filtering going on.

If i did a "reload window", the new db would show up.

**Comment by EricJizbaMSFT** [comment]
How are you determining if it was finished creating? Sometimes the portal will display the resource even if it's not "done" creating

Did you wait until the little status bar message at the bottom of VS Code disappeared? The status that says "Creating CosmosDB Account"?

**Comment by chrisdias** [comment]
i was looking in the portal, waiting until the point where I could see the map :).  

Yes, the status bar message in VS Code was gone.

**Comment by EricJizbaMSFT** [comment]
I can't repro this with the latest from master. @chrisdias do you want to try again?

Either way we need to make it more obvious when a resource is being created. We've discussed showing the node in the explorer and adding some icon or text to indicated that it's being created. Should we "re-purpose" this issue to implement that functionality?

**Comment by chrisdias** [comment]
i think we need a better notification system in VS Code.  but, in the meantime, yes adding a "working..." node or something like that in the explorer makes great sense.  I will update title.

**Comment by PrashanthCorp** [comment]
@chrisdias Currently, there is a 'working...' status on the status bar message. 
I couldn't repro this - the database appears in the tree as soon as it's created. Would a notification on completion help?

**Comment by EricJizbaMSFT** [comment]
Yes there is a `working...` status in the status bar, but it's hard to see and the user can hide their status bar. This bug it to create a 'working...' node right in the Cosmos DB explorer

**Comment by chrisdias** [comment]
I like the suggestion of creating the "working..." node. We should adopt this pattern across all extensions.

**Comment by PrashanthCorp** [comment]
A side-question : If we do implement this, are we removing it from the status bar?
