### ISSUE TITLE
No 'Open' action displays for a graph/document

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#310]
Repro Steps:
1. Choose a Cosmos DB account and expand it.
2. Create a graph/document under one database node.
3. Right click the new graph/document and check the context menu.

Expect:
There is 'Open' action in the context menu.

Actual:
There is no 'Open' action in the context menu. --Please see the below attachment:
![noopen](https://user-images.githubusercontent.com/34729022/34244076-be9f2b70-e65e-11e7-8c0a-b5f75b800e56.png)

**Comment by PrashanthCorp** [comment]
As per discussion with @fiveisprime, moving this to the future milestone. This is low priority at the moment.

**Comment by StephenWeatherford** [comment]
This is VS Code behavior. Just selecting the item will open it, there's no menu for it.
