### ISSUE TITLE
Add tslint

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#316]
Here's my thoughts on how best to split it up:
[x] 1. [MOVED] Add basic typescript rules (see settings like 'noUnusedLocals' [here](https://github.com/Microsoft/vscode-azurefunctions/blob/master/tsconfig.json))
[x] 1. Add basic tslint (see lint script [here](https://github.com/Microsoft/vscode-azurefunctions/blob/master/package.json#L367))
[x] 1. Add microsoft contributed rules (see [here](https://github.com/Microsoft/vscode-azurefunctions/blob/master/tslint.json))

Remaining rules:
[ ] P1: no-unsafe-any
[ ] P1: strict null checking
[ ] no-floating-promises
[ ] promise-function-async - [Stephen] suggest grandfather in existing code (disable per line) and turning on
[ ] no-string-literal   - [Stephen] suggest turn this off, it's mostly for localization
[ ] member-access   - [Stephen] I think can auto-fix

**Comment by StephenWeatherford** [comment]
> Adding a checklist of remaining rules. Please suggest removing some rules or changing the ordering. I want to decide on what rules to enable for 0.10.0 before we get around to it.

Moved to description so we don't have to search through whole issue.  Added suggestions.

**Comment by EricJizbaMSFT** [comment]
Gonna close this as fixed after merging https://github.com/microsoft/vscode-cosmosdb/pull/1316, https://github.com/microsoft/vscode-cosmosdb/pull/1346, and https://github.com/microsoft/vscode-cosmosdb/pull/1380. Always more we could do, but don't think it's worth having the issue open any more.
