### ISSUE TITLE
No confirmation notification displays when detaching a Cosmos DB account

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#320]
Repro Steps:

1. Choose a Cosmos DB account and attach it.
2. After attaching successfully, detach this account.

Expect:
A confirmation notification displays. 

Actual:
No confirmation notification dispay.

**Comment by EricJizbaMSFT** [comment]
We generally use confirmation messages for destructive actions (aka actions that you can't 'undo'). In this case, you're not deleting the account and you can easily 'undo' the action by re-attaching the account. Closing as by-design
