### ISSUE TITLE
Pressing 'Delete' key doesn't work

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#321]
Repro steps:

1. Focus on one datebase.
2. Press 'Delete' key.

Expect:
The below confirmation notification pops up.
![untitled picture](https://user-images.githubusercontent.com/34729022/34761302-190f15d0-f5db-11e7-9421-3126d91a7aad.png)

Actual:
'Delete' key doesn't work.

**Comment by StephenWeatherford** [comment]
None of the other CosmosDB items support the Delete key.  Given that you won't be deleting graphs or database very frequently and that it's an undo-able step, I'm fine with requiring users to right-click and "Delete".

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT fixed the issue that the context menu Delete doesn't work.
