### ISSUE TITLE
Keep 'Query...' more than 20 mins after excuting g.V()

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#322]
Repro steps:

1. Open one graph.
2. Input g.V() in query testbox of this graph explorer.
3. Click 'Excute'.

Expect:
Under Graph, you should see the following vertices and edges.
![2](https://user-images.githubusercontent.com/34729022/34761570-437178bc-f5dc-11e7-9b3a-6e71040e9f0a.png)

Actual:
Keep 'Query...' under 'Graph/JSON' more than 20 mins after excuting g.V().
![1](https://user-images.githubusercontent.com/34729022/34761523-14eeb3ce-f5dc-11e7-95fb-43c6f6902f58.png)

**Comment by StephenWeatherford** [comment]
@v-xuanzh Does this still repro?  Can you query see the graph in the Azure portal?

**Comment by bryceg** [comment]
I seem to have the same problem, queries that work in Azure portal are just "querying..." forever in this client.  Also seems to be no way to cancel or have it time out at least.

**Comment by StephenWeatherford** [comment]
@bryceg Bryce - I've never seen this (if anything, it's been more reliable than the portal for me).  Does it work for a simple g.V() query?  What about g.V().limit(1) or g.V().count()?

BTW, you don't need to cancel, just execute a new query.

**Comment by bryceg** [comment]
I've tried all those on different graph database instances, and I get the same result across all of them of "Querying...".  They all work fine in the portal though.
Is there any output/debug information I can look for and provide?  I do have > 5k verticies if that is potentially an issue.

**Comment by StephenWeatherford** [comment]
I have a repro, am investigating...

**Comment by StephenWeatherford** [comment]
@bryceg Thanks for bringing this to our attention!  We expect to release a new version with the fix on Thursday.  (BTW, this was caused by a change in Azure that occured when graph GA'ed in December, such that the gremlin endpoint for graph accounts created in the portal since GA are different than those created before GA, or created with the current version of the extension.)

**Comment by v-xuanzh** [comment]
@StephenWeatherford It displays the error _**'Could not find a valid gremlin endpoint for graph_name'**_ under Graph/JSON after clicking 'Execute'. Could you help to take look it?
![error](https://user-images.githubusercontent.com/34729022/35428658-4476d7c8-0268-11e8-9b3b-f46a5714355e.PNG)

**Comment by StephenWeatherford** [comment]
I've got one graph account that has this behavior as well.  I think it's an issue on the Azure side, and I've engaged them to help.

**Comment by StephenWeatherford** [comment]
@v-xuanzh Does this happen with only this single graph account?

**Comment by v-xuanzh** [comment]
@StephenWeatherford Yes, this error only occurs for graph account.

**Comment by v-etzha** [comment]
I got Gremlin Query Execution Error when attempting to add vertices and edges to the graph using the following query:
g.addV('label','employee','id','s','name','Stephen').addV('label','employee','id','e','name','Eric').addV('label','employee','id','j','name','Jing').addE("manages").to(g.V("s")).outV().addE("manages").to(g.V("e")).inV().addE("knows").to(g.V("s")).inV().addE("knows").to(g.V("e"))
![image](https://user-images.githubusercontent.com/34734408/36626680-034abd66-1972-11e8-98de-dc7957cbb104.png)

**Comment by StephenWeatherford** [comment]
This means you specified the wrong partition key when you created the graph. Please see test instructions. Whatever partition key you specify must be given a property value when you add a vertex with addV. The above query assigns a value to the "name" property, which is what the partition key should have been when creating the graph.

**Comment by StephenWeatherford** [comment]
If you get the error "Could not find a valid gremlin endpoint for graph_name", it means you're using an old CosmosDB graph account that is no longer compatible with the portal. Try creating a new one using the current version of the extension.  See #352.
