### ISSUE TITLE
Create a collection successfully with an existing name

### ISSUE THREAD

**Issue by v-yangyc** [microsoft/vscode-cosmosdb#328]
Repro Steps:
1. Right click a database.
2. Create a collection with an existing collection name.
3. Verify whether an error dialog pops up or not.

Expect:
Error occurs after pressing Enter.

Actual:
The created collection displays successfully. See the below attachment:
![actual](https://user-images.githubusercontent.com/34733307/35131857-5f56d9a6-fcc0-11e7-8b01-b76626732893.PNG)

More info:
The created collection will disappear after refreshing.

**Comment by neelip** [comment]
Currently, SQL displays an error message with creating collection with existing collection name. Mongo doesn't create the duplicate collection but doesn't show an error.
