### ISSUE TITLE
The error displays in output window is inconsistent with the prompt when creating a graph  

### ISSUE THREAD

**Issue by v-yangyc** [Microsoft/vscode-cosmosdb#330]
Repro Steps:
1. Create a graph.
2. Input a valid graph name and partition key then press Enter.
3. Input a valid throughput capacity value like "1004" then press Enter.

Expect:
The error displays in output window is consistent with the prompt. 

Actual:
The error displays in output window is inconsistent with the prompt. See the attachment below.
![compare](https://user-images.githubusercontent.com/34733307/35143620-010ce428-fcfa-11e7-9fa1-2a9f01b875d0.PNG)

**Comment by StephenWeatherford** [comment]
For "unlimited" capacity collections and graphs, which is all we currently support, the minimum is 1000 (you can verify on the portal).  So we're doing the right thing and you can ignore what the Azure error message is saying.
