### ISSUE TITLE
Can't delete a DocDB document

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#347]
![screen shot 2018-01-25 at 1 30 28 pm](https://user-images.githubusercontent.com/11282622/35413330-ec8013fc-01d3-11e8-94ea-640b3c75b451.png)

**Comment by EricJizbaMSFT** [comment]
It's not worth squeezing this into 0.4.0 - users can workaround the issue by deleting it in the portal

**Comment by StephenWeatherford** [comment]
Moved to 0.6.0.

**Comment by PrashanthCorp** [comment]
It looks like I've fixed this via #597. And #544 looks like a dupe of this. 

@EricJizbaMSFT  let me know what the scenario is, I'll verify if it still repros.

**Comment by EricJizbaMSFT** [comment]
I don't remember the exact steps I did to get to this, but yes it looks covered by the PR/issue you mentioned
