### ISSUE TITLE
Delete accounts in extension

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-cosmosdb#348]
I'd like to be able to delete my account through the extension instead of having to go through the portal.

**Comment by nturinski** [comment]
I tried to delete a CosmosDB MongoDB account that I just created.

Also, account name is not in "quotes" like we normally wrap label names in.

![image](https://user-images.githubusercontent.com/5290572/36995446-efa382ea-2068-11e8-8644-98247b2784ba.png)

![image](https://user-images.githubusercontent.com/5290572/36995466-fb7c3d1e-2068-11e8-90dd-05f3ed25d8d4.png)

**Comment by nturinski** [comment]
After this error, it ended up deleting anyway.  Not sure what's going on here.

**Comment by StephenWeatherford** [comment]
Sounds like simple Azure behavior, probably just needed to wait a while before trying to delete after creation.
