### ISSUE TITLE
Make selecting subscriptions more discoverable

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-cosmosdb#351]
from marketplace review: 

Rating: 5/5
Nice work! Please add some docs on how to filter the Subscriptions once you sign in with an Azure account. I discovered it after clicking on my account name on the lower part of the screen, but being a user with lots of subscriptions, it was important to know how to "clean up" the list.

**Comment by StephenWeatherford** [comment]
@fiveisprime, @chrisdias, @ealsur 
After discussing with Matt, I've done two things in the Storage extension, and will repeat for the others:

1) Added a "key" button on subscription nodes (tooltip: "Select Subscriptions...")
![image](https://user-images.githubusercontent.com/6913354/36118118-c9972abc-0ff0-11e8-8e0c-947fc4e2778e.png)

2) Added the following information to the readme:
![image](https://user-images.githubusercontent.com/6913354/36118085-b084aa72-0ff0-11e8-9fa7-977c58e61365.png)

Does this suffice?  Thanks!

**Comment by fiveisprime** [comment]
Yes! I love it :shipit:
