### ISSUE TITLE
It doesn't show conflict if creating resource group using an existing name

### ISSUE THREAD

**Issue by v-etzha** [Microsoft/vscode-cosmosdb#356]
Repro Steps:

1. Click "Create Account" button.
2. Find an existing resource group.
3. Select the subscription where the existing resource group is.
4. Select "Create Resource Group".
5. Type the name of the existing resource group.

Expect: 
It shows "Resource Group name XXX already exists."
![image](https://user-images.githubusercontent.com/34734408/35726151-c80ace56-083e-11e8-8a7c-d6b3b9a5da13.png)

Actual:
It doesn't show the conflict.
![image](https://user-images.githubusercontent.com/34734408/35726183-e748d5ec-083e-11e8-9e7a-81d73d49ea00.png)

**Comment by EricJizbaMSFT** [comment]
This was fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/412
