### ISSUE TITLE
DocumentDB: Allow setting the partition key value during document creation

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#357]
CosmosDB doesn't allow modifying the partition key once a document is created.

**Comment by StephenWeatherford** [comment]
https://github.com/Microsoft/vscode-cosmosdb/issues/347.

**Comment by StephenWeatherford** [comment]
We need to either allow them to enter the partition key while creating the document, or allow them to change it afterwards (a la #358)

**Comment by PrashanthCorp** [comment]
Closing via #638
