### ISSUE TITLE
Change the gallery banner color to be higher contrast

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#359]
Right now it's blue on blue:
![screen shot 2018-02-07 at 9 17 44 am](https://user-images.githubusercontent.com/11282622/35930877-f578fece-0be7-11e8-851f-e028526b68c2.png)

Not sure what the color should be, but we control this in package.json here: https://github.com/Microsoft/vscode-cosmosdb/blob/master/package.json#L12

**Comment by fiveisprime** [comment]
Here's what the [service page ](https://azure.microsoft.com/en-us/services/cosmos-db/) uses 🤷‍♀️ 

![image](https://user-images.githubusercontent.com/1186948/35931247-fb566498-0be8-11e8-84c9-0e08efc06cf6.png)

**Comment by StephenWeatherford** [comment]
@fiveisprime Are you handling this one?

**Comment by fiveisprime** [comment]
Sure, I'll figure something out.
