### ISSUE TITLE
Breaking Change regarding the usage of keytar

### ISSUE THREAD

**Issue by alexandrudima** [Microsoft/vscode-cosmosdb#364]
Hi,

I'm working on VSCode and I am trying to enable the usage of [ASAR for VSCode](https://github.com/Microsoft/vscode/issues/36997). This can improve the startup time of VSCode by [up to 5%](https://github.com/Microsoft/vscode/pull/41353). We are at a point where we are pursuing even such small gains...

I have found that your extension makes an assumption about the disk layout of VSCode's `node_modules`:
```
ms-azuretools.vscode-cosmosdb/out/src/tree/AttachedAccountsTreeItem.js:35
  this._keytar = require(`${vscode.env.appRoot}/node_modules/keytar`);
```

To make your extension entirely compatible with a distribution of VSCode that uses ASAR, and to make your extension work with both VSCode stable and VSCode insiders, you will need to try to load from two paths... Something like the following:

```js
function getNodeModule(moduleName) {
  try {
    return require(`${vscode.env.appRoot}/node_modules.asar/${moduleName}`);
  } catch(err) { }
  try {
    return require(`${vscode.env.appRoot}/node_modules/${moduleName}`);
  } catch(err) {}
  return null;
}
```

I plan to release the changes to Insiders this week, such that the Insiders build on Friday, 23.02.2018, will contain the ASAR packing of node modules. In the meantime, I have created custom builds that include this change if you wish to test your extension against a VSCode version which contains these changes:
- [Win 64](https://az764295.vo.msecnd.net/insider/64ee4f4955c99beea32fbf7bb46a0cd847cff434/VSCode-win32-x64-1.21.0-insider.zip)
- [Win 32](https://az764295.vo.msecnd.net/insider/64ee4f4955c99beea32fbf7bb46a0cd847cff434/VSCode-win32-ia32-1.21.0-insider.zip)
- [macOS](https://az764295.vo.msecnd.net/insider/64ee4f4955c99beea32fbf7bb46a0cd847cff434/VSCode-darwin-insider-unsigned.zip)
- [Linux 64](https://az764295.vo.msecnd.net/insider/64ee4f4955c99beea32fbf7bb46a0cd847cff434/code-insider-1.21.0-1519035389_amd64.tar.gz)
- [Linux 32](https://az764295.vo.msecnd.net/insider/64ee4f4955c99beea32fbf7bb46a0cd847cff434/code-insider-1.21.0-1519035388_i386.tar.gz)

**Comment by EricJizbaMSFT** [comment]
@chrisdias @chrmarti why are we referencing VS Code's node_modules? Why don't we follow the normal pattern where we add it to our package.json and reference it from our extension's node_modules directly? I'm asking you guys since it was added in this PR: https://github.com/Microsoft/vscode-cosmosdb/pull/41

cc: @StephenWeatherford

**Comment by StephenWeatherford** [comment]
Ah, I assumed we were referencing our own.  Good question.

**Comment by chrmarti** [comment]
Keytar is a native module, so you'd have to ship one version per architecture and bitness (currently 5) and these would need to be rebuilt when we update to a new V8 with a new version of Electron. Having keytar built as part of VS Code does that for us.

**Comment by alexandrudima** [comment]
I have submitted a PR to make the adoption - https://github.com/Microsoft/vscode-cosmosdb/pull/369

**Comment by EricJizbaMSFT** [comment]
@alexandrudima when will this be going into stable?

**Comment by alexandrudima** [comment]
@EricJizbaMSFT With the February release - https://github.com/Microsoft/vscode/issues/43361

**Comment by alexandrudima** [comment]
Thank you!
