### ISSUE TITLE
Scapbook find caused error "query selector must be an object"

### ISSUE THREAD

**Issue by jtuttas** [Microsoft/vscode-cosmosdb#365]
Hello,
ok I'am new in mongodb but I whant to teach my students (I'am a teacher) how to use MongoDB (as an example for a nosql database).

So why the command 'db.schueler.find({"name": "tuttas"})' in the Srapbook cause the error "query selector must be an object" !?! in the shell mongodb.exe everythink workes like expected, but I what to use the Scapbook in VS Code as the shell!

Looking forward to hear from you.

best regrads

**Comment by fluxens** [comment]
same problem as @jtuttas . every query which has a query selector fails. Only db.<collection>.find() with empty selector works.
