### ISSUE TITLE
Failed to update mongo document after closing and re-opening VS Code multiple times

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#370]
1. Open a mongo document
1. Close vscode
1. Open vscode
1. Open a mongo collection
1. Close vscode
1. Open vscode
1. Try to update the mongo _document_

Expected:
It works

Actual:
It fails with this error:
![screen shot 2018-02-23 at 2 57 17 pm](https://user-images.githubusercontent.com/11282622/36620843-df588fd2-18a9-11e8-857d-efc54e3596dd.png)

I believe it's because we change the persistence to only include the mongo collection and then we lose persistence of the mongo document.

**Comment by StephenWeatherford** [comment]
Moved to 0.6.0.
