### ISSUE TITLE
An error occurs when attempting to create an account

### ISSUE THREAD

**Issue by v-etzha** [Microsoft/vscode-cosmosdb#371]
Repro Steps:
1. Click "Create Account" button.
2. Select a subscription.
3. Select a resource group.
4. Type a name for the account.
5. Select an API.
6. Select a location.

Expected:
The account is created successfully.

Actual:
An error occurs.
![image](https://user-images.githubusercontent.com/34734408/36628186-621df67c-1987-11e8-8653-dba831ce9c85.png)

**Comment by StephenWeatherford** [comment]
This is Azure behavior. Try again.
