### ISSUE TITLE
“Cannot convert undefined or null to object” occurs after selecting subscription or saving files

### ISSUE THREAD

**Issue by v-etzha** [Microsoft/vscode-cosmosdb#372]
Repro Steps:
1. Press F1 on keyboard.
2. Enter "Azure: Select Subscriptions".
3. Select one or more subscriptions.

Expected:
No error occurs.

Actual:
Error occurs.
![image](https://user-images.githubusercontent.com/34734408/36627996-4047257e-1986-11e8-8872-e5d369bd09b4.png)

**Comment by Shurelia** [comment]
I am getting this as well. This error appears every time I save a file that had changes in the editor window, while signed in. Signing out of my azure account fixes the issue.
Ext version 0.5.0, vscode version 1.20.1. Please @ me if I can provide any more information.

**Comment by johnpapa** [comment]
getting the same error

![image](https://user-images.githubusercontent.com/1202528/37556105-82a6383c-29c7-11e8-9157-faa96f75f7e3.png)


cc @fiveisprime

**Comment by StephenWeatherford** [comment]
I've gotten this while saving files.  Haven't found a consistent repro though.

**Comment by StephenWeatherford** [comment]
Thanks for reporting this, it was fixed in v0.5.1 released a couple of days ago.
