### ISSUE TITLE
Add commands to create/persist new stored procedure

### ISSUE THREAD

**Issue by chrisdias** [Microsoft/vscode-cosmosdb#38]
Create “New” artifacts (New Stored Procedure, New User Defined Function, New Trigger)

These would create a new document locally and on save would persist to the CosmosDB

I’m not actually sure an extension can intercept the “save” operation and persist someplace else, we would need to look and see if we need a new API.

**Comment by EricJizbaMSFT** [comment]
There's definitely `onWillSaveTextDocument` and `onDidSaveTextDocument` [events](https://code.visualstudio.com/docs/extensionAPI/vscode-api) we can subscribe to. We might not be able to block it from saving locally, but we can certainly persist it to Cosmos DB in addition to locally

**Comment by EricJizbaMSFT** [comment]
Re-purposing this to just be stored procedures. We can handle UDFs and Triggers in a separate issue

**Comment by PrashanthCorp** [comment]
Fixed via above PR.
