### ISSUE TITLE
Mongo ids displayed in the tree give no information

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#381]
Today the user sees a bunch of ids like this:
![screen shot 2018-03-05 at 8 59 16 am](https://user-images.githubusercontent.com/11282622/36988336-7f66f6f2-2053-11e8-98c1-e59ae2663832.png)

But those aren't helpful at all. I see a few ways to fix (which are not mutually exclusive):
1. Create a setting so that users can specify the property to display in the tree
1. When the user creates a new document, use the value they enter for the id as the "_id" property instead of "id".  If I create a document with id specified as "exampleid", this is what I get:
```
{
  "_id": "5a9d7668dcb45709671aa200",
  "id": "exampleId"
}
```

We could be using "_id" - I know its possible since I can run this command successfully:
```
db.scores.insertOne{
    "_id": "exampleId"
})
```

**Comment by StephenWeatherford** [comment]
Show id if available.

**Comment by adwaitv** [comment]
Ideally, this could be made configurable per collection.
For example, one might want to see `name` or `username` for a `users` collection or something like a `slug` for a  `posts` collections instead of `_id`.

**Comment by StephenWeatherford** [comment]
@adwaitv Does it need to be configurable per collection (which makes for more complicated settings), or would a simple array of ordered properties work well enough, e.g.:

  "cosmosdb.docdb.displayproperties": ["slug", "username", "name", "id", "_id"]

where the first property that exists on each document is the one that is displayed?  Thanks.
