### ISSUE TITLE
Can only run the first command in a Mongo Scrapbook on Windows

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#386]
As far as I can tell, this only repros on Windows

Repro steps:
1. Connect to a DB
1. Open a mongo scrapbook
1. Add two commands:
```
db.test.find()
db.test.findOne()
```
1. Put your cursor in the second command
1. Execute command

Expected: Results of findOne are displayed
Actual: Results of find are displayed

**Comment by EricJizbaMSFT** [comment]
This repros on the old Mongo extension, too. Must've always been a problem

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Can you repro and verify if it only repros on Windows?
