### ISSUE TITLE
Intellisense in mongo scrapbook silently disappears if one command is mal-formed

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#392]
If you have one command that is malformed in your scrapbook, then none of the intellisense works. We should ideally be more robust so that one command doesn't affect the rest of the file, but we should at least display an error to the user somehow

For example, add this command to your scrapbook:
```
db.food.find( { "qty": { "$gt": 3 } }, { "item": 1, "qty": 1 } )
```

**Comment by StephenWeatherford** [comment]
Related to the error throwing?

**Comment by PrashanthCorp** [comment]
Closing via #531
