### ISSUE TITLE
Can't create a document in a Mongo DB with shard keys

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#393]
Create a MongoDB via the portal. Specify Unlimited and give a shard key. From the extension, try to add a document. 

Error: "document does not contain shard key"

**Comment by PrashanthCorp** [comment]
It looks like the shard key set in the portal does not show up when querying `getShardDistribution()`. The level of support for this on cosmos needs investigation.
