### ISSUE TITLE
Error: Timed out executing db.collection.distinct("field1.field2"<missing ')'>

### ISSUE THREAD

**Issue by roxberry** [Microsoft/vscode-cosmosdb#397]
Running this in scrapbook:

db.collection.distinct("field1.field2", {"field1.field2": { $regex: "searchString*", $options: "i" }})

Error: Timed out executing db.collection.distinct("field1.field2"<missing ')'>

Works in Mongo cli:

MongoDB shell version v3.4.9
MongoDB server version: 3.6.2

**Comment by StephenWeatherford** [comment]
Dupe of #383

**Comment by StephenWeatherford** [comment]
FYI, we released 0.6.0 with this fix a couple of days ago.  Please let us know if you run into troubles.  I expect there are still specific scenarios where things might not work.  Thanks.
