### ISSUE TITLE
The command 'vsce package' fails when creating .vsix file for cosmosdb extension

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/vscode-cosmosdb#398]
## Steps to reproduce
1. Clone the code for cosmosdb and run the command 'npm install' successfully.
2. Run the command 'vsce package', verify whether it runs successfully and create the .vsix file.

## Expected  behavior
The command runs successfully and create the .vsix file.

## Actual behavior
The command failed. You can see the screenshot below.
![vscepackage](https://user-images.githubusercontent.com/12556995/37271510-1c39f412-25cb-11e8-939d-c75d5bea1a8f.png)

## More Info:
1. node version --v8.10.0， npm version --5.7.1.
2. We tried to delete entire 'node-modules' and package-lock.json manually, then reinstall everything(with npm install) according to known issue [#165](https://github.com/Microsoft/vscode-vsce/issues/165). These 2 items (node-modules, package-lock.json )auto generated again after running ‘npm install’. In this case, it goes into a loop.

**Comment by StephenWeatherford** [comment]
Thanks.
