### ISSUE TITLE
Max number of docs is arbitrarily limited to 20

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#4]
We should either provide a 'load more' option or let the user configure how many docs they want to retrieve

**Comment by PrashanthCorp** [comment]
My initial thought was to use the globalState memento, but it might not be easy for the user to update their preference. 

I also see a use case for [user settings](https://code.visualstudio.com/docs/extensionAPI/extension-points#_contributesconfiguration). We set a default, and the user can later update it to their liking. 

Your thoughts @EricJizbaMSFT @whiskeyjay?
