### ISSUE TITLE
[Question] Allow using mongo shell from a Docker container 

### ISSUE THREAD

**Issue by lostintangent** [Microsoft/vscode-cosmosdb#40]
Is there a way to configure the scrapbook to use the `mongo` binary from a Docker container, instead of needing to install it directly on your development machine? If not, it would be cool if this was (easily) possible.

**Comment by PrashanthCorp** [comment]
Hi @lostintangent, 
Another user has a use case at #311 that could be of help. Let us know whether that works for you!

**Comment by StephenWeatherford** [comment]
@lostintangent Closing due to lack of response.  Please feel free to re-open if Prashanth's suggestion does not work for you.  Thanks for using the extension!
