### ISSUE TITLE
Display 'The results cannot be displayed visually. Please see the JSON tab for the detailed results'

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#403]
Repro steps:
1.Open one graph.
2.Input g.V() in query testbox of this graph explorer.
3.Click 'Execute'.

Expect:
Under Graph, you should see the following vertices and edges.
![expect](https://user-images.githubusercontent.com/34729092/37388852-f2b3379e-2759-11e8-8a62-55d6ac2cfb9d.png)

Actual:
Display 'The results cannot be displayed visually. Please see the JSON tab for the detailed results'.
![1-1](https://user-images.githubusercontent.com/34729092/37388845-ea886080-2759-11e8-8739-0e0278d6f778.png)

**Comment by StephenWeatherford** [comment]
This means the graph is empty (see #237, which I am fixing). Please check your repro steps to understand why your graph is empty. Thanks.
