### ISSUE TITLE
Feature request: Create document(s) from existing file(s)

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-cosmosdb#404]
Would love to be able to right click on one or more json documents in explorer and insert them into a specified collection in a database that I'm already connected to. Either in the context menu for the files, or if the file is open by right clicking in the editor the way you can with a  doc that came from the db.

![image](https://user-images.githubusercontent.com/5007120/37423238-b86cd402-2793-11e8-897c-a569c1f6f087.png)

**Comment by StephenWeatherford** [comment]
What about partition keys?

**Comment by julielerman** [comment]
Pop up a dialog to specify the partition key for the doc(s) being imported.

Also, when I use the add new document I'm asked for an ID and no partition key so I'm not sure how that's different.

**Comment by PrashanthCorp** [comment]
Fixed via #831
