### ISSUE TITLE
An error occurs when querying for large graphs

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#417]
Repro Steps:
1.  Attach to the following graph database: "AccountEndpoint=https://stephwe-graph.documents.azure.com:443/;AccountKey=IxS7rBql7GULACAv2xRH5tOdO5luqCZXb3AZJcv5NPtsJiFdZAJlw0WwEp4Ndw2qWXZqsSyDiJ3vSdEXvoJ27w=="
2. View the following graph: **_testdata/10000x2-pk_**
3. Query for "g.V()".

Expect:
The graph displays well after querying for g.V().

Actual:
An error displays after querying for g.V() more than 6mins.
![error](https://user-images.githubusercontent.com/34729022/37703639-48c33cd0-2cee-11e8-959b-b8d18db994e7.png)

**Comment by StephenWeatherford** [comment]
Can't do anything about this, it's Azure behavior, depending on the settings on your graph. Just try again.
