### ISSUE TITLE
The created database for attached MongoDB Emulator displays under DocumentDB Emulator

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#418]
Repro Steps:
1. Install the emulator from https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator.
2. Right-click on "Attached Database Accounts" -> MongoDB.
3. Create a database under the attached Emulator.
4. Right-click on "Attached Database Accounts" -> DocumentDB.

Expect:
The created database for attached MongoDB Emulator doesn't display under DocumentDB Emulator.

Actual:
The created database for attached MongoDB Emulator displays under DocumentDB Emulator.
![same](https://user-images.githubusercontent.com/34729022/37704151-05183236-2cf0-11e8-80d0-d013c3589838.png)

**Comment by StephenWeatherford** [comment]
Won't fix for now.
