### ISSUE TITLE
Add basic typescript rules

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#421]
From #316

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/microsoft/vscode-cosmosdb/pull/518, https://github.com/microsoft/vscode-cosmosdb/pull/374, https://github.com/microsoft/vscode-cosmosdb/pull/373, and https://github.com/microsoft/vscode-cosmosdb/pull/1380
