### ISSUE TITLE
Open stored procedure in portal

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-cosmosdb#425]

**Comment by StephenWeatherford** [comment]
@fiveisprime, @jinglouMSFT The best the portal will allow is for me to open up the entire account (which we already have an Open in Portal for) and open the Data Explorer tab. From there you'd need to drill down to the DB, collection and stored procedure. Still worth doing?

![image](https://user-images.githubusercontent.com/6913354/37744779-44335dea-2d2e-11e8-9162-8cf31957c601.png)

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT's comments on this:
> IMO its more confusing than valuable if the open in portal links to the Cosmos DB Account instead of directly to the stored procedure

**Comment by StephenWeatherford** [comment]
@djlan DJ, is there a way to link directly to a stored procedure in the portal? Right now I can only find a way to link to the Data Explorer for the entire CosmosDB database.  Thanks.

**Comment by fiveisprime** [comment]
That's confusing.. if we can't deep link directly, I say we scrap this.

**Comment by StephenWeatherford** [comment]
@djlan DJ? Is there a way to link directly to a stored procedure in the portal? Right now I can only find a way to link to the Data Explorer for the entire CosmosDB database. Thanks.

**Comment by StephenWeatherford** [comment]
DJ says the portal does not support direct links, so closing.
