### ISSUE TITLE
Sometimes when creating new document via right-click on collection, user is asked to select the subscription/account/db/collection

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-cosmosdb#427]
If creatiing new document by right clicking on a collection, don't make me choose account, db and collection again.

Behavior
Expand the database explorer
Right click on a collection
Choose: create new document

Expected
Extension will know that I want to add a new document to selected collection and take me directly to dialog for specifying the ID of the new account

Actual behavior
Dialog to select/create an account
Then to select/create a db from that account
Then another to select/create a collection from that db

**Comment by EricJizbaMSFT** [comment]
@julielerman does this happen consistently for you? We have a general issue where actions from the tree sometimes don't pass in the 'context' of the tree as they should. I'm wondering if this is a unique issue or if this is part of our larger problem.

For example, when you see this bug - escape the prompts, wait a few seconds, and try the action again. I'm guessing it'll work

**Comment by julielerman** [comment]
Playing more ..closed and reopened VS Code but that forces a fresh onnection. Maybe the connection was stale even though it WAS informing me about duplicate IDs in the case where I was getting the select account/db/collection/enter ID workflow.

**Comment by EricJizbaMSFT** [comment]
Yeah for me this is an inconsistent bug that could be related to refresh or could just be a timing issue. Unfortunately that means it doesn't have a quick-fix, but definitely annoying and worth further investigation

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT @nturinski It seems like I remember someone fixing this bug (sometimes getting null node in command), is that correct?  Can't find it, though.

**Comment by EricJizbaMSFT** [comment]
Yeah I definitely reduced the number of times this will happen, but unfortunately I don't think I completely eliminated this from ever happening.

Here's the original bug: https://github.com/Microsoft/vscode-azuretools/issues/86

**Comment by StephenWeatherford** [comment]
@julielerman Julie, have you still been seeing this?  Thx.

**Comment by julielerman** [comment]
haven't tried it in a while. I will bang on it a bit. Since it was random, maybe I'll hit it...

**Comment by julielerman** [comment]
so far it's all working well...

**Comment by StephenWeatherford** [comment]
Thanks.  I'm going to go ahead and close, but please re-open if you see again.
