### ISSUE TITLE
Feature Suggestion:Modify background text in create document dialog  box where ID is needed

### ISSUE THREAD

**Issue by julielerman** [Microsoft/vscode-cosmosdb#428]
When creating a new document, the first dialog asks for an ID. If you are using GUIDs for the IDs, it would be nice to have a way to auto-generate a GUID. Perhaps even have that be a setting that can determine this as a default behavior.

**Comment by EricJizbaMSFT** [comment]
You can actually do this today by leaving the input box blank and hitting enter

That being said, I think this issue is worth keeping open to address the discoverability of the feature

**Comment by julielerman** [comment]
Aha! But I just tried that and nothing happened. When I put in an id and hit enter a new doc is created and opened in the editor window

**Comment by julielerman** [comment]
So maybe just modify the background text in the dialog box :)

**Comment by EricJizbaMSFT** [comment]
What do you mean by "and nothing happened"? Did it work for you or not? If not - what API are you using (DocDB, Mongo, etc.) and what extension version?

**Comment by julielerman** [comment]
@EricJizbaMSFT I edited the comment as quickly as I could. I was expecting the doc t open in the editor window but instead, I just had to refresh the explorer window to see the new doc. Sorry about that.

**Comment by EricJizbaMSFT** [comment]
Awesome - so you were expecting the new document to open in the editor window after you created it? We could consider that functionality as well

**Comment by StephenWeatherford** [comment]
@julielerman Does this help?

![image](https://user-images.githubusercontent.com/6913354/37794196-09266922-2dce-11e8-93be-c8cfe9494251.png)

or is this better:

![image](https://user-images.githubusercontent.com/6913354/37793946-4cbecbe4-2dcd-11e8-9401-3c7390df8872.png)

**Comment by StephenWeatherford** [comment]
> Awesome - so you were expecting the new document to open in the editor window after you created it? We could consider that functionality as well

Sounds great - #429

**Comment by julielerman** [comment]
I prefer the 2nd option. It's more clear. :) Thanks. Also, I meant to add that same other feature idea (open in editor) but had to take off for a lunch meeting! Thanks for doing that! :)

**Comment by StephenWeatherford** [comment]
Thanks for the suggestions.
