### ISSUE TITLE
Open newly created documents in the editor

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#429]
From #428 from @julielerman.

**Comment by EricJizbaMSFT** [comment]
I'd just like to add my +1 to this. Since we don't ask for id when creating a mongo document anymore, it's not that obvious that something happened when you created a document (especially because the ids all look the same and you might have a bunch)

**Comment by PrashanthCorp** [comment]
Closing this via #566
