### ISSUE TITLE
Receiving error in notification center on every save in editor

### ISSUE THREAD

**Issue by tristan957** [Microsoft/vscode-cosmosdb#434]
The error is `Cannot convert undefined or null to object`

MacOS 10.13
VSCode: 1.21.1
Extension version: 0.5.0

**Comment by tristan957** [comment]
Duplicate of #372 
My bad. Closing

**Comment by StephenWeatherford** [comment]
Not a problem, thanks for letting us know. We're still trying to get a consistent repro, so if you have extra info on when it happens, that would be helpful.

**Comment by tristan957** [comment]
I'll make a more detailed comment of my setup after the weekend in the other thread. I'll be working with Cosmos fairly heavily and will keep notes on the plug-in. Unfortunately the dev tools are not very helpful in discovering the root of the problem

**Comment by StephenWeatherford** [comment]
Actually, it appears we've narrowed it down, so never mind, but thanks for being willing.

**Comment by tristan957** [comment]
No problem. Thanks for the extension

**Comment by StephenWeatherford** [comment]
Thanks for reporting this, it was fixed in v0.5.1 released a couple of days ago.

**Comment by tristan957** [comment]
Cool thanks!
