### ISSUE TITLE
The context menu doesn't contain 'Connect' for database under graph cosmos db account

### ISSUE THREAD

**Issue by v-flyuan** [Microsoft/vscode-cosmosdb#443]
## Steps to reproduce
1. Right click a database under graph cosmos DB account and the context menu opens.
2. Verify whether the context menu contains 'Connect' or not.

## Expected  behavior
The context menu contains 'Connect'. 

## Actual behavior
The context menu doesn't contain 'Connect'.
![connect](https://user-images.githubusercontent.com/12556995/37900661-7e0570de-3121-11e8-8229-baed19c1bf83.png)

**Comment by PrashanthCorp** [comment]
This is expected behavior. 
The concept of connecting to a database holds only for mongo databases (as part of the scrapbook features). 


Marking this as wontfix.
