### ISSUE TITLE
If mongo shell not found, the error shown is a timeout

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#455]

**Comment by EricJizbaMSFT** [comment]
Nope. My PR only addresses the case where 'mongo.shell.path' is not defined. If they define 'mongo.shell.path' to a bad path, they will still get the timeout

**Comment by EricJizbaMSFT** [comment]
Unassigning - not going to get to this today

**Comment by PrashanthCorp** [comment]
Reopened because I tied my PR to the wrong issue.
