### ISSUE TITLE
This Extension Breaks VSCode's JavaScript Syntax Highlighting 

### ISSUE THREAD

**Issue by beeplin** [Microsoft/vscode-cosmosdb#464]
- VSCode Version: 1.21.1
- OS Version: windows 10 1709

Steps to Reproduce: 

0. Before enabling cosmosdb extension, everything is OK. but after using this extension:

1. for single-line ternary expression the highlighting is all right:
![image](https://user-images.githubusercontent.com/13058150/38198327-e5ca6772-36be-11e8-990c-a5dcf8a4d72e.png)

2. for multi-line expression ( like `const xxx = \n boolean \n ? a :b`)
![image](https://user-images.githubusercontent.com/13058150/38198289-bdb84b8c-36be-11e8-9d2d-32ef7bfe7a80.png)

**Comment by StephenWeatherford** [comment]
@beeplin Thanks for using our extension. I'm having trouble reproducing this problem, though.  We don't handle .js files or its language/grammar so I'm not sure how we could affect their syntax highlighting.  Some questions:

1) Have you tried disabling just this extension (and reloading) and verifying the problem goes away, and that it comes back again when it's re-enabled?
2) What version of the extension are you using?  I'm using 0.5.1, the most recent.
3) Here's the file I used: [js.zip](https://github.com/Microsoft/vscode-cosmosdb/files/1869100/js.zip). Does it repro for you with this file (no folder or workspace opened)?
4) What other extensions do you have installed?

CosmosDB disabled:
![image](https://user-images.githubusercontent.com/6913354/38212002-20111f1e-3671-11e8-84ee-7d7b57b98578.png)

CosmosDB re-enabled:
![image](https://user-images.githubusercontent.com/6913354/38212044-446e8c98-3671-11e8-9226-9459ede0de25.png)

thx,
Stephen

**Comment by beeplin** [comment]
Hi @StephenWeatherford thank you for the quick reply. I am using 0.5.1 too, and I am pretty sure I disabled all other extensions. I know this issue is quite weird, but you can probablly reproduce it in this way:

![image](https://user-images.githubusercontent.com/13058150/38224323-13f59a0a-3722-11e8-8f64-5afe788829da.png)

the key difference is the position of `=`. When `=` is in the new line, it's OK; when `=` is at the end of the first line (which is prettier's default behavior), the highlighting is broken.
