### ISSUE TITLE
Mongo scrapbook doesn't accept single-quoted string literals

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#467]
... even though the grammar has SINGLE_QUOTED_STRING_LITERAL

The following works in console but not scrapbook:
  db.heroes.insert({  'id': 2,  'name': 'Batman',  'saying': "I'm Batman"})

**Comment by PrashanthCorp** [comment]
I also see regexes being a problem : 
https://docs.mongodb.com/manual/reference/operator/query/regex/

A fix is outlined here: 
https://stackoverflow.com/a/40151810/9090300

**Comment by PrashanthCorp** [comment]
Fixed via #685
