### ISSUE TITLE
argumentList in mongo grammar should be renamed argument

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#469]
arguments
	: OPEN_PARENTHESIS = '(' ( argumentList (',' argumentList)* )? CLOSED_PARENTHESIS = ')' 
	;

argumentList      <<=== this is not a list
	: literal
	| objectLiteral
	| arrayLiteral
	;

**Comment by PrashanthCorp** [comment]
We talked about this during my PR-review. The fix seems bigger than just the variable name - the visitor methods need to be renamed too.

**Comment by StephenWeatherford** [comment]
Now's the perfect time to do it, as long as it doesn't take too long.
