### ISSUE TITLE
Allow access to multi-tenant mongo server 

### ISSUE THREAD

**Issue by alikadir** [Microsoft/vscode-cosmosdb#473]
While testing Microsoft/vscode#25332

When you run your database on mlab you get a multi-tenant setup. I.e. a single mongo server has multiple databases but you are only allowed to access the db you own.

The mongoshell handles that case without issues:
mongo mongodb://<dbuser>:<dbpassword>@<server>.mlab.com:55574/<database> works without issues.

When I try to use such a connection string the in extension I get an error since the extension tries to list the databases:

not authorized on admin to execute command { listDatabases: 1 }: MongoError: not authorized on admin to execute command { listDatabases: 1 }

**Comment by jaribu** [comment]
Same issue here.

**Comment by StephenWeatherford** [comment]
@jaribu Are you saying you have version 0.6.0 of the extension and you're still seeing this issue? Can you be more specific about the details and what behavior you're seeing?  Thx.
