### ISSUE TITLE
Missing support for `update`, `updateOne` with multiple parameters

### ISSUE THREAD

**Issue by burkeholland** [Microsoft/vscode-cosmosdb#486]
Both the `update` and `updateOne` commands fail when providing a second object. It looks like they are looking for a closing parenthesis after the first object.

The following command...

```
db.heroes.updateOne({ "id": 10 }, $set: { { "name": "Burke" }})
```

returns the error...

"Error: Timed out executing db.heroes.updateOne({"id":10}<missing ')'>"

**Comment by StephenWeatherford** [comment]
@burkeholland We have already a fix for this, but it requires the mongo shell to be installed on the machine.  Would that a problem for you?  Thanks.

**Comment by PrashanthCorp** [comment]
Just clarifying here, is it supposed to be `db.heroes.updateOne({ "id": 10 }, $set: { { "name": "Burke" }})` or 
`db.heroes.updateOne({ "id": 10 }, { $set:  { "name": "Burke" }})`

I'm looking at the docs, and [this example](https://docs.mongodb.com/manual/reference/method/db.collection.updateOne/#examples) seems to suggest the latter. 

It looks like the corrected syntax works on our master build. Closing this. Feel free to reopen.

**Comment by burkeholland** [comment]
I mistyped that command - the second is correct and verified that it works against Cosmos DB via Functions and NoSQLBooster.

Sounds like this is resolved in master. I'll look for it in 0.6.0.

Thank you!
