### ISSUE TITLE
Scrapbook doesn't like arrays spread out on mutliple lines

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#489]
The following gives an error:

db.c2.insertMany([
    {"name": "Stephen", "age": 38, "male": true},
    {"name": "Stephen", "age": 38, "male": true}
])

But the following work:

db.c2.insertMany(
[{"name": "Stephen", "age": 38, "male": true},
    {"name": "Stephen", "age": 38, "male": true}
])
db.c2.insertMany([{
    "name": "Stephen", "age": 38, "male": true},
    {"name": "Stephen", "age": 38, "male": true}
])

**Comment by EricJizbaMSFT** [comment]
FYI this only repros for me on Windows. It works fine on mac

**Comment by StephenWeatherford** [comment]
Good to know, thanks.

**Comment by StephenWeatherford** [comment]
Also see this use case, which also fails to parse:

db.createUser({
    "user": "buddhi",
    "pwd": "123",
    "roles": ["readWrite", "dbAdmin"]
})

This works if you put the "}" on the same line as the ending square bracket:

db.createUser({
    "user": "buddhi",
    "pwd": "123",
    "roles": ["readWrite", "dbAdmin"]}
)

Raising to P1
