### ISSUE TITLE
Emulator: Running scrapbook commands utilizing the shell gives timeout

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#508]
Before the function is executed, the shell creation runs a `use <dbname>` that times out in case of an emulator.

**Comment by StephenWeatherford** [comment]
It's not just the emulator.  db.version() gives this, too

**Comment by StephenWeatherford** [comment]
I take it back, I think it is only for emulator.  Somehow I think the emulator got connected as my db, and I can't repro anymore with a regular MongoDB connected.

**Comment by StephenWeatherford** [comment]
The problem is here:

		try {
			this.mongoShell.stdin.write(script, 'utf8');
			this.mongoShell.stdin.write(os.EOL);
			this.mongoShell.stdin.write(executionId, 'utf8');
			this.mongoShell.stdin.write(os.EOL);
		} catch (error) {
			window.showErrorMessage(error.toString());
		}
