### ISSUE TITLE
Scrapbook: Running command gives an error if a previous command is erroneous 

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#509]
Example: 
```
db.find({"age" 33}) // No semicolon, no colon separating the key & value in filter
db.findOne({"age": 27}); // Cursor here. This line will be run
```
Running `findOne` will throw an error since we parsing encounters an error in line 1 with text `<missing ':'>`

**Comment by EricJizbaMSFT** [comment]
Agree this is annoying.

Also is this one a duplicate? https://github.com/Microsoft/vscode-cosmosdb/issues/499

**Comment by PrashanthCorp** [comment]
Oops, yes. I'll close that one, since this is more descriptive.

**Comment by StephenWeatherford** [comment]
> This has to do with throwing an error on seeing an Error Node.
