### ISSUE TITLE
JSON results disappear after resizing the editor 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#512]
Repro Steps:
1. Open one graph and execute.
2. Narrow the graph explorer editor, then resize.
3. Verify the JSON results.

Expect:
JSON results display well.

Actual:
JSON results disappear. Please see the details from "\\trinlab2\BAQAFiles\CloudToolsTest\v-dantch\Video\disappear.mp4"
![empty](https://user-images.githubusercontent.com/34729092/38548365-1b9a87d2-3ca1-11e8-896a-30ebca37aa42.png)

**Comment by PrashanthCorp** [comment]
I tried repro-ing the bug, from the video. If I finish resizing, and wait for 2 seconds, I see the results show up again. I feel it's a rendering issue, similar to https://github.com/Microsoft/vscode/issues/24643 and https://github.com/Microsoft/vscode/issues/30460. 

I am marking this as external, as the discussion in those threads suggest it is an electron bug. 

Your thoughts @StephenWeatherford ?

**Comment by StephenWeatherford** [comment]
Won't fix
