### ISSUE TITLE
Replace "DocumentDB" with "SQL"

### ISSUE THREAD

**Issue by fiveisprime** [Microsoft/vscode-cosmosdb#520]
I have confirmation from the Cosmos DB team that this should absolutely be "SQL."

See also: https://docs.microsoft.com/en-us/azure/cosmos-db/faq

**Comment by StephenWeatherford** [comment]
Should we do something like "SQL (DocumentDB)"?

**Comment by fiveisprime** [comment]
Let's just go with "SQL" and we can link to the FAQ in the changelog for clarification. This will be consistent with the portal.

**Comment by StephenWeatherford** [comment]
Dupe of #415
