### ISSUE TITLE
Fail to delete document with error for SQL accounts

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#544]
Repro steps:
Right click one document and select 'Delete Document', then check whether the document can be deleted or not.

Action: cosmosDB.deleteDocDBDocument
Error type: BadRequest
Error Message: The partition key supplied in x-ms-partitionkey header has fewer components than defined in the the collection.

More Info:
This issue doesn't reproduce in Storage Explorer. The same document can be deleted successfully in Storage Explorer.

Version: 0.6.1-alpha
OS: win32

**Comment by StephenWeatherford** [comment]
@v-dantch What's the partition key for the database? And is there a shard key?

**Comment by v-dantch** [comment]
Pop up this error when typing a string 'name' as the partition key.

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Can you repro?

**Comment by StephenWeatherford** [comment]
I can repro consistently. Happens whether you enter an ID or leave it blank.

**Comment by PrashanthCorp** [comment]
Looks to be related to [this issue](https://github.com/Azure/azure-documentdb-node/issues/222)

**Comment by StephenWeatherford** [comment]
Thanks. Given that from our extension you can only create collections with partition keys, I think we should fix this for this release if possible.  The issue you pointed to gave a work-around.

**Comment by PrashanthCorp** [comment]
It seems to stem as a regression bug from #302, which had that fix. 
The solution that works for me was to revert that fix. 

In light of that, I'm going to test this a bit more, to make sure it works in both fixed and unlimited storage, with or without partition keys.
