### ISSUE TITLE
Unclear error message displays after deleting a document which has deleted

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#546]
Repro Steps:
1. Right click one document and select 'Delete Document', then pop up a prompting dialog.
2. Delete this document in Storage Explorer or another VS Code instance.
3. Back to main instance and click 'Yes' in the prompting dialog in Step1.
4. Check the error message.

Expect:
The error message is clear.

Actual:
Unclear error message displays.
![unclear](https://user-images.githubusercontent.com/34729092/38981294-901ac9fa-43ae-11e8-9473-ed28ae2f1adc.png)

**Comment by StephenWeatherford** [comment]
I agree this is confusing.  Something more specific like "Azure reports that no documents were deleted" maybe?

**Comment by v-dantch** [comment]
Yes. It would be better to display a more clear error message like 'Azure reports that no documents were deleted' or 'The specified document does not exist'.
