### ISSUE TITLE
'Open In Portal' should be the first action in the context menu for one account

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#547]
Repro Steps:
Right click one account and check the context menu.

Suggestion
'Open In Portal' should be the first action like below.
![first](https://user-images.githubusercontent.com/34729092/38980915-9f5aa530-43ad-11e8-9b10-ee8a2678b322.png)

**Comment by StephenWeatherford** [comment]
Marking dup of #98.
