### ISSUE TITLE
Error Message: Language client is not ready yet

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#555]
Repro steps:
Use the cosmos extension (open it)

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.6.0
OS: darwin
Version 1.23.0-insider (1.23.0-insider)

cc @fiveisprime

**Comment by chrisdias** [comment]
does it repo in stable of vs code?

**Comment by johnpapa** [comment]
It only happens in the insiders version, for me

**Comment by johnpapa** [comment]
It happens within a second of clicking on the Cosmos extension in the sidebar

**Comment by johnpapa** [comment]
It is also very annoying that we cannot disable or uninstall the extension easily. 
![image](https://user-images.githubusercontent.com/1202528/39125267-62e13606-46cc-11e8-9193-c8f2627e593a.png)

**Comment by johnpapa** [comment]
as of the insiders from today (Apr 24, 2018) it works fine. No error.

**Comment by StephenWeatherford** [comment]
Weird, I can't repro it today anymore, either (Insiders or regular).  I'll keep an eye on it, please let us know if it occurs again.
