### ISSUE TITLE
Error trying to updateOne in mongo - $set syntax

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#556]
Repro steps:

I have data that looks like this

```
{
  "_id": "5a987da06c23a84554ae0519",
  "name": "Esteban Lothbrok",
  "id": 1,
  "__v": 0,
  "description": "aka Ragnar Sigurdsson"
}
```

and I try to run this command:

```
   db.heroes.updateOne(
      { "name" : "Esteban Lothbrok" },
      { $set: { "description" : "aka Ragnar Sigurdsson 2" } }
   );
```

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 5, column 5, text '$set'. Please check syntax.

Version: 0.6.0
OS: darwin

**Comment by johnpapa** [comment]
cc @fiveisprime

**Comment by StephenWeatherford** [comment]
See #466 .

**Comment by johnpapa** [comment]
Im not following what the answer is.

**Comment by StephenWeatherford** [comment]
For now double quotes are required like in JSON, although we would like to improve that:

 db.heroes.updateOne(
      { "name" : "Esteban Lothbrok" },
      { **"**$set**"**: { "description" : "aka Ragnar Sigurdsson 2" } }
   );

**Comment by johnpapa** [comment]
ah. quotes around `$set`. thanks

feel free to close

**Comment by StephenWeatherford** [comment]
Will close for now, thanks.  Still looking at removing this restriction in #466

**Comment by LordDraagonLive** [comment]
![image](https://user-images.githubusercontent.com/28833007/40485541-b60d3cec-5f56-11e8-95f8-6308a65a411b.png)
How can I enclose array values in double quotes.

@StephenWeatherford

**Comment by StephenWeatherford** [comment]
@LordDraagonLive Thanks for raising this issue.  This appears to be the same problem addressed in https://github.com/Microsoft/vscode-cosmosdb/issues/489.  Until that's fixed, you can work around it by putting the squiggly brace on the same line as the ending square bracket:

db.createUser({
    "user": "buddhi",
    "pwd": "123",
    "roles": ["readWrite", "dbAdmin"]}
)

Happy coding!
