### ISSUE TITLE
Inputting a blank value for Partition Key doesn't display error when creating a collection

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#561]
Repro Steps:
1. Right click one database under and select 'Create Collection'.
2. Input a valid collection name -> Press 'Enter' -> Input a blank valur for the Partition Key.
3. Check whether error dispays or not.

Expect:
An error displays after inputting a blank valur for Partition Key.
![expect](https://user-images.githubusercontent.com/34729022/39173274-d555f6b4-4793-11e8-99e2-0db1aac6b177.png)

Actual:
No error displays after inoutting a blank valur for Partition Key.
![actual](https://user-images.githubusercontent.com/34729022/39173285-dc34ae80-4793-11e8-9525-3a243b4bc87e.png)

**Comment by StephenWeatherford** [comment]
Won't fix.
