### ISSUE TITLE
Unable to connect when using an intermediate SSL proxy

### ISSUE THREAD

**Issue by dillten** [Microsoft/vscode-cosmosdb#562]
When an intermediate or MITM proxy is being used that alters the certificate chain, this extension throws an `Error: self signed certificate in certificate chain` regardless of the global `"http.proxyStrictSSL": false` setting.

The flag for this is currently hard-coded in https://github.com/Microsoft/vscode-cosmosdb/blob/2eb9e18ece1e8f946e2c4daba40809de54e43aa6/src/docdb/getDocumentClient.ts#L12

This setting should follow the global setting in VS Code.

**Comment by StephenWeatherford** [comment]
Fixed via #568
