### ISSUE TITLE
Cannot run queries on secondary. 

### ISSUE THREAD

**Issue by vyashole** [microsoft/vscode-cosmosdb#565]
Repro steps:
1. Connect to a secondary on a standard MongoDB replicated cluster
2. try to query a document

I tried running rs.slaveOk() from a mongo scrapbook, but that didn't work. am I missing something?

Action: cosmosDB.executeMongoCommand
Error type: 13435
Error Message: not master and slaveOk=false

Version: 0.6.0
OS: linux

**Comment by PrashanthCorp** [comment]
Hi Adwait, 
Thanks for filing an issue. We appreciate the usage. :) 

I have a couple of questions that would help me diagnose the issue. 
1. What configuration is your database running on? 
2. Where is it hosted?

**Comment by adwaitv** [comment]
Hi @PrashanthCorp, 
Here's the info you asked for. 
1. Standard MongoDB Replicated cluster
2. hosted on AWS

**Comment by vyashole** [comment]
@PrashanthCorp Just a reminder: This issue has been in `Waiting-for-response` state for a long time after I responded.

**Comment by EricJizbaMSFT** [comment]
Looks like this is almost done: https://github.com/microsoft/vscode-cosmosdb/pull/1130 Just need to verify that fix and get it merged
