### ISSUE TITLE
Open in portal functionality context item missing for attached account

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#571]
Subscription accounts have the option.

**Comment by StephenWeatherford** [comment]
We'd have to interpret the connection string to accomplish this (for Azure only), which can be quite complex.  Not sure it makes sense for this scenario.  Do you disagree?

**Comment by EricJizbaMSFT** [comment]
I'm with Stephen. IMO we should tree attached accounts as cloud-agnostic and "Open in Portal" is Azure-specific funtionality.
