### ISSUE TITLE
Create/Delete stored procedures are not available in palette

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#579]
![image](https://user-images.githubusercontent.com/6913354/39454909-bcc8677c-4c92-11e8-9c66-c3244fcdfec5.png)

**Comment by PrashanthCorp** [comment]
Create Stored Procedure exists [link](https://github.com/Microsoft/vscode-cosmosdb/blob/7687b304ccd83280d145aa725b261aca7a26d63b/package.json#L193). It's under the wrong category, :P
