### ISSUE TITLE
Tab title should indicate the opened document

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#581]
Instead, it's hard-coded to something like "cosmos-document.json" or "cosmos-stored-procedure.js"

**Comment by tec-goblin** [comment]
Hi @Microsoft/vscodeazuretools , it seems pretty straightforward once I [realized ](https://github.com/Microsoft/vscode/blob/49f8bfbc42a9f9f7cdfedc7293e36000393e2751/src/vs/platform/contextkey/common/contextkey.ts)that we can have Regexes in the "when" of Command bindings. So we don't need any more to write `"when": "resourceFilename==cosmos-document.json`, we can write something in the likes of `"when": "resourceFilename=~/(.*cosmosDoc.json)/` and name the tabs (treeItemName)cosmosDoc.json. 

There are other, harder solutions (like defining a custom language for cosmos documents and cosmos stored procedures), but, unless you already want to go for them for other reasons, I will start tomorrow working on the solution based on the proposal above. It was much fun even exploring all the alternatives.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/903
