### ISSUE TITLE
Accounts created in portal take longer to show up on our extension

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#582]
They show up quite quickly (<1 minute) in the portal ('All resources') but requires at least 5 minutes or a restart of the extension for the account to show up.

**Comment by StephenWeatherford** [comment]
You're saying that Refresh on a node doesn't pick up the new account?

**Comment by PrashanthCorp** [comment]
A refresh doesn't seem to pick it up for 4 min.

**Comment by StephenWeatherford** [comment]
It takes a while to create one.  I'd say as long as it does pick it up it's fine.  Probably just Azure behavior.
