### ISSUE TITLE
Specific error causes entire scrapbook to not be recognized

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#592]
1) Put this in a scrapbook:

adb.testdrop();
db.test.insertMany([{"a": "one"}, {"a":"a two", "b": "b two"}]);
db.test.insertMany([{"a": "one"}, {"a":"a two", "b": "b two"}]);

!) None of the lines show "Execute"
EXPECTED: lines 2 and 3 should show "Execute"

**Comment by StephenWeatherford** [comment]
ALSO: Should show "Connected to db", at least

**Comment by StephenWeatherford** [comment]
Dupe of #609?

**Comment by StephenWeatherford** [comment]
Raising priority given that it affects CodeLens

**Comment by PrashanthCorp** [comment]
Does not repro anymore. Closing.
