### ISSUE TITLE
Mongo Aggregate queries

### ISSUE THREAD

**Issue by johnwoolee** [Microsoft/vscode-cosmosdb#593]
Repro steps:
any aggregate query in mongo

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 1, column 22, text '[
'. Please check syntax.

Version: 0.6.0
OS: win32

Are aggregate queries a supported feature? Right now, it's not allowing me to write the square bracket opening the aggregate pipeline. Works fine in mongo shell, but get the error above using the Scrapbook.

```
db.avatars.aggregate([
  {
    $match: {
      _id: {$exists: true}
    }
  }
])
```

**Comment by johnwoolee** [comment]
That was it! Really looking forward to those issues being resolved. Thanks for the quick response!

**Comment by StephenWeatherford** [comment]
Glad to hear it.
