### ISSUE TITLE
SQL collection creation: Request Units have different thresholds based on fixed vs unlimited size

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#594]
Fixed : 400 - 10,000
Unlimited : 1,000- 10,000

Screenshots: 
Fixed-
![image](https://user-images.githubusercontent.com/30420973/39497372-e1f92494-4d57-11e8-919f-144c244d0f20.png)

Unlimited- 
![image](https://user-images.githubusercontent.com/30420973/39497380-f410ec0c-4d57-11e8-9dc7-19badc539e92.png)

**Comment by StephenWeatherford** [comment]
See #295

**Comment by PrashanthCorp** [comment]
Just an implementation detail. Closing it.
