### ISSUE TITLE
vscode formatter does not work

### ISSUE THREAD

**Issue by johndevedu** [microsoft/vscode-cosmosdb#595]
because .mongo extension is not recognized as being equivalent to javascript, the default vscode js formatter does not work. Is there anything in the works to remedy this? Or is there a good workaround for this?

Thanks!

**Comment by StephenWeatherford** [comment]
The only work-around I'm aware of is the following:
1) Change "mongo" to "JavaScript" in the status bar
![image](https://user-images.githubusercontent.com/6913354/39498301-36d62864-4d5c-11e8-94ba-1378e843b352.png)
2) Format the document
3) Change it back to "mongo"

We'll have to look into what it would take to get this working properly.  Thanks.

**Comment by johnwoolee** [comment]
Yes, I tried that to see that it was related to the file association, and that flow works. However, having a proper formatting association for .mongo to .js would definitely help the normal coding workflow with my teams.

As an alternative, would it be possible to allow the ctrl+shift+" command register on .js files?

**Comment by johnwoolee** [comment]
@StephenWeatherford found a quick fix! Adding the following to your vscode settings will do the trick!

```
"files.associations": {
    "*.mongo": "javascript"
}
```

**Comment by johnwoolee** [comment]
Great points. Figured there must be reasons why you picked `mongo `as a language instead of piggybacking off of `javascript`. Thinking there are two options:

1) Looking into best way to make vscode treat `mongo` as `javascript` only for the purpose of formatting. 
2) Creating a custom formatter for `mongo`. This seems kind of overkill, but might be quickest temp fix.

Thoughts?

**Comment by StephenWeatherford** [comment]
1) Having been able to find a way to re-use the JavaScript formatter, doesn't seem to be supported.  Similar questions on stackoverflow have gone unanswered.  We could hang off of javascript, but we'd have to make everything context sensitive. More importantly, we'd get stuff we *don't* want, such as intellisense and errors for JavaScript code.
2) Unfortunately this does appear to be the most reasonable fix. I'm sure we could find an appropriate open source formatter to use.

**Comment by StephenWeatherford** [comment]
3. I can try creating a separate command that changes the languageid, calls format, then changes it back.  This is by far the easier if it works.

**Comment by johnwoolee** [comment]
I like option 3 as well. That seems like it should be the easiest to implement. However, looks like the vscode api currently does not support this:

See this issue: https://github.com/Microsoft/vscode/issues/1800

**Comment by StephenWeatherford** [comment]
We're going to have trouble finding time for this with our priorities.  If it's something you would like to tackle, feel free to.

**Comment by StephenWeatherford** [comment]
Great.  Suggest you start with a free formatter.  Let us know how it goes.

**Comment by johnwoolee** [comment]
@oshalygin I'm interested in helping out. LMK how I can join the effort.

**Comment by StephenWeatherford** [comment]
If someone can find an open source package to do the formatting, we could look into hooking it up.
