### ISSUE TITLE
Cannot Connect to Azure Cosmos DB Account

### ISSUE THREAD

**Issue by varunkakkar** [Microsoft/vscode-cosmosdb#598]
Repro steps:
<Enter steps to reproduce issue>
Right Click on Database
Click on Connect
Error Recieved

Action: cosmosDB.connectMongoDB
Error type: Error
Error Message: Language client is not ready yet

Version: 0.6.0
OS: linux

**Comment by fiveisprime** [comment]
Are you on Insiders? If so, you may just need to update to fix this. If you are not on Insiders, please log an issue on VS Code core here https://github.com/Microsoft/vscode/issues

Related: https://github.com/Microsoft/vscode/issues/46626

**Comment by StephenWeatherford** [comment]
Closing for lack of response.  Feel free to reopen.
