### ISSUE TITLE
Mongo command should be included in error message during "executeAll"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#606]
I got the below error message and it took me a little bit to figure out which command was throwing the error. I would prefer a message that included the db and command name (although not the full command with arguments, because that would be too much). For example: `Error while running "db.test.insertMany": E11000 duplicate key error collection: test.scores Failed _id or unique key constraint`

Action: cosmosDB.executeAllMongoCommands
Error type: 11000
Error Message: E11000 duplicate key error collection: test.scores Failed _id or unique key constraint

Version: 0.6.1-alpha
OS: darwin

**Comment by PrashanthCorp** [comment]
Based on our discussion, it looks like this will have to wait till #647 and #615 are fixed.

**Comment by EricJizbaMSFT** [comment]
We all agree line numbers would be ideal, but I don't think that should block us from adding 'db.test.insertMany' to the error message. Feels like an easy thing to change that would help most cases

**Comment by StephenWeatherford** [comment]
Agreed, this can/should be done now.

**Comment by PrashanthCorp** [comment]
IIRC from standup, that's not what @fiveisprime and I agreed upon. 

I can see where @EricJizbaMSFT is coming from - `insertMany` tends to have a lot of arguments. I don't feel that accounts for the bulk of the commands being used. 
I disagree that it would be effective in most cases. My main issue is that without the arguments, in most cases the user has no clue which `insertMany` command was faulty. I've faced this while testing, and @fiveisprime agreed with his use-case (having multiple commands of the same instruction). 

If both of you feel strongly on this, I'll tidy up [this branch](https://github.com/Microsoft/vscode-cosmosdb/tree/ps/606) and put out a PR.

**Comment by StephenWeatherford** [comment]
I don't understand what you mean by the time being.  What's your alternative proposal?

**Comment by PrashanthCorp** [comment]
By time being, I meant this fix might be obviated if the other bugs mentioned below are fixed. I'll still fix this bug. 
Alternatively, we have your PR #652 that addresses #471. Fixing the bugs about line numbers (#647 and #615), the current bug could be solved by side-effect.

**Comment by PrashanthCorp** [comment]
Update: #652 would be modifying all the code I was changing. I'm holding this off till that is done (the merge will require me to redo the change anyway).
