### ISSUE TITLE
OPINIONS NEEDED: Too many 'result-1.json' files are generated after running mongo commands

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#607]
Most of the time I never want to save the 'result-1.json' files after running a mongo command. I'm talking about stuff like this:
![screen shot 2018-05-04 at 1 46 18 pm](https://user-images.githubusercontent.com/11282622/39652169-91904888-4fa1-11e8-9482-6e8ade2428a3.png)

And it's made worse because I always get this prompt when I go to close the files:
![screen shot 2018-05-04 at 1 42 47 pm](https://user-images.githubusercontent.com/11282622/39652032-0bfd1dea-4fa1-11e8-950a-f38219e2c9cd.png)

The only thing I might want to save is the output of a 'find' or 'findOne', but that's already handled separately. Maybe this should go to the output channel? I'm not sure.

**Comment by StephenWeatherford** [comment]
I agree we need to figure out an improved experience here, especially with the new Execute All.

**Comment by StephenWeatherford** [comment]
Investigate telemetry: How badly is this needed?

Consider using virtual file loading.

**Comment by sa-mm** [comment]
@dprice I've run into this as well. From looking at the code, it appears that `find` and `findOne` are the only commands that will display in the same window. My guess is that this is because those two commands use an "editor" that's meant to contain some azure integration. The other commands do not, so they just sent to a new window every time. (As an aside, it appears that if you chain a command with find, it won't reuse the editor either—`find().limit(1)`. I'm not sure if that's intended.)

Anyways, I've made some changes that will cause all commands that aren't `find` and `findOne` to reuse a different window. This might be what @StephenWeatherford when he said, "Consider using virtual file loading." I'll put a PR and see if they are interested.

**Comment by StephenWeatherford** [comment]
@dprice @sa-mm and all others - what's the ideal behavior you'd like to see if you could get it?  
Also, what are your normal usage patterns? Do you frequently run the same query multiple times?  Different ones?  Do you save and re-run scrapbooks?  Etc.  Thanks!

cc @fiveisprime @EricJizbaMSFT @PrashanthCorp

**Comment by sa-mm** [comment]
@StephenWeatherford My ideal behavior would be for every query (collection method, cursor method, etc.) to open in the same window, which would get reused if the query was re-run. I'd also like to be able to delete the results window without having to confirm that I actually want to delete it. I'd also like to have the results pretty printed like they are with `find` and `findOne`.

I generally use the scrapbook feature when I need to write some aggregation pipeline. I like to have the larger space available in an editor to do that. I often re-run the query multiple times as I build it and get a better sense of the extent of the problem. I have one scrapbook that I save things to, but for the most part I just open a new scrapbook and then delete it at the end of the day.

**Comment by StephenWeatherford** [comment]
@sa-mm Thanks for the info!  So when running an entire scrapbook with multiple queries, you'd like all results reported in that same window, kind of like the Mongo shell?  

Do you ever use the feature of modifying a query result and saving it back to the database via CTRL+S?

**Comment by dprice** [comment]
@StephenWeatherford I completely agree with @sa-mm. My usual mode of development whether in Robo 3T or NoSqlBooster is to work the query over and over until it works. Once the query is proven then it is applied in other areas of the codebase whether is a C# API or a 3rd party WebAPI reporting solution.

**Comment by StephenWeatherford** [comment]
@dprice Thanks, very useful to know.

**Comment by sa-mm** [comment]
@StephenWeatherford Yup, kind of like the shell, I think. I don't think I've ever modified the result and saved it back to the database.

Thanks for asking for the input. 😄

**Comment by v-andrew** [comment]
@StephenWeatherford

`find` now creates separated `result-X` window on every execution.

It’s **REALLY ANNOYING**

It is already 2 years since ticket was created. 

Is there any chance to see it fixed?

**Comment by wwlorey** [comment]
A fix for this just shipped in [v0.14.0](https://github.com/microsoft/vscode-cosmosdb/releases/tag/v0.14.0). Thanks for the feedback!
