### ISSUE TITLE
fineOne result doesn't support ObjectIDs

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#608]
This is what I see from executing `db.test.find()`:
![screen shot 2018-05-04 at 2 00 56 pm](https://user-images.githubusercontent.com/11282622/39652828-ca9e12e8-4fa3-11e8-9354-2a55bff892fb.png)

But this is what I see when I execute `db.test.findOne()`:
![screen shot 2018-05-04 at 2 03 23 pm](https://user-images.githubusercontent.com/11282622/39652868-eded8f44-4fa3-11e8-8f50-bd0aefa37f3b.png)

I'm not too familiar with ObjectIDs, but I believe the 'find' is handling it correctly and 'findOne' is not.

**Comment by StephenWeatherford** [comment]
@EricJizbaMSFT Nice catch, that's probably worth fixing today.  @PrashanthCorp, can you investigate?
