### ISSUE TITLE
Errors inside arguments are specified at incorrect position

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#615]
Repro steps:
Scrapbook: db.c1.findOneAndUpdate({"_id":{"$regex": /5a/}})

Action: cosmosDB.executeMongoCommand
Error type: SyntaxError
Error Message: Unexpected token / in JSON at position 17

Version: 0.7.0
OS: win32

EXPECTED: Correct position should be 42

**Comment by PrashanthCorp** [comment]
Looked into this again, and the error currently seems more accurate - the squiggly is right after the regex: 

![image](https://user-images.githubusercontent.com/30420973/42394595-840ba960-810f-11e8-82d7-d8e8ee4faa6c.png)


My hunch is this bug and #754 are symptoms of the same underlying behavior - the parser routinely reports the error _at the first character after_ the erroneous token.

**Comment by StephenWeatherford** [comment]
> the parser routinely reports the error at the first character after the erroneous token

The error currently is at exactly the right place because it says the "}" is the incorrect token:
![image](https://user-images.githubusercontent.com/6913354/42395783-ef487a38-8113-11e8-8854-6bc848240351.png)

This behavior is good, so it got fixed somewhere along the line, probably in my error list changes.  Closing.

#754 is different and complicated (it's also showing the error in the right place according to what it thinks is wrong).
