### ISSUE TITLE
[Linux]Pop up the error after copying account connection string

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#616]
**Repro Steps:**
1. Right click one account and select 'Copy Connection String'.

**Expect:**
The account connection string can be copied successfully.

Actual:
Pop up the error: "must have xclip installed..."
![xclip](https://user-images.githubusercontent.com/34729022/39695162-325651b6-51d9-11e8-8f02-4b11c2c4ea37.png)

**More info:**
This issue still reproduces after installing xclip and reopening VS Code.

**Comment by PrashanthCorp** [comment]
This is a known issue. Please see #64. We feel the current behavior is works well enough.
