### ISSUE TITLE
Shouldn't MongoDB extended JSON be accepted in queries?

### ISSUE THREAD

**Issue by rdumont** [Microsoft/vscode-cosmosdb#621]
Repro steps:

1. Open a new Mongo Scrapbook
2. Execute:
    ```js
    db.spaces.find({"foo": {"$numberLong": "180122546362908678"}})
    ```

<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: 2
Error Message: unknown operator: $numberLong

Version: 0.7.0
OS: linux

**Comment by PrashanthCorp** [comment]
Hi @rdumont , the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
