### ISSUE TITLE
Error: Unexpected Experience Value

### ISSUE THREAD

**Issue by johnpapa** [Microsoft/vscode-cosmosdb#623]
After the update to the Cosmos DB extension on May 7th and when using the insiders edition, I am getting this error. I get the same error in the stable too.

![image](https://user-images.githubusercontent.com/1202528/39799453-203be00e-5319-11e8-9099-3d542d97710d.png)

**Comment by PrashanthCorp** [comment]
Do you by any chance have any Cassandra accounts?

**Comment by chrisdias** [comment]
I just looked at his machine, it happens with multiple different subscriptions, and it used to work before. 

Also, there are no errors in the chrome dev tools console.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/625 and just did a patch release of the extension

**Comment by johnpapa** [comment]
you all rock. thank you so much.
