### ISSUE TITLE
An invalid Database Account should not prevent valid Accounts from being displayed

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#628]
See [this bug](https://github.com/Microsoft/vscode-cosmosdb/issues/623) where a single invalid Database Account was preventing _any_ database account from being shown. The specific error in that bug was already fixed, but other errors could still occur.

We had a similar issue in App Service that was already fixed:
Issue: https://github.com/Microsoft/vscode-azureappservice/issues/371
PR with fix: https://github.com/Microsoft/vscode-azureappservice/pull/373

**Comment by PrashanthCorp** [comment]
How do we want to notify the user about an invalid account? 
Do we want to have mock nodes for invalid accounts or write to output?

**Comment by StephenWeatherford** [comment]
We want to show the error message in a mock node.
