### ISSUE TITLE
No placeholder displays when creating a stored procedure/document

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#632]
**Repro Steps:**
1. Select one SQL DB/Mongo DB account.
2. Expand one collection and create a document/stored procedure.
3. Check whether the placeholder displays in the textbox or not.

**Expect:**
The placeholder displays in the textbox.

**Actual:**
No placeholder displays in the textbox.
![placeholder](https://user-images.githubusercontent.com/34729022/40106371-2b4b30d6-58e5-11e8-9799-b539d5ee9e09.png)

**Comment by PrashanthCorp** [comment]
This is currently working as intended.

Placeholder text serves as an instruction **only when** you are choosing from a predefined list of options (eg. selecting subscriptions). 

In the case of arbitrary text, placeholder vanishes as the user starts typing.
