### ISSUE TITLE
Getting 'Could not find Mongo shell' for invalid command syntax

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#633]
Repro steps:
1. Execute this in scrapbook:
   db.c1.insert({},{})

EXPECTED: better error

Action: cosmosDB.executeMongoCommand
Error type: ENOENT
Error Message: Could not find Mongo shell. Make sure it is on your path or you have set the 'mongo.shell.path' VS Code setting to point to the Mongo shell executable file. Attempted command: ""d:\Program Files\MongoDB\Server\3.6\bin\mongo.exe""

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
Related to #614?

**Comment by StephenWeatherford** [comment]
Never mind, had double quotes around the exe name

**Comment by PrashanthCorp** [comment]
So what does it give if you remove the outer pair of quotes?

**Comment by StephenWeatherford** [comment]
Different error, related to existing issues.
