### ISSUE TITLE
An invalid document should not prevent valid documents from being displayed

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#636]
Similar to issue #628, but for invalid documents instead of invalid database accounts. I was checking error telemetry and noticed some users were getting `Cannot read property 'toString' of undefined` when getting the children of a MongoCollection. I'm guessing it was breaking [here](https://github.com/Microsoft/vscode-cosmosdb/blob/master/src/mongo/tree/MongoDocumentTreeItem.ts#L34) because _id was not defined. I don't know how/why _id is undefined, but it does feel like documents are one of the more likely places to fail in the tree and we should handle that appropriately.

**Comment by PrashanthCorp** [comment]
It looks like this pertains to labels of the documents, We have addressed this in #569 and #719. We might have to wait for sufficient telemetry post release to know whether this is still a problem. 

Regarding documents with no `_id` field: 
In trying to generate a document with no `_id` field, here's what I've tried: 
1. Create a document from the extension (creates a default `_id`)
2. Create a document from the portal (also creates a default `_id`)
Neither seems to work.

**Comment by EricJizbaMSFT** [comment]
This issue is more about error handling than that specific error. You can reproduce the problem yourself by putting the following in the constructor of MongoDocumentTreeItem [here](https://github.com/Microsoft/vscode-cosmosdb/blob/master/src/mongo/tree/MongoDocumentTreeItem.ts#L33):
```
if (this._label === 'fail') {
    throw new Error('fail');
}
```

Insert a bunch of documents, including one with the label as 'fail'.

Expected:
All documents except the 'fail' one show up

Actual:
No documents show

**Comment by nturinski** [comment]
Nike. Just do it.
