### ISSUE TITLE
'Copy Connection String' doesn't work on linux

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#64]
Same root problem as https://github.com/Microsoft/vscode-azure-account/issues/9

The copy-paste npm package we use requires xclip, but it's not installed on most linux OS's by default

**Comment by PrashanthCorp** [comment]
I'm looking at this on Windows - the text on the Info message is clickable, selectable and can be copied to clipboard (Ctrl+C). 

Would a possible fix on Linux be : try executing a copy to clipboard, then on failure, prompt the user about xclip?
