### ISSUE TITLE
Succeed to attach an account with an unmatched account API

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#641]
Repro Steps:
1. Right click one SQL account and select 'Copy Connection String'.
2. Click 'Attach Database Account', then select another API like Gremlin.
3. Paste the copied connection string.
4. Check whether it can be attached successfully or not.

Expect:
Fail to attach with an unmatched API.

Actual:
Succeed to attach.

**Comment by StephenWeatherford** [comment]
This could actually be useful, so won't fix right now.

**Comment by v-dantch** [comment]
Ok, thanks for your update about this issue.
