### ISSUE TITLE
No matched commands display after typing Gremlin into Command Palette

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#642]
Repro Steps:
1. Press F1, then type Gremlin.
2. Check the result.

Expect:
All related commands display.

Actual:
No matched commands.
![gremlin](https://user-images.githubusercontent.com/34729092/40477491-1afa87ac-5f36-11e8-9722-1b457ea2d033.png)

**Comment by StephenWeatherford** [comment]
Use "Graph (Gremlin)" as category
