### ISSUE TITLE
Display Table accounts in the filtered results when creating collections for Mongo DB account

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#643]
Repro Steps:
1. Press F1 and type MongoDB: Create Collection.
2. Select one subscription, then check the filtered result.

Expect:
All Mongo DB accounts display and there is no Table account.

Actual:
Display Table accounts.
![table](https://user-images.githubusercontent.com/34729092/40477940-43be9682-5f37-11e8-89ee-732035db7488.png)

**Comment by PrashanthCorp** [comment]
Currently works as intended. We show all accounts and allow you to drill down. I guess we could show only those resources of type mongo. That would be an enhancement.
