### ISSUE TITLE
Cannot execute statements if I declare a variable in editor

### ISSUE THREAD

**Issue by patriciunista** [Microsoft/vscode-cosmosdb#645]
After a variable declaration, the button *Execute* disappears from the view and if I click *Execute all* it doesn't work. Here is a screenshot:

![image](https://user-images.githubusercontent.com/22194171/40490403-b3e65704-5f6b-11e8-8c98-be7316dbbf74.png)

**Comment by patriciunista** [comment]
Found that even without a variable, trying to execute `.toArray()` method it causes the same behaviour. 

So, I guess that after any `JS` code in the file, all queries won't not work, even with methods from [cursors](https://docs.mongodb.com/manual/reference/method/js-cursor/).

**Comment by StephenWeatherford** [comment]
@patriciunista We appreciate your use of our extension. Scrapbooks are not intended to be a full runtime environment, but more for quick, exploratory querying. For what you're trying to do, it would be better to use install and use the actual Mongo [shell](https://docs.mongodb.com/manual/mongo/).  Sorry for the inconvenience.

Stephen
