### ISSUE TITLE
Incorrect line reported for syntax error if "Execute" CodeLens is used

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#647]
1) Put this in a scrapbook:

db.createUser({
                "user": "buddhi",
                "pwd": "123",
                "roles": ()
                }
            )
       
2) Put cursor anywhere in the command and right-click -> "Execute MongoDB Command"
3) As expected, you get this error:

Error near line 3, column 25, text '('. Please check syntax.

4) Now click "Execute" at the top of the file
!) The line and column numbers are reported incorrectly:

Error near line 0, column 51, text '('. Please check syntax.

**Comment by StephenWeatherford** [comment]
Still repro?

**Comment by StephenWeatherford** [comment]
Current behavior:  
1) problems pane:  Behavior is correct
2) Execute Mongo Command: The line number is off by one e.g. if the bad line is line 8, the error message says line 7:
  
<img width="196" alt="image" src="https://user-images.githubusercontent.com/6913354/46114079-f8a30d00-c1a5-11e8-96d7-258414b07b10.png">
<img width="420" alt="image" src="https://user-images.githubusercontent.com/6913354/46114095-022c7500-c1a6-11e8-88d6-d09d4e3515ef.png">

3) Clicking Execute: You get completely incorrect line and column:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/6913354/46114160-461f7a00-c1a6-11e8-8f32-dbfc95ab464d.png">

**Comment by PrashanthCorp** [comment]
Regarding 3: The method `getAllCommandsFromText` removes line endings and spaces. We'll have to reconstruct the exact line and character indices before pushing the position to codelens. 
2 : Verified there's an off-by-one error [here](https://github.com/Microsoft/vscode-cosmosdb/blob/a6e8aa43a91b1600f9e5c140df1e6e222b0635d1/src/mongo/MongoScrapbook.ts#L106)
