### ISSUE TITLE
No MongoDB command found

### ISSUE THREAD

**Issue by gekeugen** [Microsoft/vscode-cosmosdb#648]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: No MongoDB command found at the current cursor location.

Version: 0.7.1
OS: linux

**Comment by StephenWeatherford** [comment]
@gekeugen Can you please provide the command that you were trying to execute?  Thanks.

**Comment by gekeugen** [comment]
I could not execute the command  'use database'
________________________________

**Comment by StephenWeatherford** [comment]
Thanks.  We only support commands starting with "db.".  

1) We should make the limitations clear in the readme
2) The fact that there's no error is probably #653 

The way that you specify the database to use is to click on "Connected to …" at the top of the scrapbook, or to right-click on a database and select "Connect".  Would "Using <db>" make this intention clearer?  Or we you needing to use multiple databases in the same scrapbook?  Thanks.

![image](https://user-images.githubusercontent.com/6913354/40813976-78513092-64f2-11e8-948b-962e0aebf48a.png)

**Comment by StephenWeatherford** [comment]
For this release, should at least better explain the model in the readme.

**Comment by PrashanthCorp** [comment]
We currently see an equivalent way to using a database - the codelens. 
Moreover, we haven't gotten a response over the last 6 weeks regarding any use-cases we've missed. 

We're closing this due to lack of response and a workaround. If you feel we have missed any of your use cases, please feel free to re-open.
