### ISSUE TITLE
Error when using updateOne mongodb command

### ISSUE THREAD

**Issue by ad-free** [Microsoft/vscode-cosmosdb#655]
Repro steps:
db.Fun.updateOne({
    "name": "A .Macdyver"
}, {
    $set: {
        "points": 1111111
    }
});

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 53, column 4, text '$set'. Please check syntax.

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
@ad-free Hey, just wanted to make sure you knew we fixed the requirement of putting quotes around property names in our last release (a couple of weeks ago).  Thanks.
