### ISSUE TITLE
Fail to upload the changed document after canceling it at the first time

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#656]
Repro Steps:
1. Open one document and make changes for it.
2. Press 'Ctrl + S' and make sure that pops up a prompting dialog.
![prompting](https://user-images.githubusercontent.com/34729092/41030663-4f956ba2-696e-11e8-84a6-564d180f2b71.png)
3. Click 'Cancel' on the prompting dialog.
4. Press 'Ctrl + S' again.

Expect:
The prompting dialog pops up again.

Actual:
The prompting dialog doesn't pop up.

**Comment by StephenWeatherford** [comment]
Seems to happen only on Windows.

We can't fix this - the dialog doesn't come up if there are no changes.  So the work-around is to make a change (even whitespace) and save again.

**Comment by v-dantch** [comment]
Ok, got it. Thanks a lot for your update.
