### ISSUE TITLE
[Suggestion]Confused log message after updating the auto-generated filed for documents

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#657]
Repro Steps:
1. Right click one Mongo DB and new a database > collection >document.
2. Open the document and edit the auto-generated filed.
![edit](https://user-images.githubusercontent.com/34729092/41032238-4aa2bc4a-6972-11e8-8764-d1baaa2caf51.PNG)
3. Press 'Ctrl + S' and click 'Upload', then check the result.

Actual:
Succeed to update from the log message. But actually the added part doesn't display for the document.
![updated](https://user-images.githubusercontent.com/34729092/41032469-fee90696-6972-11e8-8ee9-07f2665b398a.PNG)

Suggestion:
Fail to edit in the auto-generated filed. Or display a clear log message.

**Comment by StephenWeatherford** [comment]
We get this error:

Failed to update document with _id '5b185dacad64a65689d8acb0'.

Can you try again or be more specific?

**Comment by v-dantch** [comment]
Hi Stephen. This issue also reproduces and we record a video about it. Please get the details from "\\trinlab2\BAQAFiles\CloudToolsTest\v-dantch\Video\upload.mp4" . Hope this will help us.

**Comment by PrashanthCorp** [comment]
Inside the update command, we use the ID of the document to tell Cosmos _which_ document to update. Changing the ID will change which document is updated (In this case, it will most likely create a document with the new ID). 
You can try the following: 
1. Create a document, add some fields, like { id: <ID>, city: "Beijing", "Time Zone": "UTC+0800"}.
2. Save this document. 
3. Change the ID, and upload. 
4. Refresh the collection

You should see two documents in the collection with identical contents.

**Comment by v-dantch** [comment]
Hi @PrashanthCorp , we get a similar error to Stephen's if we upload the document with a **changed** ID.
![error](https://user-images.githubusercontent.com/34729092/46053068-e8047f80-c130-11e8-89f1-852beaca35d4.png)

**Comment by PrashanthCorp** [comment]
Closing for now, waiting for customer feedback
