### ISSUE TITLE
Create collection issue

### ISSUE THREAD

**Issue by StylishSingh** [Microsoft/vscode-cosmosdb#658]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.createMongoCollection
Error type: 13
Error Message: not authorized on demo to execute command { insert: "users", ordered: true, $db: "demo" }

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
@StylishSingh thanks for letting us know that this is an issue for you.  This is being tracked in #466 and related #467.  We are hoping to fix this soon.

In the meantime, you should be able to get this to work by placing double quotes around property names.

**Comment by PrashanthCorp** [comment]
Hi @StylishSingh, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
