### ISSUE TITLE
MongoDB system.indexes: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by eug48** [Microsoft/vscode-cosmosdb#661]
Repro steps:

Right-clicked on system.indexes and selected Open Collection.
I also see "Error: Cannot read property 'toString' of undefined" in the tree view when I expand some, but not all, system.indexes nodes.
Using MongoDB version 3.6.4 on WSL.

Overall this is still just an excellent extension - thanks!

Action: cosmosDB.openCollection
Error type: TypeError
Error Message: Cannot read property 'toString' of undefined

Version: 0.7.1
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @eug48, 

Thanks for using the extension! We could not repro the issue on our end. If you want to see a collection's indexes, consider using the command `db.collection.getIndexes()` instead.

**Comment by eug48** [comment]
Yes, the system.indexes collection isn't even shown anymore (I'm now using MongoDB 4.0).
