### ISSUE TITLE
Azure CosmosDB: Cannot Connect to MongoDB

### ISSUE THREAD

**Issue by MyGHid** [Microsoft/vscode-cosmosdb#662]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.1
OS: win32

**Comment by adwaitv** [comment]
Hi, 
Connection refused usually means that the port (27017 in your case) is not open or something is blocking it from connection

**Comment by MyGHid** [comment]
Thanks. What is work around this? Can I just enter a different port number?

**Comment by StephenWeatherford** [comment]
@MyGHid You're connecting to a local mongodb instance.  Please make sure you actually have the local server running.  For instance, on Windows, you would run (changing path as necessary):
```
"C:\Program Files\MongoDB\Server\3.6\bin\mongod.exe"
```

in a command prompt window and leave it open (see https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/ for more information).

If you already have started MongoDB, then in a different command window try running the MongoDB shell, for instance:
```
"C:\Program Files\MongoDB\Server\3.6\bin\mongo.exe"
```
and see if it is able to connect to the MongoDB.exe server.

You can find more information about getting started with MongoDB here: https://docs.mongodb.com/manual/installation/.  Please let us know if this resolves the issue for you.

thx,
Stephen

**Comment by StephenWeatherford** [comment]
Alternatively, if you would like to connect to an Azure instance of MongoDB, then you should sign in to Azure and browse to or create an Azure MongoDB database.  In that case you don't need to use the "Attach Database Account" command.

**Comment by MyGHid** [comment]
Yes, this helped. Thank you!
