### ISSUE TITLE
Can't update documents

### ISSUE THREAD

**Issue by roblabat** [Microsoft/vscode-cosmosdb#663]
I connect to a local database and edit a document. When trying to save it I've got this error:

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

Version: 0.7.1
OS: win32

The document looks like: 
{
    "_id": "Syi4X3csiGEEhSNTM",
    "title": "In dolore eum laudantium ipsa aliquid.",
    "content": "Aspernatur doloremque officia magni. Dolore dolorem aut voluptas quia. Quis et ipsa maiores quo quisquam aut minima sit consequuntur. Consectetur necessitatibus expedita. In est doloribus sint incidunt omnis.\n \rSint sit ullam non quia quo at sed. Hic iure eaque aliquam fuga. Rerum ut quis qui iste voluptas quaerat.\n \rQuis deleniti accusantium et deserunt. Minus doloremque dolorem porro deleniti eveniet dolore. Eum ut placeat sunt assumenda voluptatum. Tempore enim commodi quae id deleniti."
}

**Comment by PrashanthCorp** [comment]
Close via PR

**Comment by PrashanthCorp** [comment]
Hi @roblabat , the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
