### ISSUE TITLE
Cannot query collection under namespace - db.foo.bar.find()

### ISSUE THREAD

**Issue by hedefalk** [Microsoft/vscode-cosmosdb#666]
Repro steps:
create collection foo.bar

Scrapbook:

db.foo.bar.find()

Action: cosmosDB.executeAllMongoCommands
Error type: Error
Error Message: Error near line 0, column 10, text '.'. Please check syntax.

Version: 0.7.1
OS: darwin

**Comment by PrashanthCorp** [comment]
Is the database name foo and the collection name bar? 
AFAIK, for all find commands, you first need to connect to the database, and then type `db.<collectionName>.find({query...})`. It looks like either foo or bar is redundant here, and the parser throws an error expecting to see a find/insert/etc. instead of `bar`.

**Comment by hedefalk** [comment]
>Is the database name foo and the collection name bar?

No, 

>create collection foo.bar

There's a dot in the collection name which in our case used to namespace our collections:

```
> db.createCollection('foo.bar');
{ "ok" : 1 }
> db.foo.bar.insert({baz: 1});
WriteResult({ "nInserted" : 1 })
> db.foo.bar.find();
{ "_id" : ObjectId("5b1a125106cb3ffd3719dd48"), "baz" : 1 }
```

**Comment by StephenWeatherford** [comment]
@hedefalk Nice.  :-)   Thanks for letting us know about this issue.

**Comment by PrashanthCorp** [comment]
Hi Viktor, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.

**Comment by dprice** [comment]
I'm curious why this works: 
```
db.iform.note.aggregate( // rest of query
```
but this does not:
```
db.getCollection("iform.note").aggregate( //rest of query
```
 which outputs: 
```
MyDatabaseName.iform.note
```
instead of the documents

**Comment by PrashanthCorp** [comment]
Hi dprice, you trying to perform a method chaining. We recently added support for this, see #850. Please let us know if this fixes your use-case.
