### ISSUE TITLE
Cannot connect to MongoDB from VS Code Cosmos DB

### ISSUE THREAD

**Issue by MyGHid** [Microsoft/vscode-cosmosdb#669]
Cannot connect to MongoDB from VS Code Cosmos DB. I receive the following error message. I tried changing the port number but still get the same error.

# failed to connect to server [127.0.0.1:37017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:37017]
failed to connect to server [127.0.0.1:37017] on first connect [MongoError: connect ECONNREFUSED **127.0.0.1:37017]**

Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:37017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:37017]

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
@MyGHid  We'll track this issue under the first one you entered (https://github.com/Microsoft/vscode-cosmosdb/issues/662), thanks.
