### ISSUE TITLE
Argument passed in must be a single string when modifying any field in a collection

### ISSUE THREAD

**Issue by L1qu1d1c3** [Microsoft/vscode-cosmosdb#672]
Repro steps:
Modify a string field in mongodb using the cosmosDB editor.
I can provide a video if necessary

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

Version: 0.7.1
OS: win32

**Comment by PrashanthCorp** [comment]
Close via PR

**Comment by PrashanthCorp** [comment]
Hi @L1qu1d1c3 , the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.

**Comment by L1qu1d1c3** [comment]
I'll give it a try and let you know!!
Thanks!

**Comment by L1qu1d1c3** [comment]
@PrashanthCorp , tested and i can confirm it works
