### ISSUE TITLE
Error while opening a collection

### ISSUE THREAD

**Issue by geekyPrash** [Microsoft/vscode-cosmosdb#673]
Repro steps:
* Connect to local MongoDB instance
* Tried to open a collection from an existing DB/collection

Action: cosmosDB.openDocument
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
@geekyPrash Does this happen every time?  Does it block you from being able to open documents?  We have reports of this happening sporadically (see https://github.com/Microsoft/vscode-cosmosdb/issues/640).

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.  If you find a consistent way to reproduce this issue, please re-open.  Thx.
