### ISSUE TITLE
unable to save anything on local mongodb (current version on ubuntu)

### ISSUE THREAD

**Issue by lipt0n** [Microsoft/vscode-cosmosdb#674]
Repro steps:
1. create some collections with meteor
2. open database
3. edit anything (optional - you can just open anything) 
4. click upload

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters

Version: 0.7.1
OS: linux

edit:

new documents (created by cosmos) are working. It is probably connected to id.
new document has id like:
"_id": {
    "$oid": "5b1a921924938017a342358b"
  },

but documents created by meteor looks like:
  "_id": "MggBuCQhxQLHBHFso",

why can't I use string based _id ?

**Comment by bartmichu** [comment]
The same problem here with Meteor database.

**Comment by StephenWeatherford** [comment]
@bartmichu Thanks for reporting this to us.  We are tracking it in #534 and hope to have a fix out soon.

**Comment by PrashanthCorp** [comment]
Hi @lipt0n and @bartmichu , the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.

**Comment by bartmichu** [comment]
@PrashanthCorp it works great for me, thanks!
