### ISSUE TITLE
mongodb connection

### ISSUE THREAD

**Issue by sandyksit** [Microsoft/vscode-cosmosdb#675]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.1
OS: win32

**Comment by StephenWeatherford** [comment]
@sandyksit You're attempting to connect to a local mongodb instance.  Please make sure you actually have the local server running.  For instance, on Windows, you would run (changing path as necessary):
```
"C:\Program Files\MongoDB\Server\3.6\bin\mongod.exe"
```

in a command prompt window and leave it open (see https://docs.mongodb.com/manual/tutorial/install-mongodb-on-windows/ for more information).

If you already have started MongoDB, then in a different command window try running the MongoDB shell, for instance:
```
"C:\Program Files\MongoDB\Server\3.6\bin\mongo.exe"
```
and see if it is able to connect to the MongoDB.exe server.

You can find more information about getting started with MongoDB here: https://docs.mongodb.com/manual/installation/.  Please let us know if this resolves the issue for you.


Alternatively, if you would like to connect to an Azure instance of MongoDB, then you should sign in to Azure and browse to or create an Azure MongoDB database. In that case you don't need to use the "Attach Database Account" command.

thx,
Stephen

**Comment by StephenWeatherford** [comment]
I'm closing for now.  We are planning to catch this error and provide better information.  Thanks again for reporting.
