### ISSUE TITLE
Can't find out the generated result.json files on local disk before saving these

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#679]
Repro Steps:
1. Create a Mongo Scrapbook and connect to one database.
2. Add the following code like:
db.c1.drop()
db.c1.insertOne({"name": "Stephen"})
db.c1.find({})
3. Excute All.
4. Focus on one tab of the generated result.json file and check the local path.
5. Check whether these files can be found out on local disk or not according to the displayed path.

Expect:
The generated result.json files can be found out on local disk or don't display the path of these generated result.json files when focusing on tabs.

Actual:
The generated result.json files can't be found out on local disk according to the displayed path.
![result](https://user-images.githubusercontent.com/34729022/41219958-70710d10-6d4f-11e8-818c-722946dca494.png)

More info:
These files display well on local disk after saving it.

**Comment by StephenWeatherford** [comment]
This is intended behavior, thanks.
