### ISSUE TITLE
The new created account doesn't auto display in the tree view if the progress of creating account is refreshed

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#680]
Repro Steps:
1. Refresh the applied subscription during the new account is creating.
2. The progress of creating account disappear from the tree view, so check the progress in the status bar/Output.
3. Verify whether the new account auto displays in the tree view after created successfully or not.

Expect:
The new created account auto displays in the tree view.

Actual:
The new created account doesn't auto display in the tree view.

**Comment by StephenWeatherford** [comment]
Edge case that we won't worry about fixing.  Thanks, though.

**Comment by v-dantch** [comment]
Got it and thanks for your update.
