### ISSUE TITLE
Error opening (via double click in azure: cosmos db) mongodb db record.

### ISSUE THREAD

**Issue by br15** [Microsoft/vscode-cosmosdb#681]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.openDocument
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed

Version: 0.7.2
OS: win32

**Comment by StephenWeatherford** [comment]
@br15 Thanks for reporting this.  We've been having trouble finding a way to repro this.  Does it happen every time for you, or only in some scenarios?

thx,
Stephen

**Comment by br15** [comment]
Hi Stephen,

I just installed the mongo plug-in and this happened the first time I
explored my test db. When I try to recreate the issue I get the message
that I'm about to overwrite 'cosmos-document.json' every time I click on a
document in any database.  Hope this helps.

Keith

**Comment by StephenWeatherford** [comment]
@br15 Thanks.  Is it only when you *double*-click?  You only need to single click in VS Code.  (I've seen this message on a double-click, although not the other one.)

**Comment by StephenWeatherford** [comment]
This can be fixed by utilizing the new debouce functionality (see https://github.com/Microsoft/vscode-azureappservice/pull/714/files).
