### ISSUE TITLE
Trying to authenticate via GSSAPI

### ISSUE THREAD

**Issue by wmagalh** [Microsoft/vscode-cosmosdb#683]
Is that even possible? 
Since mongo shell runs behind scenes I was just wondering if connecting local DBs with Kerberos accounts would be supported.

When I try to add GSSAPI switches in the connections string I get "Authentication Failed":
mongodb://<user login>%40<DOMAIN>:<password>@<server1>,<server2>/?replicaSet=<replicaset name>&authMechanism=GSSAPI&authMechanismProperties=SERVICE_NAME:<service_name>

Thanks

**Comment by StephenWeatherford** [comment]
@wmagalh Could you verify if this works for the Mongo console?  Thanks.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response .
