### ISSUE TITLE
can't able to update the new document

### ISSUE THREAD

**Issue by sarancruzer** [Microsoft/vscode-cosmosdb#686]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.CosmosEditorManager.onDidSaveTextDocument
Error type: Error
Error Message: The "_id" field is required to update a document.

Version: 0.7.2
OS: linux

**Comment by PrashanthCorp** [comment]
Thanks for the feedback! 

Were you trying to update a mongo document or a DocumentDB document?
If it was a mongo document, the `_id` is required - this is usually automatically generated on document creation. 

Closing this, feel free to reopen.
