### ISSUE TITLE
Error while typing out a command in between two legal commands

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#689]
Repro: 
1. Have these commands typed out : 
a) `db.heroes.find({"address.City": "Goooooothammmmmmmmm"
});`
b)`db.heroes.drop();`

2. Start typing a command in between these commands. 
a)`db` -> Fine
b)`db.heroes` -> Fine
c)`db.herores.` -> Error before intellisense: "TypeError: Cannot read property 'text' of undefined"

Error stems from visitFunctionCall that tries to look up `ctx._FUNCTION_NAME.text` of the string "" (the empty string after `db.heroes`).

**Comment by PrashanthCorp** [comment]
Just tested this on master. The issue (error as a popup) no longer reproduces. (looks like PR #660 fixes this)
Instead, the problems tab mentions an error with the line. 
For `db.heroes` : The error references the fact that parsing heroes + db on the next line can't be made sense of. 
![image](https://user-images.githubusercontent.com/30420973/42114901-a868d5ea-7ba5-11e8-8d55-d091e95d0b40.png)


For `db.heroes.`, - note the dot suffix - it expects a function on the collection.
![image](https://user-images.githubusercontent.com/30420973/42114879-94cb698a-7ba5-11e8-8333-59c84d2a2086.png)

I feel the current errors mentioned are less intrusive, more informative, and intended. 

Pending adding a test case, would it make sense to close this?

**Comment by StephenWeatherford** [comment]
Yep.

**Comment by PrashanthCorp** [comment]
Closing via #741
