### ISSUE TITLE
find and findOne query fails with error

### ISSUE THREAD

**Issue by JasonMFry** [Microsoft/vscode-cosmosdb#694]
### Repro steps:

1. Connect to a database
1. Open a scrapbook
1. Type any of the following queries:
    1. `db.user.findOne(<key>: <value>)`
    1. `db.user.find(<key>: <value>)`
1. Execute the MongoDB Command

### Expect:

VSCode to display the JSON for the document

### Actual:

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 23, text ':'. Please check syntax.

### Environment:

Version: 0.7.2
OS: darwin
Insiders Build

### Gush:

I love being able to do database stuff in Code, and it's one of the several things I brag about to other engineers when trying to convert them 😄

**Comment by PrashanthCorp** [comment]
Hi Jason, 
Thanks for the feedback! Appreciate it!

Do you have a sample value for the key and value? 
We have seen a few users report a similar issue. Have you enclosed the strings in double quotes? We currently don't parse non-double-quoted strings well (JSON standards, etc.), see #466 and #467. We are working on fixing this, you can follow it at: #685 . 

If the issue is not due to quotes, we'd appreciate a sample of what you pass as arguments - we're improving the parser with every release.

**Comment by JasonMFry** [comment]
Here are a few samples that all fail with the error `Error Message: Error near line 0, column 26, text ':'. Please check syntax.`

- `db.user.find("userId": "6b0ab018-0872-4a19-9698-571a106dd837")`
- `db.user.find("firstname": "Moana")`
- `db.user.findOne("userId": "6b0ab018-0872-4a19-9698-571a106dd837")`
- `db.user.findOne("firstname": "Moana")`

and so on. Note that yesterday I tried double-quotes, single-quotes, no quotes (Robo 3T allows no quotes for the key), and all permutations thereof, and every attempt failed with either the above error or a similar one.

The key/value pairs are all copied directly from the database so I didn't mistype anything. For reference here is the sample, randomly-generated document I'm trying to query against:

```json
  {
    "_id": {
      "$oid": "5af9ae8812b9a01200914c3a"
    },
    "userId": "6b0ab018-0872-4a19-9698-571a106dd837",
    "firstname": "Moana",
    "loginDates": [
      {
        "$date": "2018-05-02T03:37:41.319Z"
      },
      {
        "$date": "2018-04-26T23:58:02.221Z"
      },
      {
        "$date": "2018-04-11T19:53:33.404Z"
      },
      {
        "$date": "2018-03-23T17:31:00.669Z"
      },
      {
        "$date": "2018-03-21T20:41:04.707Z"
      }
    ],
    "contactType": null,
    "companyId": null,
    "address2": null,
    "admin": false,
    "createdAt": {
      "$date": "2018-05-14T15:43:04.136Z"
    },
    "updatedAt": {
      "$date": "2018-05-14T15:43:04.136Z"
    }
  }
```

**Comment by fiveisprime** [comment]
I think you're just missing some curly braces.

```sh
db.user.findOne({ <key>: <value> })
db.user.find({ <key>: <value>})
```

so try `db.user.find({ "userId": "6b0ab018-0872-4a19-9698-571a106dd837" })`

Find accepts a query object and you're just passing strings separated by a colon.

**Comment by JasonMFry** [comment]
Closing issue because I had the wrong syntax.

Haha, oops. Don't mind me 🐑 

Thanks @fiveisprime! Missed some basic syntax.

**Comment by fiveisprime** [comment]
Yay! Glad that solved it. 😄 Thanks for following up.
