### ISSUE TITLE
Make connecting to authenticated DB easier

### ISSUE THREAD

**Issue by JasonMFry** [Microsoft/vscode-cosmosdb#695]
It would be nice for people who aren't as familiar with connecting to MongoDB to be given a connection wizard or a set of inputs to include the following:

1. Type
1. Name
1. Address
1. Port
1. Database
1. Username
1. Password

Screenshots are taken from Robo3T for reference

<img width="524" alt="screen shot 2018-06-19 at 7 52 25 am" src="https://user-images.githubusercontent.com/166681/41595716-d7ece65c-7395-11e8-949e-a375e62a0369.png">

<img width="528" alt="screen shot 2018-06-19 at 7 52 30 am" src="https://user-images.githubusercontent.com/166681/41595715-d7da9c36-7395-11e8-9e60-ae8f840bbd1c.png">

**Comment by JasonMFry** [comment]
I'm not sure what you mean by `provider`, nor `where your connection information is coming from`. The info is coming from my lead engineer? Is that what you're asking?

**Comment by PrashanthCorp** [comment]
Thanks for the suggestions. We shall keep an eye on feedback from the customers. We don't plan on adding this wizard, as it doesn't fit VSCode's conventions. 
We shall prioritize this in case there's more community interest.
