### ISSUE TITLE
We should capture the error from #662 and display a more useful message

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#698]
#662

**Comment by StephenWeatherford** [comment]
Changing so that we only default to the local port if we can actually connect to it (i.e. it's currently running).

**Comment by StephenWeatherford** [comment]
We're still getting people reporting this error, so we need to actually do the work to catch it and improve the error message.

**Comment by EricJizbaMSFT** [comment]
Dupe of https://github.com/microsoft/vscode-cosmosdb/issues/866
