### ISSUE TITLE
executeMongoCommand Error

### ISSUE THREAD

**Issue by gugods** [Microsoft/vscode-cosmosdb#699]
Repro steps:

 Execute Mongo command " db.Feed.find({"feedcontent":/ant/}) "

Action: cosmosDB.executeMongoCommand
Error type: SyntaxError
Error Message: Unexpected token / in JSON at position 15

Version: 0.7.2
OS: darwin

By Gugod Developer

**Comment by PrashanthCorp** [comment]
Hi Gugod, 

Thanks for your feedback! We really appreciate it. 

It looks like the error arises in using a regex inside the scrapbook. We realize we don't support it yet. We are tracking it on the first report:  #667 . We shall close this issue, feel free to reopen if you feel this is different from the bug I've mentioned above.
