### ISSUE TITLE
update doesnt work, timeout

### ISSUE THREAD

**Issue by lipt0n** [Microsoft/vscode-cosmosdb#700]
Repro steps:
db.users.update({},{
  "$pull":{
    "proposals":{
      "$elemMatch":{"_id":"4qsBHLDCb755c3vPH"}
    }
  }
})

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use meteor"

Version: 0.7.2
OS: linux

**Comment by StephenWeatherford** [comment]
See #687

**Comment by StephenWeatherford** [comment]
Closing as a dup of #687.  If you believe that is incorrect, feel free to reopen.
