### ISSUE TITLE
aggregate queries displays syntax error

### ISSUE THREAD

**Issue by martynas-m** [Microsoft/vscode-cosmosdb#708]
Repro steps:
create aggregate query. will not run. 

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 22, text '$match'. Please check syntax.

Version: 0.7.2
OS: linux

**Comment by PrashanthCorp** [comment]
Hi Martyn, 

Do you have the exact query you tried running? That would help us figure out the root issue. :) 

Please also check that you have all strings in double-quotes. See #466 and #467 for existing issues that could be the cause for your issue.

**Comment by StephenWeatherford** [comment]
@martynas-m I'm pretty sure this will be fixed by #728, which should release in about a week.

**Comment by StephenWeatherford** [comment]
Closing for now.  Please feel free to reopen if the next release does not fix it for you.

**Comment by PrashanthCorp** [comment]
Hi Martyn, the merged fix was published today (version 0.8.0). Hope this fixes your issue. :-)
Let us know how the fix holds up with your use-case.
