### ISSUE TITLE
فشل الاتصال بالخادم

### ISSUE THREAD

**Issue by Cooffe** [Microsoft/vscode-cosmosdb#709]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.7.2
OS: win32

**Comment by StephenWeatherford** [comment]
@Cooffe Looks like you found your answer in issues posted by other customers; I'm glad.  Thanks for using our extension and don't hesitate to let us know if you run into other issues.

thx,
Stephen
