### ISSUE TITLE
Parse error with multiple integers in an array

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#717]
db.Users.insertOne({"age": 22})
db.Users.find({"age" : { "$in" : [19, 20, 22, 25]}})    <<<<  This gives an error

**Comment by StephenWeatherford** [comment]
Should be fixed by collection grammar clean-up.

**Comment by PrashanthCorp** [comment]
The example shown here seems fixed by my PR. 
Adding a testcase.
