### ISSUE TITLE
Unrecognized child type in parse tree

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#737]
Repro steps:

db.c1.insert({},f)

Action: mongo.provideCodeLenses
Error type: AssertionError
Error Message: Unrecognized child type in parse tree: ErrorNode

Version: Unknown
OS: win32

**Comment by PrashanthCorp** [comment]
I don't see any screenshot or report steps...

**Comment by StephenWeatherford** [comment]
They're there now.

**Comment by PrashanthCorp** [comment]
If I ignore the ErrorNode case (i.e., return an empty object), I get the following problem output: 

![image](https://user-images.githubusercontent.com/30420973/42189423-0df7c876-7e0d-11e8-9711-0feedd1e7a7d.png)

`mismatched input 'f' expecting {'{', '[', StringLiteral, 'null', BooleanLiteral, NumericLiteral}`

The error seems pretty descriptive. As a safeguard, I'm still prevented from executing the command. 

Would this be a viable fix?

**Comment by PrashanthCorp** [comment]
Is this still considered as not-fixed? 
The error is a little more detailed now.

**Comment by PrashanthCorp** [comment]
Ping. 
Do we want to print better error messages in case of error nodes?

**Comment by StephenWeatherford** [comment]
Seems fixed to me.  Feel free to add another issue if you want specific error scenarios improved.
