### ISSUE TITLE
No Stored Procedures node displays for Graph accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#744]
Repro Steps:
1. Go to Subscription -> CosmosDB Accounts.
2. Expand one Graph account -> Check whether Stored Procedures node displays or not.

Expect:
The Stored Procedures node displays.

Actual:
No Stored Procedures node displays.

**Comment by PrashanthCorp** [comment]
Hi Xuan, 

I cannot reproduce this bug. The stored procedures node shows up in my testing. 
Refer screenshot: 
![image](https://user-images.githubusercontent.com/30420973/42239418-b3f58410-7eb8-11e8-83ff-a464bf8a651d.png)

Was there a specific account you used, that I can try reproducing this on?
