### ISSUE TITLE
An error shows under the database when undeleting an empty expanded database

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#745]
Repro Steps:
1. Go to Subscription -> CosmosDB Accounts.
2. Create an empty datebast for one account -> Expand it using the group glyph.
3. Right click the database -> Select 'Delete Database' -> Choose 'Cancel' on the popped confirmation dialog.
4. Check the tree view of the database.

Expect:
No error shows under the database.

Actual:
An error 'Error: Can't read property 'caoncat' of undefined' shows under the database.
![error](https://user-images.githubusercontent.com/34729022/42211096-35ed591e-7ea2-11e8-9ca9-c321828fe277.png)

**Comment by StephenWeatherford** [comment]
I can't repro, either.  A video showing the steps might help.

**Comment by v-xuanzh** [comment]
It seems unstable. we reproduced this issue only one time.
But found another issue: The children items disappear after undeleting one account. 

Repro Steps:
1. Select one account which contains one database at least.
2. Delete the account -> Click 'Cancel' on the popped confirmation dialog.
3. Check the children item under the account.

You can get the detail from the video(Serve path: [\\trinlab2\BAQAFiles\CloudToolsTest\v-xuanzh\screenshot\video.mov](\\trinlab2\BAQAFiles\CloudToolsTest\v-xuanzh\screenshot\video.mov))
