### ISSUE TITLE
Display an inconsistent icon between Stored Procedures node and its children items

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#746]
Repro Steps:
1. Go to Subscription -> CosmosDB Accounts.
2. Drill down from one Document accout -> Database -> Collection.
3. Create a new stored procedure -> Check whether the icon of the created item is consistent with the parent node or not.

Expect:
Display a consistent icon.

Actual:
Display an inconcsistent icon.
![icon](https://user-images.githubusercontent.com/34729022/42212307-3ee3f278-7ea5-11e8-85cd-4970463dce29.png)

**Comment by PrashanthCorp** [comment]
Close as won't fix
