### ISSUE TITLE
Display an error 'Resource Not Found' after attempting to add vertices and edged to the graph 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#751]
Platforms:Win10/Mac/Linux

Repro Steps:
1. Open a graph and attempt to add vertices and edged to the graph with  below query:
g.addV('label','employee','id','s','name','Stephen').addV('label','employee','id','e','name','Eric').addV('label','employee','id','j','name','Jing').addE("manages").to(g.V("s")).outV().addE("manages").to(g.V("e")).inV().addE("knows").to(g.V("s")).inV().addE("knows").to(g.V("e")).
2. Check the result of this graph.

Expect:
No error displays.
![expect](https://user-images.githubusercontent.com/34729092/42273665-557a4698-7f79-11e8-9fa1-886b67f1c2cb.png)

Actual:
Display an error 'Resource Not Found'.
![actual](https://user-images.githubusercontent.com/34729092/42273679-613ed462-7f79-11e8-8eb1-f93124c92503.PNG)

**Comment by PrashanthCorp** [comment]
It looks like the screenshot refers to another bug. Do you have a screenshot for the actual result in this scenario?
