### ISSUE TITLE
Incomplete command shows error in the wrong place

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#754]
See sample scrapbook:
![screen shot 2018-07-05 at 2 05 57 pm](https://user-images.githubusercontent.com/11282622/42348011-a27be12a-805c-11e8-92ce-663e4e089616.png)

My third command is completely valid and works just fine if I execute it. Seems odd that it has a red squiggle - I would expect it right after the '.' on line 3, if at all. Also the error message means nothing to me

**Comment by StephenWeatherford** [comment]
Complex issue, it's never going to work the way Eric wants it to...   But the main issue is the way the .g4 defines "db" as a token.

**Comment by PrashanthCorp** [comment]
Closing this as wontfix since the fix is unfeasible.
