### ISSUE TITLE
documentdb-node package moving to azure-cosmos-js

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#760]
Here's the announcement: https://github.com/Azure/azure-documentdb-node/issues/241

Current Repo: https://github.com/Azure/azure-documentdb-node/
New Repo: https://github.com/Azure/azure-cosmos-js

There are some breaking changes expected. 
From what I understand, node-document-db is still supported. 
We need to plan eventual migration to the new package (when they hit public preview, perhaps?)

**Comment by fiveisprime** [comment]
The new module is expected to be in an RC state by next month so let's defer any effort until then.

**Comment by christopheranderson** [comment]
FYI - the new package is published. Blog will be out soon.
