### ISSUE TITLE
Input box doesn't display red border When creating a collection with existing name

### ISSUE THREAD

**Issue by v-haiz** [microsoft/vscode-cosmosdb#767]
Repro Steps:
1. Apply one subscription-> Right click a Cosmos DB Account like '0713test'->Select 'Create Database'.
2. Enter an existing database name in input box.
3. Check whether the input box displays red or not.

Expect:
Input box displays red border.

Actual:
Input box doesn't display red border When creating a collection with existing name. Please see the below picture.
![actual1](https://user-images.githubusercontent.com/37653604/42676717-b9c232c8-8668-11e8-9807-a19a4b546db0.PNG)

**Comment by wwlorey** [comment]
Duplicate of https://github.com/microsoft/vscode-cosmosdb/issues/328
