### ISSUE TITLE
Incorrect results when using ObjectId

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#768]
```
db.a.b.insert({"companyName":ObjectId(1)})
```

Expected: error
Actual: 

treats ObjectId(1) as {}, e.g.:
```
[
  {
    "_id": {
      "$oid": "5b4d3105144319734847f3e2"
    },
    "companyName": {}
  }
]
```

**Comment by PrashanthCorp** [comment]
Adding to what you said, it looks like a problem with functionCallContext silently failing. `ObjectId(1)` is not legit syntax. In the powershell: 
![image](https://user-images.githubusercontent.com/30420973/46321151-8f047380-c596-11e8-91fd-5f32b444919e.png)

I am experimenting with making the quotes optional. This currently gives a clear error message describing the length requirement.
I'll need to test it to be confident though.

**Comment by PrashanthCorp** [comment]
I cannot repro this on master. It looks like the ObjectID PR now fixes this. 

Feel free to reopen if this repros.
