### ISSUE TITLE
failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

### ISSUE THREAD

**Issue by LarisaLub** [Microsoft/vscode-cosmosdb#770]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.8.0
OS: linux

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
