### ISSUE TITLE
TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed

### ISSUE THREAD

**Issue by srtaylo1** [Microsoft/vscode-cosmosdb#773]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.openCollection
Error type: Error
Error Message: TextEditor(vs.editor.ICodeEditor:1,$model1) has been disposed

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Looks like a dupe of #681 and #640 

Do you have more details about when you see the error? This will help us repro it on our end.

**Comment by StephenWeatherford** [comment]
Closing due to lack of response.  Please re-open if you have more information on how we can reproduce this, thanks.
