### ISSUE TITLE
isssue

### ISSUE THREAD

**Issue by udaykumargalidevara** [Microsoft/vscode-cosmosdb#774]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use MetadataTable"

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
It looks like you are trying to connect to a database. Have you tried using the codelens to connect to a database? 

Also, would you be able to provide us with the command if it was not  "use MetadataTable"? Were you trying to run an emulator? 
We would like more details to repro this.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
