### ISSUE TITLE
Cannot add ObjectId in JSON

### ISSUE THREAD

**Issue by locohost** [Microsoft/vscode-cosmosdb#775]
I'm trying to link to another document using ObjectId("...") and it shows in red and I cannot upload. What am I doing wrong?...

{
	"_id": {
		"$oid": "5b58f8d493ab342cdc679a6b"
	},
	"appId": **ObjectId**("5b58f4a593ab342cdc679a63"),
	"app": {
		"create": false,
		"edit": false,
		"read": true,
		"delete": false
	},
	"message": {
		"create": false,
		"edit": false,
		"read": true,
		"delete": false
	}
}

**Comment by locohost** [comment]
Ok I'm dumb :-/ It's...

{
    "appId": { "$oid": "5b58f4a593ab342cdc679a63" },
}

**Comment by StephenWeatherford** [comment]
Since you are using our extension, by definition you are not dumb. :-)  We realize this is confusing and are hoping to add support for ObjectId soon.  Thanks for taking the time to report the issue.

**Comment by locohost** [comment]
I like the simplicity if this extension. I find editing mongodb json easier than UIs due to quick cut/paste. However if I may suggest 2 small adds: open each json doc in new tab and a way to save queries. Then it's perfect 😎

**Comment by StephenWeatherford** [comment]
Thanks! Regarding saving queries, saving a mongo scrapbook doesn't cover this?

**Comment by locohost** [comment]
Oh, not sure. Haven't tried that yet. Well, I looked quick but did not investigate in detail. I will now. Thank you!
