### ISSUE TITLE
Document of ‘SQL(Document)’ is not highlighted when the command includes it

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#776]
Repro Steps:
1. Press 'F1' and type 'Document'.
2. Check the listed commands.

Expect:
All string including 'Document' is highlighted.

Actual:
Document of ‘SQL(Document)’ is not highlighted when the command includes it.
![compare](https://user-images.githubusercontent.com/34729092/43313776-9589e2b6-9180-11e8-8780-688793c74d68.png)

**Comment by StephenWeatherford** [comment]
Interesting, but since the other "Document" match in the commands is highlighted, I don't think vscode will care very much.  Thanks, but won't fix.

**Comment by v-dantch** [comment]
Thanks for your update.
