### ISSUE TITLE
Can't run mongodb mapReduce

### ISSUE THREAD

**Issue by ericccs** [microsoft/vscode-cosmosdb#784]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 28: 'mismatched input 'function' expecting {')', '{', '[', StringLiteral, 'null', BooleanLiteral, NumericLiteral}'. Please check syntax.

Version: 0.8.0
OS: win32

Below command supposed to be valid:
```
db.myReport.mapReduce(
    function() { emit(this.myId, 1); },
    function(key, values) {return Array.sum(values) },
    {
        query: { myId: "zzz"},
        out: "feat"
    }
)
```

**Comment by PrashanthCorp** [comment]
I'm not too sure about that. 
Currently the parser makes an error judging the end of this command (it stops at `emit(this.myId, 1);` , reacting to the semicolon). 
I'm trying to find out a way to fix this that still maintains operability with other commands.

**Comment by PrashanthCorp** [comment]
Related to #832
