### ISSUE TITLE
Trying to query mongodb with a partial match not working

### ISSUE THREAD

**Issue by ImreC** [Microsoft/vscode-cosmosdb#786]
Repro steps:
Query I am using in my scrapbook:
db.collection.find({name: /test/})
This works perfectly from Mongo Compass or Robo3T

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 37: 'missing '(' at ''('''. Please check syntax.

Version: 0.8.0
OS: win32

**Comment by StephenWeatherford** [comment]
@PrashanthCorp Perfect testcase for your regexp work.

**Comment by PrashanthCorp** [comment]
Thanks for pointing this out. Marking as dupe of #667 .

**Comment by ImreC** [comment]
The work around in #667 is totally fine for me, but good to read it's on the map.

**Comment by PrashanthCorp** [comment]
Closing as fixed
