### ISSUE TITLE
 Display an extra '1' on result.json file when getting the collection names for one mongo database with multiple collections

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-cosmosdb#787]
**Repro Steps:**
1. Choose one mongo account -> Create a database with **2** collections at least.
2. Make sure the created database shows as **'Connected'** -> Configure the **mongo.shell.path** on User Settings.
3. Create a mongo scrapbook -> Execute the command **'db.getCollectionNames()**' -> Check the result.json file.

**Expect:**
Only display the collection names without the extra '1' on the result.json file.

**Actual:**
Display the collection names with an extra '1' on the result.json file.
![actual](https://user-images.githubusercontent.com/34729022/43813832-f4ca2b3e-9ab6-11e8-9ef8-463e43565123.png)

**More info:**
This issue doesn’t reproduce for databases with only one collection.

**Comment by PrashanthCorp** [comment]
I'm unable to repro this.

**Comment by StephenWeatherford** [comment]
I see this sometimes but not always.

**Comment by PrashanthCorp** [comment]
Related to #838

**Comment by EricJizbaMSFT** [comment]
Likely fixed by https://github.com/microsoft/vscode-cosmosdb/pull/1162. Not worth more investigation unless more users report this issue
