### ISSUE TITLE
trying  to execute db.getCollection() commond on scrapbook but getting below error

### ISSUE THREAD

**Issue by vikas007bhutani** [Microsoft/vscode-cosmosdb#789]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: ENOENT
Error Message: Could not find Mongo shell. Make sure it is on your path or you have set the 'mongo.shell.path' VS Code setting to point to the Mongo shell executable file. Attempted command: "ENter"

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi, 
Do you have details of where you have installed the mongo shell?

**Comment by PrashanthCorp** [comment]
Closing for lack of response.
