### ISSUE TITLE
not authorized when create Document

### ISSUE THREAD

**Issue by tannguyen208** [Microsoft/vscode-cosmosdb#790]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: 13
Error Message: not authorized on cv-mrtan-208 to execute command { insert: "users", ordered: true, $db: "cv-mrtan-208" }

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
I have hit this error before, it was due to lack of permissions from the database itself.
Do you as a user have `readWrite` access on those databases? 

I'd be happy to help you get to the root of the issue.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response
