### ISSUE TITLE
Click Load more on Mongo document explorer

### ISSUE THREAD

**Issue by shaydoc** [Microsoft/vscode-cosmosdb#791]
Repro steps:
literally just clicked Load More on the mongo document explorer

Action: cosmosDB.loadMore
Error type: 43
Error Message: Cursor not found, cursor id: 22446571242

Version: 0.8.0
OS: darwin

**Comment by PrashanthCorp** [comment]
1. Are you able to consistently repro the bug? 
2. And does refreshing the collection solve the problem? 

If it is yes to 2, it looks like the cursor has timed out. We'll edit the title accordingly and prioritize it.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
