### ISSUE TITLE
[Suggestion]Display 'No result/ Attach New Database Account' when there are no attached database accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#793]
Repro Steps:
1. Make sure there is no attached database account.
2. F1 -> Type 'Cosmos DB: Detach', then check the result.

Actual:
There is no any warning to prompt the customer there is no any attached database account.

Suggestion:
Display 'No result/ Attach New Database Account'.
![suggestion](https://user-images.githubusercontent.com/34729092/44139406-8531eb58-a066-11e8-9bae-ec089cbf15b1.png)

**Comment by PrashanthCorp** [comment]
An info message when there are no attached accounts could solve the issue.

**Comment by v-dantch** [comment]
Yes, I agree with you.

**Comment by EricJizbaMSFT** [comment]
Okay it's weirder now. Instead of an empty list you see this:
![Screen Shot 2020-02-20 at 3 19 06 PM](https://user-images.githubusercontent.com/11282622/74989105-603da600-53f4-11ea-88df-53576f2a5425.png)

**Comment by v-dantch** [comment]
Yes, now it will prompt to attach a new database account when trying to detach account. It's better than displaying nothing in a way. 
But it seems that don't make any sense to attach an account which will be detached immediately.  What do you think about it?
