### ISSUE TITLE
trying to run a simple aggregate query Times out every time

### ISSUE THREAD

**Issue by smv-orrin** [Microsoft/vscode-cosmosdb#794]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeAllMongoCommands
Error type: string
Error Message: Timed out executing MongoDB command "db.ingestion_queue.aggregate([{$match:{date_time:{$gte:ISODate("2018-08-09")}}},{$group:{_id:{provider:"$provider_name",file_type:"$file_type"},total:{$sum:"$file_size_bytes"}}}],{maxTimeMS:0});"

Version: 0.8.0
OS: darwin

**Comment by smv-orrin** [comment]
No problem, happy to help.  As far as reproducing it, there isn't much to report, just connecting to a mongo instance in VS Code and trying to run the query makes it happen.  I can run the same query without issue when executing via the mongo shell.  Let me know if you need anything else to dig further.

**Comment by smv-orrin** [comment]
![screen shot 2018-08-16 at 1 54 53 pm](https://user-images.githubusercontent.com/8709753/44228920-1ff4cc00-a15c-11e8-8837-60d6323ab3d8.png)
![screen shot 2018-08-16 at 1 55 37 pm](https://user-images.githubusercontent.com/8709753/44228933-26834380-a15c-11e8-9f41-260b361dd943.png)

**Comment by smv-orrin** [comment]
Other info worth noting.  I'm connecting to the primary node in a replicaSet thru a local port forward, so the local port (9204) is forwarded to the 27017 port of the primary node.  I'm able to execute the same query via Robo 3T.

**Comment by PrashanthCorp** [comment]
Ah, I missed the ISODate. :) 
#769 is a log of that. 

We are looking into fixing that. 

As a workaround, we support using [`$date` from EJSON](https://docs.mongodb.com/manual/reference/mongodb-extended-json/#date) . 
Hope that helps.

**Comment by StephenWeatherford** [comment]
I'm guessing the "timed out" is an incorrect error message, we should fix that.  Unfortunately requires a rewrite of one of our classes.

**Comment by StephenWeatherford** [comment]
Would you mind quickly trying an experimental version that may report better errors? It's easy to uninstall afterwards via the extensions view in vs code.  See instructions here: https://github.com/Microsoft/vscode-cosmosdb/issues/852#issuecomment-479734886.

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
Closing, as the error no longer occurs.
