### ISSUE TITLE
MongoDB limit() function doesn't seem to be supported when querying from scrapbook files

### ISSUE THREAD

**Issue by zachsa** [Microsoft/vscode-cosmosdb#795]
MongoDB `limit(<n>)` is not supported by API? Writing the following in `Scrapbook-1.mongo`:

This works:
`db.<collectionName>.find({})`

But this does not;
`db.<collectionName>.find({}).limit(10)`

I'm quite new to Mongo so I could be missing something obvious. But looking at this documentation: https://docs.mongodb.com/manual/reference/method/cursor.limit/

It seems to me that the query with `limit(10)` should work. should it work?

**Comment by PrashanthCorp** [comment]
Hi Zach, 
Thanks for using the extension and reaching out to us. 
Unfortunately, we don't support the limit query as of now. 
Would allowing a limit field inside the parameters of `find` work for you?

**Comment by zachsa** [comment]
Thanks for getting back to me. I’m new to Mongo and didn’t realize there was a limit field.

 

It would be helpful if you mentioned the features that aren’t supported in the readme – would have saved me quite a lot of time (and I’m sorry if such is present and I just didn’t see it!).

 

I really like using VS Code as a database IDE by the way. Thank you very much for providing this software and please add me to any mailing lists you have.

**Comment by PrashanthCorp** [comment]
Hi @zachsa , 

All public discussion happens on Github. 

It looks like another symptom of your bug is that method chaining is not supported. Looks like referencing #785 might help us keep track of this.

**Comment by PrashanthCorp** [comment]
Closing via #850
