### ISSUE TITLE
The displayed name of the created document for one SQL account shows as the set partition key 

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#796]
Repro steps:
1. Expand SQL account -> Database -> Collection.
2. Right click 'Document' -> Select 'Create Document' -> Input a unique document ID 'test1'-> Enter a value for the partition key '/name' -> Press 'Enter'.
3. Check the displayed document name.

Expect:
It displays as the unique document ID.

Actual:
It displays as the set partition key.
![name](https://user-images.githubusercontent.com/34729022/44515751-e15a9680-a6b2-11e8-9d52-656868ff6275.png)

**Comment by v-xuanzh** [comment]
There is no doubt that the created document shows the set id after pressing 'Enter' dirctly(No value).
But I think it is more resonable that still shows the created document id even if user set a value for the Partition key.

**Comment by PrashanthCorp** [comment]
There is an order of preference in deciding the label : name, ID, UUID, _id... 

You can set the order using the setting `cosmosDB.documentLabelFields`.
