### ISSUE TITLE
aggregate in scrapbook

### ISSUE THREAD

**Issue by jaffarc** [Microsoft/vscode-cosmosdb#797]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use dash"

command:  db.users.aggregate([]) 
`db.users.aggregate([
     {
         "$match": {
             "email": "jaffar@email.com"
         }
     }

 ])`

Version: 0.8.0
OS: linux

**Comment by PrashanthCorp** [comment]
Hi Jaffar, 
Thanks for using our extension! 
My first diagnosis is that it probably isn't connecting to the database `dash` properly. Were you able to run other commands without errors? 

Also, is the database housed in cosmos? If it is you will have to set the preview feature to true: 
![image](https://user-images.githubusercontent.com/30420973/44543072-651c7f00-a6c3-11e8-9dd5-4c176b151770.png)

Let me know if this helps.

**Comment by jaffarc** [comment]
I thank you, I'm connected as find it shows me the results.

![screenshot from 2018-08-23 21-56-03](https://user-images.githubusercontent.com/2094756/44559356-ec97db80-a71f-11e8-8921-03d6864af4cd.png)

db.users.find({"email": "jaffar@email.com"}) => show result
with timeout aggregate.

**Comment by PrashanthCorp** [comment]
I tried reproducing your error, but I've unsuccessful. Here's what I did - 

1. create a collection "users". 
2. Create a document with the email field you mentioned. 
3. Run your query as is. 

I get back the document I inserted. 

Is there anything I'm missing that would help me repro your issue? 
Also, are you using the cosmos emulator?

**Comment by StephenWeatherford** [comment]
#852?

**Comment by StephenWeatherford** [comment]
General false timeout issue is tracked in https://github.com/Microsoft/vscode-cosmosdb/issues/852.
