### ISSUE TITLE
Error when trying to open GraphExplorer

### ISSUE THREAD

**Issue by AbhishekTripathi** [Microsoft/vscode-cosmosdb#799]
Repro steps:
<Enter steps to reproduce issue>
I connected to my subscription and then went through selection boxes to select the graph database and the collection. In the end, I got below error. The query interface didn't open.

Action: cosmosDB.openGraphExplorer
Error type: TypeError
Error Message: node.treeItem.showExplorer is not a function

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Thanks for filing this! :) 
Got it to repro, I should have a PR fix out soon.

**Comment by PrashanthCorp** [comment]
Just to clarify, were you trying to use the command palette to open a graph? 
Apologies that it doesn't currently work. For the time being, you could use the explorer tree, get to the graph you're looking for, and click on `Graph`. That should open the graph.

**Comment by AbhishekTripathi** [comment]
Yes it was through command palette. I still get the same error. Clicking in the explorer tree works as expected. It is a workaround.
