### ISSUE TITLE
Display loading bar during initial load

### ISSUE THREAD

**Issue by FadeZhanger** [Microsoft/vscode-cosmosdb#803]
After initially opening Cosmos from the activity bar, the sidebar stays blank without any indication that it is doing something. This can be fixed by adding a loading bar at the top (which is already used when opening a collection or document).

Video: http://recordit.co/W3wX6R6BBa

Thanks for this great extension!

**Comment by EricJizbaMSFT** [comment]
Similar to https://github.com/Microsoft/vscode-azuretools/issues/84

**Comment by EricJizbaMSFT** [comment]
Closing for same reasons listed here: https://github.com/Microsoft/vscode-azuretools/issues/84#issuecomment-465732954
