### ISSUE TITLE
[Suggestion] Display a unique icon for different types of Cosmos DB accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#805]
Repro Steps:
1. Make sure there are different types of Cosmos DB accounts.
2. Check the icon of them.

Actual:
All icons of different types of Cosmos DB account are same.

Suggestion:
Display matched icon for different types of Cosmos DB accounts.
![icon](https://user-images.githubusercontent.com/34729092/45014853-65940e80-b00f-11e8-871c-5c9cd2b1308d.png)

**Comment by EricJizbaMSFT** [comment]
The type of account is in the label and we match the portal right now so we're going to close this as won't fix
