### ISSUE TITLE
[Suggestion]Add a better prompt about 'Partition Key' when creating a graph/collection

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#806]
Repro Steps:
1. Create a new Cosmos DB account with SQL API ->Create a new Database.
2. Respond with valid Collection name after creating the new database successfully.
3. Prompt to type the 'Partition Key'.

Actual:
Only display 'Partition Key (Press 'Enter' to confirm or 'Escape' to cancel)'.

Suggestion:
Add a better prompt about 'Partition Key'.
![suggestion](https://user-images.githubusercontent.com/34729092/45015166-61b4bc00-b010-11e8-9957-f5fdbb26e34c.png)

More Info:
This issue also reproduces when creating a graph.

**Comment by PrashanthCorp** [comment]
We can add a placeholder. A defaultValue would not be good here - this is something the user needs to deliberately set (cannot be changed), giving them a defaultValue will not help them here.

**Comment by v-dantch** [comment]
It is ok to add a placeholder. Thanks for your update.

**Comment by PrashanthCorp** [comment]
We will need an example of the form `address/city/state`

**Comment by v-dantch** [comment]
Got it. Thanks for your sharing.
