### ISSUE TITLE
Display 'stored Procedure' not 'Stored Procedure' when creating a new Stored Procedure

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#808]
Repro Steps:
1. Create a new Cosmos DB with Gremlin API.
2. After creating successfully, create a new database ->Create a new graph.
3. Expand the new created graph ->Right click 'Stored Procedures' node and select 'Create Stored Procedure'.
4. Check the prompt.

Expect:
Display 'Enter a unique Stored Procedure ID'.

Actual:
Display 'Enter a unique stored Procedure ID'.
![compare](https://user-images.githubusercontent.com/34729092/45015733-21563d80-b012-11e8-9932-71a5ad43011c.png)

**Comment by StephenWeatherford** [comment]
Good catch, although I'd say it should be: Display 'Enter a unique stored procedure ID'.

**Comment by v-dantch** [comment]
Ah~ oh ~. Got it. Thanks for your update :).
