### ISSUE TITLE
The attached SQL emulator shows well on the tree view without Cosmos DB Emulator installed

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#811]
Repro Steps:
1. Make sure the Cosmos DB Emulator isn't installed.
2. Right click 'Attached Database Accounts' -> Select 'Attach Emulator' -> Choose 'SQL' API.

Expect:
1. Pop up an error dialog due to the Cosmos DB Emualtor isn't installed.
2. The attached SQL Emualtor doesn't show on the tree view.

Actual:
1. No error dialog pops up after choosing 'SQL' API.
2. The attached SQL Emulator shows well on the tree view.

More info:
Keep loading more than 3 miniutes and display an error after attempting to expand the attached SQL Emulator account.
![error](https://user-images.githubusercontent.com/34729022/45287596-2e72a100-b4d8-11e8-8f81-eef986941995.png)

**Comment by StephenWeatherford** [comment]
It would be nice to show a better message and let them know what to install. I prefer that to hiding the functionality. That's already handled by #706, thx.
