### ISSUE TITLE
[Suggestion]Keep consistent when adding a collection between VS Code and portal

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-cosmosdb#813]
Repro steps:
1. Right click on a SQL account -> Select 'Open In Portal' -> Select 'Add Collection'.
2. Drill down from the same SQL account in Step1 ->  Create a new database -> Right click on this new database -> Select 'Create Collection'.

Actual:
In VS Code, it prompts user to enter a collection name for this new collection.
In portal, it prompts user to enter a collection id for this new collection.

Suggestion:
Keep consistent when adding a collection between VS Code and portal.
![capture3](https://user-images.githubusercontent.com/41351993/45353208-d3a97a00-b5a9-11e8-9e8e-c03de3edba05.PNG)

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/828
