### ISSUE TITLE
Need statistics for RU etc.

### ISSUE THREAD

**Issue by AbhishekTripathi** [microsoft/vscode-cosmosdb#814]
This is for enhancement. Can you please have additional statistic displayed on query? I would like to see information like RU, duration etc. This would be immensely helpful in tuning the queries. I am more concerned about the Gremlin graph API but same can be extended to all other cosmos offerings.

**Comment by tec-goblin** [comment]
I confirm this is very useful. I might try to contribute code for it myself at some point.

**Comment by tec-goblin** [comment]
I think that this one would require some changes in gremlinClient in the gremlin module first. As the gremlin client used by the VScode plugin doesn't provide this information, the plugin cannot provide the information either. 
But good news, it seems it [has been just added to the .NET Client](https://github.com/apache/tinkerpop/pull/915). While the [original issue](https://issues.apache.org/jira/browse/TINKERPOP-1913) seems to be implying that it has been applied to the javascript client too, it [doesn't seem to be the case in the code](https://github.com/apache/tinkerpop/blob/cff4c161615f2b50bda27b6ba523c7f52b833532/gremlin-javascript/src/main/javascript/gremlin-javascript/lib/driver/driver-remote-connection.js).

I could ask for the change in apache tinkerpop, unless someone in @Microsoft/vscodeazuretools prefers to do it (I don't even remember my login in Apache).

**Comment by EricJizbaMSFT** [comment]
Blocked by https://github.com/microsoft/vscode-cosmosdb/issues/982
