### ISSUE TITLE
MongoDB: TextEditor - edit not possible on closed editor

### ISSUE THREAD

**Issue by DannyDuran** [Microsoft/vscode-cosmosdb#815]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: TextEditor#edit not possible on closed editors

Version: 0.8.0
OS: linux

**Comment by PrashanthCorp** [comment]
We could consistently repro this. It looks like it could be a race condition. Do you happen to have a repro?
