### ISSUE TITLE
self signed certificate

### ISSUE THREAD

**Issue by DAD713** [Microsoft/vscode-cosmosdb#817]
![2018-09-13_8-14-42](https://user-images.githubusercontent.com/16339587/45488001-01b7c700-b72e-11e8-95c0-6351017b709f.jpg)

how do I get past this?

Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.createDocDBDatabase
Error type: DEPTH_ZERO_SELF_SIGNED_CERT
Error Message: self signed certificate

Version: 0.8.0
OS: win32

**Comment by StephenWeatherford** [comment]
You can try setting http.proxyStrictSSL to false.

**Comment by DAD713** [comment]
Thank you, that worked

Joe

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
