### ISSUE TITLE
Mongo fing by regex

### ISSUE THREAD

**Issue by alexandar** [Microsoft/vscode-cosmosdb#819]
Repro steps:
Execute query: db.properties.find({origin:/test/i})

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 36: 'mismatched input '}' expecting '(''. Please check syntax.

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Fixed via #761
