### ISSUE TITLE
Commands don't work against cosmosDb account

### ISSUE THREAD

**Issue by hanigan6** [microsoft/vscode-cosmosdb#820]
Repro steps:
Attach to Db Account
Connect to db
Create new shell command
`db.collection.createIndex({"name": 1, "shardKey": 1}, {unique: true})`

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use klic"

Connected to a VPN with access through the portal
Version: 0.8.0
OS: win32

Other commands like
`db.collection.find({})`
work just fine

only happens on a cosmosDb MongoApi account

**Comment by hanigan6** [comment]
Basic commands work such as 
`db.collection.find({});` this returns all documents like you would expect

**Comment by StephenWeatherford** [comment]
Would you mind quickly trying an experimental version that may report better errors? It's easy to uninstall afterwards via the extensions view in vs code.  See instructions here: https://github.com/Microsoft/vscode-cosmosdb/issues/852#issuecomment-479734886.

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
With the next release, I've fixed some scenarios where we show timeout instead of the correct error message.  Hopefully that will allow you to better understand the actual issue.  Thanks!

Fixed by #1162
