### ISSUE TITLE
Creating a Cosmos DB Account returns an error

### ISSUE THREAD

**Issue by johnpapa** [microsoft/vscode-cosmosdb#821]
Repro steps:
1. Right click the `add account` button in the cosmos extension
2. enter the name `vikings-core`
3. select `SQL`

the error below appeared

```
Action: cosmosDB.createAccount
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":17}}

Version: 0.8.0
OS: darwin
```

cc @fiveisprime 

info from vscode below

VS Code version: Code - Insiders 1.28.0-insider (29e6dce4352db76d8956035990b8630580226588, 2018-09-14T08:13:40.136Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz (16 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.49GB free)|
|Process Argv|/Applications/Visual Studio Code - Insiders.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
ng-template|Ang|0.1.10
vscode-custom-css|be5|2.7.1
markdown-preview-github-styles|bie|0.1.3
path-intellisense|chr|1.4.2
vscode-markdownlint|Dav|0.20.0
vscode-eslint|dba|1.6.0
EditorConfig|Edi|0.12.4
tslint|eg2|1.0.39
vscode-npm-script|eg2|0.3.5
prettier-vscode|esb|1.6.1
vscode-pull-request-github|Git|0.1.5
Angular1|joh|0.2.0
angular-essentials|joh|0.4.0
Angular2|joh|6.1.5
vscode-azureappservice|ms-|0.9.1
vscode-azurefunctions|ms-|0.10.2
vscode-cosmosdb|ms-|0.8.0
azure-account|ms-|0.4.3
azurecli|ms-|0.4.2
vsliveshare|ms-|0.3.666
vsliveshare-audio|ms-|0.1.32
vsliveshare-pack|ms-|0.1.2
debugger-for-chrome|msj|4.10.1
angular2-inline|nat|0.0.17
vetur|oct|0.12.6
vscode-docker|Pet|0.2.0
material-icon-theme|PKi|3.6.0
polacode|pnp|0.2.2
vue-vscode-snippets|sdr|1.3.0
code-settings-sync|Sha|3.1.2

(1 theme extensions excluded)

</details>

**Comment by johnpapa** [comment]
i discovered after this that i was unable to refresh the cosmos accounts in the tree because it appears i was logged out of azure. i dont know if that was the cause of this (i was in as i started it) or if it logged me out because of the above error

**Comment by StephenWeatherford** [comment]
#910

**Comment by PrashanthCorp** [comment]
Closing as not repro
