### ISSUE TITLE
Remove the action 'Attach Database Account…' under Attached Database Accounts

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-cosmosdb#823]
**Repro steps:**
1. Make sure there is no attached account.
2. Expand 'Attached Database Accounts' node.

**Expect**:
Remove the action 'Attach Database Account...' because there are two actions on the attached context menu.

**Actual**:
Display an extra action 'Attach Database Account...' under 'Attached Database Accounts' node.
![action](https://user-images.githubusercontent.com/34729022/45613266-3e98fc00-ba55-11e8-9efa-e266d0da81f0.png)

**Comment by nturinski** [comment]
Closing as this "bydesign".  We think that the user could be confused when expanding the Attached Database Accounts tree item and not seeing anything under it.  Even though it's in the context menu, it's nice to have it in the tree view for extra discoverability 😃
