### ISSUE TITLE
Show an unmatched error message when creating a Graph with empty name

### ISSUE THREAD

**Issue by v-xuanzh** [microsoft/vscode-cosmosdb#824]
**Repro Steps:**
1. Choose a Graph account -> Create a database -> Right click the database then select 'Create Graph'.
2. Leave the Graph name is empty(Press 'Enter' directly in the popped prompt)
3. Check the displayed error message.

**Expect**:
It shows **'Graph name** cannot be empty'.

**Actual**:
It shows **'Collection name** cannot be empty'.
![errormessage](https://user-images.githubusercontent.com/34729022/45613004-5ae86900-ba54-11e8-8c0e-71b5303fc5d1.png)

**Comment by PrashanthCorp** [comment]
It's an issue with how we have made code common. 
The placeholder uses the variable defined [here](https://github.com/Microsoft/vscode-cosmosdb/blob/4117863eabf2fc919c2f4bf458a803149786625d/src/docdb/tree/DocDBTreeItemBase.ts#L18), while the error message comes from validation via [a static method](https://github.com/Microsoft/vscode-cosmosdb/blob/4117863eabf2fc919c2f4bf458a803149786625d/src/docdb/tree/DocDBDatabaseTreeItemBase.ts#L139) that won't have access to the required variable

**Comment by nturinski** [comment]
This doesn't seem like a very common scenario and graph has pretty low usage.
