### ISSUE TITLE
The database icon is not sensible under Light theme

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#825]
Repro steps:
1. Change the current color theme to Light(Visual Studio).
2. Choose one account and check the database icon.

Expect:
The database icon is sensible.

Actual:
The database icon is not sensible.
![icon](https://user-images.githubusercontent.com/34729022/45613420-c979f680-ba55-11e8-907e-baac8c9e38fb.png)

More info:
This issue also reproduces for 'Stored Procedures' node.

**Comment by PrashanthCorp** [comment]
It may not pass high contrast requirements, but it looks fine for now.
