### ISSUE TITLE
The created document from SQL Emulator dispalys as 'undefined' under MongoDB Emulator

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#827]
**Repro steps:**
1. Make sure Azure Cosmos DB Emulator is installed.
2. Attache both MongoDB Emulator and SQL Emulator.
3. Create a database named 'mongotest1' under **MongoDB Emulator**.
4. Expand **SQL Emulator** -> Create a document named 'docutest1' under the new created database in step3.
5. Back to the **MongoDB Emulator** and refresh the parent node.

**Expect**:
The created document in step4 doesn't display under SQL Emulator.

**Actual**:
The created document  in step4 displays as 'undefined' under SQL Emulator.
![aaa](https://user-images.githubusercontent.com/34729022/45615502-398b7b00-ba5c-11e8-8deb-6a83b06e4ae3.png)

**Comment by PrashanthCorp** [comment]
I don't believe interoperability between different modes of the emulator is high priority. We shall close this until external customers feels this requires fixing.
