### ISSUE TITLE
Support Javascript (JS) expressions

### ISSUE THREAD

**Issue by ljy19891118** [microsoft/vscode-cosmosdb#832]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 31: 'mismatched input '{' expecting {',', '}'}'. Please check syntax.

Version: 0.8.0
OS: darwin

--------
I can't excute a '$where' query with function, and tell me a syntax error. But it's actually supported by MongoDB.

**Comment by PrashanthCorp** [comment]
We currently don't support full JS syntax in the scrapbook. Thanks for your feedback, we shall consider this feature.

**Comment by RicardoNiepel** [comment]
Any news?

**Comment by koljada** [comment]
Without JS support it's like living with only one hand. Are there any plans to support it?
