### ISSUE TITLE
[engineering]DocumentLabelTest is runtime dependent

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#833]
`assert.equal(getDocumentTreeItemLabel(doc), 0);` depends on the function `getDocumentLabelFields`, which picks up the local workspace settings. 

We need a default for the `documentLabelFields` array so that the success of the test does not depend on who is running it.

**Comment by StephenWeatherford** [comment]
Might be interesting to if the functions extension is handling this in their tests.  In docker, I've been adding injectable functions/etc into extensionVariables.ts, similar to ext.ui.  Perhaps there should be a ext.settings.{get,set,etc} type of functionality that can be modified by tests.

**Comment by neelip** [comment]
This already available with the current release.
