### ISSUE TITLE
Pop up an error after running command 'Cosmos DB: Update to Cloud'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#837]
Repro Steps:
1. F1 -> Type and select 'Cosmos DB: Update to Cloud'.
2. Check the result.

Expect:
Prompt to select one changed document, then save and upload it to Cloud.
![expect](https://user-images.githubusercontent.com/34729092/46068883-bb208e80-c169-11e8-867a-362b36963459.PNG)

Actual:
Pop up an error.
![error](https://user-images.githubusercontent.com/34729092/46067680-f5d4f780-c166-11e8-9ac9-961501e203ad.png)

**Comment by StephenWeatherford** [comment]
This command should be removed from the command palette.

**Comment by v-dantch** [comment]
Verified on the latest build [20190526.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=6335), this command was removed.
