### ISSUE TITLE
issue with authorization token is not valid at the current time

### ISSUE THREAD

**Issue by dharmiksv** [Microsoft/vscode-cosmosdb#842]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.createDocDBDatabase
Error type: Forbidden
Error Message: The authorization token is not valid at the current time. Please create another token and retry (token start time: Tue, 02 Oct 2018 12:00:46 GMT, token expiry time: Tue, 02 Oct 2018 12:15:46 GMT, current server time: Tue, 02 Oct 2018 11:54:00 GMT).
ActivityId: f5644cc2-b10e-4406-ae18-aa7f01446e0c, Microsoft.Azure.Documents.Common/2.0.0.0

Version: 0.8.0
OS: win32

**Comment by StephenWeatherford** [comment]
@dharmiksv Does this happen consistently?  If so, can you provide more info for us to attempt to recreate it?  Thx.
