### ISSUE TITLE
Mongo Shell VsCode

### ISSUE THREAD

**Issue by ReignOnU** [Microsoft/vscode-cosmosdb#843]
Repro steps:
db.Users.aggregate( [ { $match : { "UserName" : "test" } } ] );

Action: cosmosDB.executeMongoCommand
Error type: ENOENT
Error Message: Could not find Mongo shell. Make sure it is on your path or you have set the 'mongo.shell.path' VS Code setting to point to the Mongo shell executable file. Attempted command: "C:\Program Files\MongoDB\Server\4.0\bin"

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
You would need the path to contain the exe file. In this case, C:\Program Files\MongoDB\Server\4.0\bin\ _mongo.exe_ . 
Let us know if that solves your problem.

**Comment by ReignOnU** [comment]
I added the following path "C:\Program Files\MongoDB\Server\4.0\bin\mongo" and it worked.
There is no folder in bin called mongo.  I'm assuming its referencingthe executable called mongo which is a bit misleading as the variable refers to the path, not file.

**Comment by StephenWeatherford** [comment]
I'm glad it worked, thanks for letting us know.  I did do some refinements to make this clearer, and also added code so we will accept either the folder or the file (#844), so hopefully this will be less confusing from now on.  Thanks for taking the time to report the issue, you've improved the experience for everyone.
