### ISSUE TITLE
Port debug improvements including DEBUGTELEMETRY

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#855]
- [ ] Use vscode-azureextensionui >= 0.16.6
- [ ] Port index.d.ts from https://github.com/Microsoft/vscode-docker/blob/294fda2f133fa3bf55379e7d417c333a04d19491/test/index.ts
- [ ] Add these env vars to Launch Tests configuration:
			"env": {
				"MOCHA_grep": "", // RegExp of tests to run (empty for all)
				"MOCHA_enableTimeouts": "0", // Disable time-outs
				"DEBUGTELEMETRY": "1",
				"NODE_DEBUG": ""
			}
- [ ] Add this env var to Launch Extension configuration:
			"env": {
				"DEBUGTELEMETRY": "1"
			},
- [ ] DEBUGTELEMETRY env set in launch.json (F5 and tests) and package.json test script
- [ ] set DEBUGTELEMETRY=1 in your npm test.  If using a script, I suggest this:

   "test": "npm run build && cross-env CODE_TESTS_WORKSPACE=./test/test.code-workspace DEBUGTELEMETRY=1 node ./node_modules/vscode/bin/test",

You'll need to add "cross-env": "^5.2.0", to devDependencies

If using gulp for tests, you can follow vscode-azurefunctions's model.

**Comment by EricJizbaMSFT** [comment]
Fixed in https://github.com/Microsoft/vscode-cosmosdb/pull/912
