### ISSUE TITLE
Keep consistent for Partition Key Input Box mode between VS Code and Portal

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-cosmosdb#859]
Repro Steps:
1. Right click a SQL account -> Select 'Open In Portal' -> Select 'Add Collection' -> Type a valid value without '/ ' -> Check the input box of 'Partition Key'.
2. Drill down from the same SQL account in Step1 -> Select ‘Create Collection’ under one database -> Enter a collection name  -> Type a valid value without '/ ' -> Check the input box of 'Partition Key'.

Expect:
Keep consistent for 'Partition Key' input box model between VS Code and Portal and auto display '/' after typing the valid Partition Key value in VS Code.

Actual:
In portal, auto display '/' after typing the valid Partition Key value.
In VS Code, don't auto display '/' after typing the valid Partition Key value.

**Comment by PrashanthCorp** [comment]
We already have validation for the partition key. (See validatePartitionKey inside DocDBDAtabaseTreeItemBase). In my opinion, we are more permissive to the user that the portal, and add the '/'  prefix if the user has not typed it in. 
I'm for closing this as we are providing a smoother experience.
