### ISSUE TITLE
Pop up an error after executing multiple lines and projections for 'db.<collection name>.find()'

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-cosmosdb#860]
Repro Steps:
1. New a scrapbook and connect to one database.
2. Edit the following and run it:
  		db.heroes.drop();
		db.heroes.insert({
		    "name": "Batman",
		    "saying": "I'm Batman"
		});
		db.heroes.insert({
			"_id": {"$oid" : "5a7e04558ceb7f33005d6134"},
		    "name": "Joker",
		    "saying": "Ha ha"
		});
		db.heroes.find({"name": "Joker", 
		"_id": {"$oid" : "5a7e04558ceb7f33005d6134"},
		}, {"name": 0})

Expect:
Succeed to execute without errors.

Actual:
Pop up an error dialog.

**Comment by PrashanthCorp** [comment]
Nice catch. Looks like we try to parse the second argument twice, leading to an error.
