### ISSUE TITLE
Fail to validate against existing collection name when typing new collection name

### ISSUE THREAD

**Issue by v-xianya** [Microsoft/vscode-cosmosdb#861]
Repro Steps:
1. Expand a SQL Storage account -> Create a database -> Create a collection under this database.
2. Create another collection with the same name in step1 and under the same database.

Expect:
Validate against existing collection name when typing new collection name.

Actual:
Fail to validate against existing collection name when typing new collection name.

**Comment by StephenWeatherford** [comment]
Won't fix in this scenario, thanks for filing.
