### ISSUE TITLE
Failed to run mongo find

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#869]
Possible duplicate of https://github.com/Microsoft/vscode-cosmosdb/issues/860

Repro steps:
I'm trying to run this command:
`db.products.find( { "qty": { "$gt": 25 } }, { "item": 1, "qty": 1 } )`
I got it from these examples:
https://docs.mongodb.com/manual/reference/method/db.collection.find/#specify-the-fields-to-return

Action: cosmosDB.executeMongoCommand
Error type: SyntaxError
Error Message: Unexpected token o in JSON at position 1

Version: 0.8.1-alpha
OS: darwin

**Comment by PrashanthCorp** [comment]
Looks like it. It seems to work in my PR branch, so I'm going to assume my PR fixes that too.
