### ISSUE TITLE
[Suggestion]Add more details in OUTPUT window after importing document to collections for Mongo/SQL accounts

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#874]
**Platform/OS Version:** Mac/Windows 10
**Architecture:** x64
**Node.js:** 8.9.3
**Extension Version:** ![image](https://user-images.githubusercontent.com/34729092/47003754-d5081e00-d0e4-11e8-8486-8a245ea894c0.png)

**Repro Steps:**
1. F1 -> Type and select 'Cosmos DB: Import Document into a Collection' for Mongo/SQL accounts.
2. After importing successfully, check the logs in 'OUTPUT' window.

**Actual:**
For SQL accounts, there is no log in 'OUTPUT' window.
For Mongo account, only display 'Inserted document: ~id~'
![image](https://user-images.githubusercontent.com/34729092/47004200-e140ab00-d0e5-11e8-9f3b-d8cd67d3d630.png)

**Suggestion:**
Add more details in OUTPUT window after importing document to collections for Mongo/SQL accounts like the collection path.

**Comment by PrashanthCorp** [comment]
Thanks for the suggestion. We'll wait for user feedback before fixing this.
