### ISSUE TITLE
[Suggestion]Keep consistent log info after importing one document to collection between Mongo and SQL account

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#876]
**Platform/OS Version:** Mac/Windows 10
**Architecture:** x64
**Node.js:** 8.9.3
**Extension Version:** ![image](https://user-images.githubusercontent.com/34729092/47003754-d5081e00-d0e4-11e8-8486-8a245ea894c0.png)

**Repro Steps:**
1. Import one .json file to collection for Mongo and SQL account.
2. Check the log info after importing successfully.

**Actual:**
For SQL account, display 'Imported 1 document_**s**_'.
For Mongo account, display '...Inserted 1 document**_s_** '.
![image](https://user-images.githubusercontent.com/34729092/47007063-41d2e680-d0ec-11e8-99e1-bda106cf7f77.png)

**Suggestion:**
Keep consistent log info between Mongo and SQL account.

**Comment by v-dantch** [comment]
Add more info: 
[Suggestion]Add more specific path of Cosmos DB accounts.

**Comment by EricJizbaMSFT** [comment]
@neelip
