### ISSUE TITLE
DocumentDB - handle large documents

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#88]

**Comment by EricJizbaMSFT** [comment]
Let's test this before 0.2.0 and re-evaluate

**Comment by PrashanthCorp** [comment]
Test and Verify for  0.2.0

**Comment by EricJizbaMSFT** [comment]
I did some testing and we successfully handled documents up to 2MB.

After that, I got an error saying this:
![screen shot 2017-11-01 at 2 15 55 pm](https://user-images.githubusercontent.com/11282622/32303539-6e99a4d4-bf26-11e7-8246-41168ea66aca.png)

@fiveisprime @jinglouMSFT is that sufficient for 0.2.0 or do we need to address this?

**Comment by fiveisprime** [comment]
This is sufficient for 0.2.0.

**Comment by EricJizbaMSFT** [comment]
@PrashanthCorp maybe you closed this on mistake? Moving to 0.3.0

**Comment by PrashanthCorp** [comment]
Yup, my bad.

**Comment by EricJizbaMSFT** [comment]
Closing this for now. Please reopen if anyone runs into this limitation
