### ISSUE TITLE
[Regression]Trying to create database through Mongo emulator fails on current master

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#881]
Doesn't repro on last shipped version.
Action: cosmosDB.createMongoDatabase
Error type: 18
Error Message: Authentication Failed

Version: 0.8.1-alpha
OS: win32

**Comment by PrashanthCorp** [comment]
It looks like the disparity arises from this line:
https://github.com/Microsoft/vscode-cosmosdb/blob/b94a32592e2c3a932109089863484f44611b284d/src/mongo/mongoConnectionStrings.ts#L34

The other issue is that the typical connection string for an emulator is of the form: 
mongodb://localhost:C2y6yDjf5/**R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw**/Jw==@localhost:10255?ssl=true
which the `addDatabaseToAccountConnectionString` function converts to (assume databaseName = test3): 
mongodb://localhost:C2y6yDjf5/**test3**/Jw==@localhost:10255?ssl=true.
The auth key `R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw` gets replaced with the database name.
