### ISSUE TITLE
Unexpected node encountered

### ISSUE THREAD

**Issue by StephenWeatherford** [Microsoft/vscode-cosmosdb#882]
Repro steps:
Was working with scrapbook. Error message ought to say more.

Action: mongo.provideCodeLenses
Error type: Error
Error Message: Unexpected node encountered

Version: 0.8.1-alpha
OS: win32

**Comment by PrashanthCorp** [comment]
Do you have the command you were running? 

Should we say something like "Looks like our parser could not classify ${child.text}. Would you like to report this?" That would highlight the token text. We could also include the parent's text too for more context.

**Comment by StephenWeatherford** [comment]
No, I don't.

**Comment by StephenWeatherford** [comment]
I didn't see it at first.

**Comment by StephenWeatherford** [comment]
Got it, it's with your ObjectID PR:

db.a.b.c.insert(
{
"myid": ObjectId
}
)

**Comment by StephenWeatherford** [comment]
Or this: 
db.a.b.c.insert({"myid": abc})

**Comment by PrashanthCorp** [comment]
Fixed with the ObjectID PR.
