### ISSUE TITLE
Collection with documents with the same id

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#892]
I accidently created a (SQL) document with an id that already existed. Now I'm stuck in a state where I can't delete that document or view any documents.

![screen shot 2018-10-22 at 9 43 39 am](https://user-images.githubusercontent.com/11282622/47305686-1ca81180-d5df-11e8-9e63-b4d0292e740f.png)

First question: Should I be allowed to create a document with the same id? Shouldn't our extension prevent that? 
Second question: Should we handle this situation anyways? Not sure how likely it is - but seems pretty bad that it completely blocks me from viewing _any_ documents or fixing the situation

Here are the two documents (as viewed in the portal). Maybe we should be using "_rid" for the tree's id since that's actually different?
```
{
    "id": "fdsa",
    "dfafsd": "fsda",
    "_rid": "FSQaAIvV3wgDAAAAAAAAAA==",
    "_self": "dbs/FSQaAA==/colls/FSQaAIvV3wg=/docs/FSQaAIvV3wgDAAAAAAAAAA==/",
    "_etag": "\"3500d66a-0000-0700-0000-5bccf3260000\"",
    "_attachments": "attachments/",
    "_ts": 1540158246
}
```

```
{
    "id": "fdsa",
    "dfafsd": "fdsa",
    "_rid": "FSQaAIvV3wgEAAAAAAAAAA==",
    "_self": "dbs/FSQaAA==/colls/FSQaAIvV3wg=/docs/FSQaAIvV3wgEAAAAAAAAAA==/",
    "_etag": "\"41004c6c-0000-0700-0000-5bcdfdc30000\"",
    "_attachments": "attachments/",
    "_ts": 1540226499
}
```

**Comment by PrashanthCorp** [comment]
Thanks for the catch! 

On a first look, this bug might be similar to #588 - both seem to be symptoms of using the id as a proxy for unique identifier, while Cosmos does not ensure uniqueness with that field. 

So maybe we might need to use multiple fields for the treeItem.id (your bug suggests another field too).
