### ISSUE TITLE
Commands passed to the shell using EJSON syntax are not converted to mongo shell syntax

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#906]
For commands through the API, using syntax such as `db.coll.find({ "_id": {"$oid": <sampleID>}})` is fine, since the arguments get converted to objects via EJSON.parse
We do not make an conversion of `"$oid" : x` to `ObjectId(x)` when we pass commands to the shell.

**Comment by nturinski** [comment]
Not clear what the issue here is.
