### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rajapriyamuthuvel** [Microsoft/vscode-cosmosdb#907]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachEmulator
Error type: Error
Error Message: failed to connect to server [localhost:10255] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:10255]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi, 
It looks like a dupe of #662. Please let us know if it works.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
