### ISSUE TITLE
Unable to create CosmosDB account for mongodb client:

### ISSUE THREAD

**Issue by johnkoukgit** [Microsoft/vscode-cosmosdb#910]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.createAccount
Error type: object
Error Message: {"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{},"_listeners":null,"_isException":false,"_errorId":7}}

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
