### ISSUE TITLE
MongoDb connection to VSCode

### ISSUE THREAD

**Issue by syammohanp** [Microsoft/vscode-cosmosdb#924]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [cluster0-2ldgj.azure.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND cluster0-2ldgj.azure.mongodb.net cluster0-2ldgj.azure.mongodb.net:27017]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Looks like a dupe of #662 . Let us know if this helps.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
