### ISSUE TITLE
There is no error when inserting a document not containing the value of partition key for SQL accounts

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#926]
**Platform/OS Version:** Mac/Windows 10
**Architecture:** x64
**Node.js:** 8.9.3
**Extension Build:**: [20181106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=121&view=results)

**Repro Steps:**
1. Create a SQL Collection with Partition Key 'state/city'.
2. Try to insert a document not containing partition key.(Press Enter directly).
3. Check whether an error occurs or not.

**Expect:**
There occurs an error.

**Actual:**
No error occurs.

**Comment by PrashanthCorp** [comment]
Fixed size collections do not need a partition key. Supporting this was part of 0.9.0 release. See #872
