### ISSUE TITLE
[Suggestion]Keep consistent form when selecting API, resource group and location

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#927]
**Platform / OS Version:**  Mac / Win10
**Node.js :** V8.12.0
**Build Version:** [20181106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=121&view=results)

**Repro Steps:**
1. F1 -> Type and select 'Cosmos DB: Create Account'.
2. Select the API, Resource group and location according to the notifications.
3. Check the forms of the notifications.

**Suggestion:**
Display 'Select an API for your Cosmos DB account.'.

**Actual:**
Display 'Select an API for your Cosmos DB account**...**'.
![image](https://user-images.githubusercontent.com/34729092/48058498-8d5f4880-e1f1-11e8-945d-56b25764cb67.png)

**Comment by nturinski** [comment]
REMOVE ALL THE DOTS!
