### ISSUE TITLE
Miss 'Graph (Gremlin): Create Stored Procedure' when typing 'Create Stored Procedure'

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#928]
**Platform / OS Version:**  Mac / Win10
**Node.js** : V8.12.0
**Build Version:** [20181106.2](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=121&view=results)

**Repro Steps:**
1. F1 -> Type 'Create Stored Procedure'.
2. Check the result.

**Expect:**
Display 'SQL (Document): Create Stored Procedure' and 'Graph (Gremlin): Create Stored Procedure'.

**Actual:**
Miss 'Graph (Gremlin): Create Stored Procedure' .
![image](https://user-images.githubusercontent.com/34729092/48058727-242c0500-e1f2-11e8-988e-2e512697e93e.png)

**Comment by PrashanthCorp** [comment]
Decision - Have the prompt: "Cosmos DB: Create SP" for commands spanning SQL + Gremlin. 
Change all categories to have a prefix of 'Cosmos DB' ('Cosmos mongo')

**Comment by v-mengwe** [comment]
There is also no command "Graph(Gremlin): Delete Stored Procedures…", only have "Core(SQL): Delete Stored Procedures…".
![image](https://user-images.githubusercontent.com/62053665/82811846-4369b080-9ec4-11ea-9c37-195d7547ee28.png)
![image](https://user-images.githubusercontent.com/62053665/82811892-6300d900-9ec4-11ea-8d9a-c29c09e692b5.png)
