### ISSUE TITLE
testing with gulp outputs useless error messages

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#932]
The output for tests with gulp is not verbose. You don't see any test information. This is fine if there are no failing tests. However, when a test fails, this is the output I see: 

![image](https://user-images.githubusercontent.com/30420973/48237497-b6abe000-e37b-11e8-879d-56a3d276bf2a.png)

There is _no_ indication of which test is failing. Having to launch tests in debug mode just to find what tests are failing is not ideal - this might not be possible if the devops pipeline has a failing test.

**Comment by PrashanthCorp** [comment]
When I'm ready to push code upstream I usually do an npm run test; npm run all; then a git push (I can run these in the background, and not have to wait for output)
I also prefer npm run test over debug because I:
1. Already have an experimental instance running (I'm testing or prototyping something)
2. Have breakpoints set at multiple places. This is not a big hassle.

Knowing that it gets written to an xml file helps.

________________________________

**Comment by nturinski** [comment]
Eric says this is fixed by mocha-multi-reporters.
