### ISSUE TITLE
Unrecognized child type

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#934]
input: 
`db.coll.find({name: /"\\\\b"})`

Error: Unrecognized node type encountered. Could not parse / as part of /<missing '('>"\\\\b"})

ANOTHER REPRO:
db.ingestion_queue.find( { "date_time": {"$gte": ISODate2("2018-08-09T00:00:00.000Z")} } )

Error Message: Error near line 0, column 45: 'Unrecognized node type encountered. Could not parse ISODate2 as part of ISODate2("2018-08-09T00:00:00.000Z")'. Please check syntax.

**Comment by StephenWeatherford** [comment]
We just need a friendlier message like "Unrecognized function name" or even "Unable to parse 'ISODate2', or "Unable to parse syntax" or whatever, whatever's easiest, just  so it doesn't sound like an internal error.
