### ISSUE TITLE
[Regex] Handling escape characters

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#937]
Our handling of escape(d) characters needs some love. This issue will catalog the use-cases that don't work. Please add any issue with regex or escaping characters under this issue. 

1. db.heroes.find({s: /a\\/})  - Fine
db.heroes.find({s: /a\\/}) //comment - Error

2. db.coll.insert({s: "a\\\\b"}) - inserts a document "a\\\\\\\\b"

**Comment by codermrrob** [comment]
This is actually a major issue for us and prevents us from using vscode-cosmosdb.
We store json schema and many pattern (regex) attributes are broken by this. Also strings that contain escaped quotes are damaged.
