### ISSUE TITLE
connection to mongodb 

### ISSUE THREAD

**Issue by AswiniThota** [Microsoft/vscode-cosmosdb#938]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Looks like a dupe of #662.

**Comment by PrashanthCorp** [comment]
Closing due to lack of response.
