### ISSUE TITLE
MongoDB creation

### ISSUE THREAD

**Issue by Abarno** [Microsoft/vscode-cosmosdb#943]
Repro steps:
<Enter steps to reproduce issue>

Action: cosmosDB.createAccount
Error type: Error
Error Message: Entry not found in cache.

Version: 0.8.0
OS: win32

**Comment by PrashanthCorp** [comment]
Hi @Abarno , we're sorry to hear that. Do you have any steps to repro this bug? Does this bug repro in the latest release? (0.9.1)
Your input would help others facing a similar issue.

**Comment by StephenWeatherford** [comment]
@Abarno  Did this go away after restarting vscode? 
@PrashanthCorp If yes to above, this would probably be fixed by moving to the shared tree code.

**Comment by bblommers** [comment]
I've just experience the same issue. It does go away after restarting VSCode, so it's not a major issue, but it is reproducable across versions.

Repro steps:

1. Create a Free Trial account without any resources (Not sure if this is relevant)
2. Start VSCode
3. Leave VSCode/your pc open for 12+hours? (Again..not sure if this is relevant )
4. Open the Azure-tab
5. In the Azure-tab in VSCode, click 'Create Account'
6. Give any name
7. Choose MongoDB
8. An error message pops up, and no account was created

Action: cosmosDB.createAccount
Error type: Error
Error Message: Entry not found in cache.

Version: 0.10.1
OS: win32
VS Code Version: 1.33.0

**Comment by EricJizbaMSFT** [comment]
This is being tracked here: https://github.com/Microsoft/vscode-azure-account/issues/53
