### ISSUE TITLE
use database-name timeout

### ISSUE THREAD

**Issue by hanigan6** [Microsoft/vscode-cosmosdb#950]
Repro steps:
Connected to corprate vpn <- I feel like this is the root cause, are there certain things that need to be allowed from a vpn connection? We are not able to find the comos account while not on the vpn
`connected to database-test`
`db.collection.find({})`      this works

command fails on:
 `db.collection.getIndexes()`
will also fail on similar commands such as 
`db.version()`

**These commands work from the mongo shell installed on my local machine**

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command "use database-test"

mongo shell: 3.4 (shell mapped to path, and mapped on the setting `mongo.shell.path`)
cosmos preview version 3.4.2
Version: 0.9.0
OS: win32

**Comment by StephenWeatherford** [comment]
@hanigan6 We are tracking this now in https://github.com/Microsoft/vscode-cosmosdb/issues/852. It would also be great if you would try the experimental VSIX that I mention there, and see if it gives any better error messages.  Thanks!
