### ISSUE TITLE
Cannot Refresh MongoDB after Deleting Databases

### ISSUE THREAD

**Issue by derme302** [Microsoft/vscode-cosmosdb#956]
I have a connection to a local MongoDB.

After I delete the databases (right-click -> delete) I run a script that re-creates the same databases (with the same names).

I then click refresh inside the plugin and my new databases don't appear. I have to restart VSCode in order to view them.

Let me know if I can attach a log file or anything else.

**Comment by derme302** [comment]
Nothing too fancy, I just run a Python script that calls mongorestore in a subprocess.

**Comment by derme302** [comment]
Fixed in v0.9.1

**Comment by PrashanthCorp** [comment]
Closing as fixed.
