### ISSUE TITLE
Parser - functionCallContext - we throw an error if the functionCall is close to an identified functionCall

### ISSUE THREAD

**Issue by PrashanthCorp** [microsoft/vscode-cosmosdb#957]
- [ ] Handle casing issues more gracefully (objectid, ObjectID instead of ObjectId)
- [ ] If the user is still typing out the function (Ob, Obj, -> ObjectId), don't throw an error message immediately. 
- [ ] If there is a typo, inform the user more gracefully

**Comment by nturinski** [comment]
In the context of Mongo scrapbooks.  Need exact casing, etc.
