### ISSUE TITLE
Parse Query Errors from DocDB node SDK

### ISSUE THREAD

**Issue by PrashanthCorp** [Microsoft/vscode-cosmosdb#96]
The current error object has a format requiring multiple JSON.parse operations on the object. Not high priority.

**Comment by EricJizbaMSFT** [comment]
See https://github.com/Microsoft/vscode-azureappservice/issues/99 for example error

**Comment by PrashanthCorp** [comment]
For reference, 
{"code":409,"body":"{\"code\":\"Conflict\",\"message\":\"Message: {\\\"Errors\\\":[\\\"Resource with specified id or name already exists\\\"]}\\r\\n...."}
