### ISSUE TITLE
There shows a confused error message when running 'Import Document into a Collection' with no Workspace opened

### ISSUE THREAD

**Issue by v-xuanzh** [Microsoft/vscode-cosmosdb#961]
**Platform / OS Version:**  Windows/ Mac / Linux
**Node.js** : V8.12.0
**Build Version:** [20181121.5](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=773&view=logs)

**Repro Steps:**
1. Make sure there is no warkspace opened.
2. Open Command Palette -> Type 'Import Document into a Collection' -> Run this command.
3. Check the result.

**Expect Experiment:**
There shows a clear error message.

**Actual Experiment:**
There shows a confused error message as below.
![error](https://user-images.githubusercontent.com/34729022/48896118-cd752b00-ee81-11e8-9a29-b594eec15889.png)

**Comment by PrashanthCorp** [comment]
This error arises from vscode's showOpenDialog command.
