### ISSUE TITLE
Switch from "mongodb-extended-json" to "js-bson"

### ISSUE THREAD

**Issue by EricJizbaMSFT** [Microsoft/vscode-cosmosdb#963]
"mongodb-extended-json" is no longer maintained and depends on "event-stream" - which is having some issues right now :/ https://github.com/dominictarr/event-stream/issues/116

**Comment by PrashanthCorp** [comment]
I'm currently blocked by :

**Comment by PrashanthCorp** [comment]
Currently blocked by : https://github.com/mongodb-js/mongodb-extjson/issues/28 , which can throw an error at this line: 

https://github.com/Microsoft/vscode-cosmosdb/blob/0e679a7e3d39ea8094365a1e3c238f9ebe63fe90/src/mongo/MongoScrapbook.ts#L249

**Comment by PrashanthCorp** [comment]
It looks like mongodb-ext-json is also deprecated. The event-stream vulnerability is also fixed. 

Postponing this until needed.
