### ISSUE TITLE
Errored attached databases cause connections node to fail to parse/load

### ISSUE THREAD

**Issue by fiveisprime** [microsoft/vscode-cosmosdb#966]
Repro:

1. In app service extension, connect to a database on Azure
1. Start local mongo `$ docker run --rm -d -p 27017:27017/tcp mongo:latest`
1. In the cosmos extension, attach to `mongodb://127.0.0.1:27017`
1. Stop local mongo `$ docker stop <id>` or `$ docker stop $(docker ps -q)` if it's the only container running
1. Reload vs code
1. Expand connections node to see mongo error

![image](https://user-images.githubusercontent.com/1186948/49048652-5ea11600-f190-11e8-971d-d7deb33e3d6c.png)

**Comment by EricJizbaMSFT** [comment]
The key here is that the error in app service is for a db account that's not actually the connected one
