### ISSUE TITLE
Unknown or unsupported transport “disabled” for address “disabled:”

### ISSUE THREAD

**Issue by anks333** [Microsoft/vscode-cosmosdb#968]
I am not able to connect my local mongodb server. 
Error: `Unknown or unsupported transport “disabled” for address “disabled:”`
OS: Linux

**Comment by PrashanthCorp** [comment]
Thanks for the report Ankit. 
 
Are you running vscode on a remote desktop?

**Comment by anks333** [comment]
Restarted my system and it started working. May be problem with OS.
Thanks
