### ISSUE TITLE
Make sure we use keytar as little as possible

### ISSUE THREAD

**Issue by SkeLLLa** [microsoft/vscode-cosmosdb#974]
After last update previously attached databases gone. Also now it doesn't attach neither to local mongo intance, not to remote.

There are no logs as well in devtools console. Also there are nothing in extension "output".

Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

Extension: 0.9.1

PS: Reinstalling extension also doesn't resolve this issue.

**Comment by PrashanthCorp** [comment]
We're sorry to hear that @SkeLLLa . Do you have an example of a connection string you're using? (please remove any personally identifiable info before pasting here)
Was there any error when you tried attaching? 

There are a few features that touched the attached databases section in this release. To maintain compatibility, we have some tests outlined [here](https://github.com/Microsoft/vscode-cosmosdb/blob/master/test/mongoConnectionStrings.test.ts). If your connection string is not covered here, we'll account for it. Thanks for taking the time to report this bug and helping make this product better!

**Comment by SkeLLLa** [comment]
@PrashanthCorp Downgrade to 0.8.0 solves the issue, so it's definitely in 0.9.X version.

**Comment by StephenWeatherford** [comment]
Sounds similar to another issue we were looking at today.

**Comment by SkeLLLa** [comment]
As far as I understood sometimes extension or vscode itself doesn't work properly with secure password storage, like kwallet/keyring on linux.

**Comment by PrashanthCorp** [comment]
Hi @skella, can you verify if you still hit the issue? And if there's any repro, that would help too!

**Comment by SkeLLLa** [comment]
@PrashanthCorp yes, it's working for now. However I think it worth to mention that this extension requires 3rd party keyring software to be installed on user machine (e.g. for linux gnome-keyring). Also it would be good if the version of such software will be specified.

**Comment by PrashanthCorp** [comment]
Thanks for the update! We have had challenges with Linux due to the variety of keyring software that users can use. We shall try to be upfront about that.

________________________________

**Comment by SkeLLLa** [comment]
I was able to catch similar issue today. The root cause of it that vscode, as far as I understood, should launch `gnome-keyring-daemon` in order to provide access for this extension to stored passwords. However sometimes it fails to do that. And in this case we'll not receive anything.

Just as an improvement I think this extension should store databases with some kind of flag `hasCredentials`. If that flag is set tu `true`, then it should retrieve creds from keyring. If not (e.g. local development database), it should connect to it without keyring.

**Comment by EricJizbaMSFT** [comment]
To summarize: Need to make sure we use keytar as little as possible to prevent people having to mess with gnome-keyring thing

**Comment by wwlorey** [comment]
Closing as won't fix
