### ISSUE TITLE
Cannot import data to mongo

### ISSUE THREAD

**Issue by abbye516** [Microsoft/vscode-cosmosdb#978]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.importDocument
Error type: TypeError
Error Message: Cannot read property '0' of undefined

Version: 0.9.1
OS: darwin

**Comment by StephenWeatherford** [comment]
@abbye516 Do you have more information on what exactly you were doing when this happened?  E.g. what menu items, how many documents were you importing?  This will help us to repro it.  Thx.
