### ISSUE TITLE
Context menu commands should be grouped/sorted

### ISSUE THREAD

**Issue by ejizba** [microsoft/vscode-cosmosdb#98]

**Comment by EricJizbaMSFT** [comment]
This looks even worse now. Every item defaults to its own group if it doesn't have a group (probably a change on VS Code's side, but easy enough for us to fix on our side):

![screen shot 2018-11-13 at 8 37 56 am](https://user-images.githubusercontent.com/11282622/48428338-a69b5400-e71f-11e8-8170-fde835b1cb77.png)
![screen shot 2018-11-13 at 8 37 51 am](https://user-images.githubusercontent.com/11282622/48428339-a69b5400-e71f-11e8-8fe9-6c65c95494a1.png)
![screen shot 2018-11-13 at 8 37 27 am](https://user-images.githubusercontent.com/11282622/48428340-a69b5400-e71f-11e8-8fb2-c6bc50142c94.png)

**Comment by StephenWeatherford** [comment]
That's a vscode bug: https://github.com/Microsoft/vscode/issues/62875

**Comment by StephenWeatherford** [comment]
Only repros on insiders.

**Comment by ejizba** [comment]
Fixed in https://github.com/microsoft/vscode-cosmosdb/pull/1793
