### ISSUE TITLE
Error when using hyphenated collection names

### ISSUE THREAD

**Issue by khaosdoctor** [microsoft/vscode-cosmosdb#981]
When I try to perform a find operation in a collection with a hyphenated name I get this error.

## Repro steps:

1. Open a scratchbook
2. `db.getCollection('my-collection').find({})`
3. Execute

## Result:

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: collection name must be a String

Version: 0.9.1
OS: darwin

**Comment by nturinski** [comment]
Fixed by #1263

**Comment by nturinski** [comment]
Hi @khaosdoctor

I know that this was over a year ago, but this issue is finally resolved with the release of v0.12.0.  Thank you for your patience, and I hope that this fix will end up being useful for you!

Have a great weekend! 😄
