### ISSUE TITLE
Error when modifying data in MongoDB

### ISSUE THREAD

**Issue by danielngn** [Microsoft/vscode-cosmosdb#983]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.importDocument
Error type: TypeError
Error Message: Cannot read property 'replace' of undefined

Version: 0.9.1
OS: win32

**Comment by StephenWeatherford** [comment]
@danielngn I'm having trouble reproducing this.  Is it possible to describe exactly what you are doing when this error occurs?  Thanks!

**Comment by danielngn** [comment]
Hi Stephen, this seems to be reported via MongoDB's own feedback feature. I don't remember exactly what happened as that's 2 months ago. It appears to be from Action: cosmosDB.importDocument, so I was trying to import a document and it failed, with the option to report the failure.

**Comment by StephenWeatherford** [comment]
Yes, thanks.  Sorry it took so long to get to it. I tried that scenario and also looked through the code but found nothing obvious. I'm going to go ahead and close for now. If you see it again, please reactivate and let us know what you did.  Thanks for taking the time to report!
