### ISSUE TITLE
Fail to create a Gremlin account for Azure China account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#984]
**OS:** Mac / Windows
**Node.js :** V10.13.0
**Build Version:** [20181217.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1612&view=results)

**Repro Steps:**
1. Open VS Code -> Sign in with 'Azure China account'.
2. Right click the subscription -> Select "Create Account" -> Select 'Gremlin' as API for the account.
3. Check the result.

**Expect:**
Create account successfully.

**Actual:**
Pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/50440592-e3b75080-0931-11e9-8a75-e0c52c0e87c3.png)

**More Info:**
This issue doesn't reproduce for Azure and Azure Germany accounts.

**Comment by nturinski** [comment]
@v-xianya I think Mooncake should be updated to support Gremlin by now.  If not, this is a platform issue and not a bug with the extension.

**Comment by v-xianya** [comment]
Hi, @nturinski Got it and thanks for your update😊
