### ISSUE TITLE
An error occurs when deleting an account for Azure account

### ISSUE THREAD

**Issue by v-xianya** [microsoft/vscode-cosmosdb#985]
**OS:** Mac / Windows
**Node.js :** V10.13.0
**Build Version:** [20181217.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1612&view=results)

**Repro Steps:**
1. Open VS Code -> Sign in with Azure accout.
2. Select one subscription which contains at least one account.
3. Select the account and delete it.

**Expect:**
The account can be deleted successfully.

**Actual:**
Fail to delete the account and pop up an error dialog.
![image](https://user-images.githubusercontent.com/41351993/50441062-efa41200-0933-11e9-9fd5-79650f682c68.png)

**More Info:**
This issue **doesn't** reproduce for Azure China and Germany accounts.

**Comment by StephenWeatherford** [comment]
In 0.9.1, I'm seeing the spinner hang in the treeview (but account is still deleted and Refresh fixes it)

**Comment by EricJizbaMSFT** [comment]
Will and Neelima haven't seen this error and they've deleted accounts. Also we have a nightly test now that would be failing if it still repro-ed: https://github.com/microsoft/vscode-cosmosdb/blob/master/test/nightly/azureResourceMongoDB.test.ts#L88

Must've been fixed at some point
