### ISSUE TITLE
Azure Cosmos DB visual studio code extention error: Timed out executing MongoDB command while updateMany command

### ISSUE THREAD

**Issue by pspkshah** [Microsoft/vscode-cosmosdb#986]
Repro steps:
perform any updateMany command by tried updating object against the property.

Timed out executing MongoDB command

Action: cosmosDB.executeMongoCommand
Error type: string
Error Message: Timed out executing MongoDB command

Version: 0.9.1
OS: win32

**Comment by PrashanthCorp** [comment]
The command must have timed out. It most likely originated from https://github.com/Microsoft/vscode-cosmosdb/blob/bfa0352842fa47b385e04c3da574ec2c7872d49b/src/mongo/shell.ts#L99

We set a default value for the timeout so that the extension is responsive. You can modify this behavior by changing the `mongo.shell.timeout` setting. Please let us know if changing that does not help.

**Comment by StephenWeatherford** [comment]
Also see https://github.com/Microsoft/vscode-cosmosdb/issues/85.

Closing due to lack of response. Please feel free to re-open with more information.

**Comment by pspkshah** [comment]
> The command must have timed out. It most likely originated from
> 
> [vscode-cosmosdb/src/mongo/shell.ts](https://github.com/Microsoft/vscode-cosmosdb/blob/bfa0352842fa47b385e04c3da574ec2c7872d49b/src/mongo/shell.ts#L99)
> 
> Line 99 in [bfa0352](/Microsoft/vscode-cosmosdb/commit/bfa0352842fa47b385e04c3da574ec2c7872d49b)
> 
>  e(`Timed out executing MongoDB command "${script}"`); 
> We set a default value for the timeout so that the extension is responsive. You can modify this behavior by changing the `mongo.shell.timeout` setting. Please let us know if changing that does not help.

where do I have to fire this command ?
mongo.shell.timeout

From VS code only ?

**Comment by StephenWeatherford** [comment]
In vscode, type CTRL(CMD)+comma, and search for and change the mongo.shell.timeout setting.  If that doesn't fix it, it's likely the issue in https://github.com/Microsoft/vscode-cosmosdb/issues/852.
