### ISSUE TITLE
Fail to run 'db.version();' with an error (Windows)

### ISSUE THREAD

**Issue by v-dantch** [microsoft/vscode-cosmosdb#988]
**OS:** Win10
**Node.js:** V 10.14.2
**Build Version:** [20190103.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1805&view=results)

**Repro Steps:**
1. Install the [mongo shell]( https://www.mongodb.com/download-center#community) and set the 'mongo.shell.path' in VS Code.
2. New a scrapbook and run 'db.version();'.
3. Check the result.

**Expect:**
Return a version.

**Actual:**
Pop up an error.
![image](https://user-images.githubusercontent.com/34729092/50677691-31207580-1036-11e9-997d-03204b00dcfa.png)

**Comment by StephenWeatherford** [comment]
Can you try this again?  I can't repro.  Are you sure the mongo.shell.path is correct?  You could also try removing this setting and trying again, and selecting the Browse option to find the .exe directly.  Thanks.

**Comment by v-dantch** [comment]
Hi Stephen, today we verified this issue on the [20190124.8](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2453) and it only reproduces on Windows.

**Comment by StephenWeatherford** [comment]
Still can't repro, but this is an issue some customers are reporting, so I'd love to be able to repro this. Some questions:
1) What kind of database are you connected to? Emulator? Local? Cosmos?
2) Does it work if you try it against a different kind of database?

Also, could you please try installing the extension from https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2476 and see what results you get?  Thx.

**Comment by StephenWeatherford** [comment]
See also #852.

**Comment by v-dantch** [comment]
Hi Stephen, please get the details from below:
-- This issue reproduces for all databases of Cosmos, Local, Emulator.

And, I tried this issue on the provided build and latest build:
--Provided build [20180125.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2476): Pop up an error: login failed. Though I have signed in successfully.
--The latest build [20190127.1](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=2509&view=results): Also repro 'Timed out...'

**Comment by v-dantch** [comment]
Please get more from the screenshot:
![image](https://user-images.githubusercontent.com/34729092/51820306-2601e380-228a-11e9-868c-85e7ecae5a2a.png)

**Comment by StephenWeatherford** [comment]
Would you mind quickly trying an experimental version that may report better errors? It's easy to uninstall afterwards via the extensions view in vs code.  See instructions here: https://github.com/Microsoft/vscode-cosmosdb/issues/852#issuecomment-479734886.

Thanks!
Stephen

**Comment by StephenWeatherford** [comment]
Could you please try once more using https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5664?

Also, what kind of database are you connected to?  Thx.

**Comment by v-dantch** [comment]
Hi Stephen, verified on the build [20190502.18](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=5664) , this issue doesn't rproduce when connecting to a MongoDB.

**Comment by StephenWeatherford** [comment]
Fixed by #1162
