### ISSUE TITLE
Miss the cursor when putting it in the query text-box 

### ISSUE THREAD

**Issue by v-dantch** [Microsoft/vscode-cosmosdb#989]
**OS:** Win10
**Node.js:** V 10.14.2
**Build Version:** [20190103.3](https://dev.azure.com/ms-azuretools/AzCode/_build/results?buildId=1805&view=results)

**Repro Steps:**
1. Create a new account with Graph API -> Create a new database -> Create a new Graph with partition key ="name".
2. Open the graph, put the cursor in the query text-box.
3. Check the result.

**Expect:**
Display the cursor in the query text-box.

**Actual:**
Miss the cursor when putting it in the query text-box.
![image](https://user-images.githubusercontent.com/34729092/50678011-b8221d80-1037-11e9-80dc-3b1367f490d6.png)

**Comment by v-xuanzh** [comment]
This issue doesn't reproduce on build 20190108.1. So close it.
