### ISSUE TITLE
findOne and find behave differently when a document not found

### ISSUE THREAD

**Issue by MullinsN** [microsoft/vscode-cosmosdb#990]
So this is against a collection held in a database setup via https://cloud.mongodb.com on AWS with Azure Cosmos DB 0.9.1.

db.movieDetails.findOne({"title": "The Adventures of Tiantin"}) 

Provides a error box in the bottom left hand - Could not find any documents.
No comos-result.json

db.movieDetails.find({"title": "The Adventures of Tiantin"})

No error box.
However an empty comos-result.json

I appreciate that they are different commands, but consistent behavior would be handy.

**Comment by StephenWeatherford** [comment]
Related to #607.

@MullinsN What would be your ideal behavior for this as well as other commands?  Thanks!
