### ISSUE TITLE
Replace usage of Buffer()

### ISSUE THREAD

**Issue by StephenWeatherford** [microsoft/vscode-cosmosdb#993]
(node:8460) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by StephenWeatherford** [comment]
Still getting this

(node:39492) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
warning.js:18

**Comment by PrashanthCorp** [comment]
I don't see any other place our codebase uses Buffer. Could this be dependency bubbling up the warning?

**Comment by StephenWeatherford** [comment]
Can you figure out where it's coming from?

**Comment by PrashanthCorp** [comment]
Do you have a repro? That will help me figure out where it's coming from.

**Comment by Sneezry** [comment]
If you find this error when install from vsix, this may be the reason: https://github.com/microsoft/vscode/issues/67534

**Comment by PrashanthCorp** [comment]
Thanks @Sneezry for the tip! We'll keep track of that bug.

**Comment by PrashanthCorp** [comment]
The referenced issue is fixed, and we don't have a repro. 
Closing this.
