### ISSUE TITLE
Azure MongDB new Date() issue

### ISSUE THREAD

**Issue by Jarobusa** [Microsoft/vscode-cosmosdb#995]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

db.history.find({"createdDate": {$gt: new Date('2019-01-11')}})

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: Error near line 0, column 36: 'Unrecognized node type encountered. Could not parse newDate as part of newDate('2019-01-11')'. Please check syntax.

Version: 0.9.1
OS: win32

**Comment by PrashanthCorp** [comment]
@Jarobusa , 
1. Using Date('yyy-mm-dd') should work. You don't need the 'new' keyword. 
2. Did you type newDate(...) before adding the space? I'm trying to understand the origin of the error.

**Comment by Jarobusa** [comment]
That was the issue.    The code sample I was using. had new in front of the date but that is not needed.   
  

  
Thank you,
  
Robbie   
  

  
  

  
  
>
