### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by gabrielbpinho** [Microsoft/vscode-cosmosdb#997]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.attachDatabaseAccount
Error type: Error
Error Message: failed to connect to server [127.0.0.1:27017] on first connect [MongoError: connect ECONNREFUSED 127.0.0.1:27017]

Version: 0.9.1
OS: win32

**Comment by StephenWeatherford** [comment]
[@gabrielbpinho Is your local mongo db instance running?  We can't connect if it's not running (see https://github.com/Microsoft/vscode-cosmosdb/issues/675#issuecomment-395892899).
