### ISSUE TITLE
Collection name must be a string.

### ISSUE THREAD

**Issue by camerone** [microsoft/vscode-cosmosdb#998]
&lt;Please be sure to remove any private information before submitting.&gt;

Repro steps:
&lt;Enter steps to reproduce issue&gt;

Action: cosmosDB.executeMongoCommand
Error type: Error
Error Message: collection name must be a String

Version: 0.9.0
OS: darwin

**Comment by StephenWeatherford** [comment]
@camerone We need more information on what you were doing in order to analyze the issue.  Please fill in the repro steps.  Thanks.

**Comment by StephenWeatherford** [comment]
Here's a way to repro:

db.find()

**Comment by PrashanthCorp** [comment]
Will be fixed by #1089

**Comment by nturinski** [comment]
This is now fixed with v0.12.0
