### ISSUE TITLE
cursor does not exist, was killed or timed out

### ISSUE THREAD

**Issue by EricJizbaMSFT** [microsoft/vscode-cosmosdb#999]
Repro steps:
1. Expand a mongo collection
1. Import a large collection of documents
1. Click "Load more..."

Action: cosmosDB.loadMore
Error type: Error
Error Message: cursor does not exist, was killed or timed out

Version: 0.9.2-alpha
OS: darwin

**Comment by PrashanthCorp** [comment]
To do: Check if there's an option to keep the cursor alive.

**Comment by wwlorey** [comment]
I'm not able to repro this one. @EricJizbaMSFT if you get a sec can you try reproducing again?

**Comment by EricJizbaMSFT** [comment]
Can't repro any more
